/// The file is generated. Don't change anything here
enum BlockMaterial {

  waxed_oxidized_copper_trapdoor('Waxed Oxidized Copper Trapdoor', 'waxed_oxidized_copper_trapdoor',
      64),
  pink_glazed_terracotta('Pink Glazed Terracotta', 'pink_glazed_terracotta', 64),
  blast_furnace('Blast Furnace', 'blast_furnace', 64),
  white_shulker_box('White Shulker Box', 'white_shulker_box', 1),
  weathered_copper_trapdoor('Weathered Copper Trapdoor', 'weathered_copper_trapdoor', 64),
  redstone_block('Redstone Block', 'redstone_block', 64),
  lime_shulker_box('Lime Shulker Box', 'lime_shulker_box', 1),
  stripped_dark_oak_log('Stripped Dark Oak Log', 'stripped_dark_oak_log', 64),
  blue_ice('Blue Ice', 'blue_ice', 64),
  white_bed('White Bed', 'white_bed', 1),
  mangrove_stairs('Mangrove Stairs', 'mangrove_stairs', 64),
  jungle_log('Jungle Log', 'jungle_log', 64),
  verdant_froglight('Verdant Froglight', 'verdant_froglight', 64),
  cyan_glazed_terracotta('Cyan Glazed Terracotta', 'cyan_glazed_terracotta', 64),
  dark_oak_leaves('Dark Oak Leaves', 'dark_oak_leaves', 64),
  cake('Cake', 'cake', 1),
  red_tulip('Red Tulip', 'red_tulip', 64),
  spruce_leaves('Spruce Leaves', 'spruce_leaves', 64),
  bamboo_sign('Bamboo Sign', 'bamboo_sign', 16),
  green_banner('Green Banner', 'green_banner', 16),
  waxed_exposed_chiseled_copper('Waxed Exposed Chiseled Copper', 'waxed_exposed_chiseled_copper',
      64),
  light_gray_wool('Light Gray Wool', 'light_gray_wool', 64),
  crimson_roots('Crimson Roots', 'crimson_roots', 64),
  amethyst_cluster('Amethyst Cluster', 'amethyst_cluster', 64),
  bubble_coral_block('Bubble Coral Block', 'bubble_coral_block', 64),
  brown_glazed_terracotta('Brown Glazed Terracotta', 'brown_glazed_terracotta', 64),
  cherry_hanging_sign('Cherry Hanging Sign', 'cherry_hanging_sign', 16),
  nether_gold_ore('Nether Gold Ore', 'nether_gold_ore', 64),
  yellow_concrete('Yellow Concrete', 'yellow_concrete', 64),
  light_blue_shulker_box('Light Blue Shulker Box', 'light_blue_shulker_box', 1),
  brown_stained_glass('Brown Stained Glass', 'brown_stained_glass', 64),
  pearlescent_froglight('Pearlescent Froglight', 'pearlescent_froglight', 64),
  soul_campfire('Soul Campfire', 'soul_campfire', 64),
  polished_blackstone_wall('Polished Blackstone Wall', 'polished_blackstone_wall', 64),
  cracked_polished_blackstone_bricks('Cracked Polished Blackstone Bricks',
      'cracked_polished_blackstone_bricks', 64),
  stonecutter('Stonecutter', 'stonecutter', 64),
  blue_glazed_terracotta('Blue Glazed Terracotta', 'blue_glazed_terracotta', 64),
  black_shulker_box('Black Shulker Box', 'black_shulker_box', 1),
  grindstone('Grindstone', 'grindstone', 64),
  blue_orchid('Blue Orchid', 'blue_orchid', 64),
  tuff_bricks('Tuff Bricks', 'tuff_bricks', 64),
  smooth_quartz_slab('Smooth Quartz Slab', 'smooth_quartz_slab', 64),
  suspicious_gravel('Suspicious Gravel', 'suspicious_gravel', 64),
  red_banner('Red Banner', 'red_banner', 16),
  stripped_dark_oak_wood('Stripped Dark Oak Wood', 'stripped_dark_oak_wood', 64),
  iron_door('Iron Door', 'iron_door', 64),
  test_instance_block('Test Instance Block', 'test_instance_block', 64),
  mossy_cobblestone_wall('Mossy Cobblestone Wall', 'mossy_cobblestone_wall', 64),
  acacia_door('Acacia Door', 'acacia_door', 64),
  smooth_sandstone('Smooth Sandstone', 'smooth_sandstone', 64),
  spruce_fence('Spruce Fence', 'spruce_fence', 64),
  red_nether_brick_wall('Red Nether Brick Wall', 'red_nether_brick_wall', 64),
  chiseled_resin_bricks('Chiseled Resin Bricks', 'chiseled_resin_bricks', 64),
  pale_moss_block('Pale Moss Block', 'pale_moss_block', 64),
  gray_stained_glass('Gray Stained Glass', 'gray_stained_glass', 64),
  spore_blossom('Spore Blossom', 'spore_blossom', 64),
  purple_candle('Purple Candle', 'purple_candle', 64),
  green_wool('Green Wool', 'green_wool', 64),
  birch_door('Birch Door', 'birch_door', 64),
  gray_glazed_terracotta('Gray Glazed Terracotta', 'gray_glazed_terracotta', 64),
  pale_oak_stairs('Pale Oak Stairs', 'pale_oak_stairs', 64),
  chain_command_block('Chain Command Block', 'chain_command_block', 64),
  stripped_jungle_log('Stripped Jungle Log', 'stripped_jungle_log', 64),
  stripped_acacia_log('Stripped Acacia Log', 'stripped_acacia_log', 64),
  lime_stained_glass('Lime Stained Glass', 'lime_stained_glass', 64),
  tube_coral('Tube Coral', 'tube_coral', 64),
  waxed_cut_copper_slab('Waxed Cut Copper Slab', 'waxed_cut_copper_slab', 64),
  short_grass('Short Grass', 'short_grass', 64),
  jungle_stairs('Jungle Stairs', 'jungle_stairs', 64),
  oak_sapling('Oak Sapling', 'oak_sapling', 64),
  stone_brick_slab('Stone Brick Slab', 'stone_brick_slab', 64),
  mud_bricks('Mud Bricks', 'mud_bricks', 64),
  smooth_stone('Smooth Stone', 'smooth_stone', 64),
  nether_wart_block('Nether Wart Block', 'nether_wart_block', 64),
  granite_wall('Granite Wall', 'granite_wall', 64),
  magenta_bed('Magenta Bed', 'magenta_bed', 1),
  barrel('Barrel', 'barrel', 64),
  brown_concrete('Brown Concrete', 'brown_concrete', 64),
  bamboo_stairs('Bamboo Stairs', 'bamboo_stairs', 64),
  light_gray_stained_glass('Light Gray Stained Glass', 'light_gray_stained_glass', 64),
  deepslate_brick_slab('Deepslate Brick Slab', 'deepslate_brick_slab', 64),
  infested_stone('Infested Stone', 'infested_stone', 64),
  waxed_exposed_cut_copper_stairs('Waxed Exposed Cut Copper Stairs',
      'waxed_exposed_cut_copper_stairs', 64),
  oxidized_copper_trapdoor('Oxidized Copper Trapdoor', 'oxidized_copper_trapdoor', 64),
  deepslate_emerald_ore('Deepslate Emerald Ore', 'deepslate_emerald_ore', 64),
  birch_pressure_plate('Birch Pressure Plate', 'birch_pressure_plate', 64),
  cobblestone_slab('Cobblestone Slab', 'cobblestone_slab', 64),
  oak_fence('Oak Fence', 'oak_fence', 64),
  cherry_sign('Cherry Sign', 'cherry_sign', 16),
  dead_fire_coral('Dead Fire Coral', 'dead_fire_coral', 64),
  crimson_fence('Crimson Fence', 'crimson_fence', 64),
  glow_lichen('Glow Lichen', 'glow_lichen', 64),
  blackstone_stairs('Blackstone Stairs', 'blackstone_stairs', 64),
  diorite_slab('Diorite Slab', 'diorite_slab', 64),
  birch_planks('Birch Planks', 'birch_planks', 64),
  brick_stairs('Brick Stairs', 'brick_stairs', 64),
  light_gray_stained_glass_pane('Light Gray Stained Glass Pane', 'light_gray_stained_glass_pane',
      64),
  warped_slab('Warped Slab', 'warped_slab', 64),
  small_dripleaf('Small Dripleaf', 'small_dripleaf', 64),
  bubble_coral('Bubble Coral', 'bubble_coral', 64),
  beetroot_seeds('Beetroot Seeds', 'beetroot_seeds', 64),
  dead_brain_coral_fan('Dead Brain Coral Fan', 'dead_brain_coral_fan', 64),
  orange_terracotta('Orange Terracotta', 'orange_terracotta', 64),
  cut_red_sandstone('Cut Red Sandstone', 'cut_red_sandstone', 64),
  gray_bed('Gray Bed', 'gray_bed', 1),
  light_blue_glazed_terracotta('Light Blue Glazed Terracotta', 'light_blue_glazed_terracotta', 64),
  exposed_copper_grate('Exposed Copper Grate', 'exposed_copper_grate', 64),
  exposed_chiseled_copper('Exposed Chiseled Copper', 'exposed_chiseled_copper', 64),
  vault('Vault', 'vault', 64),
  infested_stone_bricks('Infested Stone Bricks', 'infested_stone_bricks', 64),
  yellow_carpet('Yellow Carpet', 'yellow_carpet', 64),
  end_stone_brick_stairs('End Stone Brick Stairs', 'end_stone_brick_stairs', 64),
  chorus_flower('Chorus Flower', 'chorus_flower', 64),
  weathered_copper_grate('Weathered Copper Grate', 'weathered_copper_grate', 64),
  infested_deepslate('Infested Deepslate', 'infested_deepslate', 64),
  hanging_roots('Hanging Roots', 'hanging_roots', 64),
  warped_planks('Warped Planks', 'warped_planks', 64),
  shulker_box('Shulker Box', 'shulker_box', 1),
  brown_banner('Brown Banner', 'brown_banner', 16),
  waxed_oxidized_cut_copper_slab('Waxed Oxidized Cut Copper Slab', 'waxed_oxidized_cut_copper_slab',
      64),
  dragon_head('Dragon Head', 'dragon_head', 64),
  birch_stairs('Birch Stairs', 'birch_stairs', 64),
  black_carpet('Black Carpet', 'black_carpet', 64),
  quartz_pillar('Quartz Pillar', 'quartz_pillar', 64),
  chiseled_tuff('Chiseled Tuff', 'chiseled_tuff', 64),
  cyan_bed('Cyan Bed', 'cyan_bed', 1),
  stripped_warped_hyphae('Stripped Warped Hyphae', 'stripped_warped_hyphae', 64),
  pink_carpet('Pink Carpet', 'pink_carpet', 64),
  polished_blackstone_pressure_plate('Polished Blackstone Pressure Plate',
      'polished_blackstone_pressure_plate', 64),
  tuff('Tuff', 'tuff', 64),
  magenta_stained_glass('Magenta Stained Glass', 'magenta_stained_glass', 64),
  crimson_trapdoor('Crimson Trapdoor', 'crimson_trapdoor', 64),
  short_dry_grass('Short Dry Grass', 'short_dry_grass', 64),
  mangrove_fence('Mangrove Fence', 'mangrove_fence', 64),
  rail('Rail', 'rail', 64),
  birch_button('Birch Button', 'birch_button', 64),
  red_glazed_terracotta('Red Glazed Terracotta', 'red_glazed_terracotta', 64),
  dark_prismarine_stairs('Dark Prismarine Stairs', 'dark_prismarine_stairs', 64),
  warped_button('Warped Button', 'warped_button', 64),
  gray_concrete('Gray Concrete', 'gray_concrete', 64),
  polished_diorite('Polished Diorite', 'polished_diorite', 64),
  pale_oak_fence_gate('Pale Oak Fence Gate', 'pale_oak_fence_gate', 64),
  torchflower('Torchflower', 'torchflower', 64),
  acacia_stairs('Acacia Stairs', 'acacia_stairs', 64),
  piston('Piston', 'piston', 64),
  chiseled_polished_blackstone('Chiseled Polished Blackstone', 'chiseled_polished_blackstone', 64),
  mossy_cobblestone_slab('Mossy Cobblestone Slab', 'mossy_cobblestone_slab', 64),
  dark_prismarine_slab('Dark Prismarine Slab', 'dark_prismarine_slab', 64),
  waxed_weathered_copper('Waxed Weathered Copper', 'waxed_weathered_copper', 64),
  sculk('Sculk', 'sculk', 64),
  yellow_bed('Yellow Bed', 'yellow_bed', 1),
  stone_slab('Stone Slab', 'stone_slab', 64),
  cracked_deepslate_tiles('Cracked Deepslate Tiles', 'cracked_deepslate_tiles', 64),
  waxed_exposed_copper_bulb('Waxed Exposed Copper Bulb', 'waxed_exposed_copper_bulb', 64),
  dead_horn_coral_block('Dead Horn Coral Block', 'dead_horn_coral_block', 64),
  decorated_pot('Decorated Pot', 'decorated_pot', 64),
  red_concrete_powder('Red Concrete Powder', 'red_concrete_powder', 64),
  red_candle('Red Candle', 'red_candle', 64),
  acacia_wood('Acacia Wood', 'acacia_wood', 64),
  black_stained_glass_pane('Black Stained Glass Pane', 'black_stained_glass_pane', 64),
  chiseled_bookshelf('Chiseled Bookshelf', 'chiseled_bookshelf', 64),
  mangrove_pressure_plate('Mangrove Pressure Plate', 'mangrove_pressure_plate', 64),
  smooth_sandstone_stairs('Smooth Sandstone Stairs', 'smooth_sandstone_stairs', 64),
  redstone_ore('Redstone Ore', 'redstone_ore', 64),
  cherry_button('Cherry Button', 'cherry_button', 64),
  melon_seeds('Melon Seeds', 'melon_seeds', 64),
  shroomlight('Shroomlight', 'shroomlight', 64),
  spruce_slab('Spruce Slab', 'spruce_slab', 64),
  waxed_exposed_copper_grate('Waxed Exposed Copper Grate', 'waxed_exposed_copper_grate', 64),
  warped_fence('Warped Fence', 'warped_fence', 64),
  dead_bubble_coral_block('Dead Bubble Coral Block', 'dead_bubble_coral_block', 64),
  prismarine_bricks('Prismarine Bricks', 'prismarine_bricks', 64),
  scaffolding('Scaffolding', 'scaffolding', 64),
  blue_wool('Blue Wool', 'blue_wool', 64),
  jungle_wood('Jungle Wood', 'jungle_wood', 64),
  stone('Stone', 'stone', 64),
  magma_block('Magma Block', 'magma_block', 64),
  exposed_cut_copper('Exposed Cut Copper', 'exposed_cut_copper', 64),
  orange_candle('Orange Candle', 'orange_candle', 64),
  mycelium('Mycelium', 'mycelium', 64),
  diorite_stairs('Diorite Stairs', 'diorite_stairs', 64),
  polished_blackstone_brick_wall('Polished Blackstone Brick Wall', 'polished_blackstone_brick_wall',
      64),
  yellow_stained_glass('Yellow Stained Glass', 'yellow_stained_glass', 64),
  pink_shulker_box('Pink Shulker Box', 'pink_shulker_box', 1),
  pink_terracotta('Pink Terracotta', 'pink_terracotta', 64),
  dead_bush('Dead Bush', 'dead_bush', 64),
  stone_pressure_plate('Stone Pressure Plate', 'stone_pressure_plate', 64),
  crimson_fungus('Crimson Fungus', 'crimson_fungus', 64),
  nether_brick_fence('Nether Brick Fence', 'nether_brick_fence', 64),
  flowering_azalea('Flowering Azalea', 'flowering_azalea', 64),
  chorus_plant('Chorus Plant', 'chorus_plant', 64),
  pale_oak_sapling('Pale Oak Sapling', 'pale_oak_sapling', 64),
  oxidized_cut_copper('Oxidized Cut Copper', 'oxidized_cut_copper', 64),
  red_nether_brick_stairs('Red Nether Brick Stairs', 'red_nether_brick_stairs', 64),
  cyan_banner('Cyan Banner', 'cyan_banner', 16),
  mossy_cobblestone_stairs('Mossy Cobblestone Stairs', 'mossy_cobblestone_stairs', 64),
  iron_ore('Iron Ore', 'iron_ore', 64),
  gilded_blackstone('Gilded Blackstone', 'gilded_blackstone', 64),
  pitcher_plant('Pitcher Plant', 'pitcher_plant', 64),
  petrified_oak_slab('Petrified Oak Slab', 'petrified_oak_slab', 64),
  red_terracotta('Red Terracotta', 'red_terracotta', 64),
  large_amethyst_bud('Large Amethyst Bud', 'large_amethyst_bud', 64),
  black_glazed_terracotta('Black Glazed Terracotta', 'black_glazed_terracotta', 64),
  resin_clump('Resin Clump', 'resin_clump', 64),
  crafting_table('Crafting Table', 'crafting_table', 64),
  nether_wart('Nether Wart', 'nether_wart', 64),
  end_portal_frame('End Portal Frame', 'end_portal_frame', 64),
  fire_coral_block('Fire Coral Block', 'fire_coral_block', 64),
  cut_sandstone('Cut Sandstone', 'cut_sandstone', 64),
  polished_blackstone_brick_stairs('Polished Blackstone Brick Stairs',
      'polished_blackstone_brick_stairs', 64),
  sculk_sensor('Sculk Sensor', 'sculk_sensor', 64),
  moss_carpet('Moss Carpet', 'moss_carpet', 64),
  white_concrete('White Concrete', 'white_concrete', 64),
  dispenser('Dispenser', 'dispenser', 64),
  purple_stained_glass('Purple Stained Glass', 'purple_stained_glass', 64),
  quartz_stairs('Quartz Stairs', 'quartz_stairs', 64),
  sculk_catalyst('Sculk Catalyst', 'sculk_catalyst', 64),
  stripped_spruce_log('Stripped Spruce Log', 'stripped_spruce_log', 64),
  muddy_mangrove_roots('Muddy Mangrove Roots', 'muddy_mangrove_roots', 64),
  pale_oak_slab('Pale Oak Slab', 'pale_oak_slab', 64),
  oak_trapdoor('Oak Trapdoor', 'oak_trapdoor', 64),
  polished_blackstone_slab('Polished Blackstone Slab', 'polished_blackstone_slab', 64),
  twisting_vines('Twisting Vines', 'twisting_vines', 64),
  bell('Bell', 'bell', 64),
  dead_bubble_coral('Dead Bubble Coral', 'dead_bubble_coral', 64),
  jungle_leaves('Jungle Leaves', 'jungle_leaves', 64),
  orange_concrete('Orange Concrete', 'orange_concrete', 64),
  azalea_leaves('Azalea Leaves', 'azalea_leaves', 64),
  green_glazed_terracotta('Green Glazed Terracotta', 'green_glazed_terracotta', 64),
  waxed_copper_grate('Waxed Copper Grate', 'waxed_copper_grate', 64),
  hay_block('Hay Block', 'hay_block', 64),
  dark_oak_stairs('Dark Oak Stairs', 'dark_oak_stairs', 64),
  turtle_egg('Turtle Egg', 'turtle_egg', 64),
  waxed_exposed_cut_copper('Waxed Exposed Cut Copper', 'waxed_exposed_cut_copper', 64),
  comparator('Comparator', 'comparator', 64),
  granite_stairs('Granite Stairs', 'granite_stairs', 64),
  birch_fence_gate('Birch Fence Gate', 'birch_fence_gate', 64),
  packed_mud('Packed Mud', 'packed_mud', 64),
  jigsaw('Jigsaw', 'jigsaw', 64),
  prismarine('Prismarine', 'prismarine', 64),
  wet_sponge('Wet Sponge', 'wet_sponge', 64),
  quartz_slab('Quartz Slab', 'quartz_slab', 64),
  bamboo_pressure_plate('Bamboo Pressure Plate', 'bamboo_pressure_plate', 64),
  exposed_cut_copper_stairs('Exposed Cut Copper Stairs', 'exposed_cut_copper_stairs', 64),
  cyan_terracotta('Cyan Terracotta', 'cyan_terracotta', 64),
  red_shulker_box('Red Shulker Box', 'red_shulker_box', 1),
  jungle_door('Jungle Door', 'jungle_door', 64),
  lily_of_the_valley('Lily Of The Valley', 'lily_of_the_valley', 64),
  dark_oak_pressure_plate('Dark Oak Pressure Plate', 'dark_oak_pressure_plate', 64),
  cyan_stained_glass_pane('Cyan Stained Glass Pane', 'cyan_stained_glass_pane', 64),
  copper_block('Copper Block', 'copper_block', 64),
  granite('Granite', 'granite', 64),
  black_concrete_powder('Black Concrete Powder', 'black_concrete_powder', 64),
  oxidized_chiseled_copper('Oxidized Chiseled Copper', 'oxidized_chiseled_copper', 64),
  stripped_jungle_wood('Stripped Jungle Wood', 'stripped_jungle_wood', 64),
  blackstone('Blackstone', 'blackstone', 64),
  tall_grass('Tall Grass', 'tall_grass', 64),
  gold_ore('Gold Ore', 'gold_ore', 64),
  warped_hanging_sign('Warped Hanging Sign', 'warped_hanging_sign', 16),
  deepslate_tiles('Deepslate Tiles', 'deepslate_tiles', 64),
  nether_sprouts('Nether Sprouts', 'nether_sprouts', 64),
  green_bed('Green Bed', 'green_bed', 1),
  allium('Allium', 'allium', 64),
  chiseled_quartz_block('Chiseled Quartz Block', 'chiseled_quartz_block', 64),
  chiseled_sandstone('Chiseled Sandstone', 'chiseled_sandstone', 64),
  stripped_birch_wood('Stripped Birch Wood', 'stripped_birch_wood', 64),
  glow_berries('Glow Berries', 'glow_berries', 64),
  yellow_glazed_terracotta('Yellow Glazed Terracotta', 'yellow_glazed_terracotta', 64),
  waxed_weathered_copper_bulb('Waxed Weathered Copper Bulb', 'waxed_weathered_copper_bulb', 64),
  packed_ice('Packed Ice', 'packed_ice', 64),
  blue_candle('Blue Candle', 'blue_candle', 64),
  copper_grate('Copper Grate', 'copper_grate', 64),
  light_gray_carpet('Light Gray Carpet', 'light_gray_carpet', 64),
  warped_fence_gate('Warped Fence Gate', 'warped_fence_gate', 64),
  purpur_block('Purpur Block', 'purpur_block', 64),
  cherry_log('Cherry Log', 'cherry_log', 64),
  weathered_copper_door('Weathered Copper Door', 'weathered_copper_door', 64),
  resin_brick_wall('Resin Brick Wall', 'resin_brick_wall', 64),
  polished_andesite('Polished Andesite', 'polished_andesite', 64),
  calcite('Calcite', 'calcite', 64),
  oak_fence_gate('Oak Fence Gate', 'oak_fence_gate', 64),
  oak_wood('Oak Wood', 'oak_wood', 64),
  smooth_sandstone_slab('Smooth Sandstone Slab', 'smooth_sandstone_slab', 64),
  gray_concrete_powder('Gray Concrete Powder', 'gray_concrete_powder', 64),
  waxed_weathered_cut_copper_slab('Waxed Weathered Cut Copper Slab',
      'waxed_weathered_cut_copper_slab', 64),
  dead_tube_coral_fan('Dead Tube Coral Fan', 'dead_tube_coral_fan', 64),
  pink_banner('Pink Banner', 'pink_banner', 16),
  crimson_stairs('Crimson Stairs', 'crimson_stairs', 64),
  bamboo_mosaic('Bamboo Mosaic', 'bamboo_mosaic', 64),
  deepslate_lapis_ore('Deepslate Lapis Ore', 'deepslate_lapis_ore', 64),
  waxed_weathered_copper_trapdoor('Waxed Weathered Copper Trapdoor',
      'waxed_weathered_copper_trapdoor', 64),
  dark_oak_sign('Dark Oak Sign', 'dark_oak_sign', 16),
  honeycomb_block('Honeycomb Block', 'honeycomb_block', 64),
  granite_slab('Granite Slab', 'granite_slab', 64),
  structure_block('Structure Block', 'structure_block', 64),
  red_wool('Red Wool', 'red_wool', 64),
  tuff_brick_wall('Tuff Brick Wall', 'tuff_brick_wall', 64),
  chipped_anvil('Chipped Anvil', 'chipped_anvil', 64),
  black_bed('Black Bed', 'black_bed', 1),
  cobbled_deepslate_slab('Cobbled Deepslate Slab', 'cobbled_deepslate_slab', 64),
  oxidized_copper_grate('Oxidized Copper Grate', 'oxidized_copper_grate', 64),
  polished_diorite_slab('Polished Diorite Slab', 'polished_diorite_slab', 64),
  oxidized_copper('Oxidized Copper', 'oxidized_copper', 64),
  jungle_button('Jungle Button', 'jungle_button', 64),
  gold_block('Gold Block', 'gold_block', 64),
  composter('Composter', 'composter', 64),
  waxed_weathered_cut_copper_stairs('Waxed Weathered Cut Copper Stairs',
      'waxed_weathered_cut_copper_stairs', 64),
  polished_andesite_stairs('Polished Andesite Stairs', 'polished_andesite_stairs', 64),
  cut_red_sandstone_slab('Cut Red Sandstone Slab', 'cut_red_sandstone_slab', 64),
  pale_oak_leaves('Pale Oak Leaves', 'pale_oak_leaves', 64),
  pointed_dripstone('Pointed Dripstone', 'pointed_dripstone', 64),
  soul_sand('Soul Sand', 'soul_sand', 64),
  waxed_copper_trapdoor('Waxed Copper Trapdoor', 'waxed_copper_trapdoor', 64),
  birch_sapling('Birch Sapling', 'birch_sapling', 64),
  honey_block('Honey Block', 'honey_block', 64),
  lever('Lever', 'lever', 64),
  cornflower('Cornflower', 'cornflower', 64),
  stripped_birch_log('Stripped Birch Log', 'stripped_birch_log', 64),
  cobblestone_stairs('Cobblestone Stairs', 'cobblestone_stairs', 64),
  dead_brain_coral_block('Dead Brain Coral Block', 'dead_brain_coral_block', 64),
  mud_brick_stairs('Mud Brick Stairs', 'mud_brick_stairs', 64),
  lightning_rod('Lightning Rod', 'lightning_rod', 64),
  stripped_acacia_wood('Stripped Acacia Wood', 'stripped_acacia_wood', 64),
  stripped_warped_stem('Stripped Warped Stem', 'stripped_warped_stem', 64),
  crying_obsidian('Crying Obsidian', 'crying_obsidian', 64),
  pink_concrete('Pink Concrete', 'pink_concrete', 64),
  crafter('Crafter', 'crafter', 64),
  enchanting_table('Enchanting Table', 'enchanting_table', 64),
  purpur_slab('Purpur Slab', 'purpur_slab', 64),
  bone_block('Bone Block', 'bone_block', 64),
  yellow_banner('Yellow Banner', 'yellow_banner', 16),
  waxed_copper_block('Waxed Copper Block', 'waxed_copper_block', 64),
  orange_shulker_box('Orange Shulker Box', 'orange_shulker_box', 1),
  deepslate_diamond_ore('Deepslate Diamond Ore', 'deepslate_diamond_ore', 64),
  cut_sandstone_slab('Cut Sandstone Slab', 'cut_sandstone_slab', 64),
  resin_bricks('Resin Bricks', 'resin_bricks', 64),
  polished_tuff('Polished Tuff', 'polished_tuff', 64),
  soul_torch('Soul Torch', 'soul_torch', 64),
  cherry_fence_gate('Cherry Fence Gate', 'cherry_fence_gate', 64),
  weathered_cut_copper_stairs('Weathered Cut Copper Stairs', 'weathered_cut_copper_stairs', 64),
  coal_block('Coal Block', 'coal_block', 64),
  seagrass('Seagrass', 'seagrass', 64),
  end_stone('End Stone', 'end_stone', 64),
  acacia_fence('Acacia Fence', 'acacia_fence', 64),
  waxed_oxidized_copper_bulb('Waxed Oxidized Copper Bulb', 'waxed_oxidized_copper_bulb', 64),
  sea_pickle('Sea Pickle', 'sea_pickle', 64),
  stripped_pale_oak_wood('Stripped Pale Oak Wood', 'stripped_pale_oak_wood', 64),
  sugar_cane('Sugar Cane', 'sugar_cane', 64),
  purple_banner('Purple Banner', 'purple_banner', 16),
  wheat_seeds('Wheat Seeds', 'wheat_seeds', 64),
  dark_oak_hanging_sign('Dark Oak Hanging Sign', 'dark_oak_hanging_sign', 16),
  dark_prismarine('Dark Prismarine', 'dark_prismarine', 64),
  azalea('Azalea', 'azalea', 64),
  blue_stained_glass('Blue Stained Glass', 'blue_stained_glass', 64),
  iron_trapdoor('Iron Trapdoor', 'iron_trapdoor', 64),
  deepslate_tile_wall('Deepslate Tile Wall', 'deepslate_tile_wall', 64),
  tnt('Tnt', 'tnt', 64),
  birch_log('Birch Log', 'birch_log', 64),
  stone_brick_wall('Stone Brick Wall', 'stone_brick_wall', 64),
  raw_copper_block('Raw Copper Block', 'raw_copper_block', 64),
  light_blue_banner('Light Blue Banner', 'light_blue_banner', 16),
  deepslate_redstone_ore('Deepslate Redstone Ore', 'deepslate_redstone_ore', 64),
  smooth_red_sandstone_stairs('Smooth Red Sandstone Stairs', 'smooth_red_sandstone_stairs', 64),
  light_gray_concrete_powder('Light Gray Concrete Powder', 'light_gray_concrete_powder', 64),
  dropper('Dropper', 'dropper', 64),
  warped_hyphae('Warped Hyphae', 'warped_hyphae', 64),
  andesite_slab('Andesite Slab', 'andesite_slab', 64),
  polished_deepslate_slab('Polished Deepslate Slab', 'polished_deepslate_slab', 64),
  daylight_detector('Daylight Detector', 'daylight_detector', 64),
  sandstone_slab('Sandstone Slab', 'sandstone_slab', 64),
  blue_shulker_box('Blue Shulker Box', 'blue_shulker_box', 1),
  orange_stained_glass('Orange Stained Glass', 'orange_stained_glass', 64),
  tall_dry_grass('Tall Dry Grass', 'tall_dry_grass', 64),
  spruce_hanging_sign('Spruce Hanging Sign', 'spruce_hanging_sign', 16),
  mangrove_door('Mangrove Door', 'mangrove_door', 64),
  pink_candle('Pink Candle', 'pink_candle', 64),
  observer('Observer', 'observer', 64),
  lantern('Lantern', 'lantern', 64),
  lime_bed('Lime Bed', 'lime_bed', 1),
  creaking_heart('Creaking Heart', 'creaking_heart', 64),
  pink_concrete_powder('Pink Concrete Powder', 'pink_concrete_powder', 64),
  brick_slab('Brick Slab', 'brick_slab', 64),
  lime_terracotta('Lime Terracotta', 'lime_terracotta', 64),
  dried_ghast('Dried Ghast', 'dried_ghast', 64),
  brick_wall('Brick Wall', 'brick_wall', 64),
  light_gray_shulker_box('Light Gray Shulker Box', 'light_gray_shulker_box', 1),
  dandelion('Dandelion', 'dandelion', 64),
  coarse_dirt('Coarse Dirt', 'coarse_dirt', 64),
  dead_tube_coral('Dead Tube Coral', 'dead_tube_coral', 64),
  magenta_carpet('Magenta Carpet', 'magenta_carpet', 64),
  cyan_shulker_box('Cyan Shulker Box', 'cyan_shulker_box', 1),
  ladder('Ladder', 'ladder', 64),
  orange_glazed_terracotta('Orange Glazed Terracotta', 'orange_glazed_terracotta', 64),
  jungle_sign('Jungle Sign', 'jungle_sign', 16),
  mangrove_propagule('Mangrove Propagule', 'mangrove_propagule', 64),
  weathered_copper('Weathered Copper', 'weathered_copper', 64),
  mossy_stone_brick_stairs('Mossy Stone Brick Stairs', 'mossy_stone_brick_stairs', 64),
  bamboo_block('Bamboo Block', 'bamboo_block', 64),
  pumpkin('Pumpkin', 'pumpkin', 64),
  spruce_wood('Spruce Wood', 'spruce_wood', 64),
  pale_oak_hanging_sign('Pale Oak Hanging Sign', 'pale_oak_hanging_sign', 16),
  ochre_froglight('Ochre Froglight', 'ochre_froglight', 64),
  red_nether_brick_slab('Red Nether Brick Slab', 'red_nether_brick_slab', 64),
  green_shulker_box('Green Shulker Box', 'green_shulker_box', 1),
  farmland('Farmland', 'farmland', 64),
  exposed_copper_bulb('Exposed Copper Bulb', 'exposed_copper_bulb', 64),
  magenta_banner('Magenta Banner', 'magenta_banner', 16),
  pale_oak_pressure_plate('Pale Oak Pressure Plate', 'pale_oak_pressure_plate', 64),
  brown_mushroom_block('Brown Mushroom Block', 'brown_mushroom_block', 64),
  stripped_mangrove_log('Stripped Mangrove Log', 'stripped_mangrove_log', 64),
  bush('Bush', 'bush', 64),
  cyan_wool('Cyan Wool', 'cyan_wool', 64),
  cocoa_beans('Cocoa Beans', 'cocoa_beans', 64),
  sticky_piston('Sticky Piston', 'sticky_piston', 64),
  stripped_oak_log('Stripped Oak Log', 'stripped_oak_log', 64),
  pale_oak_planks('Pale Oak Planks', 'pale_oak_planks', 64),
  prismarine_brick_stairs('Prismarine Brick Stairs', 'prismarine_brick_stairs', 64),
  polished_diorite_stairs('Polished Diorite Stairs', 'polished_diorite_stairs', 64),
  big_dripleaf('Big Dripleaf', 'big_dripleaf', 64),
  copper_ore('Copper Ore', 'copper_ore', 64),
  red_sandstone_wall('Red Sandstone Wall', 'red_sandstone_wall', 64),
  stripped_pale_oak_log('Stripped Pale Oak Log', 'stripped_pale_oak_log', 64),
  leaf_litter('Leaf Litter', 'leaf_litter', 64),
  damaged_anvil('Damaged Anvil', 'damaged_anvil', 64),
  light_gray_terracotta('Light Gray Terracotta', 'light_gray_terracotta', 64),
  peony('Peony', 'peony', 64),
  acacia_fence_gate('Acacia Fence Gate', 'acacia_fence_gate', 64),
  spruce_sapling('Spruce Sapling', 'spruce_sapling', 64),
  dark_oak_sapling('Dark Oak Sapling', 'dark_oak_sapling', 64),
  nether_bricks('Nether Bricks', 'nether_bricks', 64),
  infested_cracked_stone_bricks('Infested Cracked Stone Bricks', 'infested_cracked_stone_bricks',
      64),
  command_block('Command Block', 'command_block', 64),
  brown_terracotta('Brown Terracotta', 'brown_terracotta', 64),
  pale_oak_button('Pale Oak Button', 'pale_oak_button', 64),
  deepslate_copper_ore('Deepslate Copper Ore', 'deepslate_copper_ore', 64),
  stone_button('Stone Button', 'stone_button', 64),
  exposed_cut_copper_slab('Exposed Cut Copper Slab', 'exposed_cut_copper_slab', 64),
  jungle_fence('Jungle Fence', 'jungle_fence', 64),
  oxidized_cut_copper_stairs('Oxidized Cut Copper Stairs', 'oxidized_cut_copper_stairs', 64),
  flower_pot('Flower Pot', 'flower_pot', 64),
  spruce_log('Spruce Log', 'spruce_log', 64),
  chiseled_deepslate('Chiseled Deepslate', 'chiseled_deepslate', 64),
  diorite('Diorite', 'diorite', 64),
  red_bed('Red Bed', 'red_bed', 1),
  oak_slab('Oak Slab', 'oak_slab', 64),
  crimson_button('Crimson Button', 'crimson_button', 64),
  brown_concrete_powder('Brown Concrete Powder', 'brown_concrete_powder', 64),
  mangrove_trapdoor('Mangrove Trapdoor', 'mangrove_trapdoor', 64),
  magenta_stained_glass_pane('Magenta Stained Glass Pane', 'magenta_stained_glass_pane', 64),
  smoker('Smoker', 'smoker', 64),
  polished_blackstone('Polished Blackstone', 'polished_blackstone', 64),
  cut_copper('Cut Copper', 'cut_copper', 64),
  cobbled_deepslate('Cobbled Deepslate', 'cobbled_deepslate', 64),
  cobbled_deepslate_stairs('Cobbled Deepslate Stairs', 'cobbled_deepslate_stairs', 64),
  mangrove_roots('Mangrove Roots', 'mangrove_roots', 64),
  smooth_red_sandstone_slab('Smooth Red Sandstone Slab', 'smooth_red_sandstone_slab', 64),
  pale_moss_carpet('Pale Moss Carpet', 'pale_moss_carpet', 64),
  nether_brick_slab('Nether Brick Slab', 'nether_brick_slab', 64),
  waxed_weathered_chiseled_copper('Waxed Weathered Chiseled Copper',
      'waxed_weathered_chiseled_copper', 64),
  note_block('Note Block', 'note_block', 64),
  black_candle('Black Candle', 'black_candle', 64),
  jack_o_lantern('Jack O Lantern', 'jack_o_lantern', 64),
  resin_brick_slab('Resin Brick Slab', 'resin_brick_slab', 64),
  redstone_torch('Redstone Torch', 'redstone_torch', 64),
  dark_oak_door('Dark Oak Door', 'dark_oak_door', 64),
  yellow_concrete_powder('Yellow Concrete Powder', 'yellow_concrete_powder', 64),
  red_concrete('Red Concrete', 'red_concrete', 64),
  waxed_cut_copper_stairs('Waxed Cut Copper Stairs', 'waxed_cut_copper_stairs', 64),
  dead_bubble_coral_fan('Dead Bubble Coral Fan', 'dead_bubble_coral_fan', 64),
  repeater('Repeater', 'repeater', 64),
  sandstone('Sandstone', 'sandstone', 64),
  cherry_pressure_plate('Cherry Pressure Plate', 'cherry_pressure_plate', 64),
  copper_trapdoor('Copper Trapdoor', 'copper_trapdoor', 64),
  stripped_cherry_log('Stripped Cherry Log', 'stripped_cherry_log', 64),
  blue_concrete_powder('Blue Concrete Powder', 'blue_concrete_powder', 64),
  test_block('Test Block', 'test_block', 64),
  green_candle('Green Candle', 'green_candle', 64),
  diamond_ore('Diamond Ore', 'diamond_ore', 64),
  light_blue_concrete_powder('Light Blue Concrete Powder', 'light_blue_concrete_powder', 64),
  string('String', 'string', 64),
  sand('Sand', 'sand', 64),
  soul_soil('Soul Soil', 'soul_soil', 64),
  glowstone('Glowstone', 'glowstone', 64),
  polished_granite_slab('Polished Granite Slab', 'polished_granite_slab', 64),
  dark_oak_slab('Dark Oak Slab', 'dark_oak_slab', 64),
  iron_block('Iron Block', 'iron_block', 64),
  brown_candle('Brown Candle', 'brown_candle', 64),
  fire_coral('Fire Coral', 'fire_coral', 64),
  polished_deepslate_stairs('Polished Deepslate Stairs', 'polished_deepslate_stairs', 64),
  birch_sign('Birch Sign', 'birch_sign', 16),
  orange_banner('Orange Banner', 'orange_banner', 16),
  chiseled_copper('Chiseled Copper', 'chiseled_copper', 64),
  waxed_chiseled_copper('Waxed Chiseled Copper', 'waxed_chiseled_copper', 64),
  tinted_glass('Tinted Glass', 'tinted_glass', 64),
  polished_tuff_slab('Polished Tuff Slab', 'polished_tuff_slab', 64),
  sweet_berries('Sweet Berries', 'sweet_berries', 64),
  lime_stained_glass_pane('Lime Stained Glass Pane', 'lime_stained_glass_pane', 64),
  chiseled_red_sandstone('Chiseled Red Sandstone', 'chiseled_red_sandstone', 64),
  open_eyeblossom('Open Eyeblossom', 'open_eyeblossom', 64),
  mangrove_log('Mangrove Log', 'mangrove_log', 64),
  bamboo_door('Bamboo Door', 'bamboo_door', 64),
  purple_carpet('Purple Carpet', 'purple_carpet', 64),
  tripwire_hook('Tripwire Hook', 'tripwire_hook', 64),
  yellow_shulker_box('Yellow Shulker Box', 'yellow_shulker_box', 1),
  dragon_egg('Dragon Egg', 'dragon_egg', 64),
  oak_pressure_plate('Oak Pressure Plate', 'oak_pressure_plate', 64),
  acacia_hanging_sign('Acacia Hanging Sign', 'acacia_hanging_sign', 16),
  crimson_sign('Crimson Sign', 'crimson_sign', 16),
  magenta_wool('Magenta Wool', 'magenta_wool', 64),
  mossy_cobblestone('Mossy Cobblestone', 'mossy_cobblestone', 64),
  suspicious_sand('Suspicious Sand', 'suspicious_sand', 64),
  dead_fire_coral_fan('Dead Fire Coral Fan', 'dead_fire_coral_fan', 64),
  smooth_stone_slab('Smooth Stone Slab', 'smooth_stone_slab', 64),
  brown_bed('Brown Bed', 'brown_bed', 1),
  diamond_block('Diamond Block', 'diamond_block', 64),
  cracked_deepslate_bricks('Cracked Deepslate Bricks', 'cracked_deepslate_bricks', 64),
  mangrove_slab('Mangrove Slab', 'mangrove_slab', 64),
  pink_stained_glass_pane('Pink Stained Glass Pane', 'pink_stained_glass_pane', 64),
  stripped_crimson_stem('Stripped Crimson Stem', 'stripped_crimson_stem', 64),
  jungle_sapling('Jungle Sapling', 'jungle_sapling', 64),
  smooth_red_sandstone('Smooth Red Sandstone', 'smooth_red_sandstone', 64),
  nether_quartz_ore('Nether Quartz Ore', 'nether_quartz_ore', 64),
  jungle_trapdoor('Jungle Trapdoor', 'jungle_trapdoor', 64),
  spruce_planks('Spruce Planks', 'spruce_planks', 64),
  stone_stairs('Stone Stairs', 'stone_stairs', 64),
  spawner('Spawner', 'spawner', 64),
  pale_oak_trapdoor('Pale Oak Trapdoor', 'pale_oak_trapdoor', 64),
  light_gray_candle('Light Gray Candle', 'light_gray_candle', 64),
  purple_wool('Purple Wool', 'purple_wool', 64),
  pink_wool('Pink Wool', 'pink_wool', 64),
  birch_wood('Birch Wood', 'birch_wood', 64),
  lily_pad('Lily Pad', 'lily_pad', 64),
  dark_oak_fence_gate('Dark Oak Fence Gate', 'dark_oak_fence_gate', 64),
  polished_deepslate_wall('Polished Deepslate Wall', 'polished_deepslate_wall', 64),
  carved_pumpkin('Carved Pumpkin', 'carved_pumpkin', 64),
  lime_glazed_terracotta('Lime Glazed Terracotta', 'lime_glazed_terracotta', 64),
  crimson_nylium('Crimson Nylium', 'crimson_nylium', 64),
  pink_bed('Pink Bed', 'pink_bed', 1),
  warped_roots('Warped Roots', 'warped_roots', 64),
  dark_oak_trapdoor('Dark Oak Trapdoor', 'dark_oak_trapdoor', 64),
  sniffer_egg('Sniffer Egg', 'sniffer_egg', 64),
  mushroom_stem('Mushroom Stem', 'mushroom_stem', 64),
  dark_oak_planks('Dark Oak Planks', 'dark_oak_planks', 64),
  orange_wool('Orange Wool', 'orange_wool', 64),
  mossy_stone_bricks('Mossy Stone Bricks', 'mossy_stone_bricks', 64),
  acacia_pressure_plate('Acacia Pressure Plate', 'acacia_pressure_plate', 64),
  brain_coral_block('Brain Coral Block', 'brain_coral_block', 64),
  crimson_fence_gate('Crimson Fence Gate', 'crimson_fence_gate', 64),
  wither_rose('Wither Rose', 'wither_rose', 64),
  smooth_basalt('Smooth Basalt', 'smooth_basalt', 64),
  ancient_debris('Ancient Debris', 'ancient_debris', 64),
  bamboo_trapdoor('Bamboo Trapdoor', 'bamboo_trapdoor', 64),
  fern('Fern', 'fern', 64),
  pale_oak_fence('Pale Oak Fence', 'pale_oak_fence', 64),
  end_rod('End Rod', 'end_rod', 64),
  fletching_table('Fletching Table', 'fletching_table', 64),
  deepslate_brick_stairs('Deepslate Brick Stairs', 'deepslate_brick_stairs', 64),
  stripped_spruce_wood('Stripped Spruce Wood', 'stripped_spruce_wood', 64),
  bookshelf('Bookshelf', 'bookshelf', 64),
  polished_basalt('Polished Basalt', 'polished_basalt', 64),
  hopper('Hopper', 'hopper', 64),
  deepslate_coal_ore('Deepslate Coal Ore', 'deepslate_coal_ore', 64),
  basalt('Basalt', 'basalt', 64),
  weathered_cut_copper_slab('Weathered Cut Copper Slab', 'weathered_cut_copper_slab', 64),
  black_banner('Black Banner', 'black_banner', 16),
  light_blue_candle('Light Blue Candle', 'light_blue_candle', 64),
  deepslate_brick_wall('Deepslate Brick Wall', 'deepslate_brick_wall', 64),
  end_stone_bricks('End Stone Bricks', 'end_stone_bricks', 64),
  acacia_sapling('Acacia Sapling', 'acacia_sapling', 64),
  purple_stained_glass_pane('Purple Stained Glass Pane', 'purple_stained_glass_pane', 64),
  grass_block('Grass Block', 'grass_block', 64),
  deepslate('Deepslate', 'deepslate', 64),
  potato('Potato', 'potato', 64),
  target('Target', 'target', 64),
  large_fern('Large Fern', 'large_fern', 64),
  acacia_trapdoor('Acacia Trapdoor', 'acacia_trapdoor', 64),
  cobweb('Cobweb', 'cobweb', 64),
  acacia_log('Acacia Log', 'acacia_log', 64),
  frogspawn('Frogspawn', 'frogspawn', 64),
  green_stained_glass('Green Stained Glass', 'green_stained_glass', 64),
  detector_rail('Detector Rail', 'detector_rail', 64),
  mossy_stone_brick_wall('Mossy Stone Brick Wall', 'mossy_stone_brick_wall', 64),
  lime_candle('Lime Candle', 'lime_candle', 64),
  light_blue_bed('Light Blue Bed', 'light_blue_bed', 1),
  smithing_table('Smithing Table', 'smithing_table', 64),
  andesite_wall('Andesite Wall', 'andesite_wall', 64),
  bamboo_fence('Bamboo Fence', 'bamboo_fence', 64),
  chiseled_tuff_bricks('Chiseled Tuff Bricks', 'chiseled_tuff_bricks', 64),
  calibrated_sculk_sensor('Calibrated Sculk Sensor', 'calibrated_sculk_sensor', 64),
  chest('Chest', 'chest', 64),
  yellow_candle('Yellow Candle', 'yellow_candle', 64),
  jungle_slab('Jungle Slab', 'jungle_slab', 64),
  jungle_pressure_plate('Jungle Pressure Plate', 'jungle_pressure_plate', 64),
  magenta_shulker_box('Magenta Shulker Box', 'magenta_shulker_box', 1),
  cyan_concrete('Cyan Concrete', 'cyan_concrete', 64),
  lodestone('Lodestone', 'lodestone', 64),
  pumpkin_seeds('Pumpkin Seeds', 'pumpkin_seeds', 64),
  copper_door('Copper Door', 'copper_door', 64),
  cherry_fence('Cherry Fence', 'cherry_fence', 64),
  warped_wart_block('Warped Wart Block', 'warped_wart_block', 64),
  white_carpet('White Carpet', 'white_carpet', 64),
  cherry_door('Cherry Door', 'cherry_door', 64),
  brown_carpet('Brown Carpet', 'brown_carpet', 64),
  skeleton_skull('Skeleton Skull', 'skeleton_skull', 64),
  mangrove_button('Mangrove Button', 'mangrove_button', 64),
  magenta_terracotta('Magenta Terracotta', 'magenta_terracotta', 64),
  firefly_bush('Firefly Bush', 'firefly_bush', 64),
  waxed_oxidized_copper('Waxed Oxidized Copper', 'waxed_oxidized_copper', 64),
  cut_copper_slab('Cut Copper Slab', 'cut_copper_slab', 64),
  brown_wool('Brown Wool', 'brown_wool', 64),
  crimson_hyphae('Crimson Hyphae', 'crimson_hyphae', 64),
  mud_brick_slab('Mud Brick Slab', 'mud_brick_slab', 64),
  red_nether_bricks('Red Nether Bricks', 'red_nether_bricks', 64),
  purple_shulker_box('Purple Shulker Box', 'purple_shulker_box', 1),
  emerald_ore('Emerald Ore', 'emerald_ore', 64),
  exposed_copper_door('Exposed Copper Door', 'exposed_copper_door', 64),
  weathered_copper_bulb('Weathered Copper Bulb', 'weathered_copper_bulb', 64),
  prismarine_wall('Prismarine Wall', 'prismarine_wall', 64),
  trial_spawner('Trial Spawner', 'trial_spawner', 64),
  light_weighted_pressure_plate('Light Weighted Pressure Plate', 'light_weighted_pressure_plate',
      64),
  mud('Mud', 'mud', 64),
  oak_leaves('Oak Leaves', 'oak_leaves', 64),
  red_sandstone('Red Sandstone', 'red_sandstone', 64),
  red_mushroom('Red Mushroom', 'red_mushroom', 64),
  emerald_block('Emerald Block', 'emerald_block', 64),
  netherite_block('Netherite Block', 'netherite_block', 64),
  quartz_bricks('Quartz Bricks', 'quartz_bricks', 64),
  waxed_oxidized_cut_copper_stairs('Waxed Oxidized Cut Copper Stairs',
      'waxed_oxidized_cut_copper_stairs', 64),
  stripped_oak_wood('Stripped Oak Wood', 'stripped_oak_wood', 64),
  waxed_weathered_cut_copper('Waxed Weathered Cut Copper', 'waxed_weathered_cut_copper', 64),
  waxed_copper_bulb('Waxed Copper Bulb', 'waxed_copper_bulb', 64),
  vine('Vine', 'vine', 64),
  iron_bars('Iron Bars', 'iron_bars', 64),
  cobbled_deepslate_wall('Cobbled Deepslate Wall', 'cobbled_deepslate_wall', 64),
  andesite('Andesite', 'andesite', 64),
  candle('Candle', 'candle', 64),
  tuff_wall('Tuff Wall', 'tuff_wall', 64),
  blue_terracotta('Blue Terracotta', 'blue_terracotta', 64),
  yellow_wool('Yellow Wool', 'yellow_wool', 64),
  polished_andesite_slab('Polished Andesite Slab', 'polished_andesite_slab', 64),
  white_concrete_powder('White Concrete Powder', 'white_concrete_powder', 64),
  obsidian('Obsidian', 'obsidian', 64),
  stone_bricks('Stone Bricks', 'stone_bricks', 64),
  redstone('Redstone', 'redstone', 64),
  bamboo_planks('Bamboo Planks', 'bamboo_planks', 64),
  lapis_ore('Lapis Ore', 'lapis_ore', 64),
  orange_concrete_powder('Orange Concrete Powder', 'orange_concrete_powder', 64),
  mangrove_hanging_sign('Mangrove Hanging Sign', 'mangrove_hanging_sign', 16),
  gray_terracotta('Gray Terracotta', 'gray_terracotta', 64),
  wither_skeleton_skull('Wither Skeleton Skull', 'wither_skeleton_skull', 64),
  stripped_crimson_hyphae('Stripped Crimson Hyphae', 'stripped_crimson_hyphae', 64),
  carrot('Carrot', 'carrot', 64),
  warped_fungus('Warped Fungus', 'warped_fungus', 64),
  terracotta('Terracotta', 'terracotta', 64),
  cherry_wood('Cherry Wood', 'cherry_wood', 64),
  soul_lantern('Soul Lantern', 'soul_lantern', 64),
  lapis_block('Lapis Block', 'lapis_block', 64),
  blackstone_wall('Blackstone Wall', 'blackstone_wall', 64),
  green_concrete('Green Concrete', 'green_concrete', 64),
  cyan_carpet('Cyan Carpet', 'cyan_carpet', 64),
  warped_sign('Warped Sign', 'warped_sign', 16),
  polished_blackstone_stairs('Polished Blackstone Stairs', 'polished_blackstone_stairs', 64),
  brown_mushroom('Brown Mushroom', 'brown_mushroom', 64),
  cherry_stairs('Cherry Stairs', 'cherry_stairs', 64),
  white_stained_glass_pane('White Stained Glass Pane', 'white_stained_glass_pane', 64),
  spruce_button('Spruce Button', 'spruce_button', 64),
  pale_oak_log('Pale Oak Log', 'pale_oak_log', 64),
  cherry_sapling('Cherry Sapling', 'cherry_sapling', 64),
  gray_stained_glass_pane('Gray Stained Glass Pane', 'gray_stained_glass_pane', 64),
  end_stone_brick_wall('End Stone Brick Wall', 'end_stone_brick_wall', 64),
  cobblestone('Cobblestone', 'cobblestone', 64),
  medium_amethyst_bud('Medium Amethyst Bud', 'medium_amethyst_bud', 64),
  brain_coral('Brain Coral', 'brain_coral', 64),
  birch_trapdoor('Birch Trapdoor', 'birch_trapdoor', 64),
  white_wool('White Wool', 'white_wool', 64),
  pitcher_pod('Pitcher Pod', 'pitcher_pod', 64),
  warped_door('Warped Door', 'warped_door', 64),
  glass('Glass', 'glass', 64),
  oxidized_copper_bulb('Oxidized Copper Bulb', 'oxidized_copper_bulb', 64),
  trapped_chest('Trapped Chest', 'trapped_chest', 64),
  weeping_vines('Weeping Vines', 'weeping_vines', 64),
  cherry_slab('Cherry Slab', 'cherry_slab', 64),
  end_stone_brick_slab('End Stone Brick Slab', 'end_stone_brick_slab', 64),
  green_stained_glass_pane('Green Stained Glass Pane', 'green_stained_glass_pane', 64),
  green_concrete_powder('Green Concrete Powder', 'green_concrete_powder', 64),
  slime_block('Slime Block', 'slime_block', 64),
  polished_blackstone_brick_slab('Polished Blackstone Brick Slab', 'polished_blackstone_brick_slab',
      64),
  bedrock('Bedrock', 'bedrock', 64),
  acacia_sign('Acacia Sign', 'acacia_sign', 16),
  small_amethyst_bud('Small Amethyst Bud', 'small_amethyst_bud', 64),
  bamboo_button('Bamboo Button', 'bamboo_button', 64),
  oxeye_daisy('Oxeye Daisy', 'oxeye_daisy', 64),
  horn_coral('Horn Coral', 'horn_coral', 64),
  polished_tuff_wall('Polished Tuff Wall', 'polished_tuff_wall', 64),
  polished_deepslate('Polished Deepslate', 'polished_deepslate', 64),
  cauldron('Cauldron', 'cauldron', 64),
  jungle_hanging_sign('Jungle Hanging Sign', 'jungle_hanging_sign', 16),
  bamboo_mosaic_slab('Bamboo Mosaic Slab', 'bamboo_mosaic_slab', 64),
  infested_cobblestone('Infested Cobblestone', 'infested_cobblestone', 64),
  heavy_core('Heavy Core', 'heavy_core', 64),
  bricks('Bricks', 'bricks', 64),
  sandstone_wall('Sandstone Wall', 'sandstone_wall', 64),
  warped_pressure_plate('Warped Pressure Plate', 'warped_pressure_plate', 64),
  waxed_exposed_cut_copper_slab('Waxed Exposed Cut Copper Slab', 'waxed_exposed_cut_copper_slab',
      64),
  kelp('Kelp', 'kelp', 64),
  bamboo_fence_gate('Bamboo Fence Gate', 'bamboo_fence_gate', 64),
  amethyst_block('Amethyst Block', 'amethyst_block', 64),
  chain('Chain', 'chain', 64),
  waxed_weathered_copper_door('Waxed Weathered Copper Door', 'waxed_weathered_copper_door', 64),
  cracked_stone_bricks('Cracked Stone Bricks', 'cracked_stone_bricks', 64),
  acacia_leaves('Acacia Leaves', 'acacia_leaves', 64),
  dried_kelp_block('Dried Kelp Block', 'dried_kelp_block', 64),
  cherry_planks('Cherry Planks', 'cherry_planks', 64),
  waxed_weathered_copper_grate('Waxed Weathered Copper Grate', 'waxed_weathered_copper_grate', 64),
  jungle_fence_gate('Jungle Fence Gate', 'jungle_fence_gate', 64),
  black_stained_glass('Black Stained Glass', 'black_stained_glass', 64),
  pink_stained_glass('Pink Stained Glass', 'pink_stained_glass', 64),
  waxed_cut_copper('Waxed Cut Copper', 'waxed_cut_copper', 64),
  raw_gold_block('Raw Gold Block', 'raw_gold_block', 64),
  closed_eyeblossom('Closed Eyeblossom', 'closed_eyeblossom', 64),
  zombie_head('Zombie Head', 'zombie_head', 64),
  gravel('Gravel', 'gravel', 64),
  jukebox('Jukebox', 'jukebox', 64),
  oxidized_cut_copper_slab('Oxidized Cut Copper Slab', 'oxidized_cut_copper_slab', 64),
  stripped_mangrove_wood('Stripped Mangrove Wood', 'stripped_mangrove_wood', 64),
  oak_sign('Oak Sign', 'oak_sign', 16),
  red_sand('Red Sand', 'red_sand', 64),
  light_blue_wool('Light Blue Wool', 'light_blue_wool', 64),
  oak_door('Oak Door', 'oak_door', 64),
  cyan_stained_glass('Cyan Stained Glass', 'cyan_stained_glass', 64),
  light_gray_banner('Light Gray Banner', 'light_gray_banner', 16),
  exposed_copper_trapdoor('Exposed Copper Trapdoor', 'exposed_copper_trapdoor', 64),
  orange_stained_glass_pane('Orange Stained Glass Pane', 'orange_stained_glass_pane', 64),
  light_gray_concrete('Light Gray Concrete', 'light_gray_concrete', 64),
  blue_bed('Blue Bed', 'blue_bed', 1),
  blue_carpet('Blue Carpet', 'blue_carpet', 64),
  dead_tube_coral_block('Dead Tube Coral Block', 'dead_tube_coral_block', 64),
  lime_carpet('Lime Carpet', 'lime_carpet', 64),
  light_gray_bed('Light Gray Bed', 'light_gray_bed', 1),
  gray_carpet('Gray Carpet', 'gray_carpet', 64),
  magenta_glazed_terracotta('Magenta Glazed Terracotta', 'magenta_glazed_terracotta', 64),
  brain_coral_fan('Brain Coral Fan', 'brain_coral_fan', 64),
  deepslate_iron_ore('Deepslate Iron Ore', 'deepslate_iron_ore', 64),
  brown_shulker_box('Brown Shulker Box', 'brown_shulker_box', 1),
  heavy_weighted_pressure_plate('Heavy Weighted Pressure Plate', 'heavy_weighted_pressure_plate',
      64),
  weathered_cut_copper('Weathered Cut Copper', 'weathered_cut_copper', 64),
  pale_oak_sign('Pale Oak Sign', 'pale_oak_sign', 16),
  weathered_chiseled_copper('Weathered Chiseled Copper', 'weathered_chiseled_copper', 64),
  deepslate_gold_ore('Deepslate Gold Ore', 'deepslate_gold_ore', 64),
  jungle_planks('Jungle Planks', 'jungle_planks', 64),
  cyan_concrete_powder('Cyan Concrete Powder', 'cyan_concrete_powder', 64),
  campfire('Campfire', 'campfire', 64),
  spruce_stairs('Spruce Stairs', 'spruce_stairs', 64),
  purpur_stairs('Purpur Stairs', 'purpur_stairs', 64),
  torch('Torch', 'torch', 64),
  birch_fence('Birch Fence', 'birch_fence', 64),
  sandstone_stairs('Sandstone Stairs', 'sandstone_stairs', 64),
  stripped_bamboo_block('Stripped Bamboo Block', 'stripped_bamboo_block', 64),
  magenta_concrete('Magenta Concrete', 'magenta_concrete', 64),
  mud_brick_wall('Mud Brick Wall', 'mud_brick_wall', 64),
  tuff_stairs('Tuff Stairs', 'tuff_stairs', 64),
  light('Light', 'light', 64),
  melon('Melon', 'melon', 64),
  waxed_exposed_copper_trapdoor('Waxed Exposed Copper Trapdoor', 'waxed_exposed_copper_trapdoor',
      64),
  snow_block('Snow Block', 'snow_block', 64),
  player_head('Player Head', 'player_head', 64),
  cracked_nether_bricks('Cracked Nether Bricks', 'cracked_nether_bricks', 64),
  warped_nylium('Warped Nylium', 'warped_nylium', 64),
  mangrove_sign('Mangrove Sign', 'mangrove_sign', 16),
  birch_hanging_sign('Birch Hanging Sign', 'birch_hanging_sign', 16),
  diorite_wall('Diorite Wall', 'diorite_wall', 64),
  cyan_candle('Cyan Candle', 'cyan_candle', 64),
  birch_leaves('Birch Leaves', 'birch_leaves', 64),
  prismarine_brick_slab('Prismarine Brick Slab', 'prismarine_brick_slab', 64),
  anvil('Anvil', 'anvil', 64),
  gray_wool('Gray Wool', 'gray_wool', 64),
  reinforced_deepslate('Reinforced Deepslate', 'reinforced_deepslate', 64),
  chiseled_stone_bricks('Chiseled Stone Bricks', 'chiseled_stone_bricks', 64),
  dead_horn_coral_fan('Dead Horn Coral Fan', 'dead_horn_coral_fan', 64),
  spruce_trapdoor('Spruce Trapdoor', 'spruce_trapdoor', 64),
  brewing_stand('Brewing Stand', 'brewing_stand', 64),
  purple_glazed_terracotta('Purple Glazed Terracotta', 'purple_glazed_terracotta', 64),
  mangrove_planks('Mangrove Planks', 'mangrove_planks', 64),
  copper_bulb('Copper Bulb', 'copper_bulb', 64),
  horn_coral_block('Horn Coral Block', 'horn_coral_block', 64),
  lectern('Lectern', 'lectern', 64),
  glass_pane('Glass Pane', 'glass_pane', 64),
  purple_concrete_powder('Purple Concrete Powder', 'purple_concrete_powder', 64),
  oxidized_copper_door('Oxidized Copper Door', 'oxidized_copper_door', 64),
  andesite_stairs('Andesite Stairs', 'andesite_stairs', 64),
  crimson_slab('Crimson Slab', 'crimson_slab', 64),
  red_carpet('Red Carpet', 'red_carpet', 64),
  pink_petals('Pink Petals', 'pink_petals', 64),
  bamboo('Bamboo', 'bamboo', 64),
  warped_stairs('Warped Stairs', 'warped_stairs', 64),
  red_mushroom_block('Red Mushroom Block', 'red_mushroom_block', 64),
  tuff_brick_slab('Tuff Brick Slab', 'tuff_brick_slab', 64),
  light_blue_stained_glass('Light Blue Stained Glass', 'light_blue_stained_glass', 64),
  dirt_path('Dirt Path', 'dirt_path', 64),
  mangrove_fence_gate('Mangrove Fence Gate', 'mangrove_fence_gate', 64),
  dark_oak_button('Dark Oak Button', 'dark_oak_button', 64),
  pale_oak_door('Pale Oak Door', 'pale_oak_door', 64),
  horn_coral_fan('Horn Coral Fan', 'horn_coral_fan', 64),
  mangrove_wood('Mangrove Wood', 'mangrove_wood', 64),
  white_banner('White Banner', 'white_banner', 16),
  cherry_trapdoor('Cherry Trapdoor', 'cherry_trapdoor', 64),
  lime_concrete_powder('Lime Concrete Powder', 'lime_concrete_powder', 64),
  beehive('Beehive', 'beehive', 64),
  tuff_brick_stairs('Tuff Brick Stairs', 'tuff_brick_stairs', 64),
  wildflowers('Wildflowers', 'wildflowers', 64),
  moss_block('Moss Block', 'moss_block', 64),
  deepslate_tile_slab('Deepslate Tile Slab', 'deepslate_tile_slab', 64),
  gray_candle('Gray Candle', 'gray_candle', 64),
  podzol('Podzol', 'podzol', 64),
  beacon('Beacon', 'beacon', 64),
  quartz_block('Quartz Block', 'quartz_block', 64),
  cartography_table('Cartography Table', 'cartography_table', 64),
  oak_hanging_sign('Oak Hanging Sign', 'oak_hanging_sign', 16),
  spruce_sign('Spruce Sign', 'spruce_sign', 16),
  polished_granite('Polished Granite', 'polished_granite', 64),
  white_terracotta('White Terracotta', 'white_terracotta', 64),
  purple_terracotta('Purple Terracotta', 'purple_terracotta', 64),
  redstone_lamp('Redstone Lamp', 'redstone_lamp', 64),
  pale_oak_wood('Pale Oak Wood', 'pale_oak_wood', 64),
  yellow_stained_glass_pane('Yellow Stained Glass Pane', 'yellow_stained_glass_pane', 64),
  sculk_vein('Sculk Vein', 'sculk_vein', 64),
  acacia_button('Acacia Button', 'acacia_button', 64),
  lime_banner('Lime Banner', 'lime_banner', 16),
  green_terracotta('Green Terracotta', 'green_terracotta', 64),
  red_stained_glass_pane('Red Stained Glass Pane', 'red_stained_glass_pane', 64),
  dark_oak_log('Dark Oak Log', 'dark_oak_log', 64),
  lilac('Lilac', 'lilac', 64),
  torchflower_seeds('Torchflower Seeds', 'torchflower_seeds', 64),
  cherry_leaves('Cherry Leaves', 'cherry_leaves', 64),
  waxed_oxidized_cut_copper('Waxed Oxidized Cut Copper', 'waxed_oxidized_cut_copper', 64),
  dead_fire_coral_block('Dead Fire Coral Block', 'dead_fire_coral_block', 64),
  resin_brick_stairs('Resin Brick Stairs', 'resin_brick_stairs', 64),
  dirt('Dirt', 'dirt', 64),
  netherrack('Netherrack', 'netherrack', 64),
  stripped_cherry_wood('Stripped Cherry Wood', 'stripped_cherry_wood', 64),
  spruce_fence_gate('Spruce Fence Gate', 'spruce_fence_gate', 64),
  resin_block('Resin Block', 'resin_block', 64),
  cactus_flower('Cactus Flower', 'cactus_flower', 64),
  waxed_exposed_copper('Waxed Exposed Copper', 'waxed_exposed_copper', 64),
  pale_hanging_moss('Pale Hanging Moss', 'pale_hanging_moss', 64),
  magenta_concrete_powder('Magenta Concrete Powder', 'magenta_concrete_powder', 64),
  purple_concrete('Purple Concrete', 'purple_concrete', 64),
  rooted_dirt('Rooted Dirt', 'rooted_dirt', 64),
  chiseled_nether_bricks('Chiseled Nether Bricks', 'chiseled_nether_bricks', 64),
  sponge('Sponge', 'sponge', 64),
  structure_void('Structure Void', 'structure_void', 64),
  green_carpet('Green Carpet', 'green_carpet', 64),
  budding_amethyst('Budding Amethyst', 'budding_amethyst', 64),
  dead_horn_coral('Dead Horn Coral', 'dead_horn_coral', 64),
  infested_chiseled_stone_bricks('Infested Chiseled Stone Bricks', 'infested_chiseled_stone_bricks',
      64),
  bamboo_slab('Bamboo Slab', 'bamboo_slab', 64),
  oak_button('Oak Button', 'oak_button', 64),
  dark_oak_wood('Dark Oak Wood', 'dark_oak_wood', 64),
  black_wool('Black Wool', 'black_wool', 64),
  stone_brick_stairs('Stone Brick Stairs', 'stone_brick_stairs', 64),
  mangrove_leaves('Mangrove Leaves', 'mangrove_leaves', 64),
  blue_concrete('Blue Concrete', 'blue_concrete', 64),
  red_stained_glass('Red Stained Glass', 'red_stained_glass', 64),
  polished_blackstone_button('Polished Blackstone Button', 'polished_blackstone_button', 64),
  purpur_pillar('Purpur Pillar', 'purpur_pillar', 64),
  pink_tulip('Pink Tulip', 'pink_tulip', 64),
  oak_planks('Oak Planks', 'oak_planks', 64),
  exposed_copper('Exposed Copper', 'exposed_copper', 64),
  deepslate_bricks('Deepslate Bricks', 'deepslate_bricks', 64),
  mossy_stone_brick_slab('Mossy Stone Brick Slab', 'mossy_stone_brick_slab', 64),
  prismarine_slab('Prismarine Slab', 'prismarine_slab', 64),
  spruce_door('Spruce Door', 'spruce_door', 64),
  smooth_quartz_stairs('Smooth Quartz Stairs', 'smooth_quartz_stairs', 64),
  bamboo_mosaic_stairs('Bamboo Mosaic Stairs', 'bamboo_mosaic_stairs', 64),
  waxed_oxidized_copper_door('Waxed Oxidized Copper Door', 'waxed_oxidized_copper_door', 64),
  black_concrete('Black Concrete', 'black_concrete', 64),
  bamboo_hanging_sign('Bamboo Hanging Sign', 'bamboo_hanging_sign', 16),
  waxed_exposed_copper_door('Waxed Exposed Copper Door', 'waxed_exposed_copper_door', 64),
  cobblestone_wall('Cobblestone Wall', 'cobblestone_wall', 64),
  ender_chest('Ender Chest', 'ender_chest', 64),
  creeper_head('Creeper Head', 'creeper_head', 64),
  polished_tuff_stairs('Polished Tuff Stairs', 'polished_tuff_stairs', 64),
  orange_bed('Orange Bed', 'orange_bed', 1),
  azure_bluet('Azure Bluet', 'azure_bluet', 64),
  piglin_head('Piglin Head', 'piglin_head', 64),
  light_gray_glazed_terracotta('Light Gray Glazed Terracotta', 'light_gray_glazed_terracotta', 64),
  birch_slab('Birch Slab', 'birch_slab', 64),
  ice('Ice', 'ice', 64),
  dark_oak_fence('Dark Oak Fence', 'dark_oak_fence', 64),
  warped_trapdoor('Warped Trapdoor', 'warped_trapdoor', 64),
  acacia_slab('Acacia Slab', 'acacia_slab', 64),
  polished_granite_stairs('Polished Granite Stairs', 'polished_granite_stairs', 64),
  acacia_planks('Acacia Planks', 'acacia_planks', 64),
  lime_concrete('Lime Concrete', 'lime_concrete', 64),
  magenta_candle('Magenta Candle', 'magenta_candle', 64),
  light_blue_stained_glass_pane('Light Blue Stained Glass Pane', 'light_blue_stained_glass_pane',
      64),
  infested_mossy_stone_bricks('Infested Mossy Stone Bricks', 'infested_mossy_stone_bricks', 64),
  dead_brain_coral('Dead Brain Coral', 'dead_brain_coral', 64),
  white_tulip('White Tulip', 'white_tulip', 64),
  oak_log('Oak Log', 'oak_log', 64),
  loom('Loom', 'loom', 64),
  brown_stained_glass_pane('Brown Stained Glass Pane', 'brown_stained_glass_pane', 64),
  fire_coral_fan('Fire Coral Fan', 'fire_coral_fan', 64),
  tuff_slab('Tuff Slab', 'tuff_slab', 64),
  sunflower('Sunflower', 'sunflower', 64),
  white_stained_glass('White Stained Glass', 'white_stained_glass', 64),
  warped_stem('Warped Stem', 'warped_stem', 64),
  nether_brick_stairs('Nether Brick Stairs', 'nether_brick_stairs', 64),
  cut_copper_stairs('Cut Copper Stairs', 'cut_copper_stairs', 64),
  barrier('Barrier', 'barrier', 64),
  crimson_planks('Crimson Planks', 'crimson_planks', 64),
  crimson_door('Crimson Door', 'crimson_door', 64),
  respawn_anchor('Respawn Anchor', 'respawn_anchor', 64),
  black_terracotta('Black Terracotta', 'black_terracotta', 64),
  clay('Clay', 'clay', 64),
  red_sandstone_stairs('Red Sandstone Stairs', 'red_sandstone_stairs', 64),
  nether_brick_wall('Nether Brick Wall', 'nether_brick_wall', 64),
  powered_rail('Powered Rail', 'powered_rail', 64),
  gray_banner('Gray Banner', 'gray_banner', 16),
  rose_bush('Rose Bush', 'rose_bush', 64),
  purple_bed('Purple Bed', 'purple_bed', 1),
  bee_nest('Bee Nest', 'bee_nest', 64),
  activator_rail('Activator Rail', 'activator_rail', 64),
  deepslate_tile_stairs('Deepslate Tile Stairs', 'deepslate_tile_stairs', 64),
  cactus('Cactus', 'cactus', 64),
  light_blue_carpet('Light Blue Carpet', 'light_blue_carpet', 64),
  prismarine_stairs('Prismarine Stairs', 'prismarine_stairs', 64),
  raw_iron_block('Raw Iron Block', 'raw_iron_block', 64),
  light_blue_concrete('Light Blue Concrete', 'light_blue_concrete', 64),
  spruce_pressure_plate('Spruce Pressure Plate', 'spruce_pressure_plate', 64),
  lime_wool('Lime Wool', 'lime_wool', 64),
  waxed_copper_door('Waxed Copper Door', 'waxed_copper_door', 64),
  repeating_command_block('Repeating Command Block', 'repeating_command_block', 64),
  tube_coral_fan('Tube Coral Fan', 'tube_coral_fan', 64),
  bubble_coral_fan('Bubble Coral Fan', 'bubble_coral_fan', 64),
  conduit('Conduit', 'conduit', 64),
  blue_stained_glass_pane('Blue Stained Glass Pane', 'blue_stained_glass_pane', 64),
  gray_shulker_box('Gray Shulker Box', 'gray_shulker_box', 1),
  powder_snow_bucket('Powder Snow Bucket', 'powder_snow_bucket', 1),
  smooth_quartz('Smooth Quartz', 'smooth_quartz', 64),
  oak_stairs('Oak Stairs', 'oak_stairs', 64),
  white_glazed_terracotta('White Glazed Terracotta', 'white_glazed_terracotta', 64),
  poppy('Poppy', 'poppy', 64),
  sea_lantern('Sea Lantern', 'sea_lantern', 64),
  light_blue_terracotta('Light Blue Terracotta', 'light_blue_terracotta', 64),
  coal_ore('Coal Ore', 'coal_ore', 64),
  white_candle('White Candle', 'white_candle', 64),
  dripstone_block('Dripstone Block', 'dripstone_block', 64),
  polished_blackstone_bricks('Polished Blackstone Bricks', 'polished_blackstone_bricks', 64),
  snow('Snow', 'snow', 64),
  crimson_hanging_sign('Crimson Hanging Sign', 'crimson_hanging_sign', 16),
  orange_tulip('Orange Tulip', 'orange_tulip', 64),
  sculk_shrieker('Sculk Shrieker', 'sculk_shrieker', 64),
  orange_carpet('Orange Carpet', 'orange_carpet', 64),
  waxed_oxidized_chiseled_copper('Waxed Oxidized Chiseled Copper', 'waxed_oxidized_chiseled_copper',
      64),
  blackstone_slab('Blackstone Slab', 'blackstone_slab', 64),
  flowering_azalea_leaves('Flowering Azalea Leaves', 'flowering_azalea_leaves', 64),
  blue_banner('Blue Banner', 'blue_banner', 16),
  waxed_oxidized_copper_grate('Waxed Oxidized Copper Grate', 'waxed_oxidized_copper_grate', 64),
  tube_coral_block('Tube Coral Block', 'tube_coral_block', 64),
  furnace('Furnace', 'furnace', 64),
  yellow_terracotta('Yellow Terracotta', 'yellow_terracotta', 64),
  crimson_stem('Crimson Stem', 'crimson_stem', 64),
  crimson_pressure_plate('Crimson Pressure Plate', 'crimson_pressure_plate', 64),
  red_sandstone_slab('Red Sandstone Slab', 'red_sandstone_slab', 64);

  final String displayName;
  final String material;
  final int maxStackSize;

  const BlockMaterial(this.displayName, this.material, this.maxStackSize);

}