/// The file is generated. Don't change anything here
enum BlockMaterial {

  redConcrete('Red Concrete', 'minecraft:red_concrete', 64),
  deadBrainCoralBlock('Dead Brain Coral Block', 'minecraft:dead_brain_coral_block', 64),
  darkOakLog('Dark Oak Log', 'minecraft:dark_oak_log', 64),
  mossyCobblestoneSlab('Mossy Cobblestone Slab', 'minecraft:mossy_cobblestone_slab', 64),
  farmland('Farmland', 'minecraft:farmland', 64),
  jungleShelf('Jungle Shelf', 'minecraft:jungle_shelf', 64),
  mudBrickStairs('Mud Brick Stairs', 'minecraft:mud_brick_stairs', 64),
  weatheredCopperBars('Weathered Copper Bars', 'minecraft:weathered_copper_bars', 64),
  wetSponge('Wet Sponge', 'minecraft:wet_sponge', 64),
  lightGrayStainedGlass('Light Gray Stained Glass', 'minecraft:light_gray_stained_glass', 64),
  waxedCutCopperSlab('Waxed Cut Copper Slab', 'minecraft:waxed_cut_copper_slab', 64),
  cherryButton('Cherry Button', 'minecraft:cherry_button', 64),
  spruceButton('Spruce Button', 'minecraft:spruce_button', 64),
  azureBluet('Azure Bluet', 'minecraft:azure_bluet', 64),
  smoker('Smoker', 'minecraft:smoker', 64),
  birchHangingSign('Birch Hanging Sign', 'minecraft:birch_hanging_sign', 16),
  paleOakFenceGate('Pale Oak Fence Gate', 'minecraft:pale_oak_fence_gate', 64),
  purpurPillar('Purpur Pillar', 'minecraft:purpur_pillar', 64),
  mangrovePlanks('Mangrove Planks', 'minecraft:mangrove_planks', 64),
  limeGlazedTerracotta('Lime Glazed Terracotta', 'minecraft:lime_glazed_terracotta', 64),
  deadHornCoralBlock('Dead Horn Coral Block', 'minecraft:dead_horn_coral_block', 64),
  deadBubbleCoralFan('Dead Bubble Coral Fan', 'minecraft:dead_bubble_coral_fan', 64),
  ironBlock('Iron Block', 'minecraft:iron_block', 64),
  deepslateIronOre('Deepslate Iron Ore', 'minecraft:deepslate_iron_ore', 64),
  dragonEgg('Dragon Egg', 'minecraft:dragon_egg', 64),
  cocoaBeans('Cocoa Beans', 'minecraft:cocoa_beans', 64),
  chorusPlant('Chorus Plant', 'minecraft:chorus_plant', 64),
  deadFireCoralBlock('Dead Fire Coral Block', 'minecraft:dead_fire_coral_block', 64),
  magentaCarpet('Magenta Carpet', 'minecraft:magenta_carpet', 64),
  purpurSlab('Purpur Slab', 'minecraft:purpur_slab', 64),
  tallGrass('Tall Grass', 'minecraft:tall_grass', 64),
  strippedJungleWood('Stripped Jungle Wood', 'minecraft:stripped_jungle_wood', 64),
  polishedAndesite('Polished Andesite', 'minecraft:polished_andesite', 64),
  spawner('Spawner', 'minecraft:spawner', 64),
  birchPressurePlate('Birch Pressure Plate', 'minecraft:birch_pressure_plate', 64),
  lightGrayCandle('Light Gray Candle', 'minecraft:light_gray_candle', 64),
  infestedStone('Infested Stone', 'minecraft:infested_stone', 64),
  oxidizedCopperChest('Oxidized Copper Chest', 'minecraft:oxidized_copper_chest', 64),
  birchStairs('Birch Stairs', 'minecraft:birch_stairs', 64),
  warpedDoor('Warped Door', 'minecraft:warped_door', 64),
  paleOakLeaves('Pale Oak Leaves', 'minecraft:pale_oak_leaves', 64),
  lightGrayBed('Light Gray Bed', 'minecraft:light_gray_bed', 1),
  weatheredCopperGolemStatue('Weathered Copper Golem Statue',
      'minecraft:weathered_copper_golem_statue', 64),
  sprucePlanks('Spruce Planks', 'minecraft:spruce_planks', 64),
  coalOre('Coal Ore', 'minecraft:coal_ore', 64),
  waxedCopperChest('Waxed Copper Chest', 'minecraft:waxed_copper_chest', 64),
  cobblestoneSlab('Cobblestone Slab', 'minecraft:cobblestone_slab', 64),
  soulCampfire('Soul Campfire', 'minecraft:soul_campfire', 64),
  spruceHangingSign('Spruce Hanging Sign', 'minecraft:spruce_hanging_sign', 16),
  pinkShulkerBox('Pink Shulker Box', 'minecraft:pink_shulker_box', 1),
  bambooPressurePlate('Bamboo Pressure Plate', 'minecraft:bamboo_pressure_plate', 64),
  warpedStairs('Warped Stairs', 'minecraft:warped_stairs', 64),
  oakHangingSign('Oak Hanging Sign', 'minecraft:oak_hanging_sign', 16),
  mangroveLeaves('Mangrove Leaves', 'minecraft:mangrove_leaves', 64),
  honeyBlock('Honey Block', 'minecraft:honey_block', 64),
  chippedAnvil('Chipped Anvil', 'minecraft:chipped_anvil', 64),
  cherryFence('Cherry Fence', 'minecraft:cherry_fence', 64),
  noteBlock('Note Block', 'minecraft:note_block', 64),
  sulfurBricks('Sulfur Bricks', 'minecraft:sulfur_bricks', 64),
  cobblestoneWall('Cobblestone Wall', 'minecraft:cobblestone_wall', 64),
  smoothRedSandstoneSlab('Smooth Red Sandstone Slab', 'minecraft:smooth_red_sandstone_slab', 64),
  jukebox('Jukebox', 'minecraft:jukebox', 64),
  stone('Stone', 'minecraft:stone', 64),
  polishedBlackstonePressurePlate('Polished Blackstone Pressure Plate',
      'minecraft:polished_blackstone_pressure_plate', 64),
  waxedOxidizedChiseledCopper('Waxed Oxidized Chiseled Copper',
      'minecraft:waxed_oxidized_chiseled_copper', 64),
  copperTrapdoor('Copper Trapdoor', 'minecraft:copper_trapdoor', 64),
  blackShulkerBox('Black Shulker Box', 'minecraft:black_shulker_box', 1),
  oakSign('Oak Sign', 'minecraft:oak_sign', 16),
  stoneSlab('Stone Slab', 'minecraft:stone_slab', 64),
  mossyStoneBrickWall('Mossy Stone Brick Wall', 'minecraft:mossy_stone_brick_wall', 64),
  cherrySlab('Cherry Slab', 'minecraft:cherry_slab', 64),
  cyanBed('Cyan Bed', 'minecraft:cyan_bed', 1),
  tuffBrickSlab('Tuff Brick Slab', 'minecraft:tuff_brick_slab', 64),
  pinkPetals('Pink Petals', 'minecraft:pink_petals', 64),
  cyanTerracotta('Cyan Terracotta', 'minecraft:cyan_terracotta', 64),
  sandstoneStairs('Sandstone Stairs', 'minecraft:sandstone_stairs', 64),
  waxedExposedCopper('Waxed Exposed Copper', 'minecraft:waxed_exposed_copper', 64),
  waxedExposedCopperChest('Waxed Exposed Copper Chest', 'minecraft:waxed_exposed_copper_chest', 64),
  tintedGlass('Tinted Glass', 'minecraft:tinted_glass', 64),
  suspiciousSand('Suspicious Sand', 'minecraft:suspicious_sand', 64),
  spruceFenceGate('Spruce Fence Gate', 'minecraft:spruce_fence_gate', 64),
  darkOakShelf('Dark Oak Shelf', 'minecraft:dark_oak_shelf', 64),
  weatheredCopper('Weathered Copper', 'minecraft:weathered_copper', 64),
  paleMossBlock('Pale Moss Block', 'minecraft:pale_moss_block', 64),
  pinkStainedGlass('Pink Stained Glass', 'minecraft:pink_stained_glass', 64),
  prismarineStairs('Prismarine Stairs', 'minecraft:prismarine_stairs', 64),
  bubbleCoralFan('Bubble Coral Fan', 'minecraft:bubble_coral_fan', 64),
  cobbledDeepslateSlab('Cobbled Deepslate Slab', 'minecraft:cobbled_deepslate_slab', 64),
  redNetherBrickSlab('Red Nether Brick Slab', 'minecraft:red_nether_brick_slab', 64),
  smoothSandstoneSlab('Smooth Sandstone Slab', 'minecraft:smooth_sandstone_slab', 64),
  blueTerracotta('Blue Terracotta', 'minecraft:blue_terracotta', 64),
  dragonHead('Dragon Head', 'minecraft:dragon_head', 64),
  blackStainedGlass('Black Stained Glass', 'minecraft:black_stained_glass', 64),
  chiseledNetherBricks('Chiseled Nether Bricks', 'minecraft:chiseled_nether_bricks', 64),
  polishedBasalt('Polished Basalt', 'minecraft:polished_basalt', 64),
  deepslateBrickStairs('Deepslate Brick Stairs', 'minecraft:deepslate_brick_stairs', 64),
  ancientDebris('Ancient Debris', 'minecraft:ancient_debris', 64),
  magmaBlock('Magma Block', 'minecraft:magma_block', 64),
  blueBanner('Blue Banner', 'minecraft:blue_banner', 16),
  orangeTerracotta('Orange Terracotta', 'minecraft:orange_terracotta', 64),
  deepslateTileWall('Deepslate Tile Wall', 'minecraft:deepslate_tile_wall', 64),
  orangeStainedGlass('Orange Stained Glass', 'minecraft:orange_stained_glass', 64),
  junglePressurePlate('Jungle Pressure Plate', 'minecraft:jungle_pressure_plate', 64),
  packedMud('Packed Mud', 'minecraft:packed_mud', 64),
  paleOakSign('Pale Oak Sign', 'minecraft:pale_oak_sign', 16),
  diamondBlock('Diamond Block', 'minecraft:diamond_block', 64),
  yellowCandle('Yellow Candle', 'minecraft:yellow_candle', 64),
  deepslateBrickSlab('Deepslate Brick Slab', 'minecraft:deepslate_brick_slab', 64),
  pumpkin('Pumpkin', 'minecraft:pumpkin', 64),
  snifferEgg('Sniffer Egg', 'minecraft:sniffer_egg', 64),
  structureVoid('Structure Void', 'minecraft:structure_void', 64),
  netherWartBlock('Nether Wart Block', 'minecraft:nether_wart_block', 64),
  lightBlueStainedGlass('Light Blue Stained Glass', 'minecraft:light_blue_stained_glass', 64),
  warpedTrapdoor('Warped Trapdoor', 'minecraft:warped_trapdoor', 64),
  crimsonPressurePlate('Crimson Pressure Plate', 'minecraft:crimson_pressure_plate', 64),
  strippedBirchLog('Stripped Birch Log', 'minecraft:stripped_birch_log', 64),
  cinnabarBrickStairs('Cinnabar Brick Stairs', 'minecraft:cinnabar_brick_stairs', 64),
  hayBlock('Hay Block', 'minecraft:hay_block', 64),
  gravel('Gravel', 'minecraft:gravel', 64),
  ironChain('Iron Chain', 'minecraft:iron_chain', 64),
  lightBlueCandle('Light Blue Candle', 'minecraft:light_blue_candle', 64),
  polishedDioriteSlab('Polished Diorite Slab', 'minecraft:polished_diorite_slab', 64),
  oxidizedCopperBulb('Oxidized Copper Bulb', 'minecraft:oxidized_copper_bulb', 64),
  oxeyeDaisy('Oxeye Daisy', 'minecraft:oxeye_daisy', 64),
  grayStainedGlassPane('Gray Stained Glass Pane', 'minecraft:gray_stained_glass_pane', 64),
  shortDryGrass('Short Dry Grass', 'minecraft:short_dry_grass', 64),
  blackTerracotta('Black Terracotta', 'minecraft:black_terracotta', 64),
  darkOakFence('Dark Oak Fence', 'minecraft:dark_oak_fence', 64),
  mossyCobblestoneStairs('Mossy Cobblestone Stairs', 'minecraft:mossy_cobblestone_stairs', 64),
  boneBlock('Bone Block', 'minecraft:bone_block', 64),
  brownMushroom('Brown Mushroom', 'minecraft:brown_mushroom', 64),
  grayCandle('Gray Candle', 'minecraft:gray_candle', 64),
  redMushroomBlock('Red Mushroom Block', 'minecraft:red_mushroom_block', 64),
  purpurStairs('Purpur Stairs', 'minecraft:purpur_stairs', 64),
  junglePlanks('Jungle Planks', 'minecraft:jungle_planks', 64),
  waxedOxidizedCopperBulb('Waxed Oxidized Copper Bulb', 'minecraft:waxed_oxidized_copper_bulb', 64),
  strippedDarkOakWood('Stripped Dark Oak Wood', 'minecraft:stripped_dark_oak_wood', 64),
  redSandstoneStairs('Red Sandstone Stairs', 'minecraft:red_sandstone_stairs', 64),
  endStoneBrickSlab('End Stone Brick Slab', 'minecraft:end_stone_brick_slab', 64),
  paleOakWood('Pale Oak Wood', 'minecraft:pale_oak_wood', 64),
  bigDripleaf('Big Dripleaf', 'minecraft:big_dripleaf', 64),
  endRod('End Rod', 'minecraft:end_rod', 64),
  melon('Melon', 'minecraft:melon', 64),
  deadTubeCoralFan('Dead Tube Coral Fan', 'minecraft:dead_tube_coral_fan', 64),
  stoneBrickSlab('Stone Brick Slab', 'minecraft:stone_brick_slab', 64),
  bambooShelf('Bamboo Shelf', 'minecraft:bamboo_shelf', 64),
  whiteConcrete('White Concrete', 'minecraft:white_concrete', 64),
  cutSandstone('Cut Sandstone', 'minecraft:cut_sandstone', 64),
  darkPrismarineSlab('Dark Prismarine Slab', 'minecraft:dark_prismarine_slab', 64),
  strippedWarpedHyphae('Stripped Warped Hyphae', 'minecraft:stripped_warped_hyphae', 64),
  purpleCandle('Purple Candle', 'minecraft:purple_candle', 64),
  waxedOxidizedCopperLantern('Waxed Oxidized Copper Lantern',
      'minecraft:waxed_oxidized_copper_lantern', 64),
  sulfurBrickWall('Sulfur Brick Wall', 'minecraft:sulfur_brick_wall', 64),
  waxedCopperBulb('Waxed Copper Bulb', 'minecraft:waxed_copper_bulb', 64),
  blueBed('Blue Bed', 'minecraft:blue_bed', 1),
  darkOakWood('Dark Oak Wood', 'minecraft:dark_oak_wood', 64),
  polishedTuffSlab('Polished Tuff Slab', 'minecraft:polished_tuff_slab', 64),
  waxedExposedCopperDoor('Waxed Exposed Copper Door', 'minecraft:waxed_exposed_copper_door', 64),
  deepslateCopperOre('Deepslate Copper Ore', 'minecraft:deepslate_copper_ore', 64),
  waxedLightningRod('Waxed Lightning Rod', 'minecraft:waxed_lightning_rod', 64),
  spruceLeaves('Spruce Leaves', 'minecraft:spruce_leaves', 64),
  waxedWeatheredCopperGrate('Waxed Weathered Copper Grate',
      'minecraft:waxed_weathered_copper_grate', 64),
  seaPickle('Sea Pickle', 'minecraft:sea_pickle', 64),
  deepslateCoalOre('Deepslate Coal Ore', 'minecraft:deepslate_coal_ore', 64),
  yellowWool('Yellow Wool', 'minecraft:yellow_wool', 64),
  darkOakDoor('Dark Oak Door', 'minecraft:dark_oak_door', 64),
  blackConcretePowder('Black Concrete Powder', 'minecraft:black_concrete_powder', 64),
  polishedGraniteStairs('Polished Granite Stairs', 'minecraft:polished_granite_stairs', 64),
  magentaBanner('Magenta Banner', 'minecraft:magenta_banner', 16),
  deepslateTileSlab('Deepslate Tile Slab', 'minecraft:deepslate_tile_slab', 64),
  blackCandle('Black Candle', 'minecraft:black_candle', 64),
  copperGrate('Copper Grate', 'minecraft:copper_grate', 64),
  cinnabarBricks('Cinnabar Bricks', 'minecraft:cinnabar_bricks', 64),
  hangingRoots('Hanging Roots', 'minecraft:hanging_roots', 64),
  redShulkerBox('Red Shulker Box', 'minecraft:red_shulker_box', 1),
  waxedOxidizedCutCopper('Waxed Oxidized Cut Copper', 'minecraft:waxed_oxidized_cut_copper', 64),
  redstone('Redstone', 'minecraft:redstone', 64),
  blackCarpet('Black Carpet', 'minecraft:black_carpet', 64),
  jungleButton('Jungle Button', 'minecraft:jungle_button', 64),
  sand('Sand', 'minecraft:sand', 64),
  waxedOxidizedCopperChest('Waxed Oxidized Copper Chest', 'minecraft:waxed_oxidized_copper_chest',
      64),
  yellowStainedGlass('Yellow Stained Glass', 'minecraft:yellow_stained_glass', 64),
  leafLitter('Leaf Litter', 'minecraft:leaf_litter', 64),
  pitcherPod('Pitcher Pod', 'minecraft:pitcher_pod', 64),
  brownConcretePowder('Brown Concrete Powder', 'minecraft:brown_concrete_powder', 64),
  pinkCandle('Pink Candle', 'minecraft:pink_candle', 64),
  smoothRedSandstoneStairs('Smooth Red Sandstone Stairs', 'minecraft:smooth_red_sandstone_stairs',
      64),
  cinnabarBrickWall('Cinnabar Brick Wall', 'minecraft:cinnabar_brick_wall', 64),
  structureBlock('Structure Block', 'minecraft:structure_block', 64),
  polishedDeepslateStairs('Polished Deepslate Stairs', 'minecraft:polished_deepslate_stairs', 64),
  azalea('Azalea', 'minecraft:azalea', 64),
  lightBlueStainedGlassPane('Light Blue Stained Glass Pane',
      'minecraft:light_blue_stained_glass_pane', 64),
  darkOakLeaves('Dark Oak Leaves', 'minecraft:dark_oak_leaves', 64),
  birchSlab('Birch Slab', 'minecraft:birch_slab', 64),
  jackOLantern('Jack O Lantern', 'minecraft:jack_o_lantern', 64),
  bambooPlanks('Bamboo Planks', 'minecraft:bamboo_planks', 64),
  cherryTrapdoor('Cherry Trapdoor', 'minecraft:cherry_trapdoor', 64),
  bambooBlock('Bamboo Block', 'minecraft:bamboo_block', 64),
  greenBed('Green Bed', 'minecraft:green_bed', 1),
  bambooFence('Bamboo Fence', 'minecraft:bamboo_fence', 64),
  lightBlueWool('Light Blue Wool', 'minecraft:light_blue_wool', 64),
  lodestone('Lodestone', 'minecraft:lodestone', 64),
  goldenDandelion('Golden Dandelion', 'minecraft:golden_dandelion', 64),
  tubeCoralBlock('Tube Coral Block', 'minecraft:tube_coral_block', 64),
  warpedHangingSign('Warped Hanging Sign', 'minecraft:warped_hanging_sign', 16),
  weatheredCopperGrate('Weathered Copper Grate', 'minecraft:weathered_copper_grate', 64),
  cherryLog('Cherry Log', 'minecraft:cherry_log', 64),
  waxedOxidizedCopperTrapdoor('Waxed Oxidized Copper Trapdoor',
      'minecraft:waxed_oxidized_copper_trapdoor', 64),
  sporeBlossom('Spore Blossom', 'minecraft:spore_blossom', 64),
  cauldron('Cauldron', 'minecraft:cauldron', 64),
  hornCoralBlock('Horn Coral Block', 'minecraft:horn_coral_block', 64),
  orangeBanner('Orange Banner', 'minecraft:orange_banner', 16),
  activatorRail('Activator Rail', 'minecraft:activator_rail', 64),
  scaffolding('Scaffolding', 'minecraft:scaffolding', 64),
  melonSeeds('Melon Seeds', 'minecraft:melon_seeds', 64),
  oxidizedCopperChain('Oxidized Copper Chain', 'minecraft:oxidized_copper_chain', 64),
  pinkWool('Pink Wool', 'minecraft:pink_wool', 64),
  redBed('Red Bed', 'minecraft:red_bed', 1),
  cutRedSandstone('Cut Red Sandstone', 'minecraft:cut_red_sandstone', 64),
  seagrass('Seagrass', 'minecraft:seagrass', 64),
  waxedOxidizedCopperGrate('Waxed Oxidized Copper Grate', 'minecraft:waxed_oxidized_copper_grate',
      64),
  sponge('Sponge', 'minecraft:sponge', 64),
  weatheredCopperTrapdoor('Weathered Copper Trapdoor', 'minecraft:weathered_copper_trapdoor', 64),
  oxidizedCutCopper('Oxidized Cut Copper', 'minecraft:oxidized_cut_copper', 64),
  lightGrayStainedGlassPane('Light Gray Stained Glass Pane',
      'minecraft:light_gray_stained_glass_pane', 64),
  tubeCoral('Tube Coral', 'minecraft:tube_coral', 64),
  polishedBlackstoneBricks('Polished Blackstone Bricks', 'minecraft:polished_blackstone_bricks',
      64),
  emeraldBlock('Emerald Block', 'minecraft:emerald_block', 64),
  mangroveFence('Mangrove Fence', 'minecraft:mangrove_fence', 64),
  acaciaSign('Acacia Sign', 'minecraft:acacia_sign', 16),
  lilac('Lilac', 'minecraft:lilac', 64),
  obsidian('Obsidian', 'minecraft:obsidian', 64),
  cake('Cake', 'minecraft:cake', 1),
  glowLichen('Glow Lichen', 'minecraft:glow_lichen', 64),
  lantern('Lantern', 'minecraft:lantern', 64),
  acaciaStairs('Acacia Stairs', 'minecraft:acacia_stairs', 64),
  polishedGraniteSlab('Polished Granite Slab', 'minecraft:polished_granite_slab', 64),
  bricks('Bricks', 'minecraft:bricks', 64),
  grayShulkerBox('Gray Shulker Box', 'minecraft:gray_shulker_box', 1),
  sculkVein('Sculk Vein', 'minecraft:sculk_vein', 64),
  chiseledResinBricks('Chiseled Resin Bricks', 'minecraft:chiseled_resin_bricks', 64),
  trialSpawner('Trial Spawner', 'minecraft:trial_spawner', 64),
  redSandstoneSlab('Red Sandstone Slab', 'minecraft:red_sandstone_slab', 64),
  cactus('Cactus', 'minecraft:cactus', 64),
  bell('Bell', 'minecraft:bell', 64),
  oxidizedChiseledCopper('Oxidized Chiseled Copper', 'minecraft:oxidized_chiseled_copper', 64),
  blastFurnace('Blast Furnace', 'minecraft:blast_furnace', 64),
  oakPressurePlate('Oak Pressure Plate', 'minecraft:oak_pressure_plate', 64),
  beeNest('Bee Nest', 'minecraft:bee_nest', 64),
  basalt('Basalt', 'minecraft:basalt', 64),
  resinClump('Resin Clump', 'minecraft:resin_clump', 64),
  pinkTerracotta('Pink Terracotta', 'minecraft:pink_terracotta', 64),
  twistingVines('Twisting Vines', 'minecraft:twisting_vines', 64),
  commandBlock('Command Block', 'minecraft:command_block', 64),
  whiteStainedGlass('White Stained Glass', 'minecraft:white_stained_glass', 64),
  magentaBed('Magenta Bed', 'minecraft:magenta_bed', 1),
  blackBed('Black Bed', 'minecraft:black_bed', 1),
  chiseledBookshelf('Chiseled Bookshelf', 'minecraft:chiseled_bookshelf', 64),
  endStone('End Stone', 'minecraft:end_stone', 64),
  glassPane('Glass Pane', 'minecraft:glass_pane', 64),
  paleOakLog('Pale Oak Log', 'minecraft:pale_oak_log', 64),
  damagedAnvil('Damaged Anvil', 'minecraft:damaged_anvil', 64),
  cyanGlazedTerracotta('Cyan Glazed Terracotta', 'minecraft:cyan_glazed_terracotta', 64),
  bambooMosaicStairs('Bamboo Mosaic Stairs', 'minecraft:bamboo_mosaic_stairs', 64),
  resinBrickStairs('Resin Brick Stairs', 'minecraft:resin_brick_stairs', 64),
  yellowStainedGlassPane('Yellow Stained Glass Pane', 'minecraft:yellow_stained_glass_pane', 64),
  mangroveTrapdoor('Mangrove Trapdoor', 'minecraft:mangrove_trapdoor', 64),
  glowstone('Glowstone', 'minecraft:glowstone', 64),
  purpleBanner('Purple Banner', 'minecraft:purple_banner', 16),
  waxedCutCopperStairs('Waxed Cut Copper Stairs', 'minecraft:waxed_cut_copper_stairs', 64),
  oakShelf('Oak Shelf', 'minecraft:oak_shelf', 64),
  copperGolemStatue('Copper Golem Statue', 'minecraft:copper_golem_statue', 64),
  chorusFlower('Chorus Flower', 'minecraft:chorus_flower', 64),
  dripstoneBlock('Dripstone Block', 'minecraft:dripstone_block', 64),
  creeperHead('Creeper Head', 'minecraft:creeper_head', 64),
  comparator('Comparator', 'minecraft:comparator', 64),
  crackedStoneBricks('Cracked Stone Bricks', 'minecraft:cracked_stone_bricks', 64),
  acaciaPressurePlate('Acacia Pressure Plate', 'minecraft:acacia_pressure_plate', 64),
  polishedBlackstoneSlab('Polished Blackstone Slab', 'minecraft:polished_blackstone_slab', 64),
  warpedFence('Warped Fence', 'minecraft:warped_fence', 64),
  jungleSign('Jungle Sign', 'minecraft:jungle_sign', 16),
  darkOakPlanks('Dark Oak Planks', 'minecraft:dark_oak_planks', 64),
  whiteCandle('White Candle', 'minecraft:white_candle', 64),
  lightBlueCarpet('Light Blue Carpet', 'minecraft:light_blue_carpet', 64),
  brownBanner('Brown Banner', 'minecraft:brown_banner', 16),
  birchDoor('Birch Door', 'minecraft:birch_door', 64),
  cherrySign('Cherry Sign', 'minecraft:cherry_sign', 16),
  weatheredChiseledCopper('Weathered Chiseled Copper', 'minecraft:weathered_chiseled_copper', 64),
  warpedShelf('Warped Shelf', 'minecraft:warped_shelf', 64),
  paleOakShelf('Pale Oak Shelf', 'minecraft:pale_oak_shelf', 64),
  pointedDripstone('Pointed Dripstone', 'minecraft:pointed_dripstone', 64),
  darkOakStairs('Dark Oak Stairs', 'minecraft:dark_oak_stairs', 64),
  limeCarpet('Lime Carpet', 'minecraft:lime_carpet', 64),
  netherWart('Nether Wart', 'minecraft:nether_wart', 64),
  polishedBlackstoneBrickWall('Polished Blackstone Brick Wall',
      'minecraft:polished_blackstone_brick_wall', 64),
  stoneStairs('Stone Stairs', 'minecraft:stone_stairs', 64),
  darkPrismarineStairs('Dark Prismarine Stairs', 'minecraft:dark_prismarine_stairs', 64),
  paleOakHangingSign('Pale Oak Hanging Sign', 'minecraft:pale_oak_hanging_sign', 16),
  goldBlock('Gold Block', 'minecraft:gold_block', 64),
  waxedCutCopper('Waxed Cut Copper', 'minecraft:waxed_cut_copper', 64),
  rootedDirt('Rooted Dirt', 'minecraft:rooted_dirt', 64),
  honeycombBlock('Honeycomb Block', 'minecraft:honeycomb_block', 64),
  waxedCopperGolemStatue('Waxed Copper Golem Statue', 'minecraft:waxed_copper_golem_statue', 64),
  paleOakTrapdoor('Pale Oak Trapdoor', 'minecraft:pale_oak_trapdoor', 64),
  chiseledPolishedBlackstone('Chiseled Polished Blackstone',
      'minecraft:chiseled_polished_blackstone', 64),
  brickSlab('Brick Slab', 'minecraft:brick_slab', 64),
  cherryDoor('Cherry Door', 'minecraft:cherry_door', 64),
  bedrock('Bedrock', 'minecraft:bedrock', 64),
  pumpkinSeeds('Pumpkin Seeds', 'minecraft:pumpkin_seeds', 64),
  waxedExposedCutCopperSlab('Waxed Exposed Cut Copper Slab',
      'minecraft:waxed_exposed_cut_copper_slab', 64),
  oakLeaves('Oak Leaves', 'minecraft:oak_leaves', 64),
  sunflower('Sunflower', 'minecraft:sunflower', 64),
  chiseledCinnabar('Chiseled Cinnabar', 'minecraft:chiseled_cinnabar', 64),
  birchWood('Birch Wood', 'minecraft:birch_wood', 64),
  birchFenceGate('Birch Fence Gate', 'minecraft:birch_fence_gate', 64),
  bambooMosaicSlab('Bamboo Mosaic Slab', 'minecraft:bamboo_mosaic_slab', 64),
  blackGlazedTerracotta('Black Glazed Terracotta', 'minecraft:black_glazed_terracotta', 64),
  acaciaSlab('Acacia Slab', 'minecraft:acacia_slab', 64),
  bambooStairs('Bamboo Stairs', 'minecraft:bamboo_stairs', 64),
  observer('Observer', 'minecraft:observer', 64),
  playerHead('Player Head', 'minecraft:player_head', 64),
  cyanStainedGlassPane('Cyan Stained Glass Pane', 'minecraft:cyan_stained_glass_pane', 64),
  warpedStem('Warped Stem', 'minecraft:warped_stem', 64),
  ice('Ice', 'minecraft:ice', 64),
  jungleStairs('Jungle Stairs', 'minecraft:jungle_stairs', 64),
  crimsonStairs('Crimson Stairs', 'minecraft:crimson_stairs', 64),
  smoothQuartzSlab('Smooth Quartz Slab', 'minecraft:smooth_quartz_slab', 64),
  rawCopperBlock('Raw Copper Block', 'minecraft:raw_copper_block', 64),
  beetrootSeeds('Beetroot Seeds', 'minecraft:beetroot_seeds', 64),
  dioriteSlab('Diorite Slab', 'minecraft:diorite_slab', 64),
  crimsonPlanks('Crimson Planks', 'minecraft:crimson_planks', 64),
  redSandstoneWall('Red Sandstone Wall', 'minecraft:red_sandstone_wall', 64),
  tuff('Tuff', 'minecraft:tuff', 64),
  andesiteSlab('Andesite Slab', 'minecraft:andesite_slab', 64),
  sulfurStairs('Sulfur Stairs', 'minecraft:sulfur_stairs', 64),
  yellowCarpet('Yellow Carpet', 'minecraft:yellow_carpet', 64),
  redCandle('Red Candle', 'minecraft:red_candle', 64),
  whiteBanner('White Banner', 'minecraft:white_banner', 16),
  andesite('Andesite', 'minecraft:andesite', 64),
  quartzSlab('Quartz Slab', 'minecraft:quartz_slab', 64),
  oxidizedLightningRod('Oxidized Lightning Rod', 'minecraft:oxidized_lightning_rod', 64),
  infestedMossyStoneBricks('Infested Mossy Stone Bricks', 'minecraft:infested_mossy_stone_bricks',
      64),
  infestedCobblestone('Infested Cobblestone', 'minecraft:infested_cobblestone', 64),
  purpleCarpet('Purple Carpet', 'minecraft:purple_carpet', 64),
  andesiteWall('Andesite Wall', 'minecraft:andesite_wall', 64),
  verdantFroglight('Verdant Froglight', 'minecraft:verdant_froglight', 64),
  crimsonNylium('Crimson Nylium', 'minecraft:crimson_nylium', 64),
  deepslateTileStairs('Deepslate Tile Stairs', 'minecraft:deepslate_tile_stairs', 64),
  deadFireCoralFan('Dead Fire Coral Fan', 'minecraft:dead_fire_coral_fan', 64),
  openEyeblossom('Open Eyeblossom', 'minecraft:open_eyeblossom', 64),
  vault('Vault', 'minecraft:vault', 64),
  closedEyeblossom('Closed Eyeblossom', 'minecraft:closed_eyeblossom', 64),
  netherrack('Netherrack', 'minecraft:netherrack', 64),
  polishedCinnabarStairs('Polished Cinnabar Stairs', 'minecraft:polished_cinnabar_stairs', 64),
  weatheredCutCopperStairs('Weathered Cut Copper Stairs', 'minecraft:weathered_cut_copper_stairs',
      64),
  shroomlight('Shroomlight', 'minecraft:shroomlight', 64),
  greenGlazedTerracotta('Green Glazed Terracotta', 'minecraft:green_glazed_terracotta', 64),
  strippedAcaciaLog('Stripped Acacia Log', 'minecraft:stripped_acacia_log', 64),
  crimsonHyphae('Crimson Hyphae', 'minecraft:crimson_hyphae', 64),
  whiteStainedGlassPane('White Stained Glass Pane', 'minecraft:white_stained_glass_pane', 64),
  whiteWool('White Wool', 'minecraft:white_wool', 64),
  redGlazedTerracotta('Red Glazed Terracotta', 'minecraft:red_glazed_terracotta', 64),
  polishedSulfurWall('Polished Sulfur Wall', 'minecraft:polished_sulfur_wall', 64),
  waxedCopperBars('Waxed Copper Bars', 'minecraft:waxed_copper_bars', 64),
  poweredRail('Powered Rail', 'minecraft:powered_rail', 64),
  brownTerracotta('Brown Terracotta', 'minecraft:brown_terracotta', 64),
  shortGrass('Short Grass', 'minecraft:short_grass', 64),
  resinBricks('Resin Bricks', 'minecraft:resin_bricks', 64),
  turtleEgg('Turtle Egg', 'minecraft:turtle_egg', 64),
  rail('Rail', 'minecraft:rail', 64),
  cyanCarpet('Cyan Carpet', 'minecraft:cyan_carpet', 64),
  testInstanceBlock('Test Instance Block', 'minecraft:test_instance_block', 64),
  copperChest('Copper Chest', 'minecraft:copper_chest', 64),
  dirtPath('Dirt Path', 'minecraft:dirt_path', 64),
  orangeCarpet('Orange Carpet', 'minecraft:orange_carpet', 64),
  orangeConcretePowder('Orange Concrete Powder', 'minecraft:orange_concrete_powder', 64),
  greenCarpet('Green Carpet', 'minecraft:green_carpet', 64),
  blackstone('Blackstone', 'minecraft:blackstone', 64),
  waxedCopperLantern('Waxed Copper Lantern', 'minecraft:waxed_copper_lantern', 64),
  potentSulfur('Potent Sulfur', 'minecraft:potent_sulfur', 64),
  netherBrickFence('Nether Brick Fence', 'minecraft:nether_brick_fence', 64),
  crackedPolishedBlackstoneBricks('Cracked Polished Blackstone Bricks',
      'minecraft:cracked_polished_blackstone_bricks', 64),
  stonecutter('Stonecutter', 'minecraft:stonecutter', 64),
  redStainedGlass('Red Stained Glass', 'minecraft:red_stained_glass', 64),
  redNetherBrickWall('Red Nether Brick Wall', 'minecraft:red_nether_brick_wall', 64),
  lever('Lever', 'minecraft:lever', 64),
  darkOakPressurePlate('Dark Oak Pressure Plate', 'minecraft:dark_oak_pressure_plate', 64),
  soulLantern('Soul Lantern', 'minecraft:soul_lantern', 64),
  orangeWool('Orange Wool', 'minecraft:orange_wool', 64),
  grayGlazedTerracotta('Gray Glazed Terracotta', 'minecraft:gray_glazed_terracotta', 64),
  lightGrayConcretePowder('Light Gray Concrete Powder', 'minecraft:light_gray_concrete_powder', 64),
  cartographyTable('Cartography Table', 'minecraft:cartography_table', 64),
  stoneBrickStairs('Stone Brick Stairs', 'minecraft:stone_brick_stairs', 64),
  netheriteBlock('Netherite Block', 'minecraft:netherite_block', 64),
  rawIronBlock('Raw Iron Block', 'minecraft:raw_iron_block', 64),
  mangroveWood('Mangrove Wood', 'minecraft:mangrove_wood', 64),
  waxedOxidizedLightningRod('Waxed Oxidized Lightning Rod',
      'minecraft:waxed_oxidized_lightning_rod', 64),
  deepslateRedstoneOre('Deepslate Redstone Ore', 'minecraft:deepslate_redstone_ore', 64),
  brownStainedGlass('Brown Stained Glass', 'minecraft:brown_stained_glass', 64),
  deepslateTiles('Deepslate Tiles', 'minecraft:deepslate_tiles', 64),
  waxedExposedCopperBars('Waxed Exposed Copper Bars', 'minecraft:waxed_exposed_copper_bars', 64),
  exposedCutCopper('Exposed Cut Copper', 'minecraft:exposed_cut_copper', 64),
  mangroveButton('Mangrove Button', 'minecraft:mangrove_button', 64),
  cobbledDeepslate('Cobbled Deepslate', 'minecraft:cobbled_deepslate', 64),
  waxedCopperDoor('Waxed Copper Door', 'minecraft:waxed_copper_door', 64),
  polishedCinnabarWall('Polished Cinnabar Wall', 'minecraft:polished_cinnabar_wall', 64),
  cornflower('Cornflower', 'minecraft:cornflower', 64),
  netherBrickStairs('Nether Brick Stairs', 'minecraft:nether_brick_stairs', 64),
  brickStairs('Brick Stairs', 'minecraft:brick_stairs', 64),
  waxedOxidizedCopperBars('Waxed Oxidized Copper Bars', 'minecraft:waxed_oxidized_copper_bars', 64),
  spruceSlab('Spruce Slab', 'minecraft:spruce_slab', 64),
  resinBrickSlab('Resin Brick Slab', 'minecraft:resin_brick_slab', 64),
  pinkCarpet('Pink Carpet', 'minecraft:pink_carpet', 64),
  poppy('Poppy', 'minecraft:poppy', 64),
  bambooDoor('Bamboo Door', 'minecraft:bamboo_door', 64),
  strippedAcaciaWood('Stripped Acacia Wood', 'minecraft:stripped_acacia_wood', 64),
  paleHangingMoss('Pale Hanging Moss', 'minecraft:pale_hanging_moss', 64),
  gildedBlackstone('Gilded Blackstone', 'minecraft:gilded_blackstone', 64),
  mudBrickWall('Mud Brick Wall', 'minecraft:mud_brick_wall', 64),
  jungleSlab('Jungle Slab', 'minecraft:jungle_slab', 64),
  weatheredCutCopper('Weathered Cut Copper', 'minecraft:weathered_cut_copper', 64),
  grayBed('Gray Bed', 'minecraft:gray_bed', 1),
  darkPrismarine('Dark Prismarine', 'minecraft:dark_prismarine', 64),
  stoneBricks('Stone Bricks', 'minecraft:stone_bricks', 64),
  polishedDeepslateWall('Polished Deepslate Wall', 'minecraft:polished_deepslate_wall', 64),
  blueStainedGlassPane('Blue Stained Glass Pane', 'minecraft:blue_stained_glass_pane', 64),
  mossyCobblestone('Mossy Cobblestone', 'minecraft:mossy_cobblestone', 64),
  lapisOre('Lapis Ore', 'minecraft:lapis_ore', 64),
  polishedTuff('Polished Tuff', 'minecraft:polished_tuff', 64),
  potato('Potato', 'minecraft:potato', 64),
  polishedDiorite('Polished Diorite', 'minecraft:polished_diorite', 64),
  oakPlanks('Oak Planks', 'minecraft:oak_planks', 64),
  redSandstone('Red Sandstone', 'minecraft:red_sandstone', 64),
  blueGlazedTerracotta('Blue Glazed Terracotta', 'minecraft:blue_glazed_terracotta', 64),
  chiseledTuff('Chiseled Tuff', 'minecraft:chiseled_tuff', 64),
  blueShulkerBox('Blue Shulker Box', 'minecraft:blue_shulker_box', 1),
  greenConcretePowder('Green Concrete Powder', 'minecraft:green_concrete_powder', 64),
  waxedWeatheredChiseledCopper('Waxed Weathered Chiseled Copper',
      'minecraft:waxed_weathered_chiseled_copper', 64),
  whiteGlazedTerracotta('White Glazed Terracotta', 'minecraft:white_glazed_terracotta', 64),
  whiteTulip('White Tulip', 'minecraft:white_tulip', 64),
  acaciaPlanks('Acacia Planks', 'minecraft:acacia_planks', 64),
  cryingObsidian('Crying Obsidian', 'minecraft:crying_obsidian', 64),
  sculkSensor('Sculk Sensor', 'minecraft:sculk_sensor', 64),
  strippedCrimsonStem('Stripped Crimson Stem', 'minecraft:stripped_crimson_stem', 64),
  lightBlueBed('Light Blue Bed', 'minecraft:light_blue_bed', 1),
  repeatingCommandBlock('Repeating Command Block', 'minecraft:repeating_command_block', 64),
  exposedCopperChain('Exposed Copper Chain', 'minecraft:exposed_copper_chain', 64),
  birchButton('Birch Button', 'minecraft:birch_button', 64),
  darkOakSlab('Dark Oak Slab', 'minecraft:dark_oak_slab', 64),
  fireCoralBlock('Fire Coral Block', 'minecraft:fire_coral_block', 64),
  soulSoil('Soul Soil', 'minecraft:soul_soil', 64),
  tuffBrickStairs('Tuff Brick Stairs', 'minecraft:tuff_brick_stairs', 64),
  brownMushroomBlock('Brown Mushroom Block', 'minecraft:brown_mushroom_block', 64),
  paleOakDoor('Pale Oak Door', 'minecraft:pale_oak_door', 64),
  polishedSulfur('Polished Sulfur', 'minecraft:polished_sulfur', 64),
  darkOakFenceGate('Dark Oak Fence Gate', 'minecraft:dark_oak_fence_gate', 64),
  waxedCopperBlock('Waxed Copper Block', 'minecraft:waxed_copper_block', 64),
  chiseledStoneBricks('Chiseled Stone Bricks', 'minecraft:chiseled_stone_bricks', 64),
  pinkConcrete('Pink Concrete', 'minecraft:pink_concrete', 64),
  magentaTerracotta('Magenta Terracotta', 'minecraft:magenta_terracotta', 64),
  composter('Composter', 'minecraft:composter', 64),
  purpleConcrete('Purple Concrete', 'minecraft:purple_concrete', 64),
  warpedFungus('Warped Fungus', 'minecraft:warped_fungus', 64),
  jungleDoor('Jungle Door', 'minecraft:jungle_door', 64),
  tuffSlab('Tuff Slab', 'minecraft:tuff_slab', 64),
  polishedAndesiteStairs('Polished Andesite Stairs', 'minecraft:polished_andesite_stairs', 64),
  mangroveStairs('Mangrove Stairs', 'minecraft:mangrove_stairs', 64),
  quartzBricks('Quartz Bricks', 'minecraft:quartz_bricks', 64),
  deepslate('Deepslate', 'minecraft:deepslate', 64),
  acaciaLog('Acacia Log', 'minecraft:acacia_log', 64),
  oakSapling('Oak Sapling', 'minecraft:oak_sapling', 64),
  mangroveSlab('Mangrove Slab', 'minecraft:mangrove_slab', 64),
  redMushroom('Red Mushroom', 'minecraft:red_mushroom', 64),
  crimsonShelf('Crimson Shelf', 'minecraft:crimson_shelf', 64),
  weatheredCopperChain('Weathered Copper Chain', 'minecraft:weathered_copper_chain', 64),
  target('Target', 'minecraft:target', 64),
  infestedStoneBricks('Infested Stone Bricks', 'minecraft:infested_stone_bricks', 64),
  crackedDeepslateTiles('Cracked Deepslate Tiles', 'minecraft:cracked_deepslate_tiles', 64),
  weatheredLightningRod('Weathered Lightning Rod', 'minecraft:weathered_lightning_rod', 64),
  lightBlueConcrete('Light Blue Concrete', 'minecraft:light_blue_concrete', 64),
  muddyMangroveRoots('Muddy Mangrove Roots', 'minecraft:muddy_mangrove_roots', 64),
  cherryPlanks('Cherry Planks', 'minecraft:cherry_planks', 64),
  cherryWood('Cherry Wood', 'minecraft:cherry_wood', 64),
  sulfurBrickSlab('Sulfur Brick Slab', 'minecraft:sulfur_brick_slab', 64),
  crimsonRoots('Crimson Roots', 'minecraft:crimson_roots', 64),
  bambooButton('Bamboo Button', 'minecraft:bamboo_button', 64),
  waxedOxidizedCutCopperSlab('Waxed Oxidized Cut Copper Slab',
      'minecraft:waxed_oxidized_cut_copper_slab', 64),
  pinkGlazedTerracotta('Pink Glazed Terracotta', 'minecraft:pink_glazed_terracotta', 64),
  jungleTrapdoor('Jungle Trapdoor', 'minecraft:jungle_trapdoor', 64),
  pinkBed('Pink Bed', 'minecraft:pink_bed', 1),
  podzol('Podzol', 'minecraft:podzol', 64),
  andesiteStairs('Andesite Stairs', 'minecraft:andesite_stairs', 64),
  darkOakSapling('Dark Oak Sapling', 'minecraft:dark_oak_sapling', 64),
  witherRose('Wither Rose', 'minecraft:wither_rose', 64),
  bambooSign('Bamboo Sign', 'minecraft:bamboo_sign', 16),
  endStoneBrickWall('End Stone Brick Wall', 'minecraft:end_stone_brick_wall', 64),
  waxedWeatheredCutCopperSlab('Waxed Weathered Cut Copper Slab',
      'minecraft:waxed_weathered_cut_copper_slab', 64),
  waxedExposedCutCopper('Waxed Exposed Cut Copper', 'minecraft:waxed_exposed_cut_copper', 64),
  crimsonSign('Crimson Sign', 'minecraft:crimson_sign', 16),
  decoratedPot('Decorated Pot', 'minecraft:decorated_pot', 64),
  waxedExposedCopperBulb('Waxed Exposed Copper Bulb', 'minecraft:waxed_exposed_copper_bulb', 64),
  weatheredCopperChest('Weathered Copper Chest', 'minecraft:weathered_copper_chest', 64),
  paleOakFence('Pale Oak Fence', 'minecraft:pale_oak_fence', 64),
  driedKelpBlock('Dried Kelp Block', 'minecraft:dried_kelp_block', 64),
  craftingTable('Crafting Table', 'minecraft:crafting_table', 64),
  exposedCopperGrate('Exposed Copper Grate', 'minecraft:exposed_copper_grate', 64),
  polishedCinnabarSlab('Polished Cinnabar Slab', 'minecraft:polished_cinnabar_slab', 64),
  strippedDarkOakLog('Stripped Dark Oak Log', 'minecraft:stripped_dark_oak_log', 64),
  amethystBlock('Amethyst Block', 'minecraft:amethyst_block', 64),
  cutCopper('Cut Copper', 'minecraft:cut_copper', 64),
  barrier('Barrier', 'minecraft:barrier', 64),
  ironOre('Iron Ore', 'minecraft:iron_ore', 64),
  smoothRedSandstone('Smooth Red Sandstone', 'minecraft:smooth_red_sandstone', 64),
  glowBerries('Glow Berries', 'minecraft:glow_berries', 64),
  grayConcrete('Gray Concrete', 'minecraft:gray_concrete', 64),
  acaciaFence('Acacia Fence', 'minecraft:acacia_fence', 64),
  waxedWeatheredCopperDoor('Waxed Weathered Copper Door', 'minecraft:waxed_weathered_copper_door',
      64),
  netherBricks('Nether Bricks', 'minecraft:nether_bricks', 64),
  jungleFence('Jungle Fence', 'minecraft:jungle_fence', 64),
  warpedWartBlock('Warped Wart Block', 'minecraft:warped_wart_block', 64),
  oxidizedCopperLantern('Oxidized Copper Lantern', 'minecraft:oxidized_copper_lantern', 64),
  dioriteWall('Diorite Wall', 'minecraft:diorite_wall', 64),
  waxedExposedCutCopperStairs('Waxed Exposed Cut Copper Stairs',
      'minecraft:waxed_exposed_cut_copper_stairs', 64),
  weatheredCutCopperSlab('Weathered Cut Copper Slab', 'minecraft:weathered_cut_copper_slab', 64),
  zombieHead('Zombie Head', 'minecraft:zombie_head', 64),
  smoothQuartz('Smooth Quartz', 'minecraft:smooth_quartz', 64),
  smithingTable('Smithing Table', 'minecraft:smithing_table', 64),
  cyanWool('Cyan Wool', 'minecraft:cyan_wool', 64),
  deepslateDiamondOre('Deepslate Diamond Ore', 'minecraft:deepslate_diamond_ore', 64),
  tallDryGrass('Tall Dry Grass', 'minecraft:tall_dry_grass', 64),
  deadBubbleCoralBlock('Dead Bubble Coral Block', 'minecraft:dead_bubble_coral_block', 64),
  terracotta('Terracotta', 'minecraft:terracotta', 64),
  deadBrainCoralFan('Dead Brain Coral Fan', 'minecraft:dead_brain_coral_fan', 64),
  polishedBlackstoneBrickSlab('Polished Blackstone Brick Slab',
      'minecraft:polished_blackstone_brick_slab', 64),
  carvedPumpkin('Carved Pumpkin', 'minecraft:carved_pumpkin', 64),
  orangeBed('Orange Bed', 'minecraft:orange_bed', 1),
  waxedWeatheredCutCopper('Waxed Weathered Cut Copper', 'minecraft:waxed_weathered_cut_copper', 64),
  purpleWool('Purple Wool', 'minecraft:purple_wool', 64),
  pinkConcretePowder('Pink Concrete Powder', 'minecraft:pink_concrete_powder', 64),
  tubeCoralFan('Tube Coral Fan', 'minecraft:tube_coral_fan', 64),
  lectern('Lectern', 'minecraft:lectern', 64),
  redstoneOre('Redstone Ore', 'minecraft:redstone_ore', 64),
  trappedChest('Trapped Chest', 'minecraft:trapped_chest', 64),
  birchLog('Birch Log', 'minecraft:birch_log', 64),
  limeCandle('Lime Candle', 'minecraft:lime_candle', 64),
  mangroveSign('Mangrove Sign', 'minecraft:mangrove_sign', 16),
  orangeShulkerBox('Orange Shulker Box', 'minecraft:orange_shulker_box', 1),
  enderChest('Ender Chest', 'minecraft:ender_chest', 64),
  graniteStairs('Granite Stairs', 'minecraft:granite_stairs', 64),
  smoothStone('Smooth Stone', 'minecraft:smooth_stone', 64),
  deadBubbleCoral('Dead Bubble Coral', 'minecraft:dead_bubble_coral', 64),
  waxedWeatheredCutCopperStairs('Waxed Weathered Cut Copper Stairs',
      'minecraft:waxed_weathered_cut_copper_stairs', 64),
  birchTrapdoor('Birch Trapdoor', 'minecraft:birch_trapdoor', 64),
  chiseledSandstone('Chiseled Sandstone', 'minecraft:chiseled_sandstone', 64),
  grayStainedGlass('Gray Stained Glass', 'minecraft:gray_stained_glass', 64),
  lilyPad('Lily Pad', 'minecraft:lily_pad', 64),
  quartzBlock('Quartz Block', 'minecraft:quartz_block', 64),
  snow('Snow', 'minecraft:snow', 64),
  pinkTulip('Pink Tulip', 'minecraft:pink_tulip', 64),
  mangrovePressurePlate('Mangrove Pressure Plate', 'minecraft:mangrove_pressure_plate', 64),
  greenConcrete('Green Concrete', 'minecraft:green_concrete', 64),
  jungleFenceGate('Jungle Fence Gate', 'minecraft:jungle_fence_gate', 64),
  cobweb('Cobweb', 'minecraft:cobweb', 64),
  spruceDoor('Spruce Door', 'minecraft:spruce_door', 64),
  prismarineWall('Prismarine Wall', 'minecraft:prismarine_wall', 64),
  quartzPillar('Quartz Pillar', 'minecraft:quartz_pillar', 64),
  deadBush('Dead Bush', 'minecraft:dead_bush', 64),
  cherryShelf('Cherry Shelf', 'minecraft:cherry_shelf', 64),
  redConcretePowder('Red Concrete Powder', 'minecraft:red_concrete_powder', 64),
  petrifiedOakSlab('Petrified Oak Slab', 'minecraft:petrified_oak_slab', 64),
  cobbledDeepslateStairs('Cobbled Deepslate Stairs', 'minecraft:cobbled_deepslate_stairs', 64),
  chainCommandBlock('Chain Command Block', 'minecraft:chain_command_block', 64),
  chiseledRedSandstone('Chiseled Red Sandstone', 'minecraft:chiseled_red_sandstone', 64),
  jungleSapling('Jungle Sapling', 'minecraft:jungle_sapling', 64),
  clay('Clay', 'minecraft:clay', 64),
  brainCoralFan('Brain Coral Fan', 'minecraft:brain_coral_fan', 64),
  magentaWool('Magenta Wool', 'minecraft:magenta_wool', 64),
  limeBanner('Lime Banner', 'minecraft:lime_banner', 16),
  orangeStainedGlassPane('Orange Stained Glass Pane', 'minecraft:orange_stained_glass_pane', 64),
  sulfurWall('Sulfur Wall', 'minecraft:sulfur_wall', 64),
  copperBulb('Copper Bulb', 'minecraft:copper_bulb', 64),
  purpleStainedGlass('Purple Stained Glass', 'minecraft:purple_stained_glass', 64),
  barrel('Barrel', 'minecraft:barrel', 64),
  blueConcretePowder('Blue Concrete Powder', 'minecraft:blue_concrete_powder', 64),
  polishedTuffStairs('Polished Tuff Stairs', 'minecraft:polished_tuff_stairs', 64),
  pitcherPlant('Pitcher Plant', 'minecraft:pitcher_plant', 64),
  redstoneLamp('Redstone Lamp', 'minecraft:redstone_lamp', 64),
  cherryHangingSign('Cherry Hanging Sign', 'minecraft:cherry_hanging_sign', 16),
  lightGrayCarpet('Light Gray Carpet', 'minecraft:light_gray_carpet', 64),
  greenWool('Green Wool', 'minecraft:green_wool', 64),
  redWool('Red Wool', 'minecraft:red_wool', 64),
  tripwireHook('Tripwire Hook', 'minecraft:tripwire_hook', 64),
  lightBlueConcretePowder('Light Blue Concrete Powder', 'minecraft:light_blue_concrete_powder', 64),
  spruceSapling('Spruce Sapling', 'minecraft:spruce_sapling', 64),
  graniteSlab('Granite Slab', 'minecraft:granite_slab', 64),
  blackConcrete('Black Concrete', 'minecraft:black_concrete', 64),
  weatheredCopperBulb('Weathered Copper Bulb', 'minecraft:weathered_copper_bulb', 64),
  yellowGlazedTerracotta('Yellow Glazed Terracotta', 'minecraft:yellow_glazed_terracotta', 64),
  waxedCopperGrate('Waxed Copper Grate', 'minecraft:waxed_copper_grate', 64),
  heavyCore('Heavy Core', 'minecraft:heavy_core', 64),
  grayWool('Gray Wool', 'minecraft:gray_wool', 64),
  orangeTulip('Orange Tulip', 'minecraft:orange_tulip', 64),
  purpleTerracotta('Purple Terracotta', 'minecraft:purple_terracotta', 64),
  deepslateBrickWall('Deepslate Brick Wall', 'minecraft:deepslate_brick_wall', 64),
  bubbleCoral('Bubble Coral', 'minecraft:bubble_coral', 64),
  spruceWood('Spruce Wood', 'minecraft:spruce_wood', 64),
  strippedCrimsonHyphae('Stripped Crimson Hyphae', 'minecraft:stripped_crimson_hyphae', 64),
  paleOakButton('Pale Oak Button', 'minecraft:pale_oak_button', 64),
  diamondOre('Diamond Ore', 'minecraft:diamond_ore', 64),
  lightWeightedPressurePlate('Light Weighted Pressure Plate',
      'minecraft:light_weighted_pressure_plate', 64),
  prismarineBrickStairs('Prismarine Brick Stairs', 'minecraft:prismarine_brick_stairs', 64),
  redCarpet('Red Carpet', 'minecraft:red_carpet', 64),
  strippedSpruceWood('Stripped Spruce Wood', 'minecraft:stripped_spruce_wood', 64),
  cherryStairs('Cherry Stairs', 'minecraft:cherry_stairs', 64),
  brainCoral('Brain Coral', 'minecraft:brain_coral', 64),
  netherBrickWall('Nether Brick Wall', 'minecraft:nether_brick_wall', 64),
  oxidizedCopperTrapdoor('Oxidized Copper Trapdoor', 'minecraft:oxidized_copper_trapdoor', 64),
  oakDoor('Oak Door', 'minecraft:oak_door', 64),
  birchLeaves('Birch Leaves', 'minecraft:birch_leaves', 64),
  waxedExposedCopperGrate('Waxed Exposed Copper Grate', 'minecraft:waxed_exposed_copper_grate', 64),
  magentaShulkerBox('Magenta Shulker Box', 'minecraft:magenta_shulker_box', 1),
  whiteShulkerBox('White Shulker Box', 'minecraft:white_shulker_box', 1),
  whiteTerracotta('White Terracotta', 'minecraft:white_terracotta', 64),
  brownCandle('Brown Candle', 'minecraft:brown_candle', 64),
  packedIce('Packed Ice', 'minecraft:packed_ice', 64),
  crackedNetherBricks('Cracked Nether Bricks', 'minecraft:cracked_nether_bricks', 64),
  exposedCopper('Exposed Copper', 'minecraft:exposed_copper', 64),
  oakTrapdoor('Oak Trapdoor', 'minecraft:oak_trapdoor', 64),
  lightGrayWool('Light Gray Wool', 'minecraft:light_gray_wool', 64),
  fireflyBush('Firefly Bush', 'minecraft:firefly_bush', 64),
  magentaConcretePowder('Magenta Concrete Powder', 'minecraft:magenta_concrete_powder', 64),
  testBlock('Test Block', 'minecraft:test_block', 64),
  bambooFenceGate('Bamboo Fence Gate', 'minecraft:bamboo_fence_gate', 64),
  shulkerBox('Shulker Box', 'minecraft:shulker_box', 1),
  greenBanner('Green Banner', 'minecraft:green_banner', 16),
  greenStainedGlassPane('Green Stained Glass Pane', 'minecraft:green_stained_glass_pane', 64),
  exposedChiseledCopper('Exposed Chiseled Copper', 'minecraft:exposed_chiseled_copper', 64),
  grassBlock('Grass Block', 'minecraft:grass_block', 64),
  exposedCopperGolemStatue('Exposed Copper Golem Statue', 'minecraft:exposed_copper_golem_statue',
      64),
  cutCopperStairs('Cut Copper Stairs', 'minecraft:cut_copper_stairs', 64),
  brownShulkerBox('Brown Shulker Box', 'minecraft:brown_shulker_box', 1),
  oxidizedCutCopperStairs('Oxidized Cut Copper Stairs', 'minecraft:oxidized_cut_copper_stairs', 64),
  mycelium('Mycelium', 'minecraft:mycelium', 64),
  orangeCandle('Orange Candle', 'minecraft:orange_candle', 64),
  acaciaSapling('Acacia Sapling', 'minecraft:acacia_sapling', 64),
  exposedCopperDoor('Exposed Copper Door', 'minecraft:exposed_copper_door', 64),
  warpedPlanks('Warped Planks', 'minecraft:warped_planks', 64),
  mangrovePropagule('Mangrove Propagule', 'minecraft:mangrove_propagule', 64),
  peony('Peony', 'minecraft:peony', 64),
  weatheredCopperDoor('Weathered Copper Door', 'minecraft:weathered_copper_door', 64),
  strippedPaleOakLog('Stripped Pale Oak Log', 'minecraft:stripped_pale_oak_log', 64),
  acaciaHangingSign('Acacia Hanging Sign', 'minecraft:acacia_hanging_sign', 16),
  respawnAnchor('Respawn Anchor', 'minecraft:respawn_anchor', 64),
  deadHornCoral('Dead Horn Coral', 'minecraft:dead_horn_coral', 64),
  reinforcedDeepslate('Reinforced Deepslate', 'minecraft:reinforced_deepslate', 64),
  sculkCatalyst('Sculk Catalyst', 'minecraft:sculk_catalyst', 64),
  mossyStoneBrickSlab('Mossy Stone Brick Slab', 'minecraft:mossy_stone_brick_slab', 64),
  lightGrayShulkerBox('Light Gray Shulker Box', 'minecraft:light_gray_shulker_box', 1),
  conduit('Conduit', 'minecraft:conduit', 64),
  polishedDeepslateSlab('Polished Deepslate Slab', 'minecraft:polished_deepslate_slab', 64),
  warpedButton('Warped Button', 'minecraft:warped_button', 64),
  cobblestoneStairs('Cobblestone Stairs', 'minecraft:cobblestone_stairs', 64),
  torchflowerSeeds('Torchflower Seeds', 'minecraft:torchflower_seeds', 64),
  carrot('Carrot', 'minecraft:carrot', 64),
  cyanShulkerBox('Cyan Shulker Box', 'minecraft:cyan_shulker_box', 1),
  pinkBanner('Pink Banner', 'minecraft:pink_banner', 16),
  sulfurSlab('Sulfur Slab', 'minecraft:sulfur_slab', 64),
  hornCoralFan('Horn Coral Fan', 'minecraft:horn_coral_fan', 64),
  grindstone('Grindstone', 'minecraft:grindstone', 64),
  copperLantern('Copper Lantern', 'minecraft:copper_lantern', 64),
  infestedChiseledStoneBricks('Infested Chiseled Stone Bricks',
      'minecraft:infested_chiseled_stone_bricks', 64),
  deadTubeCoralBlock('Dead Tube Coral Block', 'minecraft:dead_tube_coral_block', 64),
  oxidizedCopperGolemStatue('Oxidized Copper Golem Statue',
      'minecraft:oxidized_copper_golem_statue', 64),
  lightGrayBanner('Light Gray Banner', 'minecraft:light_gray_banner', 16),
  birchSign('Birch Sign', 'minecraft:birch_sign', 16),
  dirt('Dirt', 'minecraft:dirt', 64),
  cyanBanner('Cyan Banner', 'minecraft:cyan_banner', 16),
  glass('Glass', 'minecraft:glass', 64),
  rawGoldBlock('Raw Gold Block', 'minecraft:raw_gold_block', 64),
  hornCoral('Horn Coral', 'minecraft:horn_coral', 64),
  prismarineSlab('Prismarine Slab', 'minecraft:prismarine_slab', 64),
  soulTorch('Soul Torch', 'minecraft:soul_torch', 64),
  crimsonTrapdoor('Crimson Trapdoor', 'minecraft:crimson_trapdoor', 64),
  yellowConcrete('Yellow Concrete', 'minecraft:yellow_concrete', 64),
  birchPlanks('Birch Planks', 'minecraft:birch_planks', 64),
  coalBlock('Coal Block', 'minecraft:coal_block', 64),
  loom('Loom', 'minecraft:loom', 64),
  fletchingTable('Fletching Table', 'minecraft:fletching_table', 64),
  redStainedGlassPane('Red Stained Glass Pane', 'minecraft:red_stained_glass_pane', 64),
  azaleaLeaves('Azalea Leaves', 'minecraft:azalea_leaves', 64),
  crimsonButton('Crimson Button', 'minecraft:crimson_button', 64),
  limeConcretePowder('Lime Concrete Powder', 'minecraft:lime_concrete_powder', 64),
  cyanConcretePowder('Cyan Concrete Powder', 'minecraft:cyan_concrete_powder', 64),
  oxidizedCopperGrate('Oxidized Copper Grate', 'minecraft:oxidized_copper_grate', 64),
  warpedRoots('Warped Roots', 'minecraft:warped_roots', 64),
  cinnabarStairs('Cinnabar Stairs', 'minecraft:cinnabar_stairs', 64),
  acaciaFenceGate('Acacia Fence Gate', 'minecraft:acacia_fence_gate', 64),
  brewingStand('Brewing Stand', 'minecraft:brewing_stand', 64),
  tuffWall('Tuff Wall', 'minecraft:tuff_wall', 64),
  graniteWall('Granite Wall', 'minecraft:granite_wall', 64),
  prismarineBrickSlab('Prismarine Brick Slab', 'minecraft:prismarine_brick_slab', 64),
  netherQuartzOre('Nether Quartz Ore', 'minecraft:nether_quartz_ore', 64),
  bamboo('Bamboo', 'minecraft:bamboo', 64),
  greenTerracotta('Green Terracotta', 'minecraft:green_terracotta', 64),
  crimsonHangingSign('Crimson Hanging Sign', 'minecraft:crimson_hanging_sign', 16),
  smallDripleaf('Small Dripleaf', 'minecraft:small_dripleaf', 64),
  dandelion('Dandelion', 'minecraft:dandelion', 64),
  emeraldOre('Emerald Ore', 'minecraft:emerald_ore', 64),
  limeConcrete('Lime Concrete', 'minecraft:lime_concrete', 64),
  yellowConcretePowder('Yellow Concrete Powder', 'minecraft:yellow_concrete_powder', 64),
  granite('Granite', 'minecraft:granite', 64),
  soulSand('Soul Sand', 'minecraft:soul_sand', 64),
  torchflower('Torchflower', 'minecraft:torchflower', 64),
  furnace('Furnace', 'minecraft:furnace', 64),
  strippedJungleLog('Stripped Jungle Log', 'minecraft:stripped_jungle_log', 64),
  copperChain('Copper Chain', 'minecraft:copper_chain', 64),
  darkOakHangingSign('Dark Oak Hanging Sign', 'minecraft:dark_oak_hanging_sign', 16),
  exposedLightningRod('Exposed Lightning Rod', 'minecraft:exposed_lightning_rod', 64),
  warpedSign('Warped Sign', 'minecraft:warped_sign', 16),
  paleOakSlab('Pale Oak Slab', 'minecraft:pale_oak_slab', 64),
  redTerracotta('Red Terracotta', 'minecraft:red_terracotta', 64),
  paleOakPressurePlate('Pale Oak Pressure Plate', 'minecraft:pale_oak_pressure_plate', 64),
  blackWool('Black Wool', 'minecraft:black_wool', 64),
  warpedHyphae('Warped Hyphae', 'minecraft:warped_hyphae', 64),
  endPortalFrame('End Portal Frame', 'minecraft:end_portal_frame', 64),
  crimsonFenceGate('Crimson Fence Gate', 'minecraft:crimson_fence_gate', 64),
  waxedWeatheredLightningRod('Waxed Weathered Lightning Rod',
      'minecraft:waxed_weathered_lightning_rod', 64),
  warpedPressurePlate('Warped Pressure Plate', 'minecraft:warped_pressure_plate', 64),
  oxidizedCopperBars('Oxidized Copper Bars', 'minecraft:oxidized_copper_bars', 64),
  blueCarpet('Blue Carpet', 'minecraft:blue_carpet', 64),
  strippedBirchWood('Stripped Birch Wood', 'minecraft:stripped_birch_wood', 64),
  copperBars('Copper Bars', 'minecraft:copper_bars', 64),
  brickWall('Brick Wall', 'minecraft:brick_wall', 64),
  prismarine('Prismarine', 'minecraft:prismarine', 64),
  bubbleCoralBlock('Bubble Coral Block', 'minecraft:bubble_coral_block', 64),
  mangroveRoots('Mangrove Roots', 'minecraft:mangrove_roots', 64),
  jungleLog('Jungle Log', 'minecraft:jungle_log', 64),
  deadBrainCoral('Dead Brain Coral', 'minecraft:dead_brain_coral', 64),
  mushroomStem('Mushroom Stem', 'minecraft:mushroom_stem', 64),
  purpleGlazedTerracotta('Purple Glazed Terracotta', 'minecraft:purple_glazed_terracotta', 64),
  mediumAmethystBud('Medium Amethyst Bud', 'minecraft:medium_amethyst_bud', 64),
  strippedPaleOakWood('Stripped Pale Oak Wood', 'minecraft:stripped_pale_oak_wood', 64),
  netherBrickSlab('Nether Brick Slab', 'minecraft:nether_brick_slab', 64),
  fireCoral('Fire Coral', 'minecraft:fire_coral', 64),
  exposedCopperBulb('Exposed Copper Bulb', 'minecraft:exposed_copper_bulb', 64),
  mossBlock('Moss Block', 'minecraft:moss_block', 64),
  skeletonSkull('Skeleton Skull', 'minecraft:skeleton_skull', 64),
  purpleStainedGlassPane('Purple Stained Glass Pane', 'minecraft:purple_stained_glass_pane', 64),
  deadFireCoral('Dead Fire Coral', 'minecraft:dead_fire_coral', 64),
  lapisBlock('Lapis Block', 'minecraft:lapis_block', 64),
  cyanConcrete('Cyan Concrete', 'minecraft:cyan_concrete', 64),
  wildflowers('Wildflowers', 'minecraft:wildflowers', 64),
  acaciaShelf('Acacia Shelf', 'minecraft:acacia_shelf', 64),
  strippedOakLog('Stripped Oak Log', 'minecraft:stripped_oak_log', 64),
  torch('Torch', 'minecraft:torch', 64),
  darkOakButton('Dark Oak Button', 'minecraft:dark_oak_button', 64),
  beehive('Beehive', 'minecraft:beehive', 64),
  chiseledTuffBricks('Chiseled Tuff Bricks', 'minecraft:chiseled_tuff_bricks', 64),
  wheatSeeds('Wheat Seeds', 'minecraft:wheat_seeds', 64),
  waxedWeatheredCopperBars('Waxed Weathered Copper Bars', 'minecraft:waxed_weathered_copper_bars',
      64),
  oxidizedCopper('Oxidized Copper', 'minecraft:oxidized_copper', 64),
  polishedDioriteStairs('Polished Diorite Stairs', 'minecraft:polished_diorite_stairs', 64),
  prismarineBricks('Prismarine Bricks', 'minecraft:prismarine_bricks', 64),
  infestedCrackedStoneBricks('Infested Cracked Stone Bricks',
      'minecraft:infested_cracked_stone_bricks', 64),
  resinBrickWall('Resin Brick Wall', 'minecraft:resin_brick_wall', 64),
  cutSandstoneSlab('Cut Sandstone Slab', 'minecraft:cut_sandstone_slab', 64),
  tnt('Tnt', 'minecraft:tnt', 64),
  sugarCane('Sugar Cane', 'minecraft:sugar_cane', 64),
  copperDoor('Copper Door', 'minecraft:copper_door', 64),
  blueStainedGlass('Blue Stained Glass', 'minecraft:blue_stained_glass', 64),
  buddingAmethyst('Budding Amethyst', 'minecraft:budding_amethyst', 64),
  exposedCutCopperStairs('Exposed Cut Copper Stairs', 'minecraft:exposed_cut_copper_stairs', 64),
  chest('Chest', 'minecraft:chest', 64),
  brainCoralBlock('Brain Coral Block', 'minecraft:brain_coral_block', 64),
  kelp('Kelp', 'minecraft:kelp', 64),
  yellowBanner('Yellow Banner', 'minecraft:yellow_banner', 16),
  oxidizedCutCopperSlab('Oxidized Cut Copper Slab', 'minecraft:oxidized_cut_copper_slab', 64),
  exposedCopperLantern('Exposed Copper Lantern', 'minecraft:exposed_copper_lantern', 64),
  waxedWeatheredCopperGolemStatue('Waxed Weathered Copper Golem Statue',
      'minecraft:waxed_weathered_copper_golem_statue', 64),
  smallAmethystBud('Small Amethyst Bud', 'minecraft:small_amethyst_bud', 64),
  polishedAndesiteSlab('Polished Andesite Slab', 'minecraft:polished_andesite_slab', 64),
  redSand('Red Sand', 'minecraft:red_sand', 64),
  mossyCobblestoneWall('Mossy Cobblestone Wall', 'minecraft:mossy_cobblestone_wall', 64),
  exposedCopperChest('Exposed Copper Chest', 'minecraft:exposed_copper_chest', 64),
  polishedBlackstoneBrickStairs('Polished Blackstone Brick Stairs',
      'minecraft:polished_blackstone_brick_stairs', 64),
  brownConcrete('Brown Concrete', 'minecraft:brown_concrete', 64),
  sulfurBrickStairs('Sulfur Brick Stairs', 'minecraft:sulfur_brick_stairs', 64),
  paleMossCarpet('Pale Moss Carpet', 'minecraft:pale_moss_carpet', 64),
  blackstoneWall('Blackstone Wall', 'minecraft:blackstone_wall', 64),
  paleOakStairs('Pale Oak Stairs', 'minecraft:pale_oak_stairs', 64),
  sweetBerries('Sweet Berries', 'minecraft:sweet_berries', 64),
  campfire('Campfire', 'minecraft:campfire', 64),
  cobblestone('Cobblestone', 'minecraft:cobblestone', 64),
  waxedCopperTrapdoor('Waxed Copper Trapdoor', 'minecraft:waxed_copper_trapdoor', 64),
  dioriteStairs('Diorite Stairs', 'minecraft:diorite_stairs', 64),
  bush('Bush', 'minecraft:bush', 64),
  slimeBlock('Slime Block', 'minecraft:slime_block', 64),
  deepslateBricks('Deepslate Bricks', 'minecraft:deepslate_bricks', 64),
  acaciaWood('Acacia Wood', 'minecraft:acacia_wood', 64),
  grayBanner('Gray Banner', 'minecraft:gray_banner', 16),
  blueWool('Blue Wool', 'minecraft:blue_wool', 64),
  spruceStairs('Spruce Stairs', 'minecraft:spruce_stairs', 64),
  magentaCandle('Magenta Candle', 'minecraft:magenta_candle', 64),
  spruceFence('Spruce Fence', 'minecraft:spruce_fence', 64),
  cinnabarSlab('Cinnabar Slab', 'minecraft:cinnabar_slab', 64),
  polishedGranite('Polished Granite', 'minecraft:polished_granite', 64),
  redTulip('Red Tulip', 'minecraft:red_tulip', 64),
  deadTubeCoral('Dead Tube Coral', 'minecraft:dead_tube_coral', 64),
  sprucePressurePlate('Spruce Pressure Plate', 'minecraft:spruce_pressure_plate', 64),
  paleOakSapling('Pale Oak Sapling', 'minecraft:pale_oak_sapling', 64),
  calibratedSculkSensor('Calibrated Sculk Sensor', 'minecraft:calibrated_sculk_sensor', 64),
  greenStainedGlass('Green Stained Glass', 'minecraft:green_stained_glass', 64),
  roseBush('Rose Bush', 'minecraft:rose_bush', 64),
  exposedCutCopperSlab('Exposed Cut Copper Slab', 'minecraft:exposed_cut_copper_slab', 64),
  brownCarpet('Brown Carpet', 'minecraft:brown_carpet', 64),
  fireCoralFan('Fire Coral Fan', 'minecraft:fire_coral_fan', 64),
  diorite('Diorite', 'minecraft:diorite', 64),
  spruceSign('Spruce Sign', 'minecraft:spruce_sign', 16),
  acaciaButton('Acacia Button', 'minecraft:acacia_button', 64),
  waxedWeatheredCopperChain('Waxed Weathered Copper Chain',
      'minecraft:waxed_weathered_copper_chain', 64),
  oakSlab('Oak Slab', 'minecraft:oak_slab', 64),
  darkOakTrapdoor('Dark Oak Trapdoor', 'minecraft:dark_oak_trapdoor', 64),
  acaciaLeaves('Acacia Leaves', 'minecraft:acacia_leaves', 64),
  anvil('Anvil', 'minecraft:anvil', 64),
  driedGhast('Dried Ghast', 'minecraft:dried_ghast', 64),
  strippedOakWood('Stripped Oak Wood', 'minecraft:stripped_oak_wood', 64),
  magentaStainedGlassPane('Magenta Stained Glass Pane', 'minecraft:magenta_stained_glass_pane', 64),
  greenShulkerBox('Green Shulker Box', 'minecraft:green_shulker_box', 1),
  dropper('Dropper', 'minecraft:dropper', 64),
  vine('Vine', 'minecraft:vine', 64),
  lightBlueTerracotta('Light Blue Terracotta', 'minecraft:light_blue_terracotta', 64),
  ironDoor('Iron Door', 'minecraft:iron_door', 64),
  piston('Piston', 'minecraft:piston', 64),
  warpedFenceGate('Warped Fence Gate', 'minecraft:warped_fence_gate', 64),
  waxedExposedCopperChain('Waxed Exposed Copper Chain', 'minecraft:waxed_exposed_copper_chain', 64),
  piglinHead('Piglin Head', 'minecraft:piglin_head', 64),
  blackBanner('Black Banner', 'minecraft:black_banner', 16),
  stonePressurePlate('Stone Pressure Plate', 'minecraft:stone_pressure_plate', 64),
  waxedOxidizedCopperChain('Waxed Oxidized Copper Chain', 'minecraft:waxed_oxidized_copper_chain',
      64),
  waxedExposedLightningRod('Waxed Exposed Lightning Rod', 'minecraft:waxed_exposed_lightning_rod',
      64),
  blackstoneSlab('Blackstone Slab', 'minecraft:blackstone_slab', 64),
  mudBricks('Mud Bricks', 'minecraft:mud_bricks', 64),
  redstoneBlock('Redstone Block', 'minecraft:redstone_block', 64),
  grayCarpet('Gray Carpet', 'minecraft:gray_carpet', 64),
  polishedBlackstoneButton('Polished Blackstone Button', 'minecraft:polished_blackstone_button',
      64),
  infestedDeepslate('Infested Deepslate', 'minecraft:infested_deepslate', 64),
  powderSnowBucket('Powder Snow Bucket', 'minecraft:powder_snow_bucket', 1),
  brownBed('Brown Bed', 'minecraft:brown_bed', 1),
  mudBrickSlab('Mud Brick Slab', 'minecraft:mud_brick_slab', 64),
  darkOakSign('Dark Oak Sign', 'minecraft:dark_oak_sign', 16),
  allium('Allium', 'minecraft:allium', 64),
  jungleWood('Jungle Wood', 'minecraft:jungle_wood', 64),
  sulfur('Sulfur', 'minecraft:sulfur', 64),
  jungleHangingSign('Jungle Hanging Sign', 'minecraft:jungle_hanging_sign', 16),
  sulfurSpike('Sulfur Spike', 'minecraft:sulfur_spike', 64),
  whiteBed('White Bed', 'minecraft:white_bed', 1),
  floweringAzaleaLeaves('Flowering Azalea Leaves', 'minecraft:flowering_azalea_leaves', 64),
  lilyOfTheValley('Lily Of The Valley', 'minecraft:lily_of_the_valley', 64),
  oakStairs('Oak Stairs', 'minecraft:oak_stairs', 64),
  cinnabarBrickSlab('Cinnabar Brick Slab', 'minecraft:cinnabar_brick_slab', 64),
  cinnabarWall('Cinnabar Wall', 'minecraft:cinnabar_wall', 64),
  light('Light', 'minecraft:light', 64),
  copperOre('Copper Ore', 'minecraft:copper_ore', 64),
  waxedWeatheredCopperTrapdoor('Waxed Weathered Copper Trapdoor',
      'minecraft:waxed_weathered_copper_trapdoor', 64),
  crackedDeepslateBricks('Cracked Deepslate Bricks', 'minecraft:cracked_deepslate_bricks', 64),
  copperBlock('Copper Block', 'minecraft:copper_block', 64),
  warpedSlab('Warped Slab', 'minecraft:warped_slab', 64),
  brownGlazedTerracotta('Brown Glazed Terracotta', 'minecraft:brown_glazed_terracotta', 64),
  endStoneBricks('End Stone Bricks', 'minecraft:end_stone_bricks', 64),
  chiseledQuartzBlock('Chiseled Quartz Block', 'minecraft:chiseled_quartz_block', 64),
  lightGrayGlazedTerracotta('Light Gray Glazed Terracotta',
      'minecraft:light_gray_glazed_terracotta', 64),
  cyanStainedGlass('Cyan Stained Glass', 'minecraft:cyan_stained_glass', 64),
  smoothSandstoneStairs('Smooth Sandstone Stairs', 'minecraft:smooth_sandstone_stairs', 64),
  orangeGlazedTerracotta('Orange Glazed Terracotta', 'minecraft:orange_glazed_terracotta', 64),
  creakingHeart('Creaking Heart', 'minecraft:creaking_heart', 64),
  whiteCarpet('White Carpet', 'minecraft:white_carpet', 64),
  cherryPressurePlate('Cherry Pressure Plate', 'minecraft:cherry_pressure_plate', 64),
  amethystCluster('Amethyst Cluster', 'minecraft:amethyst_cluster', 64),
  redstoneTorch('Redstone Torch', 'minecraft:redstone_torch', 64),
  whiteConcretePowder('White Concrete Powder', 'minecraft:white_concrete_powder', 64),
  crimsonDoor('Crimson Door', 'minecraft:crimson_door', 64),
  flowerPot('Flower Pot', 'minecraft:flower_pot', 64),
  hopper('Hopper', 'minecraft:hopper', 64),
  fern('Fern', 'minecraft:fern', 64),
  polishedBlackstoneWall('Polished Blackstone Wall', 'minecraft:polished_blackstone_wall', 64),
  waxedWeatheredCopperChest('Waxed Weathered Copper Chest',
      'minecraft:waxed_weathered_copper_chest', 64),
  strippedBambooBlock('Stripped Bamboo Block', 'minecraft:stripped_bamboo_block', 64),
  waxedExposedChiseledCopper('Waxed Exposed Chiseled Copper',
      'minecraft:waxed_exposed_chiseled_copper', 64),
  tuffBricks('Tuff Bricks', 'minecraft:tuff_bricks', 64),
  jungleLeaves('Jungle Leaves', 'minecraft:jungle_leaves', 64),
  spruceLog('Spruce Log', 'minecraft:spruce_log', 64),
  goldOre('Gold Ore', 'minecraft:gold_ore', 64),
  blackstoneStairs('Blackstone Stairs', 'minecraft:blackstone_stairs', 64),
  frogspawn('Frogspawn', 'minecraft:frogspawn', 64),
  lightBlueShulkerBox('Light Blue Shulker Box', 'minecraft:light_blue_shulker_box', 1),
  waxedOxidizedCutCopperStairs('Waxed Oxidized Cut Copper Stairs',
      'minecraft:waxed_oxidized_cut_copper_stairs', 64),
  bambooHangingSign('Bamboo Hanging Sign', 'minecraft:bamboo_hanging_sign', 16),
  brownWool('Brown Wool', 'minecraft:brown_wool', 64),
  largeFern('Large Fern', 'minecraft:large_fern', 64),
  limeStainedGlassPane('Lime Stained Glass Pane', 'minecraft:lime_stained_glass_pane', 64),
  waxedOxidizedCopper('Waxed Oxidized Copper', 'minecraft:waxed_oxidized_copper', 64),
  waxedExposedCopperGolemStatue('Waxed Exposed Copper Golem Statue',
      'minecraft:waxed_exposed_copper_golem_statue', 64),
  dispenser('Dispenser', 'minecraft:dispenser', 64),
  purpleShulkerBox('Purple Shulker Box', 'minecraft:purple_shulker_box', 1),
  cutCopperSlab('Cut Copper Slab', 'minecraft:cut_copper_slab', 64),
  oakFence('Oak Fence', 'minecraft:oak_fence', 64),
  largeAmethystBud('Large Amethyst Bud', 'minecraft:large_amethyst_bud', 64),
  resinBlock('Resin Block', 'minecraft:resin_block', 64),
  mangroveHangingSign('Mangrove Hanging Sign', 'minecraft:mangrove_hanging_sign', 16),
  magentaConcrete('Magenta Concrete', 'minecraft:magenta_concrete', 64),
  yellowTerracotta('Yellow Terracotta', 'minecraft:yellow_terracotta', 64),
  oakWood('Oak Wood', 'minecraft:oak_wood', 64),
  redNetherBrickStairs('Red Nether Brick Stairs', 'minecraft:red_nether_brick_stairs', 64),
  purpleBed('Purple Bed', 'minecraft:purple_bed', 1),
  floweringAzalea('Flowering Azalea', 'minecraft:flowering_azalea', 64),
  cherrySapling('Cherry Sapling', 'minecraft:cherry_sapling', 64),
  witherSkeletonSkull('Wither Skeleton Skull', 'minecraft:wither_skeleton_skull', 64),
  limeStainedGlass('Lime Stained Glass', 'minecraft:lime_stained_glass', 64),
  purpurBlock('Purpur Block', 'minecraft:purpur_block', 64),
  cherryFenceGate('Cherry Fence Gate', 'minecraft:cherry_fence_gate', 64),
  pinkStainedGlassPane('Pink Stained Glass Pane', 'minecraft:pink_stained_glass_pane', 64),
  blueIce('Blue Ice', 'minecraft:blue_ice', 64),
  chiseledSulfur('Chiseled Sulfur', 'minecraft:chiseled_sulfur', 64),
  mossCarpet('Moss Carpet', 'minecraft:moss_carpet', 64),
  smoothStoneSlab('Smooth Stone Slab', 'minecraft:smooth_stone_slab', 64),
  coarseDirt('Coarse Dirt', 'minecraft:coarse_dirt', 64),
  redBanner('Red Banner', 'minecraft:red_banner', 16),
  grayTerracotta('Gray Terracotta', 'minecraft:gray_terracotta', 64),
  birchSapling('Birch Sapling', 'minecraft:birch_sapling', 64),
  mangroveFenceGate('Mangrove Fence Gate', 'minecraft:mangrove_fence_gate', 64),
  stoneBrickWall('Stone Brick Wall', 'minecraft:stone_brick_wall', 64),
  waxedCopperChain('Waxed Copper Chain', 'minecraft:waxed_copper_chain', 64),
  cactusFlower('Cactus Flower', 'minecraft:cactus_flower', 64),
  oakLog('Oak Log', 'minecraft:oak_log', 64),
  sandstone('Sandstone', 'minecraft:sandstone', 64),
  chiseledDeepslate('Chiseled Deepslate', 'minecraft:chiseled_deepslate', 64),
  waxedExposedCopperTrapdoor('Waxed Exposed Copper Trapdoor',
      'minecraft:waxed_exposed_copper_trapdoor', 64),
  snowBlock('Snow Block', 'minecraft:snow_block', 64),
  weatheredCopperLantern('Weathered Copper Lantern', 'minecraft:weathered_copper_lantern', 64),
  beacon('Beacon', 'minecraft:beacon', 64),
  limeWool('Lime Wool', 'minecraft:lime_wool', 64),
  quartzStairs('Quartz Stairs', 'minecraft:quartz_stairs', 64),
  netherGoldOre('Nether Gold Ore', 'minecraft:nether_gold_ore', 64),
  blueOrchid('Blue Orchid', 'minecraft:blue_orchid', 64),
  deadHornCoralFan('Dead Horn Coral Fan', 'minecraft:dead_horn_coral_fan', 64),
  birchShelf('Birch Shelf', 'minecraft:birch_shelf', 64),
  strippedMangroveLog('Stripped Mangrove Log', 'minecraft:stripped_mangrove_log', 64),
  candle('Candle', 'minecraft:candle', 64),
  blueCandle('Blue Candle', 'minecraft:blue_candle', 64),
  ironTrapdoor('Iron Trapdoor', 'minecraft:iron_trapdoor', 64),
  cyanCandle('Cyan Candle', 'minecraft:cyan_candle', 64),
  deepslateEmeraldOre('Deepslate Emerald Ore', 'minecraft:deepslate_emerald_ore', 64),
  heavyWeightedPressurePlate('Heavy Weighted Pressure Plate',
      'minecraft:heavy_weighted_pressure_plate', 64),
  crimsonSlab('Crimson Slab', 'minecraft:crimson_slab', 64),
  lightBlueBanner('Light Blue Banner', 'minecraft:light_blue_banner', 16),
  copperTorch('Copper Torch', 'minecraft:copper_torch', 64),
  bambooSlab('Bamboo Slab', 'minecraft:bamboo_slab', 64),
  acaciaTrapdoor('Acacia Trapdoor', 'minecraft:acacia_trapdoor', 64),
  waxedWeatheredCopper('Waxed Weathered Copper', 'minecraft:waxed_weathered_copper', 64),
  stickyPiston('Sticky Piston', 'minecraft:sticky_piston', 64),
  polishedBlackstoneStairs('Polished Blackstone Stairs', 'minecraft:polished_blackstone_stairs',
      64),
  waxedOxidizedCopperDoor('Waxed Oxidized Copper Door', 'minecraft:waxed_oxidized_copper_door', 64),
  spruceTrapdoor('Spruce Trapdoor', 'minecraft:spruce_trapdoor', 64),
  blueConcrete('Blue Concrete', 'minecraft:blue_concrete', 64),
  exposedCopperBars('Exposed Copper Bars', 'minecraft:exposed_copper_bars', 64),
  warpedNylium('Warped Nylium', 'minecraft:warped_nylium', 64),
  chiseledCopper('Chiseled Copper', 'minecraft:chiseled_copper', 64),
  pearlescentFroglight('Pearlescent Froglight', 'minecraft:pearlescent_froglight', 64),
  netherSprouts('Nether Sprouts', 'minecraft:nether_sprouts', 64),
  ladder('Ladder', 'minecraft:ladder', 64),
  paleOakPlanks('Pale Oak Planks', 'minecraft:pale_oak_planks', 64),
  grayConcretePowder('Gray Concrete Powder', 'minecraft:gray_concrete_powder', 64),
  cutRedSandstoneSlab('Cut Red Sandstone Slab', 'minecraft:cut_red_sandstone_slab', 64),
  mangroveDoor('Mangrove Door', 'minecraft:mangrove_door', 64),
  suspiciousGravel('Suspicious Gravel', 'minecraft:suspicious_gravel', 64),
  deepslateGoldOre('Deepslate Gold Ore', 'minecraft:deepslate_gold_ore', 64),
  mud('Mud', 'minecraft:mud', 64),
  greenCandle('Green Candle', 'minecraft:green_candle', 64),
  strippedMangroveWood('Stripped Mangrove Wood', 'minecraft:stripped_mangrove_wood', 64),
  waxedWeatheredCopperBulb('Waxed Weathered Copper Bulb', 'minecraft:waxed_weathered_copper_bulb',
      64),
  blackStainedGlassPane('Black Stained Glass Pane', 'minecraft:black_stained_glass_pane', 64),
  smoothQuartzStairs('Smooth Quartz Stairs', 'minecraft:smooth_quartz_stairs', 64),
  sculkShrieker('Sculk Shrieker', 'minecraft:sculk_shrieker', 64),
  yellowShulkerBox('Yellow Shulker Box', 'minecraft:yellow_shulker_box', 1),
  polishedCinnabar('Polished Cinnabar', 'minecraft:polished_cinnabar', 64),
  cinnabar('Cinnabar', 'minecraft:cinnabar', 64),
  bambooTrapdoor('Bamboo Trapdoor', 'minecraft:bamboo_trapdoor', 64),
  birchFence('Birch Fence', 'minecraft:birch_fence', 64),
  polishedBlackstone('Polished Blackstone', 'minecraft:polished_blackstone', 64),
  magentaGlazedTerracotta('Magenta Glazed Terracotta', 'minecraft:magenta_glazed_terracotta', 64),
  purpleConcretePowder('Purple Concrete Powder', 'minecraft:purple_concrete_powder', 64),
  ochreFroglight('Ochre Froglight', 'minecraft:ochre_froglight', 64),
  crimsonStem('Crimson Stem', 'minecraft:crimson_stem', 64),
  calcite('Calcite', 'minecraft:calcite', 64),
  redNetherBricks('Red Nether Bricks', 'minecraft:red_nether_bricks', 64),
  lightningRod('Lightning Rod', 'minecraft:lightning_rod', 64),
  limeTerracotta('Lime Terracotta', 'minecraft:lime_terracotta', 64),
  orangeConcrete('Orange Concrete', 'minecraft:orange_concrete', 64),
  brownStainedGlassPane('Brown Stained Glass Pane', 'minecraft:brown_stained_glass_pane', 64),
  repeater('Repeater', 'minecraft:repeater', 64),
  weepingVines('Weeping Vines', 'minecraft:weeping_vines', 64),
  lightGrayConcrete('Light Gray Concrete', 'minecraft:light_gray_concrete', 64),
  ironBars('Iron Bars', 'minecraft:iron_bars', 64),
  waxedExposedCopperLantern('Waxed Exposed Copper Lantern',
      'minecraft:waxed_exposed_copper_lantern', 64),
  polishedTuffWall('Polished Tuff Wall', 'minecraft:polished_tuff_wall', 64),
  waxedWeatheredCopperLantern('Waxed Weathered Copper Lantern',
      'minecraft:waxed_weathered_copper_lantern', 64),
  deepslateLapisOre('Deepslate Lapis Ore', 'minecraft:deepslate_lapis_ore', 64),
  sandstoneWall('Sandstone Wall', 'minecraft:sandstone_wall', 64),
  tuffBrickWall('Tuff Brick Wall', 'minecraft:tuff_brick_wall', 64),
  spruceShelf('Spruce Shelf', 'minecraft:spruce_shelf', 64),
  yellowBed('Yellow Bed', 'minecraft:yellow_bed', 1),
  magentaStainedGlass('Magenta Stained Glass', 'minecraft:magenta_stained_glass', 64),
  cobbledDeepslateWall('Cobbled Deepslate Wall', 'minecraft:cobbled_deepslate_wall', 64),
  strippedWarpedStem('Stripped Warped Stem', 'minecraft:stripped_warped_stem', 64),
  strippedCherryWood('Stripped Cherry Wood', 'minecraft:stripped_cherry_wood', 64),
  polishedSulfurSlab('Polished Sulfur Slab', 'minecraft:polished_sulfur_slab', 64),
  mangroveShelf('Mangrove Shelf', 'minecraft:mangrove_shelf', 64),
  seaLantern('Sea Lantern', 'minecraft:sea_lantern', 64),
  enchantingTable('Enchanting Table', 'minecraft:enchanting_table', 64),
  daylightDetector('Daylight Detector', 'minecraft:daylight_detector', 64),
  mossyStoneBricks('Mossy Stone Bricks', 'minecraft:mossy_stone_bricks', 64),
  crimsonFence('Crimson Fence', 'minecraft:crimson_fence', 64),
  cherryLeaves('Cherry Leaves', 'minecraft:cherry_leaves', 64),
  waxedChiseledCopper('Waxed Chiseled Copper', 'minecraft:waxed_chiseled_copper', 64),
  detectorRail('Detector Rail', 'minecraft:detector_rail', 64),
  limeBed('Lime Bed', 'minecraft:lime_bed', 1),
  strippedCherryLog('Stripped Cherry Log', 'minecraft:stripped_cherry_log', 64),
  endStoneBrickStairs('End Stone Brick Stairs', 'minecraft:end_stone_brick_stairs', 64),
  tuffStairs('Tuff Stairs', 'minecraft:tuff_stairs', 64),
  strippedSpruceLog('Stripped Spruce Log', 'minecraft:stripped_spruce_log', 64),
  crafter('Crafter', 'minecraft:crafter', 64),
  polishedSulfurStairs('Polished Sulfur Stairs', 'minecraft:polished_sulfur_stairs', 64),
  exposedCopperTrapdoor('Exposed Copper Trapdoor', 'minecraft:exposed_copper_trapdoor', 64),
  smoothSandstone('Smooth Sandstone', 'minecraft:smooth_sandstone', 64),
  polishedDeepslate('Polished Deepslate', 'minecraft:polished_deepslate', 64),
  lightBlueGlazedTerracotta('Light Blue Glazed Terracotta',
      'minecraft:light_blue_glazed_terracotta', 64),
  sandstoneSlab('Sandstone Slab', 'minecraft:sandstone_slab', 64),
  string('String', 'minecraft:string', 64),
  sculk('Sculk', 'minecraft:sculk', 64),
  waxedOxidizedCopperGolemStatue('Waxed Oxidized Copper Golem Statue',
      'minecraft:waxed_oxidized_copper_golem_statue', 64),
  oakFenceGate('Oak Fence Gate', 'minecraft:oak_fence_gate', 64),
  bambooMosaic('Bamboo Mosaic', 'minecraft:bamboo_mosaic', 64),
  acaciaDoor('Acacia Door', 'minecraft:acacia_door', 64),
  oakButton('Oak Button', 'minecraft:oak_button', 64),
  limeShulkerBox('Lime Shulker Box', 'minecraft:lime_shulker_box', 1),
  mangroveLog('Mangrove Log', 'minecraft:mangrove_log', 64),
  smoothBasalt('Smooth Basalt', 'minecraft:smooth_basalt', 64),
  mossyStoneBrickStairs('Mossy Stone Brick Stairs', 'minecraft:mossy_stone_brick_stairs', 64),
  jigsaw('Jigsaw', 'minecraft:jigsaw', 64),
  bookshelf('Bookshelf', 'minecraft:bookshelf', 64),
  lightGrayTerracotta('Light Gray Terracotta', 'minecraft:light_gray_terracotta', 64),
  oxidizedCopperDoor('Oxidized Copper Door', 'minecraft:oxidized_copper_door', 64),
  stoneButton('Stone Button', 'minecraft:stone_button', 64),
  crimsonFungus('Crimson Fungus', 'minecraft:crimson_fungus', 64);

  final String displayName;
  final String material;
  final int maxStackSize;

  const BlockMaterial(this.displayName, this.material, this.maxStackSize);

}