/// The file is generated. Don't change anything here
enum SpawnEggMaterial {

  ghastSpawnEgg('Ghast Spawn Egg', 'minecraft:ghast_spawn_egg', 64),
  beeSpawnEgg('Bee Spawn Egg', 'minecraft:bee_spawn_egg', 64),
  nautilusSpawnEgg('Nautilus Spawn Egg', 'minecraft:nautilus_spawn_egg', 64),
  axolotlSpawnEgg('Axolotl Spawn Egg', 'minecraft:axolotl_spawn_egg', 64),
  piglinBruteSpawnEgg('Piglin Brute Spawn Egg', 'minecraft:piglin_brute_spawn_egg', 64),
  copperGolemSpawnEgg('Copper Golem Spawn Egg', 'minecraft:copper_golem_spawn_egg', 64),
  ocelotSpawnEgg('Ocelot Spawn Egg', 'minecraft:ocelot_spawn_egg', 64),
  foxSpawnEgg('Fox Spawn Egg', 'minecraft:fox_spawn_egg', 64),
  zombieSpawnEgg('Zombie Spawn Egg', 'minecraft:zombie_spawn_egg', 64),
  silverfishSpawnEgg('Silverfish Spawn Egg', 'minecraft:silverfish_spawn_egg', 64),
  muleSpawnEgg('Mule Spawn Egg', 'minecraft:mule_spawn_egg', 64),
  creakingSpawnEgg('Creaking Spawn Egg', 'minecraft:creaking_spawn_egg', 64),
  allaySpawnEgg('Allay Spawn Egg', 'minecraft:allay_spawn_egg', 64),
  breezeSpawnEgg('Breeze Spawn Egg', 'minecraft:breeze_spawn_egg', 64),
  evokerSpawnEgg('Evoker Spawn Egg', 'minecraft:evoker_spawn_egg', 64),
  hoglinSpawnEgg('Hoglin Spawn Egg', 'minecraft:hoglin_spawn_egg', 64),
  armadilloSpawnEgg('Armadillo Spawn Egg', 'minecraft:armadillo_spawn_egg', 64),
  guardianSpawnEgg('Guardian Spawn Egg', 'minecraft:guardian_spawn_egg', 64),
  frogSpawnEgg('Frog Spawn Egg', 'minecraft:frog_spawn_egg', 64),
  skeletonHorseSpawnEgg('Skeleton Horse Spawn Egg', 'minecraft:skeleton_horse_spawn_egg', 64),
  zombifiedPiglinSpawnEgg('Zombified Piglin Spawn Egg', 'minecraft:zombified_piglin_spawn_egg', 64),
  elderGuardianSpawnEgg('Elder Guardian Spawn Egg', 'minecraft:elder_guardian_spawn_egg', 64),
  traderLlamaSpawnEgg('Trader Llama Spawn Egg', 'minecraft:trader_llama_spawn_egg', 64),
  wolfSpawnEgg('Wolf Spawn Egg', 'minecraft:wolf_spawn_egg', 64),
  witherSpawnEgg('Wither Spawn Egg', 'minecraft:wither_spawn_egg', 64),
  donkeySpawnEgg('Donkey Spawn Egg', 'minecraft:donkey_spawn_egg', 64),
  sulfurCubeSpawnEgg('Sulfur Cube Spawn Egg', 'minecraft:sulfur_cube_spawn_egg', 64),
  pillagerSpawnEgg('Pillager Spawn Egg', 'minecraft:pillager_spawn_egg', 64),
  mooshroomSpawnEgg('Mooshroom Spawn Egg', 'minecraft:mooshroom_spawn_egg', 64),
  slimeSpawnEgg('Slime Spawn Egg', 'minecraft:slime_spawn_egg', 64),
  magmaCubeSpawnEgg('Magma Cube Spawn Egg', 'minecraft:magma_cube_spawn_egg', 64),
  witchSpawnEgg('Witch Spawn Egg', 'minecraft:witch_spawn_egg', 64),
  zoglinSpawnEgg('Zoglin Spawn Egg', 'minecraft:zoglin_spawn_egg', 64),
  villagerSpawnEgg('Villager Spawn Egg', 'minecraft:villager_spawn_egg', 64),
  skeletonSpawnEgg('Skeleton Spawn Egg', 'minecraft:skeleton_spawn_egg', 64),
  vindicatorSpawnEgg('Vindicator Spawn Egg', 'minecraft:vindicator_spawn_egg', 64),
  turtleSpawnEgg('Turtle Spawn Egg', 'minecraft:turtle_spawn_egg', 64),
  pandaSpawnEgg('Panda Spawn Egg', 'minecraft:panda_spawn_egg', 64),
  snifferSpawnEgg('Sniffer Spawn Egg', 'minecraft:sniffer_spawn_egg', 64),
  wanderingTraderSpawnEgg('Wandering Trader Spawn Egg', 'minecraft:wandering_trader_spawn_egg', 64),
  straySpawnEgg('Stray Spawn Egg', 'minecraft:stray_spawn_egg', 64),
  caveSpiderSpawnEgg('Cave Spider Spawn Egg', 'minecraft:cave_spider_spawn_egg', 64),
  striderSpawnEgg('Strider Spawn Egg', 'minecraft:strider_spawn_egg', 64),
  polarBearSpawnEgg('Polar Bear Spawn Egg', 'minecraft:polar_bear_spawn_egg', 64),
  witherSkeletonSpawnEgg('Wither Skeleton Spawn Egg', 'minecraft:wither_skeleton_spawn_egg', 64),
  salmonSpawnEgg('Salmon Spawn Egg', 'minecraft:salmon_spawn_egg', 64),
  glowSquidSpawnEgg('Glow Squid Spawn Egg', 'minecraft:glow_squid_spawn_egg', 64),
  parrotSpawnEgg('Parrot Spawn Egg', 'minecraft:parrot_spawn_egg', 64),
  dolphinSpawnEgg('Dolphin Spawn Egg', 'minecraft:dolphin_spawn_egg', 64),
  catSpawnEgg('Cat Spawn Egg', 'minecraft:cat_spawn_egg', 64),
  endermanSpawnEgg('Enderman Spawn Egg', 'minecraft:enderman_spawn_egg', 64),
  piglinSpawnEgg('Piglin Spawn Egg', 'minecraft:piglin_spawn_egg', 64),
  shulkerSpawnEgg('Shulker Spawn Egg', 'minecraft:shulker_spawn_egg', 64),
  spiderSpawnEgg('Spider Spawn Egg', 'minecraft:spider_spawn_egg', 64),
  vexSpawnEgg('Vex Spawn Egg', 'minecraft:vex_spawn_egg', 64),
  zombieHorseSpawnEgg('Zombie Horse Spawn Egg', 'minecraft:zombie_horse_spawn_egg', 64),
  camelSpawnEgg('Camel Spawn Egg', 'minecraft:camel_spawn_egg', 64),
  goatSpawnEgg('Goat Spawn Egg', 'minecraft:goat_spawn_egg', 64),
  snowGolemSpawnEgg('Snow Golem Spawn Egg', 'minecraft:snow_golem_spawn_egg', 64),
  huskSpawnEgg('Husk Spawn Egg', 'minecraft:husk_spawn_egg', 64),
  endermiteSpawnEgg('Endermite Spawn Egg', 'minecraft:endermite_spawn_egg', 64),
  phantomSpawnEgg('Phantom Spawn Egg', 'minecraft:phantom_spawn_egg', 64),
  camelHuskSpawnEgg('Camel Husk Spawn Egg', 'minecraft:camel_husk_spawn_egg', 64),
  squidSpawnEgg('Squid Spawn Egg', 'minecraft:squid_spawn_egg', 64),
  parchedSpawnEgg('Parched Spawn Egg', 'minecraft:parched_spawn_egg', 64),
  tadpoleSpawnEgg('Tadpole Spawn Egg', 'minecraft:tadpole_spawn_egg', 64),
  horseSpawnEgg('Horse Spawn Egg', 'minecraft:horse_spawn_egg', 64),
  ironGolemSpawnEgg('Iron Golem Spawn Egg', 'minecraft:iron_golem_spawn_egg', 64),
  ravagerSpawnEgg('Ravager Spawn Egg', 'minecraft:ravager_spawn_egg', 64),
  enderDragonSpawnEgg('Ender Dragon Spawn Egg', 'minecraft:ender_dragon_spawn_egg', 64),
  happyGhastSpawnEgg('Happy Ghast Spawn Egg', 'minecraft:happy_ghast_spawn_egg', 64),
  drownedSpawnEgg('Drowned Spawn Egg', 'minecraft:drowned_spawn_egg', 64),
  chickenSpawnEgg('Chicken Spawn Egg', 'minecraft:chicken_spawn_egg', 64),
  tropicalFishSpawnEgg('Tropical Fish Spawn Egg', 'minecraft:tropical_fish_spawn_egg', 64),
  boggedSpawnEgg('Bogged Spawn Egg', 'minecraft:bogged_spawn_egg', 64),
  creeperSpawnEgg('Creeper Spawn Egg', 'minecraft:creeper_spawn_egg', 64),
  sheepSpawnEgg('Sheep Spawn Egg', 'minecraft:sheep_spawn_egg', 64),
  codSpawnEgg('Cod Spawn Egg', 'minecraft:cod_spawn_egg', 64),
  pufferfishSpawnEgg('Pufferfish Spawn Egg', 'minecraft:pufferfish_spawn_egg', 64),
  zombieNautilusSpawnEgg('Zombie Nautilus Spawn Egg', 'minecraft:zombie_nautilus_spawn_egg', 64),
  cowSpawnEgg('Cow Spawn Egg', 'minecraft:cow_spawn_egg', 64),
  pigSpawnEgg('Pig Spawn Egg', 'minecraft:pig_spawn_egg', 64),
  batSpawnEgg('Bat Spawn Egg', 'minecraft:bat_spawn_egg', 64),
  wardenSpawnEgg('Warden Spawn Egg', 'minecraft:warden_spawn_egg', 64),
  llamaSpawnEgg('Llama Spawn Egg', 'minecraft:llama_spawn_egg', 64),
  blazeSpawnEgg('Blaze Spawn Egg', 'minecraft:blaze_spawn_egg', 64),
  zombieVillagerSpawnEgg('Zombie Villager Spawn Egg', 'minecraft:zombie_villager_spawn_egg', 64),
  rabbitSpawnEgg('Rabbit Spawn Egg', 'minecraft:rabbit_spawn_egg', 64);

  final String displayName;
  final String material;
  final int maxStackSize;

  const SpawnEggMaterial(this.displayName, this.material, this.maxStackSize);

}