/// Generated class to represent the available entities from the game Minecraft
enum EntityType {

  evoker('Evoker', 'minecraft:evoker'),
  villager('Villager', 'minecraft:villager'),
  cherryBoat('Cherry Boat', 'minecraft:cherry_boat'),
  interaction('Interaction', 'minecraft:interaction'),
  paleOakChestBoat('Pale Oak Chest Boat', 'minecraft:pale_oak_chest_boat'),
  glowSquid('Glow Squid', 'minecraft:glow_squid'),
  spawnerMinecart('Spawner Minecart', 'minecraft:spawner_minecart'),
  tntMinecart('Tnt Minecart', 'minecraft:tnt_minecart'),
  pufferfish('Pufferfish', 'minecraft:pufferfish'),
  oakBoat('Oak Boat', 'minecraft:oak_boat'),
  zombieHorse('Zombie Horse', 'minecraft:zombie_horse'),
  bogged('Bogged', 'minecraft:bogged'),
  minecart('Minecart', 'minecraft:minecart'),
  camelHusk('Camel Husk', 'minecraft:camel_husk'),
  arrow('Arrow', 'minecraft:arrow'),
  oakChestBoat('Oak Chest Boat', 'minecraft:oak_chest_boat'),
  happyGhast('Happy Ghast', 'minecraft:happy_ghast'),
  ghast('Ghast', 'minecraft:ghast'),
  skeletonHorse('Skeleton Horse', 'minecraft:skeleton_horse'),
  mule('Mule', 'minecraft:mule'),
  trident('Trident', 'minecraft:trident'),
  llama('Llama', 'minecraft:llama'),
  experienceBottle('Experience Bottle', 'minecraft:experience_bottle'),
  cod('Cod', 'minecraft:cod'),
  vex('Vex', 'minecraft:vex'),
  egg('Egg', 'minecraft:egg'),
  creeper('Creeper', 'minecraft:creeper'),
  glowItemFrame('Glow Item Frame', 'minecraft:glow_item_frame'),
  shulkerBullet('Shulker Bullet', 'minecraft:shulker_bullet'),
  cherryChestBoat('Cherry Chest Boat', 'minecraft:cherry_chest_boat'),
  spectralArrow('Spectral Arrow', 'minecraft:spectral_arrow'),
  giant('Giant', 'minecraft:giant'),
  donkey('Donkey', 'minecraft:donkey'),
  snowball('Snowball', 'minecraft:snowball'),
  hoglin('Hoglin', 'minecraft:hoglin'),
  experienceOrb('Experience Orb', 'minecraft:experience_orb'),
  enderDragon('Ender Dragon', 'minecraft:ender_dragon'),
  jungleChestBoat('Jungle Chest Boat', 'minecraft:jungle_chest_boat'),
  silverfish('Silverfish', 'minecraft:silverfish'),
  wolf('Wolf', 'minecraft:wolf'),
  ocelot('Ocelot', 'minecraft:ocelot'),
  bambooRaft('Bamboo Raft', 'minecraft:bamboo_raft'),
  wanderingTrader('Wandering Trader', 'minecraft:wandering_trader'),
  darkOakChestBoat('Dark Oak Chest Boat', 'minecraft:dark_oak_chest_boat'),
  skeleton('Skeleton', 'minecraft:skeleton'),
  jungleBoat('Jungle Boat', 'minecraft:jungle_boat'),
  fishingBobber('Fishing Bobber', 'minecraft:fishing_bobber'),
  snowGolem('Snow Golem', 'minecraft:snow_golem'),
  splashPotion('Splash Potion', 'minecraft:splash_potion'),
  tadpole('Tadpole', 'minecraft:tadpole'),
  armorStand('Armor Stand', 'minecraft:armor_stand'),
  dragonFireball('Dragon Fireball', 'minecraft:dragon_fireball'),
  salmon('Salmon', 'minecraft:salmon'),
  pillager('Pillager', 'minecraft:pillager'),
  acaciaChestBoat('Acacia Chest Boat', 'minecraft:acacia_chest_boat'),
  turtle('Turtle', 'minecraft:turtle'),
  axolotl('Axolotl', 'minecraft:axolotl'),
  commandBlockMinecart('Command Block Minecart', 'minecraft:command_block_minecart'),
  leashKnot('Leash Knot', 'minecraft:leash_knot'),
  zombieNautilus('Zombie Nautilus', 'minecraft:zombie_nautilus'),
  cow('Cow', 'minecraft:cow'),
  zombie('Zombie', 'minecraft:zombie'),
  camel('Camel', 'minecraft:camel'),
  witherSkull('Wither Skull', 'minecraft:wither_skull'),
  vindicator('Vindicator', 'minecraft:vindicator'),
  endermite('Endermite', 'minecraft:endermite'),
  spider('Spider', 'minecraft:spider'),
  cat('Cat', 'minecraft:cat'),
  panda('Panda', 'minecraft:panda'),
  husk('Husk', 'minecraft:husk'),
  bee('Bee', 'minecraft:bee'),
  breezeWindCharge('Breeze Wind Charge', 'minecraft:breeze_wind_charge'),
  warden('Warden', 'minecraft:warden'),
  lingeringPotion('Lingering Potion', 'minecraft:lingering_potion'),
  dolphin('Dolphin', 'minecraft:dolphin'),
  birchBoat('Birch Boat', 'minecraft:birch_boat'),
  enderPearl('Ender Pearl', 'minecraft:ender_pearl'),
  sniffer('Sniffer', 'minecraft:sniffer'),
  parched('Parched', 'minecraft:parched'),
  tropicalFish('Tropical Fish', 'minecraft:tropical_fish'),
  bat('Bat', 'minecraft:bat'),
  fox('Fox', 'minecraft:fox'),
  ironGolem('Iron Golem', 'minecraft:iron_golem'),
  magmaCube('Magma Cube', 'minecraft:magma_cube'),
  breeze('Breeze', 'minecraft:breeze'),
  textDisplay('Text Display', 'minecraft:text_display'),
  guardian('Guardian', 'minecraft:guardian'),
  fireball('Fireball', 'minecraft:fireball'),
  strider('Strider', 'minecraft:strider'),
  elderGuardian('Elder Guardian', 'minecraft:elder_guardian'),
  mangroveChestBoat('Mangrove Chest Boat', 'minecraft:mangrove_chest_boat'),
  ravager('Ravager', 'minecraft:ravager'),
  traderLlama('Trader Llama', 'minecraft:trader_llama'),
  eyeOfEnder('Eye Of Ender', 'minecraft:eye_of_ender'),
  acaciaBoat('Acacia Boat', 'minecraft:acacia_boat'),
  zoglin('Zoglin', 'minecraft:zoglin'),
  sheep('Sheep', 'minecraft:sheep'),
  copperGolem('Copper Golem', 'minecraft:copper_golem'),
  illusioner('Illusioner', 'minecraft:illusioner'),
  mangroveBoat('Mangrove Boat', 'minecraft:mangrove_boat'),
  mannequin('Mannequin', 'minecraft:mannequin'),
  creaking('Creaking', 'minecraft:creaking'),
  windCharge('Wind Charge', 'minecraft:wind_charge'),
  item('Item', 'minecraft:item'),
  painting('Painting', 'minecraft:painting'),
  areaEffectCloud('Area Effect Cloud', 'minecraft:area_effect_cloud'),
  enderman('Enderman', 'minecraft:enderman'),
  allay('Allay', 'minecraft:allay'),
  pig('Pig', 'minecraft:pig'),
  itemFrame('Item Frame', 'minecraft:item_frame'),
  bambooChestRaft('Bamboo Chest Raft', 'minecraft:bamboo_chest_raft'),
  endCrystal('End Crystal', 'minecraft:end_crystal'),
  polarBear('Polar Bear', 'minecraft:polar_bear'),
  horse('Horse', 'minecraft:horse'),
  zombieVillager('Zombie Villager', 'minecraft:zombie_villager'),
  marker('Marker', 'minecraft:marker'),
  rabbit('Rabbit', 'minecraft:rabbit'),
  itemDisplay('Item Display', 'minecraft:item_display'),
  chestMinecart('Chest Minecart', 'minecraft:chest_minecart'),
  llamaSpit('Llama Spit', 'minecraft:llama_spit'),
  darkOakBoat('Dark Oak Boat', 'minecraft:dark_oak_boat'),
  zombifiedPiglin('Zombified Piglin', 'minecraft:zombified_piglin'),
  spruceChestBoat('Spruce Chest Boat', 'minecraft:spruce_chest_boat'),
  spruceBoat('Spruce Boat', 'minecraft:spruce_boat'),
  phantom('Phantom', 'minecraft:phantom'),
  goat('Goat', 'minecraft:goat'),
  paleOakBoat('Pale Oak Boat', 'minecraft:pale_oak_boat'),
  birchChestBoat('Birch Chest Boat', 'minecraft:birch_chest_boat'),
  slime('Slime', 'minecraft:slime'),
  fireworkRocket('Firework Rocket', 'minecraft:firework_rocket'),
  smallFireball('Small Fireball', 'minecraft:small_fireball'),
  piglin('Piglin', 'minecraft:piglin'),
  parrot('Parrot', 'minecraft:parrot'),
  squid('Squid', 'minecraft:squid'),
  mooshroom('Mooshroom', 'minecraft:mooshroom'),
  drowned('Drowned', 'minecraft:drowned'),
  blockDisplay('Block Display', 'minecraft:block_display'),
  tnt('Tnt', 'minecraft:tnt'),
  caveSpider('Cave Spider', 'minecraft:cave_spider'),
  furnaceMinecart('Furnace Minecart', 'minecraft:furnace_minecart'),
  lightningBolt('Lightning Bolt', 'minecraft:lightning_bolt'),
  chicken('Chicken', 'minecraft:chicken'),
  fallingBlock('Falling Block', 'minecraft:falling_block'),
  frog('Frog', 'minecraft:frog'),
  nautilus('Nautilus', 'minecraft:nautilus'),
  armadillo('Armadillo', 'minecraft:armadillo'),
  wither('Wither', 'minecraft:wither'),
  witch('Witch', 'minecraft:witch'),
  evokerFangs('Evoker Fangs', 'minecraft:evoker_fangs'),
  piglinBrute('Piglin Brute', 'minecraft:piglin_brute'),
  shulker('Shulker', 'minecraft:shulker'),
  hopperMinecart('Hopper Minecart', 'minecraft:hopper_minecart'),
  player('Player', 'minecraft:player'),
  stray('Stray', 'minecraft:stray'),
  witherSkeleton('Wither Skeleton', 'minecraft:wither_skeleton'),
  ominousItemSpawner('Ominous Item Spawner', 'minecraft:ominous_item_spawner'),
  sulfurCube('Sulfur Cube', 'minecraft:sulfur_cube'),
  blaze('Blaze', 'minecraft:blaze');

  final String displayName;
  final String type;

  const EntityType(this.displayName, this.type);

}