/// Generated class to represent the available entities from the game Minecraft
enum EntityType {

  breeze('Breeze', 'breeze'),
  cat('Cat', 'cat'),
  acacia_boat('Acacia Boat', 'acacia_boat'),
  polar_bear('Polar Bear', 'polar_bear'),
  bamboo_raft('Bamboo Raft', 'bamboo_raft'),
  stray('Stray', 'stray'),
  fishing_bobber('Fishing Bobber', 'fishing_bobber'),
  phantom('Phantom', 'phantom'),
  wither('Wither', 'wither'),
  experience_orb('Experience Orb', 'experience_orb'),
  interaction('Interaction', 'interaction'),
  llama('Llama', 'llama'),
  salmon('Salmon', 'salmon'),
  eye_of_ender('Eye Of Ender', 'eye_of_ender'),
  trident('Trident', 'trident'),
  minecart('Minecart', 'minecart'),
  mooshroom('Mooshroom', 'mooshroom'),
  leash_knot('Leash Knot', 'leash_knot'),
  endermite('Endermite', 'endermite'),
  dark_oak_boat('Dark Oak Boat', 'dark_oak_boat'),
  llama_spit('Llama Spit', 'llama_spit'),
  giant('Giant', 'giant'),
  iron_golem('Iron Golem', 'iron_golem'),
  cherry_chest_boat('Cherry Chest Boat', 'cherry_chest_boat'),
  piglin_brute('Piglin Brute', 'piglin_brute'),
  tnt_minecart('Tnt Minecart', 'tnt_minecart'),
  allay('Allay', 'allay'),
  zombie_horse('Zombie Horse', 'zombie_horse'),
  snow_golem('Snow Golem', 'snow_golem'),
  ender_pearl('Ender Pearl', 'ender_pearl'),
  zombie('Zombie', 'zombie'),
  skeleton_horse('Skeleton Horse', 'skeleton_horse'),
  bogged('Bogged', 'bogged'),
  painting('Painting', 'painting'),
  dragon_fireball('Dragon Fireball', 'dragon_fireball'),
  oak_chest_boat('Oak Chest Boat', 'oak_chest_boat'),
  evoker_fangs('Evoker Fangs', 'evoker_fangs'),
  strider('Strider', 'strider'),
  evoker('Evoker', 'evoker'),
  goat('Goat', 'goat'),
  mangrove_boat('Mangrove Boat', 'mangrove_boat'),
  horse('Horse', 'horse'),
  sniffer('Sniffer', 'sniffer'),
  player('Player', 'player'),
  splash_potion('Splash Potion', 'splash_potion'),
  wither_skeleton('Wither Skeleton', 'wither_skeleton'),
  pale_oak_boat('Pale Oak Boat', 'pale_oak_boat'),
  lingering_potion('Lingering Potion', 'lingering_potion'),
  elder_guardian('Elder Guardian', 'elder_guardian'),
  camel('Camel', 'camel'),
  creaking('Creaking', 'creaking'),
  slime('Slime', 'slime'),
  wolf('Wolf', 'wolf'),
  drowned('Drowned', 'drowned'),
  armadillo('Armadillo', 'armadillo'),
  mule('Mule', 'mule'),
  parrot('Parrot', 'parrot'),
  ravager('Ravager', 'ravager'),
  axolotl('Axolotl', 'axolotl'),
  acacia_chest_boat('Acacia Chest Boat', 'acacia_chest_boat'),
  warden('Warden', 'warden'),
  command_block_minecart('Command Block Minecart', 'command_block_minecart'),
  breeze_wind_charge('Breeze Wind Charge', 'breeze_wind_charge'),
  item_frame('Item Frame', 'item_frame'),
  bee('Bee', 'bee'),
  trader_llama('Trader Llama', 'trader_llama'),
  piglin('Piglin', 'piglin'),
  squid('Squid', 'squid'),
  ominous_item_spawner('Ominous Item Spawner', 'ominous_item_spawner'),
  creeper('Creeper', 'creeper'),
  ocelot('Ocelot', 'ocelot'),
  mangrove_chest_boat('Mangrove Chest Boat', 'mangrove_chest_boat'),
  pufferfish('Pufferfish', 'pufferfish'),
  jungle_chest_boat('Jungle Chest Boat', 'jungle_chest_boat'),
  spruce_boat('Spruce Boat', 'spruce_boat'),
  vindicator('Vindicator', 'vindicator'),
  zoglin('Zoglin', 'zoglin'),
  hopper_minecart('Hopper Minecart', 'hopper_minecart'),
  furnace_minecart('Furnace Minecart', 'furnace_minecart'),
  magma_cube('Magma Cube', 'magma_cube'),
  sheep('Sheep', 'sheep'),
  wandering_trader('Wandering Trader', 'wandering_trader'),
  ghast('Ghast', 'ghast'),
  shulker('Shulker', 'shulker'),
  vex('Vex', 'vex'),
  fireball('Fireball', 'fireball'),
  fox('Fox', 'fox'),
  cherry_boat('Cherry Boat', 'cherry_boat'),
  husk('Husk', 'husk'),
  ender_dragon('Ender Dragon', 'ender_dragon'),
  dark_oak_chest_boat('Dark Oak Chest Boat', 'dark_oak_chest_boat'),
  villager('Villager', 'villager'),
  bamboo_chest_raft('Bamboo Chest Raft', 'bamboo_chest_raft'),
  tnt('Tnt', 'tnt'),
  zombified_piglin('Zombified Piglin', 'zombified_piglin'),
  glow_squid('Glow Squid', 'glow_squid'),
  guardian('Guardian', 'guardian'),
  birch_boat('Birch Boat', 'birch_boat'),
  zombie_villager('Zombie Villager', 'zombie_villager'),
  wither_skull('Wither Skull', 'wither_skull'),
  jungle_boat('Jungle Boat', 'jungle_boat'),
  tadpole('Tadpole', 'tadpole'),
  spruce_chest_boat('Spruce Chest Boat', 'spruce_chest_boat'),
  spider('Spider', 'spider'),
  panda('Panda', 'panda'),
  spectral_arrow('Spectral Arrow', 'spectral_arrow'),
  experience_bottle('Experience Bottle', 'experience_bottle'),
  oak_boat('Oak Boat', 'oak_boat'),
  cave_spider('Cave Spider', 'cave_spider'),
  area_effect_cloud('Area Effect Cloud', 'area_effect_cloud'),
  wind_charge('Wind Charge', 'wind_charge'),
  birch_chest_boat('Birch Chest Boat', 'birch_chest_boat'),
  rabbit('Rabbit', 'rabbit'),
  chest_minecart('Chest Minecart', 'chest_minecart'),
  dolphin('Dolphin', 'dolphin'),
  happy_ghast('Happy Ghast', 'happy_ghast'),
  small_fireball('Small Fireball', 'small_fireball'),
  tropical_fish('Tropical Fish', 'tropical_fish'),
  armor_stand('Armor Stand', 'armor_stand'),
  enderman('Enderman', 'enderman'),
  end_crystal('End Crystal', 'end_crystal'),
  cow('Cow', 'cow'),
  blaze('Blaze', 'blaze'),
  firework_rocket('Firework Rocket', 'firework_rocket'),
  pig('Pig', 'pig'),
  bat('Bat', 'bat'),
  frog('Frog', 'frog'),
  donkey('Donkey', 'donkey'),
  block_display('Block Display', 'block_display'),
  falling_block('Falling Block', 'falling_block'),
  item_display('Item Display', 'item_display'),
  text_display('Text Display', 'text_display'),
  hoglin('Hoglin', 'hoglin'),
  item('Item', 'item'),
  silverfish('Silverfish', 'silverfish'),
  pale_oak_chest_boat('Pale Oak Chest Boat', 'pale_oak_chest_boat'),
  chicken('Chicken', 'chicken'),
  snowball('Snowball', 'snowball'),
  egg('Egg', 'egg'),
  cod('Cod', 'cod'),
  turtle('Turtle', 'turtle'),
  spawner_minecart('Spawner Minecart', 'spawner_minecart'),
  shulker_bullet('Shulker Bullet', 'shulker_bullet'),
  glow_item_frame('Glow Item Frame', 'glow_item_frame'),
  skeleton('Skeleton', 'skeleton'),
  arrow('Arrow', 'arrow'),
  marker('Marker', 'marker'),
  illusioner('Illusioner', 'illusioner'),
  witch('Witch', 'witch'),
  lightning_bolt('Lightning Bolt', 'lightning_bolt'),
  pillager('Pillager', 'pillager');

  final String displayName;
  final String type;

  const EntityType(this.displayName, this.type);

}