/// The file is generated. Don't change anything here
enum BannerPattern {

  base('Base', 'minecraft:base', 'minecraft:base', 'block.minecraft.banner.base'),
  border('Border', 'minecraft:border', 'minecraft:border', 'block.minecraft.banner.border'),
  bricks('Bricks', 'minecraft:bricks', 'minecraft:bricks', 'block.minecraft.banner.bricks'),
  circle('Circle', 'minecraft:circle', 'minecraft:circle', 'block.minecraft.banner.circle'),
  creeper('Creeper', 'minecraft:creeper', 'minecraft:creeper', 'block.minecraft.banner.creeper'),
  cross('Cross', 'minecraft:cross', 'minecraft:cross', 'block.minecraft.banner.cross'),
  curlyBorder('Curly Border', 'minecraft:curly_border', 'minecraft:curly_border',
      'block.minecraft.banner.curly_border'),
  diagonalLeft('Diagonal Left', 'minecraft:diagonal_left', 'minecraft:diagonal_left',
      'block.minecraft.banner.diagonal_left'),
  diagonalRight('Diagonal Right', 'minecraft:diagonal_right', 'minecraft:diagonal_right',
      'block.minecraft.banner.diagonal_right'),
  diagonalUpLeft('Diagonal Up Left', 'minecraft:diagonal_up_left', 'minecraft:diagonal_up_left',
      'block.minecraft.banner.diagonal_up_left'),
  diagonalUpRight('Diagonal Up Right', 'minecraft:diagonal_up_right', 'minecraft:diagonal_up_right',
      'block.minecraft.banner.diagonal_up_right'),
  flow('Flow', 'minecraft:flow', 'minecraft:flow', 'block.minecraft.banner.flow'),
  flower('Flower', 'minecraft:flower', 'minecraft:flower', 'block.minecraft.banner.flower'),
  globe('Globe', 'minecraft:globe', 'minecraft:globe', 'block.minecraft.banner.globe'),
  gradient('Gradient', 'minecraft:gradient', 'minecraft:gradient',
      'block.minecraft.banner.gradient'),
  gradientUp('Gradient Up', 'minecraft:gradient_up', 'minecraft:gradient_up',
      'block.minecraft.banner.gradient_up'),
  guster('Guster', 'minecraft:guster', 'minecraft:guster', 'block.minecraft.banner.guster'),
  halfHorizontal('Half Horizontal', 'minecraft:half_horizontal', 'minecraft:half_horizontal',
      'block.minecraft.banner.half_horizontal'),
  halfHorizontalBottom('Half Horizontal Bottom', 'minecraft:half_horizontal_bottom',
      'minecraft:half_horizontal_bottom', 'block.minecraft.banner.half_horizontal_bottom'),
  halfVertical('Half Vertical', 'minecraft:half_vertical', 'minecraft:half_vertical',
      'block.minecraft.banner.half_vertical'),
  halfVerticalRight('Half Vertical Right', 'minecraft:half_vertical_right',
      'minecraft:half_vertical_right', 'block.minecraft.banner.half_vertical_right'),
  mojang('Mojang', 'minecraft:mojang', 'minecraft:mojang', 'block.minecraft.banner.mojang'),
  piglin('Piglin', 'minecraft:piglin', 'minecraft:piglin', 'block.minecraft.banner.piglin'),
  rhombus('Rhombus', 'minecraft:rhombus', 'minecraft:rhombus', 'block.minecraft.banner.rhombus'),
  skull('Skull', 'minecraft:skull', 'minecraft:skull', 'block.minecraft.banner.skull'),
  smallStripes('Small Stripes', 'minecraft:small_stripes', 'minecraft:small_stripes',
      'block.minecraft.banner.small_stripes'),
  squareBottomLeft('Square Bottom Left', 'minecraft:square_bottom_left',
      'minecraft:square_bottom_left', 'block.minecraft.banner.square_bottom_left'),
  squareBottomRight('Square Bottom Right', 'minecraft:square_bottom_right',
      'minecraft:square_bottom_right', 'block.minecraft.banner.square_bottom_right'),
  squareTopLeft('Square Top Left', 'minecraft:square_top_left', 'minecraft:square_top_left',
      'block.minecraft.banner.square_top_left'),
  squareTopRight('Square Top Right', 'minecraft:square_top_right', 'minecraft:square_top_right',
      'block.minecraft.banner.square_top_right'),
  straightCross('Straight Cross', 'minecraft:straight_cross', 'minecraft:straight_cross',
      'block.minecraft.banner.straight_cross'),
  stripeBottom('Stripe Bottom', 'minecraft:stripe_bottom', 'minecraft:stripe_bottom',
      'block.minecraft.banner.stripe_bottom'),
  stripeCenter('Stripe Center', 'minecraft:stripe_center', 'minecraft:stripe_center',
      'block.minecraft.banner.stripe_center'),
  stripeDownleft('Stripe Downleft', 'minecraft:stripe_downleft', 'minecraft:stripe_downleft',
      'block.minecraft.banner.stripe_downleft'),
  stripeDownright('Stripe Downright', 'minecraft:stripe_downright', 'minecraft:stripe_downright',
      'block.minecraft.banner.stripe_downright'),
  stripeLeft('Stripe Left', 'minecraft:stripe_left', 'minecraft:stripe_left',
      'block.minecraft.banner.stripe_left'),
  stripeMiddle('Stripe Middle', 'minecraft:stripe_middle', 'minecraft:stripe_middle',
      'block.minecraft.banner.stripe_middle'),
  stripeRight('Stripe Right', 'minecraft:stripe_right', 'minecraft:stripe_right',
      'block.minecraft.banner.stripe_right'),
  stripeTop('Stripe Top', 'minecraft:stripe_top', 'minecraft:stripe_top',
      'block.minecraft.banner.stripe_top'),
  triangleBottom('Triangle Bottom', 'minecraft:triangle_bottom', 'minecraft:triangle_bottom',
      'block.minecraft.banner.triangle_bottom'),
  triangleTop('Triangle Top', 'minecraft:triangle_top', 'minecraft:triangle_top',
      'block.minecraft.banner.triangle_top'),
  trianglesBottom('Triangles Bottom', 'minecraft:triangles_bottom', 'minecraft:triangles_bottom',
      'block.minecraft.banner.triangles_bottom'),
  trianglesTop('Triangles Top', 'minecraft:triangles_top', 'minecraft:triangles_top',
      'block.minecraft.banner.triangles_top');

  final String displayName;
  final String key;
  final String assetId;
  final String translationKey;

  const BannerPattern(this.displayName, this.key, this.assetId, this.translationKey);

}