/// Generated class for the sound events. Don't edit this file manually
enum BlockSound {

  woolHit('Wool hit', 'minecraft:block.wool.hit'),
  dripstoneBlockPlace('Dripstone Block place', 'minecraft:block.dripstone_block.place'),
  netherBricksFall('Nether Bricks fall', 'minecraft:block.nether_bricks.fall'),
  copperDoorClose('Copper Door close', 'minecraft:block.copper_door.close'),
  froglightHit('Froglight hit', 'minecraft:block.froglight.hit'),
  sculkBreak('Sculk break', 'minecraft:block.sculk.break'),
  smallDripleafStep('Small Dripleaf step', 'minecraft:block.small_dripleaf.step'),
  caveVinesPickBerries('Cave Vines pick Berries', 'minecraft:block.cave_vines.pick_berries'),
  froglightPlace('Froglight place', 'minecraft:block.froglight.place'),
  scaffoldingPlace('Scaffolding place', 'minecraft:block.scaffolding.place'),
  deepslateBricksPlace('Deepslate Bricks place', 'minecraft:block.deepslate_bricks.place'),
  chainPlace('Chain place', 'minecraft:block.chain.place'),
  tuffBricksBreak('Tuff Bricks break', 'minecraft:block.tuff_bricks.break'),
  sculkVeinPlace('Sculk Vein place', 'minecraft:block.sculk_vein.place'),
  sweetBerryBushBreak('Sweet Berry Bush break', 'minecraft:block.sweet_berry_bush.break'),
  bigDripleafPlace('Big Dripleaf place', 'minecraft:block.big_dripleaf.place'),
  azaleaHit('Azalea hit', 'minecraft:block.azalea.hit'),
  basaltBreak('Basalt break', 'minecraft:block.basalt.break'),
  shelfBreak('Shelf break', 'minecraft:block.shelf.break'),
  cherryWoodButtonClickOff('Cherry Wood Button click Off',
      'minecraft:block.cherry_wood_button.click_off'),
  creakingHeartHit('Creaking Heart hit', 'minecraft:block.creaking_heart.hit'),
  tuffPlace('Tuff place', 'minecraft:block.tuff.place'),
  spawnerPlace('Spawner place', 'minecraft:block.spawner.place'),
  shroomlightPlace('Shroomlight place', 'minecraft:block.shroomlight.place'),
  honeyBlockSlide('Honey Block slide', 'minecraft:block.honey_block.slide'),
  packedMudStep('Packed Mud step', 'minecraft:block.packed_mud.step'),
  ironFall('Iron fall', 'minecraft:block.iron.fall'),
  mossFall('Moss fall', 'minecraft:block.moss.fall'),
  heavyCoreFall('Heavy Core fall', 'minecraft:block.heavy_core.fall'),
  shelfTakeItem('Shelf take Item', 'minecraft:block.shelf.take_item'),
  copperGolemStatueStep('Copper Golem Statue step', 'minecraft:block.copper_golem_statue.step'),
  azaleaLeavesPlace('Azalea Leaves place', 'minecraft:block.azalea_leaves.place'),
  noteBlockTrumpetExposed('Note Block trumpet Exposed',
      'minecraft:block.note_block.trumpet_exposed'),
  vaultActivate('Vault activate', 'minecraft:block.vault.activate'),
  mossCarpetFall('Moss Carpet fall', 'minecraft:block.moss_carpet.fall'),
  gravelBreak('Gravel break', 'minecraft:block.gravel.break'),
  vaultRejectRewardedPlayer('Vault reject Rewarded Player',
      'minecraft:block.vault.reject_rewarded_player'),
  netherSproutsFall('Nether Sprouts fall', 'minecraft:block.nether_sprouts.fall'),
  bambooSaplingBreak('Bamboo Sapling break', 'minecraft:block.bamboo_sapling.break'),
  mangroveRootsPlace('Mangrove Roots place', 'minecraft:block.mangrove_roots.place'),
  ladderHit('Ladder hit', 'minecraft:block.ladder.hit'),
  smallAmethystBudPlace('Small Amethyst Bud place', 'minecraft:block.small_amethyst_bud.place'),
  anvilUse('Anvil use', 'minecraft:block.anvil.use'),
  netherGoldOrePlace('Nether Gold Ore place', 'minecraft:block.nether_gold_ore.place'),
  stemBreak('Stem break', 'minecraft:block.stem.break'),
  shelfFall('Shelf fall', 'minecraft:block.shelf.fall'),
  candleBreak('Candle break', 'minecraft:block.candle.break'),
  spongeHit('Sponge hit', 'minecraft:block.sponge.hit'),
  woolPlace('Wool place', 'minecraft:block.wool.place'),
  netherWoodHangingSignStep('Nether Wood Hanging Sign step',
      'minecraft:block.nether_wood_hanging_sign.step'),
  woodBreak('Wood break', 'minecraft:block.wood.break'),
  soulSoilHit('Soul Soil hit', 'minecraft:block.soul_soil.hit'),
  sculkSpread('Sculk spread', 'minecraft:block.sculk.spread'),
  copperTrapdoorOpen('Copper Trapdoor open', 'minecraft:block.copper_trapdoor.open'),
  dispenserFail('Dispenser fail', 'minecraft:block.dispenser.fail'),
  sulfurSpikePlace('Sulfur Spike place', 'minecraft:block.sulfur_spike.place'),
  sculkVeinStep('Sculk Vein step', 'minecraft:block.sculk_vein.step'),
  noteBlockBell('Note Block bell', 'minecraft:block.note_block.bell'),
  noteBlockWitherSkeleton('Note Block wither Skeleton',
      'minecraft:block.note_block.imitate.wither_skeleton'),
  pinkPetalsBreak('Pink Petals break', 'minecraft:block.pink_petals.break'),
  trialSpawnerDetectPlayer('Trial Spawner detect Player',
      'minecraft:block.trial_spawner.detect_player'),
  glassBreak('Glass break', 'minecraft:block.glass.break'),
  sculkCatalystStep('Sculk Catalyst step', 'minecraft:block.sculk_catalyst.step'),
  sulfurPlace('Sulfur place', 'minecraft:block.sulfur.place'),
  tripwireClickOff('Tripwire click Off', 'minecraft:block.tripwire.click_off'),
  comparatorClick('Comparator click', 'minecraft:block.comparator.click'),
  decoratedPotInsertFail('Decorated Pot insert Fail', 'minecraft:block.decorated_pot.insert_fail'),
  netherWoodButtonClickOn('Nether Wood Button click On',
      'minecraft:block.nether_wood_button.click_on'),
  netherWoodHangingSignPlace('Nether Wood Hanging Sign place',
      'minecraft:block.nether_wood_hanging_sign.place'),
  azaleaBreak('Azalea break', 'minecraft:block.azalea.break'),
  lodestoneStep('Lodestone step', 'minecraft:block.lodestone.step'),
  spongeFall('Sponge fall', 'minecraft:block.sponge.fall'),
  sulfurSpikeFall('Sulfur Spike fall', 'minecraft:block.sulfur_spike.fall'),
  grassBreak('Grass break', 'minecraft:block.grass.break'),
  mossPlace('Moss place', 'minecraft:block.moss.place'),
  copperTrapdoorClose('Copper Trapdoor close', 'minecraft:block.copper_trapdoor.close'),
  copperDoorOpen('Copper Door open', 'minecraft:block.copper_door.open'),
  netherOreHit('Nether Ore hit', 'minecraft:block.nether_ore.hit'),
  resinPlace('Resin place', 'minecraft:block.resin.place'),
  soulSoilPlace('Soul Soil place', 'minecraft:block.soul_soil.place'),
  metalFall('Metal fall', 'minecraft:block.metal.fall'),
  deepslateBricksFall('Deepslate Bricks fall', 'minecraft:block.deepslate_bricks.fall'),
  cropBreak('Crop break', 'minecraft:block.crop.break'),
  largeAmethystBudBreak('Large Amethyst Bud break', 'minecraft:block.large_amethyst_bud.break'),
  hangingSignWaxedInteractFail('Hanging Sign waxed Interact Fail',
      'minecraft:block.hanging_sign.waxed_interact_fail'),
  suspiciousGravelStep('Suspicious Gravel step', 'minecraft:block.suspicious_gravel.step'),
  eyeblossomOpen('Eyeblossom open', 'minecraft:block.eyeblossom.open'),
  hangingSignPlace('Hanging Sign place', 'minecraft:block.hanging_sign.place'),
  noteBlockHarp('Note Block harp', 'minecraft:block.note_block.harp'),
  mediumAmethystBudPlace('Medium Amethyst Bud place', 'minecraft:block.medium_amethyst_bud.place'),
  rootsBreak('Roots break', 'minecraft:block.roots.break'),
  bambooBreak('Bamboo break', 'minecraft:block.bamboo.break'),
  beehiveDrip('Beehive drip', 'minecraft:block.beehive.drip'),
  suspiciousSandFall('Suspicious Sand fall', 'minecraft:block.suspicious_sand.fall'),
  amethystClusterStep('Amethyst Cluster step', 'minecraft:block.amethyst_cluster.step'),
  vaultInsertItemFail('Vault insert Item Fail', 'minecraft:block.vault.insert_item_fail'),
  netherOreStep('Nether Ore step', 'minecraft:block.nether_ore.step'),
  eyeblossomIdle('Eyeblossom idle', 'minecraft:block.eyeblossom.idle'),
  ironDoorOpen('Iron Door open', 'minecraft:block.iron_door.open'),
  gildedBlackstoneFall('Gilded Blackstone fall', 'minecraft:block.gilded_blackstone.fall'),
  candleAmbient('Candle ambient', 'minecraft:block.candle.ambient'),
  fireAmbient('Fire ambient', 'minecraft:block.fire.ambient'),
  trialSpawnerAmbientOminous('Trial Spawner ambient Ominous',
      'minecraft:block.trial_spawner.ambient_ominous'),
  pointedDripstoneFall('Pointed Dripstone fall', 'minecraft:block.pointed_dripstone.fall'),
  powderSnowPlace('Powder Snow place', 'minecraft:block.powder_snow.place'),
  noteBlockHat('Note Block hat', 'minecraft:block.note_block.hat'),
  coralBlockHit('Coral Block hit', 'minecraft:block.coral_block.hit'),
  creakingHeartIdle('Creaking Heart idle', 'minecraft:block.creaking_heart.idle'),
  amethystBlockStep('Amethyst Block step', 'minecraft:block.amethyst_block.step'),
  heavyCorePlace('Heavy Core place', 'minecraft:block.heavy_core.place'),
  deepslateHit('Deepslate hit', 'minecraft:block.deepslate.hit'),
  cherryLeavesStep('Cherry Leaves step', 'minecraft:block.cherry_leaves.step'),
  sculkShriekerHit('Sculk Shrieker hit', 'minecraft:block.sculk_shrieker.hit'),
  woodStep('Wood step', 'minecraft:block.wood.step'),
  boneBlockHit('Bone Block hit', 'minecraft:block.bone_block.hit'),
  mangroveRootsFall('Mangrove Roots fall', 'minecraft:block.mangrove_roots.fall'),
  stemStep('Stem step', 'minecraft:block.stem.step'),
  trialSpawnerAboutToSpawnItem('Trial Spawner about To Spawn Item',
      'minecraft:block.trial_spawner.about_to_spawn_item'),
  potentSulfurFall('Potent Sulfur fall', 'minecraft:block.potent_sulfur.fall'),
  chiseledBookshelfInsert('Chiseled Bookshelf insert', 'minecraft:block.chiseled_bookshelf.insert'),
  cherryWoodHangingSignBreak('Cherry Wood Hanging Sign break',
      'minecraft:block.cherry_wood_hanging_sign.break'),
  bambooSaplingHit('Bamboo Sapling hit', 'minecraft:block.bamboo_sapling.hit'),
  netherWoodStep('Nether Wood step', 'minecraft:block.nether_wood.step'),
  amethystBlockBreak('Amethyst Block break', 'minecraft:block.amethyst_block.break'),
  smallDripleafHit('Small Dripleaf hit', 'minecraft:block.small_dripleaf.hit'),
  slimeBlockStep('Slime Block step', 'minecraft:block.slime_block.step'),
  soulSandStep('Soul Sand step', 'minecraft:block.soul_sand.step'),
  copperGolemStatueBreak('Copper Golem Statue break', 'minecraft:block.copper_golem_statue.break'),
  mudBricksPlace('Mud Bricks place', 'minecraft:block.mud_bricks.place'),
  sculkShriekerBreak('Sculk Shrieker break', 'minecraft:block.sculk_shrieker.break'),
  bellUse('Bell use', 'minecraft:block.bell.use'),
  azaleaLeavesStep('Azalea Leaves step', 'minecraft:block.azalea_leaves.step'),
  chiseledBookshelfStep('Chiseled Bookshelf step', 'minecraft:block.chiseled_bookshelf.step'),
  lavaAmbient('Lava ambient', 'minecraft:block.lava.ambient'),
  sculkCatalystPlace('Sculk Catalyst place', 'minecraft:block.sculk_catalyst.place'),
  composterFill('Composter fill', 'minecraft:block.composter.fill'),
  grassHit('Grass hit', 'minecraft:block.grass.hit'),
  packedMudHit('Packed Mud hit', 'minecraft:block.packed_mud.hit'),
  copperBulbBreak('Copper Bulb break', 'minecraft:block.copper_bulb.break'),
  tripwireDetach('Tripwire detach', 'minecraft:block.tripwire.detach'),
  copperStep('Copper step', 'minecraft:block.copper.step'),
  shroomlightStep('Shroomlight step', 'minecraft:block.shroomlight.step'),
  nyliumHit('Nylium hit', 'minecraft:block.nylium.hit'),
  cobwebBreak('Cobweb break', 'minecraft:block.cobweb.break'),
  basaltStep('Basalt step', 'minecraft:block.basalt.step'),
  sculkStep('Sculk step', 'minecraft:block.sculk.step'),
  hangingSignFall('Hanging Sign fall', 'minecraft:block.hanging_sign.fall'),
  cherryWoodButtonClickOn('Cherry Wood Button click On',
      'minecraft:block.cherry_wood_button.click_on'),
  vaultHit('Vault hit', 'minecraft:block.vault.hit'),
  resinBricksBreak('Resin Bricks break', 'minecraft:block.resin_bricks.break'),
  bigDripleafStep('Big Dripleaf step', 'minecraft:block.big_dripleaf.step'),
  shelfActivate('Shelf activate', 'minecraft:block.shelf.activate'),
  driedGhastFall('Dried Ghast fall', 'minecraft:block.dried_ghast.fall'),
  packedMudPlace('Packed Mud place', 'minecraft:block.packed_mud.place'),
  tripwireAttach('Tripwire attach', 'minecraft:block.tripwire.attach'),
  sulfurStep('Sulfur step', 'minecraft:block.sulfur.step'),
  cinnabarBreak('Cinnabar break', 'minecraft:block.cinnabar.break'),
  scaffoldingFall('Scaffolding fall', 'minecraft:block.scaffolding.fall'),
  suspiciousGravelBreak('Suspicious Gravel break', 'minecraft:block.suspicious_gravel.break'),
  weepingVinesBreak('Weeping Vines break', 'minecraft:block.weeping_vines.break'),
  amethystClusterHit('Amethyst Cluster hit', 'minecraft:block.amethyst_cluster.hit'),
  polishedTuffFall('Polished Tuff fall', 'minecraft:block.polished_tuff.fall'),
  ladderBreak('Ladder break', 'minecraft:block.ladder.break'),
  honeyBlockStep('Honey Block step', 'minecraft:block.honey_block.step'),
  copperBreak('Copper break', 'minecraft:block.copper.break'),
  soulSandBreak('Soul Sand break', 'minecraft:block.soul_sand.break'),
  beehiveExit('Beehive exit', 'minecraft:block.beehive.exit'),
  netherrackStep('Netherrack step', 'minecraft:block.netherrack.step'),
  snifferEggPlop('Sniffer Egg plop', 'minecraft:block.sniffer_egg.plop'),
  pointedDripstoneDripWater('Pointed Dripstone drip Water',
      'minecraft:block.pointed_dripstone.drip_water'),
  suspiciousSandPlace('Suspicious Sand place', 'minecraft:block.suspicious_sand.place'),
  powderSnowFall('Powder Snow fall', 'minecraft:block.powder_snow.fall'),
  noteBlockDidgeridoo('Note Block didgeridoo', 'minecraft:block.note_block.didgeridoo'),
  bambooWoodDoorOpen('Bamboo Wood Door open', 'minecraft:block.bamboo_wood_door.open'),
  sculkSensorBreak('Sculk Sensor break', 'minecraft:block.sculk_sensor.break'),
  netherWoodFenceGateOpen('Nether Wood Fence Gate open',
      'minecraft:block.nether_wood_fence_gate.open'),
  deepslateTilesFall('Deepslate Tiles fall', 'minecraft:block.deepslate_tiles.fall'),
  netheriteBlockFall('Netherite Block fall', 'minecraft:block.netherite_block.fall'),
  coralBlockBreak('Coral Block break', 'minecraft:block.coral_block.break'),
  metalPlace('Metal place', 'minecraft:block.metal.place'),
  copperChestOpen('Copper Chest open', 'minecraft:block.copper_chest.open'),
  copperGratePlace('Copper Grate place', 'minecraft:block.copper_grate.place'),
  lodestoneBreak('Lodestone break', 'minecraft:block.lodestone.break'),
  pumpkinCarve('Pumpkin carve', 'minecraft:block.pumpkin.carve'),
  tripwireClickOn('Tripwire click On', 'minecraft:block.tripwire.click_on'),
  mossCarpetHit('Moss Carpet hit', 'minecraft:block.moss_carpet.hit'),
  dripstoneBlockFall('Dripstone Block fall', 'minecraft:block.dripstone_block.fall'),
  composterFillSuccess('Composter fill Success', 'minecraft:block.composter.fill_success'),
  ladderStep('Ladder step', 'minecraft:block.ladder.step'),
  netherWoodBreak('Nether Wood break', 'minecraft:block.nether_wood.break'),
  ironHit('Iron hit', 'minecraft:block.iron.hit'),
  copperBulbFall('Copper Bulb fall', 'minecraft:block.copper_bulb.fall'),
  cherryWoodPlace('Cherry Wood place', 'minecraft:block.cherry_wood.place'),
  chiseledBookshelfEnchanted('Chiseled Bookshelf enchanted',
      'minecraft:block.chiseled_bookshelf.pickup.enchanted'),
  pointedDripstoneBreak('Pointed Dripstone break', 'minecraft:block.pointed_dripstone.break'),
  wetSpongeDries('Wet Sponge dries', 'minecraft:block.wet_sponge.dries'),
  frogspawnStep('Frogspawn step', 'minecraft:block.frogspawn.step'),
  cherrySaplingFall('Cherry Sapling fall', 'minecraft:block.cherry_sapling.fall'),
  decoratedPotBreak('Decorated Pot break', 'minecraft:block.decorated_pot.break'),
  wetGrassFall('Wet Grass fall', 'minecraft:block.wet_grass.fall'),
  polishedDeepslateStep('Polished Deepslate step', 'minecraft:block.polished_deepslate.step'),
  copperGrateStep('Copper Grate step', 'minecraft:block.copper_grate.step'),
  vaultCloseShutter('Vault close Shutter', 'minecraft:block.vault.close_shutter'),
  pointedDripstoneDripLava('Pointed Dripstone drip Lava',
      'minecraft:block.pointed_dripstone.drip_lava'),
  bambooWoodFenceGateClose('Bamboo Wood Fence Gate close',
      'minecraft:block.bamboo_wood_fence_gate.close'),
  honeyBlockPlace('Honey Block place', 'minecraft:block.honey_block.place'),
  netherSproutsBreak('Nether Sprouts break', 'minecraft:block.nether_sprouts.break'),
  shelfDeactivate('Shelf deactivate', 'minecraft:block.shelf.deactivate'),
  snowStep('Snow step', 'minecraft:block.snow.step'),
  trialSpawnerFall('Trial Spawner fall', 'minecraft:block.trial_spawner.fall'),
  chorusFlowerGrow('Chorus Flower grow', 'minecraft:block.chorus_flower.grow'),
  bambooWoodPlace('Bamboo Wood place', 'minecraft:block.bamboo_wood.place'),
  resinFall('Resin fall', 'minecraft:block.resin.fall'),
  lanternPlace('Lantern place', 'minecraft:block.lantern.place'),
  floweringAzaleaBreak('Flowering Azalea break', 'minecraft:block.flowering_azalea.break'),
  mudFall('Mud fall', 'minecraft:block.mud.fall'),
  hangingRootsStep('Hanging Roots step', 'minecraft:block.hanging_roots.step'),
  resinBricksStep('Resin Bricks step', 'minecraft:block.resin_bricks.step'),
  netherrackPlace('Netherrack place', 'minecraft:block.netherrack.place'),
  wetSpongePlace('Wet Sponge place', 'minecraft:block.wet_sponge.place'),
  chiseledBookshelfBreak('Chiseled Bookshelf break', 'minecraft:block.chiseled_bookshelf.break'),
  pointedDripstoneHit('Pointed Dripstone hit', 'minecraft:block.pointed_dripstone.hit'),
  woodenTrapdoorClose('Wooden Trapdoor close', 'minecraft:block.wooden_trapdoor.close'),
  wetGrassPlace('Wet Grass place', 'minecraft:block.wet_grass.place'),
  decoratedPotFall('Decorated Pot fall', 'minecraft:block.decorated_pot.fall'),
  conduitShort('Conduit short', 'minecraft:block.conduit.ambient.short'),
  woodenDoorOpen('Wooden Door open', 'minecraft:block.wooden_door.open'),
  woodenDoorClose('Wooden Door close', 'minecraft:block.wooden_door.close'),
  deepslateTilesPlace('Deepslate Tiles place', 'minecraft:block.deepslate_tiles.place'),
  noteBlockPling('Note Block pling', 'minecraft:block.note_block.pling'),
  noteBlockTrumpet('Note Block trumpet', 'minecraft:block.note_block.trumpet'),
  vineFall('Vine fall', 'minecraft:block.vine.fall'),
  snowBreak('Snow break', 'minecraft:block.snow.break'),
  ironTrapdoorClose('Iron Trapdoor close', 'minecraft:block.iron_trapdoor.close'),
  respawnAnchorDeplete('Respawn Anchor deplete', 'minecraft:block.respawn_anchor.deplete'),
  vaultEjectItem('Vault eject Item', 'minecraft:block.vault.eject_item'),
  eyeblossomOpenLong('Eyeblossom open Long', 'minecraft:block.eyeblossom.open_long'),
  cinnabarHit('Cinnabar hit', 'minecraft:block.cinnabar.hit'),
  sculkSensorFall('Sculk Sensor fall', 'minecraft:block.sculk_sensor.fall'),
  bambooHit('Bamboo hit', 'minecraft:block.bamboo.hit'),
  noteBlockEnderDragon('Note Block ender Dragon',
      'minecraft:block.note_block.imitate.ender_dragon'),
  cherrySaplingBreak('Cherry Sapling break', 'minecraft:block.cherry_sapling.break'),
  ancientDebrisHit('Ancient Debris hit', 'minecraft:block.ancient_debris.hit'),
  floweringAzaleaStep('Flowering Azalea step', 'minecraft:block.flowering_azalea.step'),
  rootsStep('Roots step', 'minecraft:block.roots.step'),
  cherryWoodFenceGateOpen('Cherry Wood Fence Gate open',
      'minecraft:block.cherry_wood_fence_gate.open'),
  boneBlockFall('Bone Block fall', 'minecraft:block.bone_block.fall'),
  conduitAmbient('Conduit ambient', 'minecraft:block.conduit.ambient'),
  copperGolemStatueHit('Copper Golem Statue hit', 'minecraft:block.copper_golem_statue.hit'),
  creakingHeartBreak('Creaking Heart break', 'minecraft:block.creaking_heart.break'),
  waterAmbient('Water ambient', 'minecraft:block.water.ambient'),
  floweringAzaleaHit('Flowering Azalea hit', 'minecraft:block.flowering_azalea.hit'),
  gildedBlackstoneBreak('Gilded Blackstone break', 'minecraft:block.gilded_blackstone.break'),
  copperChestWeatheredOpen('Copper Chest Weathered open',
      'minecraft:block.copper_chest_weathered.open'),
  nyliumPlace('Nylium place', 'minecraft:block.nylium.place'),
  cactusFlowerBreak('Cactus Flower break', 'minecraft:block.cactus_flower.break'),
  sculkSensorHit('Sculk Sensor hit', 'minecraft:block.sculk_sensor.hit'),
  anvilDestroy('Anvil destroy', 'minecraft:block.anvil.destroy'),
  sculkSensorClicking('Sculk Sensor clicking', 'minecraft:block.sculk_sensor.clicking'),
  chiseledBookshelfPickup('Chiseled Bookshelf pickup', 'minecraft:block.chiseled_bookshelf.pickup'),
  bambooFall('Bamboo fall', 'minecraft:block.bamboo.fall'),
  suspiciousSandHit('Suspicious Sand hit', 'minecraft:block.suspicious_sand.hit'),
  ancientDebrisStep('Ancient Debris step', 'minecraft:block.ancient_debris.step'),
  shelfPlaceItem('Shelf place Item', 'minecraft:block.shelf.place_item'),
  frogspawnBreak('Frogspawn break', 'minecraft:block.frogspawn.break'),
  grassFall('Grass fall', 'minecraft:block.grass.fall'),
  weepingVinesFall('Weeping Vines fall', 'minecraft:block.weeping_vines.fall'),
  mudBricksFall('Mud Bricks fall', 'minecraft:block.mud_bricks.fall'),
  cinnabarStep('Cinnabar step', 'minecraft:block.cinnabar.step'),
  slimeBlockPlace('Slime Block place', 'minecraft:block.slime_block.place'),
  dripstoneBlockBreak('Dripstone Block break', 'minecraft:block.dripstone_block.break'),
  rootedDirtPlace('Rooted Dirt place', 'minecraft:block.rooted_dirt.place'),
  netherGoldOreFall('Nether Gold Ore fall', 'minecraft:block.nether_gold_ore.fall'),
  noteBlockXylophone('Note Block xylophone', 'minecraft:block.note_block.xylophone'),
  cherrySaplingHit('Cherry Sapling hit', 'minecraft:block.cherry_sapling.hit'),
  bigDripleafTiltUp('Big Dripleaf tilt Up', 'minecraft:block.big_dripleaf.tilt_up'),
  sulfurSpikeLand('Sulfur Spike land', 'minecraft:block.sulfur_spike.land'),
  bambooWoodButtonClickOff('Bamboo Wood Button click Off',
      'minecraft:block.bamboo_wood_button.click_off'),
  enchantmentTableUse('Enchantment Table use', 'minecraft:block.enchantment_table.use'),
  netherSproutsHit('Nether Sprouts hit', 'minecraft:block.nether_sprouts.hit'),
  deepslatePlace('Deepslate place', 'minecraft:block.deepslate.place'),
  froglightBreak('Froglight break', 'minecraft:block.froglight.break'),
  scaffoldingBreak('Scaffolding break', 'minecraft:block.scaffolding.break'),
  deepslateBricksBreak('Deepslate Bricks break', 'minecraft:block.deepslate_bricks.break'),
  metalHit('Metal hit', 'minecraft:block.metal.hit'),
  chainBreak('Chain break', 'minecraft:block.chain.break'),
  muddyMangroveRootsPlace('Muddy Mangrove Roots place',
      'minecraft:block.muddy_mangrove_roots.place'),
  tuffFall('Tuff fall', 'minecraft:block.tuff.fall'),
  smokerSmoke('Smoker smoke', 'minecraft:block.smoker.smoke'),
  sculkVeinBreak('Sculk Vein break', 'minecraft:block.sculk_vein.break'),
  decoratedPotShatter('Decorated Pot shatter', 'minecraft:block.decorated_pot.shatter'),
  anvilHit('Anvil hit', 'minecraft:block.anvil.hit'),
  caveVinesPlace('Cave Vines place', 'minecraft:block.cave_vines.place'),
  bigDripleafBreak('Big Dripleaf break', 'minecraft:block.big_dripleaf.break'),
  pistonExtend('Piston extend', 'minecraft:block.piston.extend'),
  bambooWoodHangingSignHit('Bamboo Wood Hanging Sign hit',
      'minecraft:block.bamboo_wood_hanging_sign.hit'),
  sweetBerryBushPickBerries('Sweet Berry Bush pick Berries',
      'minecraft:block.sweet_berry_bush.pick_berries'),
  spawnerFall('Spawner fall', 'minecraft:block.spawner.fall'),
  trialSpawnerOminousActivate('Trial Spawner ominous Activate',
      'minecraft:block.trial_spawner.ominous_activate'),
  tuffBreak('Tuff break', 'minecraft:block.tuff.break'),
  spawnerBreak('Spawner break', 'minecraft:block.spawner.break'),
  netherWoodPressurePlateClickOn('Nether Wood Pressure Plate click On',
      'minecraft:block.nether_wood_pressure_plate.click_on'),
  shroomlightBreak('Shroomlight break', 'minecraft:block.shroomlight.break'),
  cherryWoodStep('Cherry Wood step', 'minecraft:block.cherry_wood.step'),
  trialSpawnerHit('Trial Spawner hit', 'minecraft:block.trial_spawner.hit'),
  potentSulfurGeyserContinuousEruption('Potent Sulfur geyser Continuous Eruption',
      'minecraft:block.potent_sulfur.geyser_continuous_eruption'),
  potentSulfurPlace('Potent Sulfur place', 'minecraft:block.potent_sulfur.place'),
  tuffBricksStep('Tuff Bricks step', 'minecraft:block.tuff_bricks.step'),
  deepslateStep('Deepslate step', 'minecraft:block.deepslate.step'),
  eyeblossomClose('Eyeblossom close', 'minecraft:block.eyeblossom.close'),
  lodestoneHit('Lodestone hit', 'minecraft:block.lodestone.hit'),
  pointedDripstoneLand('Pointed Dripstone land', 'minecraft:block.pointed_dripstone.land'),
  mangroveRootsHit('Mangrove Roots hit', 'minecraft:block.mangrove_roots.hit'),
  azaleaFall('Azalea fall', 'minecraft:block.azalea.fall'),
  azaleaLeavesBreak('Azalea Leaves break', 'minecraft:block.azalea_leaves.break'),
  spongePlace('Sponge place', 'minecraft:block.sponge.place'),
  woolStep('Wool step', 'minecraft:block.wool.step'),
  sandStep('Sand step', 'minecraft:block.sand.step'),
  noteBlockPiglin('Note Block piglin', 'minecraft:block.note_block.imitate.piglin'),
  copperChestClose('Copper Chest close', 'minecraft:block.copper_chest.close'),
  anvilFall('Anvil fall', 'minecraft:block.anvil.fall'),
  brewingStandBrew('Brewing Stand brew', 'minecraft:block.brewing_stand.brew'),
  cherryWoodTrapdoorClose('Cherry Wood Trapdoor close',
      'minecraft:block.cherry_wood_trapdoor.close'),
  chiseledBookshelfHit('Chiseled Bookshelf hit', 'minecraft:block.chiseled_bookshelf.hit'),
  smallAmethystBudBreak('Small Amethyst Bud break', 'minecraft:block.small_amethyst_bud.break'),
  honeyBlockHit('Honey Block hit', 'minecraft:block.honey_block.hit'),
  gravelFall('Gravel fall', 'minecraft:block.gravel.fall'),
  sculkShriekerStep('Sculk Shrieker step', 'minecraft:block.sculk_shrieker.step'),
  netherGoldOreBreak('Nether Gold Ore break', 'minecraft:block.nether_gold_ore.break'),
  coralBlockStep('Coral Block step', 'minecraft:block.coral_block.step'),
  netherOrePlace('Nether Ore place', 'minecraft:block.nether_ore.place'),
  bambooWoodHangingSignPlace('Bamboo Wood Hanging Sign place',
      'minecraft:block.bamboo_wood_hanging_sign.place'),
  woolBreak('Wool break', 'minecraft:block.wool.break'),
  nyliumFall('Nylium fall', 'minecraft:block.nylium.fall'),
  netherBricksStep('Nether Bricks step', 'minecraft:block.nether_bricks.step'),
  anvilPlace('Anvil place', 'minecraft:block.anvil.place'),
  sulfurSpikeBreak('Sulfur Spike break', 'minecraft:block.sulfur_spike.break'),
  woodenPressurePlateClickOn('Wooden Pressure Plate click On',
      'minecraft:block.wooden_pressure_plate.click_on'),
  mudPlace('Mud place', 'minecraft:block.mud.place'),
  lavaExtinguish('Lava extinguish', 'minecraft:block.lava.extinguish'),
  sulfurBreak('Sulfur break', 'minecraft:block.sulfur.break'),
  woodenButtonClickOn('Wooden Button click On', 'minecraft:block.wooden_button.click_on'),
  respawnAnchorAmbient('Respawn Anchor ambient', 'minecraft:block.respawn_anchor.ambient'),
  netherWoodHangingSignBreak('Nether Wood Hanging Sign break',
      'minecraft:block.nether_wood_hanging_sign.break'),
  lavaPop('Lava pop', 'minecraft:block.lava.pop'),
  chorusFlowerDeath('Chorus Flower death', 'minecraft:block.chorus_flower.death'),
  sporeBlossomPlace('Spore Blossom place', 'minecraft:block.spore_blossom.place'),
  stoneButtonClickOn('Stone Button click On', 'minecraft:block.stone_button.click_on'),
  driedGhastPlace('Dried Ghast place', 'minecraft:block.dried_ghast.place'),
  mossBreak('Moss break', 'minecraft:block.moss.break'),
  barrelClose('Barrel close', 'minecraft:block.barrel.close'),
  driedGhastAmbientWater('Dried Ghast ambient Water', 'minecraft:block.dried_ghast.ambient_water'),
  sculkCharge('Sculk charge', 'minecraft:block.sculk.charge'),
  leverClick('Lever click', 'minecraft:block.lever.click'),
  amethystClusterPlace('Amethyst Cluster place', 'minecraft:block.amethyst_cluster.place'),
  resinBreak('Resin break', 'minecraft:block.resin.break'),
  mangroveRootsBreak('Mangrove Roots break', 'minecraft:block.mangrove_roots.break'),
  soulSoilBreak('Soul Soil break', 'minecraft:block.soul_soil.break'),
  wetSpongeFall('Wet Sponge fall', 'minecraft:block.wet_sponge.fall'),
  portalTravel('Portal travel', 'minecraft:block.portal.travel'),
  chestLocked('Chest locked', 'minecraft:block.chest.locked'),
  candleExtinguish('Candle extinguish', 'minecraft:block.candle.extinguish'),
  muddyMangroveRootsFall('Muddy Mangrove Roots fall', 'minecraft:block.muddy_mangrove_roots.fall'),
  ironStep('Iron step', 'minecraft:block.iron.step'),
  hangingSignBreak('Hanging Sign break', 'minecraft:block.hanging_sign.break'),
  mediumAmethystBudBreak('Medium Amethyst Bud break', 'minecraft:block.medium_amethyst_bud.break'),
  mossStep('Moss step', 'minecraft:block.moss.step'),
  heavyCoreStep('Heavy Core step', 'minecraft:block.heavy_core.step'),
  mossCarpetStep('Moss Carpet step', 'minecraft:block.moss_carpet.step'),
  powderSnowBreak('Powder Snow break', 'minecraft:block.powder_snow.break'),
  endPortalSpawn('End Portal spawn', 'minecraft:block.end_portal.spawn'),
  netherSproutsStep('Nether Sprouts step', 'minecraft:block.nether_sprouts.step'),
  heavyCoreBreak('Heavy Core break', 'minecraft:block.heavy_core.break'),
  vaultPlace('Vault place', 'minecraft:block.vault.place'),
  chainFall('Chain fall', 'minecraft:block.chain.fall'),
  netheriteBlockPlace('Netherite Block place', 'minecraft:block.netherite_block.place'),
  slimeBlockHit('Slime Block hit', 'minecraft:block.slime_block.hit'),
  cherryWoodPressurePlateClickOff('Cherry Wood Pressure Plate click Off',
      'minecraft:block.cherry_wood_pressure_plate.click_off'),
  eyeblossomCloseLong('Eyeblossom close Long', 'minecraft:block.eyeblossom.close_long'),
  shelfStep('Shelf step', 'minecraft:block.shelf.step'),
  vaultDeactivate('Vault deactivate', 'minecraft:block.vault.deactivate'),
  cherryLeavesHit('Cherry Leaves hit', 'minecraft:block.cherry_leaves.hit'),
  netherBricksHit('Nether Bricks hit', 'minecraft:block.nether_bricks.hit'),
  driedGhastAmbient('Dried Ghast ambient', 'minecraft:block.dried_ghast.ambient'),
  muddyMangroveRootsHit('Muddy Mangrove Roots hit', 'minecraft:block.muddy_mangrove_roots.hit'),
  beaconActivate('Beacon activate', 'minecraft:block.beacon.activate'),
  cherryWoodHangingSignFall('Cherry Wood Hanging Sign fall',
      'minecraft:block.cherry_wood_hanging_sign.fall'),
  smallDripleafPlace('Small Dripleaf place', 'minecraft:block.small_dripleaf.place'),
  froglightFall('Froglight fall', 'minecraft:block.froglight.fall'),
  pinkPetalsFall('Pink Petals fall', 'minecraft:block.pink_petals.fall'),
  shulkerBoxOpen('Shulker Box open', 'minecraft:block.shulker_box.open'),
  decoratedPotHit('Decorated Pot hit', 'minecraft:block.decorated_pot.hit'),
  sculkCatalystBreak('Sculk Catalyst break', 'minecraft:block.sculk_catalyst.break'),
  spawnerHit('Spawner hit', 'minecraft:block.spawner.hit'),
  sulfurSpikeStep('Sulfur Spike step', 'minecraft:block.sulfur_spike.step'),
  netherrackHit('Netherrack hit', 'minecraft:block.netherrack.hit'),
  vaultAmbient('Vault ambient', 'minecraft:block.vault.ambient'),
  spongeStep('Sponge step', 'minecraft:block.sponge.step'),
  leafLitterPlace('Leaf Litter place', 'minecraft:block.leaf_litter.place'),
  creakingHeartSpawn('Creaking Heart spawn', 'minecraft:block.creaking_heart.spawn'),
  scaffoldingHit('Scaffolding hit', 'minecraft:block.scaffolding.hit'),
  crafterCraft('Crafter craft', 'minecraft:block.crafter.craft'),
  driedGhastTransition('Dried Ghast transition', 'minecraft:block.dried_ghast.transition'),
  metalStep('Metal step', 'minecraft:block.metal.step'),
  deepslateBricksStep('Deepslate Bricks step', 'minecraft:block.deepslate_bricks.step'),
  wartBlockPlace('Wart Block place', 'minecraft:block.wart_block.place'),
  frogspawnHit('Frogspawn hit', 'minecraft:block.frogspawn.hit'),
  copperGrateHit('Copper Grate hit', 'minecraft:block.copper_grate.hit'),
  packedMudBreak('Packed Mud break', 'minecraft:block.packed_mud.break'),
  suspiciousSandStep('Suspicious Sand step', 'minecraft:block.suspicious_sand.step'),
  polishedTuffHit('Polished Tuff hit', 'minecraft:block.polished_tuff.hit'),
  bubbleColumnBubblePop('Bubble Column bubble Pop', 'minecraft:block.bubble_column.bubble_pop'),
  trialSpawnerSpawnItemBegin('Trial Spawner spawn Item Begin',
      'minecraft:block.trial_spawner.spawn_item_begin'),
  gildedBlackstoneStep('Gilded Blackstone step', 'minecraft:block.gilded_blackstone.step'),
  hangingRootsHit('Hanging Roots hit', 'minecraft:block.hanging_roots.hit'),
  trialSpawnerOpenShutter('Trial Spawner open Shutter',
      'minecraft:block.trial_spawner.open_shutter'),
  pointedDripstoneStep('Pointed Dripstone step', 'minecraft:block.pointed_dripstone.step'),
  copperBulbTurnOn('Copper Bulb turn On', 'minecraft:block.copper_bulb.turn_on'),
  mudBricksBreak('Mud Bricks break', 'minecraft:block.mud_bricks.break'),
  cobwebFall('Cobweb fall', 'minecraft:block.cobweb.fall'),
  bubbleColumnWhirlpoolAmbient('Bubble Column whirlpool Ambient',
      'minecraft:block.bubble_column.whirlpool_ambient'),
  beaconPowerSelect('Beacon power Select', 'minecraft:block.beacon.power_select'),
  beehiveEnter('Beehive enter', 'minecraft:block.beehive.enter'),
  deepslateTilesHit('Deepslate Tiles hit', 'minecraft:block.deepslate_tiles.hit'),
  bambooWoodHangingSignFall('Bamboo Wood Hanging Sign fall',
      'minecraft:block.bamboo_wood_hanging_sign.fall'),
  hangingRootsPlace('Hanging Roots place', 'minecraft:block.hanging_roots.place'),
  soulSoilFall('Soul Soil fall', 'minecraft:block.soul_soil.fall'),
  campfireCrackle('Campfire crackle', 'minecraft:block.campfire.crackle'),
  woodenButtonClickOff('Wooden Button click Off', 'minecraft:block.wooden_button.click_off'),
  stoneFall('Stone fall', 'minecraft:block.stone.fall'),
  fireExtinguish('Fire extinguish', 'minecraft:block.fire.extinguish'),
  suspiciousSandBreak('Suspicious Sand break', 'minecraft:block.suspicious_sand.break'),
  copperChestWeatheredClose('Copper Chest Weathered close',
      'minecraft:block.copper_chest_weathered.close'),
  calcitePlace('Calcite place', 'minecraft:block.calcite.place'),
  mangroveRootsStep('Mangrove Roots step', 'minecraft:block.mangrove_roots.step'),
  potentSulfurStep('Potent Sulfur step', 'minecraft:block.potent_sulfur.step'),
  metalBreak('Metal break', 'minecraft:block.metal.break'),
  frogspawnHatch('Frogspawn hatch', 'minecraft:block.frogspawn.hatch'),
  beehiveShear('Beehive shear', 'minecraft:block.beehive.shear'),
  copperGrateBreak('Copper Grate break', 'minecraft:block.copper_grate.break'),
  sandHit('Sand hit', 'minecraft:block.sand.hit'),
  wartBlockFall('Wart Block fall', 'minecraft:block.wart_block.fall'),
  dispenserLaunch('Dispenser launch', 'minecraft:block.dispenser.launch'),
  sulfurHit('Sulfur hit', 'minecraft:block.sulfur.hit'),
  trialSpawnerSpawnItem('Trial Spawner spawn Item', 'minecraft:block.trial_spawner.spawn_item'),
  stonePlace('Stone place', 'minecraft:block.stone.place'),
  deepslateBricksHit('Deepslate Bricks hit', 'minecraft:block.deepslate_bricks.hit'),
  sporeBlossomFall('Spore Blossom fall', 'minecraft:block.spore_blossom.fall'),
  sandIdle('Sand idle', 'minecraft:block.sand.idle'),
  potentSulfurNoxiousGas('Potent Sulfur noxious Gas', 'minecraft:block.potent_sulfur.noxious_gas'),
  lanternHit('Lantern hit', 'minecraft:block.lantern.hit'),
  endGatewaySpawn('End Gateway spawn', 'minecraft:block.end_gateway.spawn'),
  ironPlace('Iron place', 'minecraft:block.iron.place'),
  hangingSignStep('Hanging Sign step', 'minecraft:block.hanging_sign.step'),
  copperBulbTurnOff('Copper Bulb turn Off', 'minecraft:block.copper_bulb.turn_off'),
  cherryWoodHit('Cherry Wood hit', 'minecraft:block.cherry_wood.hit'),
  boneBlockPlace('Bone Block place', 'minecraft:block.bone_block.place'),
  mudBricksHit('Mud Bricks hit', 'minecraft:block.mud_bricks.hit'),
  driedGhastStep('Dried Ghast step', 'minecraft:block.dried_ghast.step'),
  vaultOpenShutter('Vault open Shutter', 'minecraft:block.vault.open_shutter'),
  netherWoodPressurePlateClickOff('Nether Wood Pressure Plate click Off',
      'minecraft:block.nether_wood_pressure_plate.click_off'),
  metalPressurePlateClickOn('Metal Pressure Plate click On',
      'minecraft:block.metal_pressure_plate.click_on'),
  honeyBlockBreak('Honey Block break', 'minecraft:block.honey_block.break'),
  polishedTuffPlace('Polished Tuff place', 'minecraft:block.polished_tuff.place'),
  scaffoldingStep('Scaffolding step', 'minecraft:block.scaffolding.step'),
  trialSpawnerPlace('Trial Spawner place', 'minecraft:block.trial_spawner.place'),
  pointedDripstoneDripLavaIntoCauldron('Pointed Dripstone drip Lava Into Cauldron',
      'minecraft:block.pointed_dripstone.drip_lava_into_cauldron'),
  cherryLeavesPlace('Cherry Leaves place', 'minecraft:block.cherry_leaves.place'),
  bambooWoodTrapdoorClose('Bamboo Wood Trapdoor close',
      'minecraft:block.bamboo_wood_trapdoor.close'),
  sandPlace('Sand place', 'minecraft:block.sand.place'),
  polishedTuffStep('Polished Tuff step', 'minecraft:block.polished_tuff.step'),
  bambooWoodBreak('Bamboo Wood break', 'minecraft:block.bamboo_wood.break'),
  creakingHeartFall('Creaking Heart fall', 'minecraft:block.creaking_heart.fall'),
  noteBlockBass('Note Block bass', 'minecraft:block.note_block.bass'),
  candleHit('Candle hit', 'minecraft:block.candle.hit'),
  glassFall('Glass fall', 'minecraft:block.glass.fall'),
  rootedDirtFall('Rooted Dirt fall', 'minecraft:block.rooted_dirt.fall'),
  bambooWoodFall('Bamboo Wood fall', 'minecraft:block.bamboo_wood.fall'),
  suspiciousGravelHit('Suspicious Gravel hit', 'minecraft:block.suspicious_gravel.hit'),
  cherryWoodBreak('Cherry Wood break', 'minecraft:block.cherry_wood.break'),
  wartBlockHit('Wart Block hit', 'minecraft:block.wart_block.hit'),
  wetSpongeBreak('Wet Sponge break', 'minecraft:block.wet_sponge.break'),
  mossCarpetPlace('Moss Carpet place', 'minecraft:block.moss_carpet.place'),
  powderSnowStep('Powder Snow step', 'minecraft:block.powder_snow.step'),
  calciteFall('Calcite fall', 'minecraft:block.calcite.fall'),
  wetGrassBreak('Wet Grass break', 'minecraft:block.wet_grass.break'),
  netheriteBlockStep('Netherite Block step', 'minecraft:block.netherite_block.step'),
  driedGhastPlaceInWater('Dried Ghast place In Water',
      'minecraft:block.dried_ghast.place_in_water'),
  deepslateTilesStep('Deepslate Tiles step', 'minecraft:block.deepslate_tiles.step'),
  potentSulfurGeyserContinuousEruptionActive('Potent Sulfur geyser Continuous Eruption Active',
      'minecraft:block.potent_sulfur.geyser_continuous_eruption_active'),
  caveVinesFall('Cave Vines fall', 'minecraft:block.cave_vines.fall'),
  lanternFall('Lantern fall', 'minecraft:block.lantern.fall'),
  deadbushIdle('Deadbush idle', 'minecraft:block.deadbush.idle'),
  candleFall('Candle fall', 'minecraft:block.candle.fall'),
  gildedBlackstoneHit('Gilded Blackstone hit', 'minecraft:block.gilded_blackstone.hit'),
  dripstoneBlockStep('Dripstone Block step', 'minecraft:block.dripstone_block.step'),
  anvilLand('Anvil land', 'minecraft:block.anvil.land'),
  spongeAbsorb('Sponge absorb', 'minecraft:block.sponge.absorb'),
  stoneHit('Stone hit', 'minecraft:block.stone.hit'),
  copperBulbStep('Copper Bulb step', 'minecraft:block.copper_bulb.step'),
  leafLitterFall('Leaf Litter fall', 'minecraft:block.leaf_litter.fall'),
  fungusFall('Fungus fall', 'minecraft:block.fungus.fall'),
  resinBricksHit('Resin Bricks hit', 'minecraft:block.resin_bricks.hit'),
  metalPressurePlateClickOff('Metal Pressure Plate click Off',
      'minecraft:block.metal_pressure_plate.click_off'),
  nyliumBreak('Nylium break', 'minecraft:block.nylium.break'),
  vinePlace('Vine place', 'minecraft:block.vine.place'),
  potentSulfurGeyserEruption('Potent Sulfur geyser Eruption',
      'minecraft:block.potent_sulfur.geyser_eruption'),
  vaultFall('Vault fall', 'minecraft:block.vault.fall'),
  cherryWoodPressurePlateClickOn('Cherry Wood Pressure Plate click On',
      'minecraft:block.cherry_wood_pressure_plate.click_on'),
  cherrySaplingStep('Cherry Sapling step', 'minecraft:block.cherry_sapling.step'),
  lanternBreak('Lantern break', 'minecraft:block.lantern.break'),
  wetGrassStep('Wet Grass step', 'minecraft:block.wet_grass.step'),
  bubbleColumnWhirlpoolInside('Bubble Column whirlpool Inside',
      'minecraft:block.bubble_column.whirlpool_inside'),
  beehiveWork('Beehive work', 'minecraft:block.beehive.work'),
  dryGrassAmbient('Dry Grass ambient', 'minecraft:block.dry_grass.ambient'),
  netherrackBreak('Netherrack break', 'minecraft:block.netherrack.break'),
  trialSpawnerEjectItem('Trial Spawner eject Item', 'minecraft:block.trial_spawner.eject_item'),
  fungusPlace('Fungus place', 'minecraft:block.fungus.place'),
  slimeBlockBreak('Slime Block break', 'minecraft:block.slime_block.break'),
  amethystBlockChime('Amethyst Block chime', 'minecraft:block.amethyst_block.chime'),
  rootedDirtBreak('Rooted Dirt break', 'minecraft:block.rooted_dirt.break'),
  deepslateTilesBreak('Deepslate Tiles break', 'minecraft:block.deepslate_tiles.break'),
  trialSpawnerSpawnMob('Trial Spawner spawn Mob', 'minecraft:block.trial_spawner.spawn_mob'),
  trialSpawnerStep('Trial Spawner step', 'minecraft:block.trial_spawner.step'),
  trialSpawnerAmbient('Trial Spawner ambient', 'minecraft:block.trial_spawner.ambient'),
  chestClose('Chest close', 'minecraft:block.chest.close'),
  portalTrigger('Portal trigger', 'minecraft:block.portal.trigger'),
  smallDripleafFall('Small Dripleaf fall', 'minecraft:block.small_dripleaf.fall'),
  bubbleColumnUpwardsAmbient('Bubble Column upwards Ambient',
      'minecraft:block.bubble_column.upwards_ambient'),
  resinStep('Resin step', 'minecraft:block.resin.step'),
  pointedDripstoneDripWaterIntoCauldron('Pointed Dripstone drip Water Into Cauldron',
      'minecraft:block.pointed_dripstone.drip_water_into_cauldron'),
  bigDripleafHit('Big Dripleaf hit', 'minecraft:block.big_dripleaf.hit'),
  sculkShriekerShriek('Sculk Shrieker shriek', 'minecraft:block.sculk_shrieker.shriek'),
  mudStep('Mud step', 'minecraft:block.mud.step'),
  netherWoodHit('Nether Wood hit', 'minecraft:block.nether_wood.hit'),
  basaltHit('Basalt hit', 'minecraft:block.basalt.hit'),
  vaultInsertItem('Vault insert Item', 'minecraft:block.vault.insert_item'),
  amethystBlockResonate('Amethyst Block resonate', 'minecraft:block.amethyst_block.resonate'),
  deepslateBreak('Deepslate break', 'minecraft:block.deepslate.break'),
  chestOpen('Chest open', 'minecraft:block.chest.open'),
  noteBlockCreeper('Note Block creeper', 'minecraft:block.note_block.imitate.creeper'),
  shroomlightHit('Shroomlight hit', 'minecraft:block.shroomlight.hit'),
  vineHit('Vine hit', 'minecraft:block.vine.hit'),
  muddyMangroveRootsBreak('Muddy Mangrove Roots break',
      'minecraft:block.muddy_mangrove_roots.break'),
  snifferEggCrack('Sniffer Egg crack', 'minecraft:block.sniffer_egg.crack'),
  furnaceFireCrackle('Furnace fire Crackle', 'minecraft:block.furnace.fire_crackle'),
  decoratedPotStep('Decorated Pot step', 'minecraft:block.decorated_pot.step'),
  caveVinesBreak('Cave Vines break', 'minecraft:block.cave_vines.break'),
  vineStep('Vine step', 'minecraft:block.vine.step'),
  cherryWoodDoorClose('Cherry Wood Door close', 'minecraft:block.cherry_wood_door.close'),
  netherBricksPlace('Nether Bricks place', 'minecraft:block.nether_bricks.place'),
  noteBlockIronXylophone('Note Block iron Xylophone', 'minecraft:block.note_block.iron_xylophone'),
  noteBlockGuitar('Note Block guitar', 'minecraft:block.note_block.guitar'),
  barrelOpen('Barrel open', 'minecraft:block.barrel.open'),
  rootsHit('Roots hit', 'minecraft:block.roots.hit'),
  ironTrapdoorOpen('Iron Trapdoor open', 'minecraft:block.iron_trapdoor.open'),
  conduitTarget('Conduit target', 'minecraft:block.conduit.attack.target'),
  sculkPlace('Sculk place', 'minecraft:block.sculk.place'),
  packedMudFall('Packed Mud fall', 'minecraft:block.packed_mud.fall'),
  potentSulfurBreak('Potent Sulfur break', 'minecraft:block.potent_sulfur.break'),
  shelfMultiSwap('Shelf multi Swap', 'minecraft:block.shelf.multi_swap'),
  calciteHit('Calcite hit', 'minecraft:block.calcite.hit'),
  sculkSensorStep('Sculk Sensor step', 'minecraft:block.sculk_sensor.step'),
  bubbleColumnUpwardsInside('Bubble Column upwards Inside',
      'minecraft:block.bubble_column.upwards_inside'),
  boneBlockStep('Bone Block step', 'minecraft:block.bone_block.step'),
  copperChestOxidizedOpen('Copper Chest Oxidized open',
      'minecraft:block.copper_chest_oxidized.open'),
  redstoneTorchBurnout('Redstone Torch burnout', 'minecraft:block.redstone_torch.burnout'),
  noteBlockBit('Note Block bit', 'minecraft:block.note_block.bit'),
  polishedDeepslatePlace('Polished Deepslate place', 'minecraft:block.polished_deepslate.place'),
  netherWoodHangingSignHit('Nether Wood Hanging Sign hit',
      'minecraft:block.nether_wood_hanging_sign.hit'),
  spongeBreak('Sponge break', 'minecraft:block.sponge.break'),
  copperGolemStatueFall('Copper Golem Statue fall', 'minecraft:block.copper_golem_statue.fall'),
  woodHit('Wood hit', 'minecraft:block.wood.hit'),
  stemHit('Stem hit', 'minecraft:block.stem.hit'),
  ancientDebrisPlace('Ancient Debris place', 'minecraft:block.ancient_debris.place'),
  bambooStep('Bamboo step', 'minecraft:block.bamboo.step'),
  bigDripleafTiltDown('Big Dripleaf tilt Down', 'minecraft:block.big_dripleaf.tilt_down'),
  bambooWoodPressurePlateClickOn('Bamboo Wood Pressure Plate click On',
      'minecraft:block.bamboo_wood_pressure_plate.click_on'),
  netherOreBreak('Nether Ore break', 'minecraft:block.nether_ore.break'),
  pistonContract('Piston contract', 'minecraft:block.piston.contract'),
  weepingVinesStep('Weeping Vines step', 'minecraft:block.weeping_vines.step'),
  mudBricksStep('Mud Bricks step', 'minecraft:block.mud_bricks.step'),
  grassStep('Grass step', 'minecraft:block.grass.step'),
  bambooWoodHangingSignBreak('Bamboo Wood Hanging Sign break',
      'minecraft:block.bamboo_wood_hanging_sign.break'),
  netherGoldOreStep('Nether Gold Ore step', 'minecraft:block.nether_gold_ore.step'),
  netherWoodHangingSignFall('Nether Wood Hanging Sign fall',
      'minecraft:block.nether_wood_hanging_sign.fall'),
  anvilBreak('Anvil break', 'minecraft:block.anvil.break'),
  gravelPlace('Gravel place', 'minecraft:block.gravel.place'),
  sculkVeinFall('Sculk Vein fall', 'minecraft:block.sculk_vein.fall'),
  woodenPressurePlateClickOff('Wooden Pressure Plate click Off',
      'minecraft:block.wooden_pressure_plate.click_off'),
  sculkCatalystFall('Sculk Catalyst fall', 'minecraft:block.sculk_catalyst.fall'),
  sporeBlossomBreak('Spore Blossom break', 'minecraft:block.spore_blossom.break'),
  potentSulfurGeyserEruptionActive('Potent Sulfur geyser Eruption Active',
      'minecraft:block.potent_sulfur.geyser_eruption_active'),
  driedGhastBreak('Dried Ghast break', 'minecraft:block.dried_ghast.break'),
  lodestoneFall('Lodestone fall', 'minecraft:block.lodestone.fall'),
  tuffStep('Tuff step', 'minecraft:block.tuff.step'),
  smithingTableUse('Smithing Table use', 'minecraft:block.smithing_table.use'),
  tuffBricksPlace('Tuff Bricks place', 'minecraft:block.tuff_bricks.place'),
  amethystClusterBreak('Amethyst Cluster break', 'minecraft:block.amethyst_cluster.break'),
  stemPlace('Stem place', 'minecraft:block.stem.place'),
  sweetBerryBushPlace('Sweet Berry Bush place', 'minecraft:block.sweet_berry_bush.place'),
  basaltPlace('Basalt place', 'minecraft:block.basalt.place'),
  spawnerStep('Spawner step', 'minecraft:block.spawner.step'),
  shelfPlace('Shelf place', 'minecraft:block.shelf.place'),
  bambooWoodTrapdoorOpen('Bamboo Wood Trapdoor open', 'minecraft:block.bamboo_wood_trapdoor.open'),
  respawnAnchorCharge('Respawn Anchor charge', 'minecraft:block.respawn_anchor.charge'),
  composterEmpty('Composter empty', 'minecraft:block.composter.empty'),
  suspiciousGravelFall('Suspicious Gravel fall', 'minecraft:block.suspicious_gravel.fall'),
  pinkPetalsPlace('Pink Petals place', 'minecraft:block.pink_petals.place'),
  amethystClusterFall('Amethyst Cluster fall', 'minecraft:block.amethyst_cluster.fall'),
  netherGoldOreHit('Nether Gold Ore hit', 'minecraft:block.nether_gold_ore.hit'),
  netherOreFall('Nether Ore fall', 'minecraft:block.nether_ore.fall'),
  azaleaStep('Azalea step', 'minecraft:block.azalea.step'),
  netheriteBlockHit('Netherite Block hit', 'minecraft:block.netherite_block.hit'),
  soulSandHit('Soul Sand hit', 'minecraft:block.soul_sand.hit'),
  mudBreak('Mud break', 'minecraft:block.mud.break'),
  netherWoodTrapdoorOpen('Nether Wood Trapdoor open', 'minecraft:block.nether_wood_trapdoor.open'),
  lilyPadPlace('Lily Pad place', 'minecraft:block.lily_pad.place'),
  anvilStep('Anvil step', 'minecraft:block.anvil.step'),
  creakingHeartHurt('Creaking Heart hurt', 'minecraft:block.creaking_heart.hurt'),
  vaultBreak('Vault break', 'minecraft:block.vault.break'),
  amethystBlockFall('Amethyst Block fall', 'minecraft:block.amethyst_block.fall'),
  bambooSaplingPlace('Bamboo Sapling place', 'minecraft:block.bamboo_sapling.place'),
  caveVinesHit('Cave Vines hit', 'minecraft:block.cave_vines.hit'),
  copperChestOxidizedClose('Copper Chest Oxidized close',
      'minecraft:block.copper_chest_oxidized.close'),
  netheriteBlockBreak('Netherite Block break', 'minecraft:block.netherite_block.break'),
  sculkSensorClickingStop('Sculk Sensor clicking Stop',
      'minecraft:block.sculk_sensor.clicking_stop'),
  cherryLeavesFall('Cherry Leaves fall', 'minecraft:block.cherry_leaves.fall'),
  woodFall('Wood fall', 'minecraft:block.wood.fall'),
  fungusHit('Fungus hit', 'minecraft:block.fungus.hit'),
  gravelStep('Gravel step', 'minecraft:block.gravel.step'),
  sculkHit('Sculk hit', 'minecraft:block.sculk.hit'),
  bambooWoodButtonClickOn('Bamboo Wood Button click On',
      'minecraft:block.bamboo_wood_button.click_on'),
  conduitActivate('Conduit activate', 'minecraft:block.conduit.activate'),
  stemFall('Stem fall', 'minecraft:block.stem.fall'),
  powderSnowHit('Powder Snow hit', 'minecraft:block.powder_snow.hit'),
  nyliumStep('Nylium step', 'minecraft:block.nylium.step'),
  candlePlace('Candle place', 'minecraft:block.candle.place'),
  cherryWoodDoorOpen('Cherry Wood Door open', 'minecraft:block.cherry_wood_door.open'),
  netherWoodFall('Nether Wood fall', 'minecraft:block.nether_wood.fall'),
  woodPlace('Wood place', 'minecraft:block.wood.place'),
  potentSulfurHit('Potent Sulfur hit', 'minecraft:block.potent_sulfur.hit'),
  smallDripleafBreak('Small Dripleaf break', 'minecraft:block.small_dripleaf.break'),
  slimeBlockFall('Slime Block fall', 'minecraft:block.slime_block.fall'),
  soulSandFall('Soul Sand fall', 'minecraft:block.soul_sand.fall'),
  copperHit('Copper hit', 'minecraft:block.copper.hit'),
  azaleaLeavesFall('Azalea Leaves fall', 'minecraft:block.azalea_leaves.fall'),
  chiseledBookshelfFall('Chiseled Bookshelf fall', 'minecraft:block.chiseled_bookshelf.fall'),
  glassPlace('Glass place', 'minecraft:block.glass.place'),
  bambooWoodHit('Bamboo Wood hit', 'minecraft:block.bamboo_wood.hit'),
  azaleaPlace('Azalea place', 'minecraft:block.azalea.place'),
  copperBulbHit('Copper Bulb hit', 'minecraft:block.copper_bulb.hit'),
  sculkCatalystBloom('Sculk Catalyst bloom', 'minecraft:block.sculk_catalyst.bloom'),
  leafLitterBreak('Leaf Litter break', 'minecraft:block.leaf_litter.break'),
  copperFall('Copper fall', 'minecraft:block.copper.fall'),
  grassPlace('Grass place', 'minecraft:block.grass.place'),
  wetSpongeHit('Wet Sponge hit', 'minecraft:block.wet_sponge.hit'),
  shroomlightFall('Shroomlight fall', 'minecraft:block.shroomlight.fall'),
  sculkFall('Sculk fall', 'minecraft:block.sculk.fall'),
  basaltFall('Basalt fall', 'minecraft:block.basalt.fall'),
  weepingVinesHit('Weeping Vines hit', 'minecraft:block.weeping_vines.hit'),
  noteBlockBasedrum('Note Block basedrum', 'minecraft:block.note_block.basedrum'),
  wetSpongeStep('Wet Sponge step', 'minecraft:block.wet_sponge.step'),
  fenceGateOpen('Fence Gate open', 'minecraft:block.fence_gate.open'),
  bigDripleafFall('Big Dripleaf fall', 'minecraft:block.big_dripleaf.fall'),
  stonePressurePlateClickOn('Stone Pressure Plate click On',
      'minecraft:block.stone_pressure_plate.click_on'),
  muddyMangroveRootsStep('Muddy Mangrove Roots step', 'minecraft:block.muddy_mangrove_roots.step'),
  largeAmethystBudPlace('Large Amethyst Bud place', 'minecraft:block.large_amethyst_bud.place'),
  mossHit('Moss hit', 'minecraft:block.moss.hit'),
  rootsPlace('Roots place', 'minecraft:block.roots.place'),
  bambooPlace('Bamboo place', 'minecraft:block.bamboo.place'),
  sulfurFall('Sulfur fall', 'minecraft:block.sulfur.fall'),
  chainHit('Chain hit', 'minecraft:block.chain.hit'),
  honeyBlockFall('Honey Block fall', 'minecraft:block.honey_block.fall'),
  shelfSingleSwap('Shelf single Swap', 'minecraft:block.shelf.single_swap'),
  beaconAmbient('Beacon ambient', 'minecraft:block.beacon.ambient'),
  gravelHit('Gravel hit', 'minecraft:block.gravel.hit'),
  beaconDeactivate('Beacon deactivate', 'minecraft:block.beacon.deactivate'),
  chainStep('Chain step', 'minecraft:block.chain.step'),
  netherrackFall('Netherrack fall', 'minecraft:block.netherrack.fall'),
  hangingRootsBreak('Hanging Roots break', 'minecraft:block.hanging_roots.break'),
  noteBlockTrumpetOxidized('Note Block trumpet Oxidized',
      'minecraft:block.note_block.trumpet_oxidized'),
  calciteBreak('Calcite break', 'minecraft:block.calcite.break'),
  dripstoneBlockHit('Dripstone Block hit', 'minecraft:block.dripstone_block.hit'),
  netherWartBreak('Nether Wart break', 'minecraft:block.nether_wart.break'),
  grindstoneUse('Grindstone use', 'minecraft:block.grindstone.use'),
  noteBlockCowBell('Note Block cow Bell', 'minecraft:block.note_block.cow_bell'),
  cherryWoodHangingSignPlace('Cherry Wood Hanging Sign place',
      'minecraft:block.cherry_wood_hanging_sign.place'),
  stonePressurePlateClickOff('Stone Pressure Plate click Off',
      'minecraft:block.stone_pressure_plate.click_off'),
  conduitDeactivate('Conduit deactivate', 'minecraft:block.conduit.deactivate'),
  cherryWoodHangingSignStep('Cherry Wood Hanging Sign step',
      'minecraft:block.cherry_wood_hanging_sign.step'),
  amethystBlockPlace('Amethyst Block place', 'minecraft:block.amethyst_block.place'),
  wartBlockBreak('Wart Block break', 'minecraft:block.wart_block.break'),
  cakeAddCandle('Cake add Candle', 'minecraft:block.cake.add_candle'),
  froglightStep('Froglight step', 'minecraft:block.froglight.step'),
  copperGolemStatuePlace('Copper Golem Statue place', 'minecraft:block.copper_golem_statue.place'),
  pinkPetalsStep('Pink Petals step', 'minecraft:block.pink_petals.step'),
  sculkShriekerPlace('Sculk Shrieker place', 'minecraft:block.sculk_shrieker.place'),
  wetGrassHit('Wet Grass hit', 'minecraft:block.wet_grass.hit'),
  stoneBreak('Stone break', 'minecraft:block.stone.break'),
  ladderFall('Ladder fall', 'minecraft:block.ladder.fall'),
  dispenserDispense('Dispenser dispense', 'minecraft:block.dispenser.dispense'),
  polishedDeepslateHit('Polished Deepslate hit', 'minecraft:block.polished_deepslate.hit'),
  enderChestOpen('Ender Chest open', 'minecraft:block.ender_chest.open'),
  copperBulbPlace('Copper Bulb place', 'minecraft:block.copper_bulb.place'),
  frogspawnFall('Frogspawn fall', 'minecraft:block.frogspawn.fall'),
  noteBlockChime('Note Block chime', 'minecraft:block.note_block.chime'),
  woodenTrapdoorOpen('Wooden Trapdoor open', 'minecraft:block.wooden_trapdoor.open'),
  ironBreak('Iron break', 'minecraft:block.iron.break'),
  cobwebPlace('Cobweb place', 'minecraft:block.cobweb.place'),
  polishedDeepslateFall('Polished Deepslate fall', 'minecraft:block.polished_deepslate.fall'),
  netherWoodFenceGateClose('Nether Wood Fence Gate close',
      'minecraft:block.nether_wood_fence_gate.close'),
  copperGrateFall('Copper Grate fall', 'minecraft:block.copper_grate.fall'),
  boneBlockBreak('Bone Block break', 'minecraft:block.bone_block.break'),
  resinBricksPlace('Resin Bricks place', 'minecraft:block.resin_bricks.place'),
  rootedDirtHit('Rooted Dirt hit', 'minecraft:block.rooted_dirt.hit'),
  sulfurSpikeHit('Sulfur Spike hit', 'minecraft:block.sulfur_spike.hit'),
  blastfurnaceFireCrackle('Blastfurnace fire Crackle', 'minecraft:block.blastfurnace.fire_crackle'),
  azaleaLeavesHit('Azalea Leaves hit', 'minecraft:block.azalea_leaves.hit'),
  polishedTuffBreak('Polished Tuff break', 'minecraft:block.polished_tuff.break'),
  cherryLeavesBreak('Cherry Leaves break', 'minecraft:block.cherry_leaves.break'),
  cinnabarPlace('Cinnabar place', 'minecraft:block.cinnabar.place'),
  cobwebHit('Cobweb hit', 'minecraft:block.cobweb.hit'),
  suspiciousGravelPlace('Suspicious Gravel place', 'minecraft:block.suspicious_gravel.place'),
  snowFall('Snow fall', 'minecraft:block.snow.fall'),
  trialSpawnerBreak('Trial Spawner break', 'minecraft:block.trial_spawner.break'),
  sandBreak('Sand break', 'minecraft:block.sand.break'),
  endPortalFrameFill('End Portal Frame fill', 'minecraft:block.end_portal_frame.fill'),
  weepingVinesPlace('Weeping Vines place', 'minecraft:block.weeping_vines.place'),
  netherWoodDoorClose('Nether Wood Door close', 'minecraft:block.nether_wood_door.close'),
  leafLitterHit('Leaf Litter hit', 'minecraft:block.leaf_litter.hit'),
  bambooWoodFenceGateOpen('Bamboo Wood Fence Gate open',
      'minecraft:block.bamboo_wood_fence_gate.open'),
  ladderPlace('Ladder place', 'minecraft:block.ladder.place'),
  heavyCoreHit('Heavy Core hit', 'minecraft:block.heavy_core.hit'),
  cobwebStep('Cobweb step', 'minecraft:block.cobweb.step'),
  hangingSignHit('Hanging Sign hit', 'minecraft:block.hanging_sign.hit'),
  copperPlace('Copper place', 'minecraft:block.copper.place'),
  soulSandPlace('Soul Sand place', 'minecraft:block.soul_sand.place'),
  composterReady('Composter ready', 'minecraft:block.composter.ready'),
  cherryWoodTrapdoorOpen('Cherry Wood Trapdoor open', 'minecraft:block.cherry_wood_trapdoor.open'),
  sculkVeinHit('Sculk Vein hit', 'minecraft:block.sculk_vein.hit'),
  stoneButtonClickOff('Stone Button click Off', 'minecraft:block.stone_button.click_off'),
  cherryWoodHangingSignHit('Cherry Wood Hanging Sign hit',
      'minecraft:block.cherry_wood_hanging_sign.hit'),
  bambooWoodHangingSignStep('Bamboo Wood Hanging Sign step',
      'minecraft:block.bamboo_wood_hanging_sign.step'),
  soulSoilStep('Soul Soil step', 'minecraft:block.soul_soil.step'),
  hangingRootsFall('Hanging Roots fall', 'minecraft:block.hanging_roots.fall'),
  resinBricksFall('Resin Bricks fall', 'minecraft:block.resin_bricks.fall'),
  mossCarpetBreak('Moss Carpet break', 'minecraft:block.moss_carpet.break'),
  stoneStep('Stone step', 'minecraft:block.stone.step'),
  bambooWoodPressurePlateClickOff('Bamboo Wood Pressure Plate click Off',
      'minecraft:block.bamboo_wood_pressure_plate.click_off'),
  sculkSensorPlace('Sculk Sensor place', 'minecraft:block.sculk_sensor.place'),
  bambooWoodDoorClose('Bamboo Wood Door close', 'minecraft:block.bamboo_wood_door.close'),
  coralBlockPlace('Coral Block place', 'minecraft:block.coral_block.place'),
  wartBlockStep('Wart Block step', 'minecraft:block.wart_block.step'),
  amethystBlockHit('Amethyst Block hit', 'minecraft:block.amethyst_block.hit'),
  lodestonePlace('Lodestone place', 'minecraft:block.lodestone.place'),
  bellResonate('Bell resonate', 'minecraft:block.bell.resonate'),
  respawnAnchorSetSpawn('Respawn Anchor set Spawn', 'minecraft:block.respawn_anchor.set_spawn'),
  floweringAzaleaFall('Flowering Azalea fall', 'minecraft:block.flowering_azalea.fall'),
  rootsFall('Roots fall', 'minecraft:block.roots.fall'),
  noteBlockZombie('Note Block zombie', 'minecraft:block.note_block.imitate.zombie'),
  netherWoodPlace('Nether Wood place', 'minecraft:block.nether_wood.place'),
  sporeBlossomStep('Spore Blossom step', 'minecraft:block.spore_blossom.step'),
  pointedDripstonePlace('Pointed Dripstone place', 'minecraft:block.pointed_dripstone.place'),
  vineBreak('Vine break', 'minecraft:block.vine.break'),
  chiseledBookshelfPlace('Chiseled Bookshelf place', 'minecraft:block.chiseled_bookshelf.place'),
  decoratedPotPlace('Decorated Pot place', 'minecraft:block.decorated_pot.place'),
  sporeBlossomHit('Spore Blossom hit', 'minecraft:block.spore_blossom.hit'),
  netherWoodDoorOpen('Nether Wood Door open', 'minecraft:block.nether_wood_door.open'),
  enderChestClose('Ender Chest close', 'minecraft:block.ender_chest.close'),
  noteBlockFlute('Note Block flute', 'minecraft:block.note_block.flute'),
  ancientDebrisFall('Ancient Debris fall', 'minecraft:block.ancient_debris.fall'),
  mudHit('Mud hit', 'minecraft:block.mud.hit'),
  pinkPetalsHit('Pink Petals hit', 'minecraft:block.pink_petals.hit'),
  decoratedPotInsert('Decorated Pot insert', 'minecraft:block.decorated_pot.insert'),
  signWaxedInteractFail('Sign waxed Interact Fail', 'minecraft:block.sign.waxed_interact_fail'),
  fungusBreak('Fungus break', 'minecraft:block.fungus.break'),
  cinnabarFall('Cinnabar fall', 'minecraft:block.cinnabar.fall'),
  netherSproutsPlace('Nether Sprouts place', 'minecraft:block.nether_sprouts.place'),
  netherWoodTrapdoorClose('Nether Wood Trapdoor close',
      'minecraft:block.nether_wood_trapdoor.close'),
  netherWoodButtonClickOff('Nether Wood Button click Off',
      'minecraft:block.nether_wood_button.click_off'),
  noteBlockBanjo('Note Block banjo', 'minecraft:block.note_block.banjo'),
  noteBlockSkeleton('Note Block skeleton', 'minecraft:block.note_block.imitate.skeleton'),
  fenceGateClose('Fence Gate close', 'minecraft:block.fence_gate.close'),
  creakingHeartStep('Creaking Heart step', 'minecraft:block.creaking_heart.step'),
  ironDoorClose('Iron Door close', 'minecraft:block.iron_door.close'),
  floweringAzaleaPlace('Flowering Azalea place', 'minecraft:block.flowering_azalea.place'),
  glassStep('Glass step', 'minecraft:block.glass.step'),
  rootedDirtStep('Rooted Dirt step', 'minecraft:block.rooted_dirt.step'),
  bambooWoodStep('Bamboo Wood step', 'minecraft:block.bamboo_wood.step'),
  noteBlockSnare('Note Block snare', 'minecraft:block.note_block.snare'),
  sculkCatalystHit('Sculk Catalyst hit', 'minecraft:block.sculk_catalyst.hit'),
  trialSpawnerCloseShutter('Trial Spawner close Shutter',
      'minecraft:block.trial_spawner.close_shutter'),
  calciteStep('Calcite step', 'minecraft:block.calcite.step'),
  noteBlockTrumpetWeathered('Note Block trumpet Weathered',
      'minecraft:block.note_block.trumpet_weathered'),
  caveVinesStep('Cave Vines step', 'minecraft:block.cave_vines.step'),
  shulkerBoxClose('Shulker Box close', 'minecraft:block.shulker_box.close'),
  growingPlantCrop('Growing Plant crop', 'minecraft:block.growing_plant.crop'),
  fireflyBushIdle('Firefly Bush idle', 'minecraft:block.firefly_bush.idle'),
  netherBricksBreak('Nether Bricks break', 'minecraft:block.nether_bricks.break'),
  snowHit('Snow hit', 'minecraft:block.snow.hit'),
  lanternStep('Lantern step', 'minecraft:block.lantern.step'),
  cherryWoodFall('Cherry Wood fall', 'minecraft:block.cherry_wood.fall'),
  candleStep('Candle step', 'minecraft:block.candle.step'),
  snowPlace('Snow place', 'minecraft:block.snow.place'),
  glassHit('Glass hit', 'minecraft:block.glass.hit'),
  tuffBricksFall('Tuff Bricks fall', 'minecraft:block.tuff_bricks.fall'),
  cherrySaplingPlace('Cherry Sapling place', 'minecraft:block.cherry_sapling.place'),
  deepslateFall('Deepslate fall', 'minecraft:block.deepslate.fall'),
  polishedDeepslateBreak('Polished Deepslate break', 'minecraft:block.polished_deepslate.break'),
  snifferEggHatch('Sniffer Egg hatch', 'minecraft:block.sniffer_egg.hatch'),
  leafLitterStep('Leaf Litter step', 'minecraft:block.leaf_litter.step'),
  sandFall('Sand fall', 'minecraft:block.sand.fall'),
  woolFall('Wool fall', 'minecraft:block.wool.fall'),
  creakingHeartPlace('Creaking Heart place', 'minecraft:block.creaking_heart.place'),
  shelfHit('Shelf hit', 'minecraft:block.shelf.hit'),
  fungusStep('Fungus step', 'minecraft:block.fungus.step'),
  tuffHit('Tuff hit', 'minecraft:block.tuff.hit'),
  gildedBlackstonePlace('Gilded Blackstone place', 'minecraft:block.gilded_blackstone.place'),
  cactusFlowerPlace('Cactus Flower place', 'minecraft:block.cactus_flower.place'),
  vaultStep('Vault step', 'minecraft:block.vault.step'),
  ancientDebrisBreak('Ancient Debris break', 'minecraft:block.ancient_debris.break'),
  tuffBricksHit('Tuff Bricks hit', 'minecraft:block.tuff_bricks.hit'),
  portalAmbient('Portal ambient', 'minecraft:block.portal.ambient'),
  sculkShriekerFall('Sculk Shrieker fall', 'minecraft:block.sculk_shrieker.fall'),
  cherryWoodFenceGateClose('Cherry Wood Fence Gate close',
      'minecraft:block.cherry_wood_fence_gate.close'),
  crafterFail('Crafter fail', 'minecraft:block.crafter.fail'),
  paleHangingMossIdle('Pale Hanging Moss idle', 'minecraft:block.pale_hanging_moss.idle'),
  coralBlockFall('Coral Block fall', 'minecraft:block.coral_block.fall'),
  frogspawnPlace('Frogspawn place', 'minecraft:block.frogspawn.place');

  final String name;
  final String key;

  const BlockSound(this.name, this.key);

}