/// Generated class for the sound sources. Don't edit this file manually
enum BlockSound {

  resin_bricks_break('Resinbricks break', 'minecraft:block.resin_bricks.break'),
  bubble_column_whirlpool_inside('Bubblecolumn whirlpoolinside',
      'minecraft:block.bubble_column.whirlpool_inside'),
  sponge_absorb('Sponge absorb', 'minecraft:block.sponge.absorb'),
  moss_place('Moss place', 'minecraft:block.moss.place'),
  dripstone_block_hit('Dripstoneblock hit', 'minecraft:block.dripstone_block.hit'),
  scaffolding_fall('Scaffolding fall', 'minecraft:block.scaffolding.fall'),
  sponge_break('Sponge break', 'minecraft:block.sponge.break'),
  frogspawn_break('Frogspawn break', 'minecraft:block.frogspawn.break'),
  nylium_fall('Nylium fall', 'minecraft:block.nylium.fall'),
  powder_snow_place('Powdersnow place', 'minecraft:block.powder_snow.place'),
  moss_carpet_step('Mosscarpet step', 'minecraft:block.moss_carpet.step'),
  netherrack_fall('Netherrack fall', 'minecraft:block.netherrack.fall'),
  blastfurnace_fire_crackle('Blastfurnace firecrackle',
      'minecraft:block.blastfurnace.fire_crackle'),
  nether_wood_fence_gate_open('Netherwoodfencegate open',
      'minecraft:block.nether_wood_fence_gate.open'),
  cherry_wood_hanging_sign_break('Cherrywoodhangingsign break',
      'minecraft:block.cherry_wood_hanging_sign.break'),
  bamboo_wood_door_open('Bamboowooddoor open', 'minecraft:block.bamboo_wood_door.open'),
  iron_hit('Iron hit', 'minecraft:block.iron.hit'),
  note_block_wither_skeleton('Noteblock witherskeleton',
      'minecraft:block.note_block.imitate.wither_skeleton'),
  chiseled_bookshelf_insert('Chiseledbookshelf insert',
      'minecraft:block.chiseled_bookshelf.insert'),
  basalt_hit('Basalt hit', 'minecraft:block.basalt.hit'),
  azalea_step('Azalea step', 'minecraft:block.azalea.step'),
  creaking_heart_break('Creakingheart break', 'minecraft:block.creaking_heart.break'),
  mud_bricks_place('Mudbricks place', 'minecraft:block.mud_bricks.place'),
  bell_resonate('Bell resonate', 'minecraft:block.bell.resonate'),
  hanging_roots_step('Hangingroots step', 'minecraft:block.hanging_roots.step'),
  sculk_shrieker_place('Sculkshrieker place', 'minecraft:block.sculk_shrieker.place'),
  powder_snow_fall('Powdersnow fall', 'minecraft:block.powder_snow.fall'),
  nether_gold_ore_break('Nethergoldore break', 'minecraft:block.nether_gold_ore.break'),
  cherry_wood_door_open('Cherrywooddoor open', 'minecraft:block.cherry_wood_door.open'),
  tuff_bricks_place('Tuffbricks place', 'minecraft:block.tuff_bricks.place'),
  nether_wood_door_open('Netherwooddoor open', 'minecraft:block.nether_wood_door.open'),
  shroomlight_break('Shroomlight break', 'minecraft:block.shroomlight.break'),
  deepslate_step('Deepslate step', 'minecraft:block.deepslate.step'),
  pointed_dripstone_step('Pointeddripstone step', 'minecraft:block.pointed_dripstone.step'),
  weeping_vines_fall('Weepingvines fall', 'minecraft:block.weeping_vines.fall'),
  stone_button_click_off('Stonebutton clickoff', 'minecraft:block.stone_button.click_off'),
  cobweb_step('Cobweb step', 'minecraft:block.cobweb.step'),
  suspicious_sand_place('Suspicioussand place', 'minecraft:block.suspicious_sand.place'),
  trial_spawner_fall('Trialspawner fall', 'minecraft:block.trial_spawner.fall'),
  bamboo_wood_place('Bamboowood place', 'minecraft:block.bamboo_wood.place'),
  soul_soil_hit('Soulsoil hit', 'minecraft:block.soul_soil.hit'),
  weeping_vines_break('Weepingvines break', 'minecraft:block.weeping_vines.break'),
  wooden_trapdoor_close('Woodentrapdoor close', 'minecraft:block.wooden_trapdoor.close'),
  nether_wood_button_click_on('Netherwoodbutton clickon',
      'minecraft:block.nether_wood_button.click_on'),
  moss_step('Moss step', 'minecraft:block.moss.step'),
  metal_fall('Metal fall', 'minecraft:block.metal.fall'),
  soul_sand_break('Soulsand break', 'minecraft:block.soul_sand.break'),
  nylium_place('Nylium place', 'minecraft:block.nylium.place'),
  slime_block_break('Slimeblock break', 'minecraft:block.slime_block.break'),
  end_portal_frame_fill('Endportalframe fill', 'minecraft:block.end_portal_frame.fill'),
  shroomlight_hit('Shroomlight hit', 'minecraft:block.shroomlight.hit'),
  moss_hit('Moss hit', 'minecraft:block.moss.hit'),
  creaking_heart_hurt('Creakingheart hurt', 'minecraft:block.creaking_heart.hurt'),
  conduit_deactivate('Conduit deactivate', 'minecraft:block.conduit.deactivate'),
  cherry_wood_pressure_plate_click_on('Cherrywoodpressureplate clickon',
      'minecraft:block.cherry_wood_pressure_plate.click_on'),
  bamboo_hit('Bamboo hit', 'minecraft:block.bamboo.hit'),
  amethyst_cluster_break('Amethystcluster break', 'minecraft:block.amethyst_cluster.break'),
  grass_place('Grass place', 'minecraft:block.grass.place'),
  spawner_step('Spawner step', 'minecraft:block.spawner.step'),
  chorus_flower_grow('Chorusflower grow', 'minecraft:block.chorus_flower.grow'),
  decorated_pot_step('Decoratedpot step', 'minecraft:block.decorated_pot.step'),
  glass_place('Glass place', 'minecraft:block.glass.place'),
  suspicious_gravel_place('Suspiciousgravel place', 'minecraft:block.suspicious_gravel.place'),
  candle_ambient('Candle ambient', 'minecraft:block.candle.ambient'),
  nether_wood_door_close('Netherwooddoor close', 'minecraft:block.nether_wood_door.close'),
  beehive_enter('Beehive enter', 'minecraft:block.beehive.enter'),
  polished_deepslate_break('Polisheddeepslate break', 'minecraft:block.polished_deepslate.break'),
  deepslate_tiles_fall('Deepslatetiles fall', 'minecraft:block.deepslate_tiles.fall'),
  wooden_door_close('Woodendoor close', 'minecraft:block.wooden_door.close'),
  deepslate_break('Deepslate break', 'minecraft:block.deepslate.break'),
  froglight_step('Froglight step', 'minecraft:block.froglight.step'),
  cave_vines_pick_berries('Cavevines pickberries', 'minecraft:block.cave_vines.pick_berries'),
  water_ambient('Water ambient', 'minecraft:block.water.ambient'),
  sponge_hit('Sponge hit', 'minecraft:block.sponge.hit'),
  copper_break('Copper break', 'minecraft:block.copper.break'),
  pointed_dripstone_hit('Pointeddripstone hit', 'minecraft:block.pointed_dripstone.hit'),
  suspicious_sand_step('Suspicioussand step', 'minecraft:block.suspicious_sand.step'),
  tuff_fall('Tuff fall', 'minecraft:block.tuff.fall'),
  glass_hit('Glass hit', 'minecraft:block.glass.hit'),
  flowering_azalea_place('Floweringazalea place', 'minecraft:block.flowering_azalea.place'),
  sniffer_egg_crack('Snifferegg crack', 'minecraft:block.sniffer_egg.crack'),
  spawner_place('Spawner place', 'minecraft:block.spawner.place'),
  bamboo_step('Bamboo step', 'minecraft:block.bamboo.step'),
  moss_carpet_place('Mosscarpet place', 'minecraft:block.moss_carpet.place'),
  basalt_step('Basalt step', 'minecraft:block.basalt.step'),
  muddy_mangrove_roots_step('Muddymangroveroots step', 'minecraft:block.muddy_mangrove_roots.step'),
  small_amethyst_bud_break('Smallamethystbud break', 'minecraft:block.small_amethyst_bud.break'),
  azalea_leaves_break('Azalealeaves break', 'minecraft:block.azalea_leaves.break'),
  dripstone_block_step('Dripstoneblock step', 'minecraft:block.dripstone_block.step'),
  copper_grate_break('Coppergrate break', 'minecraft:block.copper_grate.break'),
  netherite_block_break('Netheriteblock break', 'minecraft:block.netherite_block.break'),
  nether_sprouts_hit('Nethersprouts hit', 'minecraft:block.nether_sprouts.hit'),
  fungus_place('Fungus place', 'minecraft:block.fungus.place'),
  pink_petals_step('Pinkpetals step', 'minecraft:block.pink_petals.step'),
  cherry_wood_fall('Cherrywood fall', 'minecraft:block.cherry_wood.fall'),
  nether_wood_place('Netherwood place', 'minecraft:block.nether_wood.place'),
  flowering_azalea_hit('Floweringazalea hit', 'minecraft:block.flowering_azalea.hit'),
  heavy_core_place('Heavycore place', 'minecraft:block.heavy_core.place'),
  shroomlight_step('Shroomlight step', 'minecraft:block.shroomlight.step'),
  grindstone_use('Grindstone use', 'minecraft:block.grindstone.use'),
  shulker_box_close('Shulkerbox close', 'minecraft:block.shulker_box.close'),
  coral_block_place('Coralblock place', 'minecraft:block.coral_block.place'),
  small_dripleaf_break('Smalldripleaf break', 'minecraft:block.small_dripleaf.break'),
  dispenser_launch('Dispenser launch', 'minecraft:block.dispenser.launch'),
  sculk_vein_place('Sculkvein place', 'minecraft:block.sculk_vein.place'),
  sculk_shrieker_shriek('Sculkshrieker shriek', 'minecraft:block.sculk_shrieker.shriek'),
  polished_deepslate_fall('Polisheddeepslate fall', 'minecraft:block.polished_deepslate.fall'),
  vault_insert_item('Vault insertitem', 'minecraft:block.vault.insert_item'),
  nether_sprouts_step('Nethersprouts step', 'minecraft:block.nether_sprouts.step'),
  nether_bricks_break('Netherbricks break', 'minecraft:block.nether_bricks.break'),
  beehive_drip('Beehive drip', 'minecraft:block.beehive.drip'),
  bamboo_wood_fall('Bamboowood fall', 'minecraft:block.bamboo_wood.fall'),
  polished_tuff_hit('Polishedtuff hit', 'minecraft:block.polished_tuff.hit'),
  copper_door_open('Copperdoor open', 'minecraft:block.copper_door.open'),
  chiseled_bookshelf_place('Chiseledbookshelf place', 'minecraft:block.chiseled_bookshelf.place'),
  amethyst_block_place('Amethystblock place', 'minecraft:block.amethyst_block.place'),
  leaf_litter_break('Leaflitter break', 'minecraft:block.leaf_litter.break'),
  bubble_column_bubble_pop('Bubblecolumn bubblepop', 'minecraft:block.bubble_column.bubble_pop'),
  amethyst_block_step('Amethystblock step', 'minecraft:block.amethyst_block.step'),
  packed_mud_place('Packedmud place', 'minecraft:block.packed_mud.place'),
  snow_fall('Snow fall', 'minecraft:block.snow.fall'),
  anvil_place('Anvil place', 'minecraft:block.anvil.place'),
  ender_chest_open('Enderchest open', 'minecraft:block.ender_chest.open'),
  bamboo_wood_trapdoor_open('Bamboowoodtrapdoor open', 'minecraft:block.bamboo_wood_trapdoor.open'),
  gravel_place('Gravel place', 'minecraft:block.gravel.place'),
  beehive_exit('Beehive exit', 'minecraft:block.beehive.exit'),
  sculk_catalyst_hit('Sculkcatalyst hit', 'minecraft:block.sculk_catalyst.hit'),
  creaking_heart_hit('Creakingheart hit', 'minecraft:block.creaking_heart.hit'),
  ancient_debris_step('Ancientdebris step', 'minecraft:block.ancient_debris.step'),
  glass_fall('Glass fall', 'minecraft:block.glass.fall'),
  wet_sponge_place('Wetsponge place', 'minecraft:block.wet_sponge.place'),
  vault_hit('Vault hit', 'minecraft:block.vault.hit'),
  nether_wood_button_click_off('Netherwoodbutton clickoff',
      'minecraft:block.nether_wood_button.click_off'),
  chain_break('Chain break', 'minecraft:block.chain.break'),
  big_dripleaf_tilt_up('Bigdripleaf tiltup', 'minecraft:block.big_dripleaf.tilt_up'),
  bamboo_wood_button_click_off('Bamboowoodbutton clickoff',
      'minecraft:block.bamboo_wood_button.click_off'),
  wood_break('Wood break', 'minecraft:block.wood.break'),
  calcite_step('Calcite step', 'minecraft:block.calcite.step'),
  creaking_heart_idle('Creakingheart idle', 'minecraft:block.creaking_heart.idle'),
  wooden_button_click_off('Woodenbutton clickoff', 'minecraft:block.wooden_button.click_off'),
  cake_add_candle('Cake addcandle', 'minecraft:block.cake.add_candle'),
  froglight_place('Froglight place', 'minecraft:block.froglight.place'),
  packed_mud_fall('Packedmud fall', 'minecraft:block.packed_mud.fall'),
  polished_tuff_fall('Polishedtuff fall', 'minecraft:block.polished_tuff.fall'),
  chiseled_bookshelf_pickup('Chiseledbookshelf pickup',
      'minecraft:block.chiseled_bookshelf.pickup'),
  cherry_wood_pressure_plate_click_off('Cherrywoodpressureplate clickoff',
      'minecraft:block.cherry_wood_pressure_plate.click_off'),
  fence_gate_open('Fencegate open', 'minecraft:block.fence_gate.open'),
  nether_gold_ore_hit('Nethergoldore hit', 'minecraft:block.nether_gold_ore.hit'),
  vine_fall('Vine fall', 'minecraft:block.vine.fall'),
  nether_wood_step('Netherwood step', 'minecraft:block.nether_wood.step'),
  pale_hanging_moss_idle('Palehangingmoss idle', 'minecraft:block.pale_hanging_moss.idle'),
  amethyst_cluster_hit('Amethystcluster hit', 'minecraft:block.amethyst_cluster.hit'),
  basalt_place('Basalt place', 'minecraft:block.basalt.place'),
  calcite_break('Calcite break', 'minecraft:block.calcite.break'),
  barrel_close('Barrel close', 'minecraft:block.barrel.close'),
  conduit_activate('Conduit activate', 'minecraft:block.conduit.activate'),
  chain_fall('Chain fall', 'minecraft:block.chain.fall'),
  deepslate_hit('Deepslate hit', 'minecraft:block.deepslate.hit'),
  coral_block_hit('Coralblock hit', 'minecraft:block.coral_block.hit'),
  bone_block_break('Boneblock break', 'minecraft:block.bone_block.break'),
  note_block_didgeridoo('Noteblock didgeridoo', 'minecraft:block.note_block.didgeridoo'),
  honey_block_fall('Honeyblock fall', 'minecraft:block.honey_block.fall'),
  vault_close_shutter('Vault closeshutter', 'minecraft:block.vault.close_shutter'),
  candle_fall('Candle fall', 'minecraft:block.candle.fall'),
  fence_gate_close('Fencegate close', 'minecraft:block.fence_gate.close'),
  vault_eject_item('Vault ejectitem', 'minecraft:block.vault.eject_item'),
  wool_break('Wool break', 'minecraft:block.wool.break'),
  ancient_debris_place('Ancientdebris place', 'minecraft:block.ancient_debris.place'),
  tripwire_click_off('Tripwire clickoff', 'minecraft:block.tripwire.click_off'),
  brewing_stand_brew('Brewingstand brew', 'minecraft:block.brewing_stand.brew'),
  slime_block_fall('Slimeblock fall', 'minecraft:block.slime_block.fall'),
  dried_ghast_step('Driedghast step', 'minecraft:block.dried_ghast.step'),
  conduit_short('Conduit short', 'minecraft:block.conduit.ambient.short'),
  bamboo_wood_hanging_sign_place('Bamboowoodhangingsign place',
      'minecraft:block.bamboo_wood_hanging_sign.place'),
  nether_wood_pressure_plate_click_off('Netherwoodpressureplate clickoff',
      'minecraft:block.nether_wood_pressure_plate.click_off'),
  copper_grate_fall('Coppergrate fall', 'minecraft:block.copper_grate.fall'),
  deepslate_bricks_fall('Deepslatebricks fall', 'minecraft:block.deepslate_bricks.fall'),
  scaffolding_step('Scaffolding step', 'minecraft:block.scaffolding.step'),
  vault_activate('Vault activate', 'minecraft:block.vault.activate'),
  vault_fall('Vault fall', 'minecraft:block.vault.fall'),
  netherite_block_fall('Netheriteblock fall', 'minecraft:block.netherite_block.fall'),
  spore_blossom_hit('Sporeblossom hit', 'minecraft:block.spore_blossom.hit'),
  cherry_leaves_fall('Cherryleaves fall', 'minecraft:block.cherry_leaves.fall'),
  decorated_pot_hit('Decoratedpot hit', 'minecraft:block.decorated_pot.hit'),
  sculk_sensor_fall('Sculksensor fall', 'minecraft:block.sculk_sensor.fall'),
  chiseled_bookshelf_fall('Chiseledbookshelf fall', 'minecraft:block.chiseled_bookshelf.fall'),
  fire_ambient('Fire ambient', 'minecraft:block.fire.ambient'),
  wart_block_break('Wartblock break', 'minecraft:block.wart_block.break'),
  calcite_hit('Calcite hit', 'minecraft:block.calcite.hit'),
  ender_chest_close('Enderchest close', 'minecraft:block.ender_chest.close'),
  nylium_step('Nylium step', 'minecraft:block.nylium.step'),
  hanging_sign_fall('Hangingsign fall', 'minecraft:block.hanging_sign.fall'),
  chest_open('Chest open', 'minecraft:block.chest.open'),
  big_dripleaf_break('Bigdripleaf break', 'minecraft:block.big_dripleaf.break'),
  netherrack_step('Netherrack step', 'minecraft:block.netherrack.step'),
  decorated_pot_insert_fail('Decoratedpot insertfail', 'minecraft:block.decorated_pot.insert_fail'),
  fungus_hit('Fungus hit', 'minecraft:block.fungus.hit'),
  sign_waxed_interact_fail('Sign waxedinteractfail', 'minecraft:block.sign.waxed_interact_fail'),
  resin_fall('Resin fall', 'minecraft:block.resin.fall'),
  moss_break('Moss break', 'minecraft:block.moss.break'),
  trial_spawner_hit('Trialspawner hit', 'minecraft:block.trial_spawner.hit'),
  nether_wood_hanging_sign_hit('Netherwoodhangingsign hit',
      'minecraft:block.nether_wood_hanging_sign.hit'),
  powder_snow_step('Powdersnow step', 'minecraft:block.powder_snow.step'),
  resin_bricks_fall('Resinbricks fall', 'minecraft:block.resin_bricks.fall'),
  mud_break('Mud break', 'minecraft:block.mud.break'),
  nether_bricks_hit('Netherbricks hit', 'minecraft:block.nether_bricks.hit'),
  vine_place('Vine place', 'minecraft:block.vine.place'),
  beehive_shear('Beehive shear', 'minecraft:block.beehive.shear'),
  powder_snow_break('Powdersnow break', 'minecraft:block.powder_snow.break'),
  bamboo_wood_hanging_sign_hit('Bamboowoodhangingsign hit',
      'minecraft:block.bamboo_wood_hanging_sign.hit'),
  note_block_zombie('Noteblock zombie', 'minecraft:block.note_block.imitate.zombie'),
  sculk_sensor_clicking_stop('Sculksensor clickingstop',
      'minecraft:block.sculk_sensor.clicking_stop'),
  weeping_vines_step('Weepingvines step', 'minecraft:block.weeping_vines.step'),
  copper_grate_hit('Coppergrate hit', 'minecraft:block.copper_grate.hit'),
  bubble_column_upwards_ambient('Bubblecolumn upwardsambient',
      'minecraft:block.bubble_column.upwards_ambient'),
  sand_hit('Sand hit', 'minecraft:block.sand.hit'),
  ladder_place('Ladder place', 'minecraft:block.ladder.place'),
  trial_spawner_step('Trialspawner step', 'minecraft:block.trial_spawner.step'),
  sculk_sensor_clicking('Sculksensor clicking', 'minecraft:block.sculk_sensor.clicking'),
  metal_step('Metal step', 'minecraft:block.metal.step'),
  respawn_anchor_set_spawn('Respawnanchor setspawn', 'minecraft:block.respawn_anchor.set_spawn'),
  suspicious_sand_hit('Suspicioussand hit', 'minecraft:block.suspicious_sand.hit'),
  froglight_hit('Froglight hit', 'minecraft:block.froglight.hit'),
  sculk_shrieker_break('Sculkshrieker break', 'minecraft:block.sculk_shrieker.break'),
  tuff_bricks_break('Tuffbricks break', 'minecraft:block.tuff_bricks.break'),
  sculk_hit('Sculk hit', 'minecraft:block.sculk.hit'),
  pointed_dripstone_drip_water_into_cauldron('Pointeddripstone dripwaterintocauldron',
      'minecraft:block.pointed_dripstone.drip_water_into_cauldron'),
  dispenser_fail('Dispenser fail', 'minecraft:block.dispenser.fail'),
  tuff_bricks_fall('Tuffbricks fall', 'minecraft:block.tuff_bricks.fall'),
  suspicious_sand_break('Suspicioussand break', 'minecraft:block.suspicious_sand.break'),
  bamboo_wood_break('Bamboowood break', 'minecraft:block.bamboo_wood.break'),
  netherrack_hit('Netherrack hit', 'minecraft:block.netherrack.hit'),
  anvil_hit('Anvil hit', 'minecraft:block.anvil.hit'),
  respawn_anchor_deplete('Respawnanchor deplete', 'minecraft:block.respawn_anchor.deplete'),
  deepslate_bricks_hit('Deepslatebricks hit', 'minecraft:block.deepslate_bricks.hit'),
  deepslate_tiles_hit('Deepslatetiles hit', 'minecraft:block.deepslate_tiles.hit'),
  nylium_break('Nylium break', 'minecraft:block.nylium.break'),
  dried_ghast_transition('Driedghast transition', 'minecraft:block.dried_ghast.transition'),
  chiseled_bookshelf_hit('Chiseledbookshelf hit', 'minecraft:block.chiseled_bookshelf.hit'),
  cave_vines_place('Cavevines place', 'minecraft:block.cave_vines.place'),
  composter_ready('Composter ready', 'minecraft:block.composter.ready'),
  conduit_target('Conduit target', 'minecraft:block.conduit.attack.target'),
  cherry_leaves_place('Cherryleaves place', 'minecraft:block.cherry_leaves.place'),
  gravel_fall('Gravel fall', 'minecraft:block.gravel.fall'),
  pointed_dripstone_drip_water('Pointeddripstone dripwater',
      'minecraft:block.pointed_dripstone.drip_water'),
  wet_sponge_fall('Wetsponge fall', 'minecraft:block.wet_sponge.fall'),
  beehive_work('Beehive work', 'minecraft:block.beehive.work'),
  note_block_bit('Noteblock bit', 'minecraft:block.note_block.bit'),
  deepslate_tiles_step('Deepslatetiles step', 'minecraft:block.deepslate_tiles.step'),
  coral_block_fall('Coralblock fall', 'minecraft:block.coral_block.fall'),
  frogspawn_fall('Frogspawn fall', 'minecraft:block.frogspawn.fall'),
  grass_break('Grass break', 'minecraft:block.grass.break'),
  eyeblossom_idle('Eyeblossom idle', 'minecraft:block.eyeblossom.idle'),
  sculk_catalyst_place('Sculkcatalyst place', 'minecraft:block.sculk_catalyst.place'),
  respawn_anchor_ambient('Respawnanchor ambient', 'minecraft:block.respawn_anchor.ambient'),
  eyeblossom_open_long('Eyeblossom openlong', 'minecraft:block.eyeblossom.open_long'),
  iron_fall('Iron fall', 'minecraft:block.iron.fall'),
  sand_fall('Sand fall', 'minecraft:block.sand.fall'),
  pointed_dripstone_place('Pointeddripstone place', 'minecraft:block.pointed_dripstone.place'),
  muddy_mangrove_roots_hit('Muddymangroveroots hit', 'minecraft:block.muddy_mangrove_roots.hit'),
  portal_trigger('Portal trigger', 'minecraft:block.portal.trigger'),
  tuff_step('Tuff step', 'minecraft:block.tuff.step'),
  glass_break('Glass break', 'minecraft:block.glass.break'),
  wart_block_hit('Wartblock hit', 'minecraft:block.wart_block.hit'),
  suspicious_gravel_break('Suspiciousgravel break', 'minecraft:block.suspicious_gravel.break'),
  trial_spawner_detect_player('Trialspawner detectplayer',
      'minecraft:block.trial_spawner.detect_player'),
  wooden_button_click_on('Woodenbutton clickon', 'minecraft:block.wooden_button.click_on'),
  azalea_hit('Azalea hit', 'minecraft:block.azalea.hit'),
  sponge_fall('Sponge fall', 'minecraft:block.sponge.fall'),
  anvil_fall('Anvil fall', 'minecraft:block.anvil.fall'),
  cherry_wood_step('Cherrywood step', 'minecraft:block.cherry_wood.step'),
  flowering_azalea_break('Floweringazalea break', 'minecraft:block.flowering_azalea.break'),
  spawner_break('Spawner break', 'minecraft:block.spawner.break'),
  cherry_wood_trapdoor_open('Cherrywoodtrapdoor open', 'minecraft:block.cherry_wood_trapdoor.open'),
  mangrove_roots_fall('Mangroveroots fall', 'minecraft:block.mangrove_roots.fall'),
  moss_carpet_break('Mosscarpet break', 'minecraft:block.moss_carpet.break'),
  mangrove_roots_place('Mangroveroots place', 'minecraft:block.mangrove_roots.place'),
  slime_block_hit('Slimeblock hit', 'minecraft:block.slime_block.hit'),
  cactus_flower_place('Cactusflower place', 'minecraft:block.cactus_flower.place'),
  wooden_trapdoor_open('Woodentrapdoor open', 'minecraft:block.wooden_trapdoor.open'),
  sculk_shrieker_fall('Sculkshrieker fall', 'minecraft:block.sculk_shrieker.fall'),
  lava_ambient('Lava ambient', 'minecraft:block.lava.ambient'),
  polished_deepslate_step('Polisheddeepslate step', 'minecraft:block.polished_deepslate.step'),
  vault_place('Vault place', 'minecraft:block.vault.place'),
  fungus_break('Fungus break', 'minecraft:block.fungus.break'),
  heavy_core_break('Heavycore break', 'minecraft:block.heavy_core.break'),
  stone_pressure_plate_click_on('Stonepressureplate clickon',
      'minecraft:block.stone_pressure_plate.click_on'),
  pink_petals_place('Pinkpetals place', 'minecraft:block.pink_petals.place'),
  hanging_roots_place('Hangingroots place', 'minecraft:block.hanging_roots.place'),
  nether_wood_break('Netherwood break', 'minecraft:block.nether_wood.break'),
  note_block_snare('Noteblock snare', 'minecraft:block.note_block.snare'),
  bamboo_wood_step('Bamboowood step', 'minecraft:block.bamboo_wood.step'),
  resin_bricks_hit('Resinbricks hit', 'minecraft:block.resin_bricks.hit'),
  cherry_wood_place('Cherrywood place', 'minecraft:block.cherry_wood.place'),
  note_block_iron_xylophone('Noteblock ironxylophone', 'minecraft:block.note_block.iron_xylophone'),
  metal_pressure_plate_click_on('Metalpressureplate clickon',
      'minecraft:block.metal_pressure_plate.click_on'),
  dried_ghast_ambient('Driedghast ambient', 'minecraft:block.dried_ghast.ambient'),
  vault_deactivate('Vault deactivate', 'minecraft:block.vault.deactivate'),
  coral_block_break('Coralblock break', 'minecraft:block.coral_block.break'),
  snow_step('Snow step', 'minecraft:block.snow.step'),
  medium_amethyst_bud_place('Mediumamethystbud place', 'minecraft:block.medium_amethyst_bud.place'),
  note_block_ender_dragon('Noteblock enderdragon',
      'minecraft:block.note_block.imitate.ender_dragon'),
  small_dripleaf_fall('Smalldripleaf fall', 'minecraft:block.small_dripleaf.fall'),
  roots_fall('Roots fall', 'minecraft:block.roots.fall'),
  sculk_vein_break('Sculkvein break', 'minecraft:block.sculk_vein.break'),
  iron_place('Iron place', 'minecraft:block.iron.place'),
  stone_place('Stone place', 'minecraft:block.stone.place'),
  glass_step('Glass step', 'minecraft:block.glass.step'),
  bell_use('Bell use', 'minecraft:block.bell.use'),
  amethyst_block_break('Amethystblock break', 'minecraft:block.amethyst_block.break'),
  mud_bricks_fall('Mudbricks fall', 'minecraft:block.mud_bricks.fall'),
  metal_hit('Metal hit', 'minecraft:block.metal.hit'),
  packed_mud_break('Packedmud break', 'minecraft:block.packed_mud.break'),
  wet_grass_hit('Wetgrass hit', 'minecraft:block.wet_grass.hit'),
  furnace_fire_crackle('Furnace firecrackle', 'minecraft:block.furnace.fire_crackle'),
  piston_extend('Piston extend', 'minecraft:block.piston.extend'),
  stem_break('Stem break', 'minecraft:block.stem.break'),
  eyeblossom_open('Eyeblossom open', 'minecraft:block.eyeblossom.open'),
  anvil_break('Anvil break', 'minecraft:block.anvil.break'),
  nether_gold_ore_fall('Nethergoldore fall', 'minecraft:block.nether_gold_ore.fall'),
  spawner_hit('Spawner hit', 'minecraft:block.spawner.hit'),
  packed_mud_step('Packedmud step', 'minecraft:block.packed_mud.step'),
  polished_tuff_step('Polishedtuff step', 'minecraft:block.polished_tuff.step'),
  bamboo_sapling_place('Bamboosapling place', 'minecraft:block.bamboo_sapling.place'),
  sculk_catalyst_fall('Sculkcatalyst fall', 'minecraft:block.sculk_catalyst.fall'),
  vine_step('Vine step', 'minecraft:block.vine.step'),
  lantern_break('Lantern break', 'minecraft:block.lantern.break'),
  wet_sponge_break('Wetsponge break', 'minecraft:block.wet_sponge.break'),
  chain_step('Chain step', 'minecraft:block.chain.step'),
  copper_bulb_turn_on('Copperbulb turnon', 'minecraft:block.copper_bulb.turn_on'),
  stem_fall('Stem fall', 'minecraft:block.stem.fall'),
  wood_fall('Wood fall', 'minecraft:block.wood.fall'),
  scaffolding_hit('Scaffolding hit', 'minecraft:block.scaffolding.hit'),
  netherrack_place('Netherrack place', 'minecraft:block.netherrack.place'),
  note_block_guitar('Noteblock guitar', 'minecraft:block.note_block.guitar'),
  grass_fall('Grass fall', 'minecraft:block.grass.fall'),
  trial_spawner_spawn_mob('Trialspawner spawnmob', 'minecraft:block.trial_spawner.spawn_mob'),
  deepslate_tiles_break('Deepslatetiles break', 'minecraft:block.deepslate_tiles.break'),
  froglight_break('Froglight break', 'minecraft:block.froglight.break'),
  honey_block_step('Honeyblock step', 'minecraft:block.honey_block.step'),
  sculk_place('Sculk place', 'minecraft:block.sculk.place'),
  candle_step('Candle step', 'minecraft:block.candle.step'),
  cobweb_place('Cobweb place', 'minecraft:block.cobweb.place'),
  scaffolding_place('Scaffolding place', 'minecraft:block.scaffolding.place'),
  trial_spawner_close_shutter('Trialspawner closeshutter',
      'minecraft:block.trial_spawner.close_shutter'),
  slime_block_step('Slimeblock step', 'minecraft:block.slime_block.step'),
  composter_empty('Composter empty', 'minecraft:block.composter.empty'),
  honey_block_hit('Honeyblock hit', 'minecraft:block.honey_block.hit'),
  rooted_dirt_place('Rooteddirt place', 'minecraft:block.rooted_dirt.place'),
  amethyst_block_resonate('Amethystblock resonate', 'minecraft:block.amethyst_block.resonate'),
  basalt_break('Basalt break', 'minecraft:block.basalt.break'),
  lava_pop('Lava pop', 'minecraft:block.lava.pop'),
  shulker_box_open('Shulkerbox open', 'minecraft:block.shulker_box.open'),
  dripstone_block_place('Dripstoneblock place', 'minecraft:block.dripstone_block.place'),
  decorated_pot_shatter('Decoratedpot shatter', 'minecraft:block.decorated_pot.shatter'),
  lava_extinguish('Lava extinguish', 'minecraft:block.lava.extinguish'),
  candle_hit('Candle hit', 'minecraft:block.candle.hit'),
  cherry_wood_hit('Cherrywood hit', 'minecraft:block.cherry_wood.hit'),
  vault_step('Vault step', 'minecraft:block.vault.step'),
  deepslate_bricks_step('Deepslatebricks step', 'minecraft:block.deepslate_bricks.step'),
  copper_grate_step('Coppergrate step', 'minecraft:block.copper_grate.step'),
  vine_hit('Vine hit', 'minecraft:block.vine.hit'),
  cherry_leaves_step('Cherryleaves step', 'minecraft:block.cherry_leaves.step'),
  azalea_place('Azalea place', 'minecraft:block.azalea.place'),
  leaf_litter_fall('Leaflitter fall', 'minecraft:block.leaf_litter.fall'),
  netherite_block_step('Netheriteblock step', 'minecraft:block.netherite_block.step'),
  sculk_sensor_step('Sculksensor step', 'minecraft:block.sculk_sensor.step'),
  chiseled_bookshelf_step('Chiseledbookshelf step', 'minecraft:block.chiseled_bookshelf.step'),
  ancient_debris_break('Ancientdebris break', 'minecraft:block.ancient_debris.break'),
  copper_fall('Copper fall', 'minecraft:block.copper.fall'),
  soul_soil_place('Soulsoil place', 'minecraft:block.soul_soil.place'),
  hanging_sign_step('Hangingsign step', 'minecraft:block.hanging_sign.step'),
  bamboo_wood_hanging_sign_break('Bamboowoodhangingsign break',
      'minecraft:block.bamboo_wood_hanging_sign.break'),
  trial_spawner_ominous_activate('Trialspawner ominousactivate',
      'minecraft:block.trial_spawner.ominous_activate'),
  cherry_wood_fence_gate_close('Cherrywoodfencegate close',
      'minecraft:block.cherry_wood_fence_gate.close'),
  note_block_basedrum('Noteblock basedrum', 'minecraft:block.note_block.basedrum'),
  snow_place('Snow place', 'minecraft:block.snow.place'),
  lodestone_fall('Lodestone fall', 'minecraft:block.lodestone.fall'),
  nether_sprouts_place('Nethersprouts place', 'minecraft:block.nether_sprouts.place'),
  note_block_bell('Noteblock bell', 'minecraft:block.note_block.bell'),
  honey_block_place('Honeyblock place', 'minecraft:block.honey_block.place'),
  resin_step('Resin step', 'minecraft:block.resin.step'),
  wooden_pressure_plate_click_off('Woodenpressureplate clickoff',
      'minecraft:block.wooden_pressure_plate.click_off'),
  copper_trapdoor_close('Coppertrapdoor close', 'minecraft:block.copper_trapdoor.close'),
  pointed_dripstone_drip_lava_into_cauldron('Pointeddripstone driplavaintocauldron',
      'minecraft:block.pointed_dripstone.drip_lava_into_cauldron'),
  candle_place('Candle place', 'minecraft:block.candle.place'),
  resin_bricks_step('Resinbricks step', 'minecraft:block.resin_bricks.step'),
  end_portal_spawn('Endportal spawn', 'minecraft:block.end_portal.spawn'),
  ancient_debris_hit('Ancientdebris hit', 'minecraft:block.ancient_debris.hit'),
  fungus_fall('Fungus fall', 'minecraft:block.fungus.fall'),
  mud_fall('Mud fall', 'minecraft:block.mud.fall'),
  vault_ambient('Vault ambient', 'minecraft:block.vault.ambient'),
  cherry_sapling_place('Cherrysapling place', 'minecraft:block.cherry_sapling.place'),
  wool_fall('Wool fall', 'minecraft:block.wool.fall'),
  sand_place('Sand place', 'minecraft:block.sand.place'),
  nether_wood_trapdoor_close('Netherwoodtrapdoor close',
      'minecraft:block.nether_wood_trapdoor.close'),
  nether_ore_place('Netherore place', 'minecraft:block.nether_ore.place'),
  vine_break('Vine break', 'minecraft:block.vine.break'),
  heavy_core_fall('Heavycore fall', 'minecraft:block.heavy_core.fall'),
  tuff_bricks_step('Tuffbricks step', 'minecraft:block.tuff_bricks.step'),
  ladder_break('Ladder break', 'minecraft:block.ladder.break'),
  bamboo_wood_door_close('Bamboowooddoor close', 'minecraft:block.bamboo_wood_door.close'),
  creaking_heart_spawn('Creakingheart spawn', 'minecraft:block.creaking_heart.spawn'),
  sculk_spread('Sculk spread', 'minecraft:block.sculk.spread'),
  mud_bricks_break('Mudbricks break', 'minecraft:block.mud_bricks.break'),
  anvil_land('Anvil land', 'minecraft:block.anvil.land'),
  copper_bulb_place('Copperbulb place', 'minecraft:block.copper_bulb.place'),
  sculk_sensor_place('Sculksensor place', 'minecraft:block.sculk_sensor.place'),
  sculk_vein_fall('Sculkvein fall', 'minecraft:block.sculk_vein.fall'),
  copper_hit('Copper hit', 'minecraft:block.copper.hit'),
  cherry_sapling_fall('Cherrysapling fall', 'minecraft:block.cherry_sapling.fall'),
  beacon_ambient('Beacon ambient', 'minecraft:block.beacon.ambient'),
  rooted_dirt_fall('Rooteddirt fall', 'minecraft:block.rooted_dirt.fall'),
  gravel_step('Gravel step', 'minecraft:block.gravel.step'),
  barrel_open('Barrel open', 'minecraft:block.barrel.open'),
  sculk_fall('Sculk fall', 'minecraft:block.sculk.fall'),
  chiseled_bookshelf_enchanted('Chiseledbookshelf enchanted',
      'minecraft:block.chiseled_bookshelf.insert.enchanted'),
  bamboo_wood_fence_gate_open('Bamboowoodfencegate open',
      'minecraft:block.bamboo_wood_fence_gate.open'),
  lever_click('Lever click', 'minecraft:block.lever.click'),
  muddy_mangrove_roots_place('Muddymangroveroots place',
      'minecraft:block.muddy_mangrove_roots.place'),
  wet_sponge_step('Wetsponge step', 'minecraft:block.wet_sponge.step'),
  honey_block_slide('Honeyblock slide', 'minecraft:block.honey_block.slide'),
  copper_bulb_fall('Copperbulb fall', 'minecraft:block.copper_bulb.fall'),
  coral_block_step('Coralblock step', 'minecraft:block.coral_block.step'),
  trial_spawner_about_to_spawn_item('Trialspawner abouttospawnitem',
      'minecraft:block.trial_spawner.about_to_spawn_item'),
  cave_vines_fall('Cavevines fall', 'minecraft:block.cave_vines.fall'),
  campfire_crackle('Campfire crackle', 'minecraft:block.campfire.crackle'),
  lodestone_hit('Lodestone hit', 'minecraft:block.lodestone.hit'),
  dried_ghast_place('Driedghast place', 'minecraft:block.dried_ghast.place'),
  note_block_piglin('Noteblock piglin', 'minecraft:block.note_block.imitate.piglin'),
  bamboo_wood_pressure_plate_click_off('Bamboowoodpressureplate clickoff',
      'minecraft:block.bamboo_wood_pressure_plate.click_off'),
  wet_grass_place('Wetgrass place', 'minecraft:block.wet_grass.place'),
  frogspawn_step('Frogspawn step', 'minecraft:block.frogspawn.step'),
  frogspawn_hatch('Frogspawn hatch', 'minecraft:block.frogspawn.hatch'),
  cave_vines_break('Cavevines break', 'minecraft:block.cave_vines.break'),
  end_gateway_spawn('Endgateway spawn', 'minecraft:block.end_gateway.spawn'),
  bone_block_hit('Boneblock hit', 'minecraft:block.bone_block.hit'),
  packed_mud_hit('Packedmud hit', 'minecraft:block.packed_mud.hit'),
  sand_step('Sand step', 'minecraft:block.sand.step'),
  iron_step('Iron step', 'minecraft:block.iron.step'),
  cherry_leaves_break('Cherryleaves break', 'minecraft:block.cherry_leaves.break'),
  roots_hit('Roots hit', 'minecraft:block.roots.hit'),
  hanging_sign_hit('Hangingsign hit', 'minecraft:block.hanging_sign.hit'),
  deepslate_bricks_place('Deepslatebricks place', 'minecraft:block.deepslate_bricks.place'),
  bamboo_wood_button_click_on('Bamboowoodbutton clickon',
      'minecraft:block.bamboo_wood_button.click_on'),
  tripwire_detach('Tripwire detach', 'minecraft:block.tripwire.detach'),
  sponge_step('Sponge step', 'minecraft:block.sponge.step'),
  hanging_sign_place('Hangingsign place', 'minecraft:block.hanging_sign.place'),
  gilded_blackstone_place('Gildedblackstone place', 'minecraft:block.gilded_blackstone.place'),
  nylium_hit('Nylium hit', 'minecraft:block.nylium.hit'),
  wet_sponge_hit('Wetsponge hit', 'minecraft:block.wet_sponge.hit'),
  anvil_use('Anvil use', 'minecraft:block.anvil.use'),
  beacon_power_select('Beacon powerselect', 'minecraft:block.beacon.power_select'),
  sculk_catalyst_break('Sculkcatalyst break', 'minecraft:block.sculk_catalyst.break'),
  ladder_hit('Ladder hit', 'minecraft:block.ladder.hit'),
  anvil_step('Anvil step', 'minecraft:block.anvil.step'),
  pointed_dripstone_break('Pointeddripstone break', 'minecraft:block.pointed_dripstone.break'),
  wart_block_fall('Wartblock fall', 'minecraft:block.wart_block.fall'),
  nether_wood_pressure_plate_click_on('Netherwoodpressureplate clickon',
      'minecraft:block.nether_wood_pressure_plate.click_on'),
  suspicious_gravel_fall('Suspiciousgravel fall', 'minecraft:block.suspicious_gravel.fall'),
  trial_spawner_ambient_ominous('Trialspawner ambientominous',
      'minecraft:block.trial_spawner.ambient_ominous'),
  snow_hit('Snow hit', 'minecraft:block.snow.hit'),
  amethyst_block_hit('Amethystblock hit', 'minecraft:block.amethyst_block.hit'),
  mangrove_roots_step('Mangroveroots step', 'minecraft:block.mangrove_roots.step'),
  tuff_bricks_hit('Tuffbricks hit', 'minecraft:block.tuff_bricks.hit'),
  comparator_click('Comparator click', 'minecraft:block.comparator.click'),
  decorated_pot_place('Decoratedpot place', 'minecraft:block.decorated_pot.place'),
  roots_place('Roots place', 'minecraft:block.roots.place'),
  bamboo_wood_hanging_sign_fall('Bamboowoodhangingsign fall',
      'minecraft:block.bamboo_wood_hanging_sign.fall'),
  soul_sand_fall('Soulsand fall', 'minecraft:block.soul_sand.fall'),
  metal_pressure_plate_click_off('Metalpressureplate clickoff',
      'minecraft:block.metal_pressure_plate.click_off'),
  sculk_shrieker_step('Sculkshrieker step', 'minecraft:block.sculk_shrieker.step'),
  tripwire_attach('Tripwire attach', 'minecraft:block.tripwire.attach'),
  mud_bricks_hit('Mudbricks hit', 'minecraft:block.mud_bricks.hit'),
  bamboo_wood_hit('Bamboowood hit', 'minecraft:block.bamboo_wood.hit'),
  nether_wood_hanging_sign_fall('Netherwoodhangingsign fall',
      'minecraft:block.nether_wood_hanging_sign.fall'),
  sweet_berry_bush_pick_berries('Sweetberrybush pickberries',
      'minecraft:block.sweet_berry_bush.pick_berries'),
  ladder_fall('Ladder fall', 'minecraft:block.ladder.fall'),
  spore_blossom_fall('Sporeblossom fall', 'minecraft:block.spore_blossom.fall'),
  flowering_azalea_fall('Floweringazalea fall', 'minecraft:block.flowering_azalea.fall'),
  note_block_creeper('Noteblock creeper', 'minecraft:block.note_block.imitate.creeper'),
  soul_soil_fall('Soulsoil fall', 'minecraft:block.soul_soil.fall'),
  beacon_deactivate('Beacon deactivate', 'minecraft:block.beacon.deactivate'),
  conduit_ambient('Conduit ambient', 'minecraft:block.conduit.ambient'),
  cactus_flower_break('Cactusflower break', 'minecraft:block.cactus_flower.break'),
  cherry_wood_button_click_off('Cherrywoodbutton clickoff',
      'minecraft:block.cherry_wood_button.click_off'),
  lodestone_place('Lodestone place', 'minecraft:block.lodestone.place'),
  gilded_blackstone_fall('Gildedblackstone fall', 'minecraft:block.gilded_blackstone.fall'),
  small_dripleaf_step('Smalldripleaf step', 'minecraft:block.small_dripleaf.step'),
  roots_step('Roots step', 'minecraft:block.roots.step'),
  tuff_place('Tuff place', 'minecraft:block.tuff.place'),
  candle_extinguish('Candle extinguish', 'minecraft:block.candle.extinguish'),
  vault_break('Vault break', 'minecraft:block.vault.break'),
  dried_ghast_ambient_water('Driedghast ambientwater', 'minecraft:block.dried_ghast.ambient_water'),
  spore_blossom_place('Sporeblossom place', 'minecraft:block.spore_blossom.place'),
  firefly_bush_idle('Fireflybush idle', 'minecraft:block.firefly_bush.idle'),
  note_block_xylophone('Noteblock xylophone', 'minecraft:block.note_block.xylophone'),
  piston_contract('Piston contract', 'minecraft:block.piston.contract'),
  sculk_shrieker_hit('Sculkshrieker hit', 'minecraft:block.sculk_shrieker.hit'),
  hanging_roots_break('Hangingroots break', 'minecraft:block.hanging_roots.break'),
  azalea_leaves_fall('Azalealeaves fall', 'minecraft:block.azalea_leaves.fall'),
  sniffer_egg_hatch('Snifferegg hatch', 'minecraft:block.sniffer_egg.hatch'),
  grass_hit('Grass hit', 'minecraft:block.grass.hit'),
  stem_hit('Stem hit', 'minecraft:block.stem.hit'),
  creaking_heart_fall('Creakingheart fall', 'minecraft:block.creaking_heart.fall'),
  gravel_hit('Gravel hit', 'minecraft:block.gravel.hit'),
  lantern_fall('Lantern fall', 'minecraft:block.lantern.fall'),
  medium_amethyst_bud_break('Mediumamethystbud break', 'minecraft:block.medium_amethyst_bud.break'),
  mud_bricks_step('Mudbricks step', 'minecraft:block.mud_bricks.step'),
  note_block_pling('Noteblock pling', 'minecraft:block.note_block.pling'),
  cobweb_hit('Cobweb hit', 'minecraft:block.cobweb.hit'),
  iron_break('Iron break', 'minecraft:block.iron.break'),
  netherite_block_hit('Netheriteblock hit', 'minecraft:block.netherite_block.hit'),
  nether_gold_ore_step('Nethergoldore step', 'minecraft:block.nether_gold_ore.step'),
  trial_spawner_place('Trialspawner place', 'minecraft:block.trial_spawner.place'),
  sculk_catalyst_step('Sculkcatalyst step', 'minecraft:block.sculk_catalyst.step'),
  stone_break('Stone break', 'minecraft:block.stone.break'),
  bamboo_wood_trapdoor_close('Bamboowoodtrapdoor close',
      'minecraft:block.bamboo_wood_trapdoor.close'),
  bamboo_place('Bamboo place', 'minecraft:block.bamboo.place'),
  portal_travel('Portal travel', 'minecraft:block.portal.travel'),
  metal_place('Metal place', 'minecraft:block.metal.place'),
  chiseled_bookshelf_break('Chiseledbookshelf break', 'minecraft:block.chiseled_bookshelf.break'),
  wood_step('Wood step', 'minecraft:block.wood.step'),
  stone_pressure_plate_click_off('Stonepressureplate clickoff',
      'minecraft:block.stone_pressure_plate.click_off'),
  stem_step('Stem step', 'minecraft:block.stem.step'),
  grass_step('Grass step', 'minecraft:block.grass.step'),
  cherry_wood_hanging_sign_fall('Cherrywoodhangingsign fall',
      'minecraft:block.cherry_wood_hanging_sign.fall'),
  bamboo_sapling_break('Bamboosapling break', 'minecraft:block.bamboo_sapling.break'),
  smoker_smoke('Smoker smoke', 'minecraft:block.smoker.smoke'),
  polished_tuff_place('Polishedtuff place', 'minecraft:block.polished_tuff.place'),
  bubble_column_upwards_inside('Bubblecolumn upwardsinside',
      'minecraft:block.bubble_column.upwards_inside'),
  gravel_break('Gravel break', 'minecraft:block.gravel.break'),
  heavy_core_hit('Heavycore hit', 'minecraft:block.heavy_core.hit'),
  redstone_torch_burnout('Redstonetorch burnout', 'minecraft:block.redstone_torch.burnout'),
  copper_door_close('Copperdoor close', 'minecraft:block.copper_door.close'),
  large_amethyst_bud_place('Largeamethystbud place', 'minecraft:block.large_amethyst_bud.place'),
  nether_wart_break('Netherwart break', 'minecraft:block.nether_wart.break'),
  nether_wood_hanging_sign_place('Netherwoodhangingsign place',
      'minecraft:block.nether_wood_hanging_sign.place'),
  enchantment_table_use('Enchantmenttable use', 'minecraft:block.enchantment_table.use'),
  iron_trapdoor_close('Irontrapdoor close', 'minecraft:block.iron_trapdoor.close'),
  trial_spawner_eject_item('Trialspawner ejectitem', 'minecraft:block.trial_spawner.eject_item'),
  hanging_roots_hit('Hangingroots hit', 'minecraft:block.hanging_roots.hit'),
  trial_spawner_spawn_item_begin('Trialspawner spawnitembegin',
      'minecraft:block.trial_spawner.spawn_item_begin'),
  cherry_wood_door_close('Cherrywooddoor close', 'minecraft:block.cherry_wood_door.close'),
  wool_hit('Wool hit', 'minecraft:block.wool.hit'),
  stone_fall('Stone fall', 'minecraft:block.stone.fall'),
  leaf_litter_step('Leaflitter step', 'minecraft:block.leaf_litter.step'),
  cobweb_break('Cobweb break', 'minecraft:block.cobweb.break'),
  weeping_vines_hit('Weepingvines hit', 'minecraft:block.weeping_vines.hit'),
  scaffolding_break('Scaffolding break', 'minecraft:block.scaffolding.break'),
  tripwire_click_on('Tripwire clickon', 'minecraft:block.tripwire.click_on'),
  nether_bricks_fall('Netherbricks fall', 'minecraft:block.nether_bricks.fall'),
  big_dripleaf_hit('Bigdripleaf hit', 'minecraft:block.big_dripleaf.hit'),
  rooted_dirt_break('Rooteddirt break', 'minecraft:block.rooted_dirt.break'),
  copper_step('Copper step', 'minecraft:block.copper.step'),
  resin_place('Resin place', 'minecraft:block.resin.place'),
  dripstone_block_break('Dripstoneblock break', 'minecraft:block.dripstone_block.break'),
  sweet_berry_bush_place('Sweetberrybush place', 'minecraft:block.sweet_berry_bush.place'),
  wet_grass_fall('Wetgrass fall', 'minecraft:block.wet_grass.fall'),
  note_block_cow_bell('Noteblock cowbell', 'minecraft:block.note_block.cow_bell'),
  lodestone_step('Lodestone step', 'minecraft:block.lodestone.step'),
  bamboo_sapling_hit('Bamboosapling hit', 'minecraft:block.bamboo_sapling.hit'),
  wart_block_place('Wartblock place', 'minecraft:block.wart_block.place'),
  crafter_craft('Crafter craft', 'minecraft:block.crafter.craft'),
  sniffer_egg_plop('Snifferegg plop', 'minecraft:block.sniffer_egg.plop'),
  cherry_wood_trapdoor_close('Cherrywoodtrapdoor close',
      'minecraft:block.cherry_wood_trapdoor.close'),
  azalea_break('Azalea break', 'minecraft:block.azalea.break'),
  dry_grass_ambient('Drygrass ambient', 'minecraft:block.dry_grass.ambient'),
  big_dripleaf_fall('Bigdripleaf fall', 'minecraft:block.big_dripleaf.fall'),
  chest_close('Chest close', 'minecraft:block.chest.close'),
  decorated_pot_insert('Decoratedpot insert', 'minecraft:block.decorated_pot.insert'),
  cherry_wood_fence_gate_open('Cherrywoodfencegate open',
      'minecraft:block.cherry_wood_fence_gate.open'),
  eyeblossom_close_long('Eyeblossom closelong', 'minecraft:block.eyeblossom.close_long'),
  resin_bricks_place('Resinbricks place', 'minecraft:block.resin_bricks.place'),
  small_dripleaf_hit('Smalldripleaf hit', 'minecraft:block.small_dripleaf.hit'),
  nether_wood_trapdoor_open('Netherwoodtrapdoor open', 'minecraft:block.nether_wood_trapdoor.open'),
  soul_soil_break('Soulsoil break', 'minecraft:block.soul_soil.break'),
  mud_step('Mud step', 'minecraft:block.mud.step'),
  fungus_step('Fungus step', 'minecraft:block.fungus.step'),
  amethyst_cluster_fall('Amethystcluster fall', 'minecraft:block.amethyst_cluster.fall'),
  sponge_place('Sponge place', 'minecraft:block.sponge.place'),
  frogspawn_place('Frogspawn place', 'minecraft:block.frogspawn.place'),
  vault_open_shutter('Vault openshutter', 'minecraft:block.vault.open_shutter'),
  dried_ghast_place_in_water('Driedghast placeinwater',
      'minecraft:block.dried_ghast.place_in_water'),
  mud_place('Mud place', 'minecraft:block.mud.place'),
  wool_step('Wool step', 'minecraft:block.wool.step'),
  nether_sprouts_break('Nethersprouts break', 'minecraft:block.nether_sprouts.break'),
  honey_block_break('Honeyblock break', 'minecraft:block.honey_block.break'),
  snow_break('Snow break', 'minecraft:block.snow.break'),
  iron_door_open('Irondoor open', 'minecraft:block.iron_door.open'),
  stone_button_click_on('Stonebutton clickon', 'minecraft:block.stone_button.click_on'),
  nether_ore_fall('Netherore fall', 'minecraft:block.nether_ore.fall'),
  bone_block_fall('Boneblock fall', 'minecraft:block.bone_block.fall'),
  suspicious_gravel_hit('Suspiciousgravel hit', 'minecraft:block.suspicious_gravel.hit'),
  candle_break('Candle break', 'minecraft:block.candle.break'),
  cherry_wood_hanging_sign_place('Cherrywoodhangingsign place',
      'minecraft:block.cherry_wood_hanging_sign.place'),
  cherry_wood_button_click_on('Cherrywoodbutton clickon',
      'minecraft:block.cherry_wood_button.click_on'),
  creaking_heart_place('Creakingheart place', 'minecraft:block.creaking_heart.place'),
  deadbush_idle('Deadbush idle', 'minecraft:block.deadbush.idle'),
  heavy_core_step('Heavycore step', 'minecraft:block.heavy_core.step'),
  cherry_sapling_break('Cherrysapling break', 'minecraft:block.cherry_sapling.break'),
  sand_break('Sand break', 'minecraft:block.sand.break'),
  nether_gold_ore_place('Nethergoldore place', 'minecraft:block.nether_gold_ore.place'),
  bamboo_wood_pressure_plate_click_on('Bamboowoodpressureplate clickon',
      'minecraft:block.bamboo_wood_pressure_plate.click_on'),
  moss_carpet_fall('Mosscarpet fall', 'minecraft:block.moss_carpet.fall'),
  nether_wood_fence_gate_close('Netherwoodfencegate close',
      'minecraft:block.nether_wood_fence_gate.close'),
  shroomlight_place('Shroomlight place', 'minecraft:block.shroomlight.place'),
  bamboo_wood_fence_gate_close('Bamboowoodfencegate close',
      'minecraft:block.bamboo_wood_fence_gate.close'),
  copper_bulb_turn_off('Copperbulb turnoff', 'minecraft:block.copper_bulb.turn_off'),
  note_block_chime('Noteblock chime', 'minecraft:block.note_block.chime'),
  composter_fill('Composter fill', 'minecraft:block.composter.fill'),
  nether_ore_break('Netherore break', 'minecraft:block.nether_ore.break'),
  sculk_vein_step('Sculkvein step', 'minecraft:block.sculk_vein.step'),
  weeping_vines_place('Weepingvines place', 'minecraft:block.weeping_vines.place'),
  azalea_fall('Azalea fall', 'minecraft:block.azalea.fall'),
  mangrove_roots_hit('Mangroveroots hit', 'minecraft:block.mangrove_roots.hit'),
  cherry_sapling_step('Cherrysapling step', 'minecraft:block.cherry_sapling.step'),
  nether_ore_hit('Netherore hit', 'minecraft:block.nether_ore.hit'),
  hanging_roots_fall('Hangingroots fall', 'minecraft:block.hanging_roots.fall'),
  rooted_dirt_step('Rooteddirt step', 'minecraft:block.rooted_dirt.step'),
  azalea_leaves_hit('Azalealeaves hit', 'minecraft:block.azalea_leaves.hit'),
  soul_sand_place('Soulsand place', 'minecraft:block.soul_sand.place'),
  wooden_pressure_plate_click_on('Woodenpressureplate clickon',
      'minecraft:block.wooden_pressure_plate.click_on'),
  sculk_step('Sculk step', 'minecraft:block.sculk.step'),
  slime_block_place('Slimeblock place', 'minecraft:block.slime_block.place'),
  lantern_hit('Lantern hit', 'minecraft:block.lantern.hit'),
  copper_bulb_step('Copperbulb step', 'minecraft:block.copper_bulb.step'),
  cave_vines_hit('Cavevines hit', 'minecraft:block.cave_vines.hit'),
  pointed_dripstone_fall('Pointeddripstone fall', 'minecraft:block.pointed_dripstone.fall'),
  deepslate_fall('Deepslate fall', 'minecraft:block.deepslate.fall'),
  cave_vines_step('Cavevines step', 'minecraft:block.cave_vines.step'),
  cobweb_fall('Cobweb fall', 'minecraft:block.cobweb.fall'),
  copper_bulb_break('Copperbulb break', 'minecraft:block.copper_bulb.break'),
  crafter_fail('Crafter fail', 'minecraft:block.crafter.fail'),
  sculk_sensor_break('Sculksensor break', 'minecraft:block.sculk_sensor.break'),
  moss_carpet_hit('Mosscarpet hit', 'minecraft:block.moss_carpet.hit'),
  trial_spawner_ambient('Trialspawner ambient', 'minecraft:block.trial_spawner.ambient'),
  note_block_flute('Noteblock flute', 'minecraft:block.note_block.flute'),
  amethyst_cluster_place('Amethystcluster place', 'minecraft:block.amethyst_cluster.place'),
  sculk_sensor_hit('Sculksensor hit', 'minecraft:block.sculk_sensor.hit'),
  moss_fall('Moss fall', 'minecraft:block.moss.fall'),
  muddy_mangrove_roots_break('Muddymangroveroots break',
      'minecraft:block.muddy_mangrove_roots.break'),
  sculk_catalyst_bloom('Sculkcatalyst bloom', 'minecraft:block.sculk_catalyst.bloom'),
  pumpkin_carve('Pumpkin carve', 'minecraft:block.pumpkin.carve'),
  anvil_destroy('Anvil destroy', 'minecraft:block.anvil.destroy'),
  dried_ghast_break('Driedghast break', 'minecraft:block.dried_ghast.break'),
  wet_grass_break('Wetgrass break', 'minecraft:block.wet_grass.break'),
  iron_trapdoor_open('Irontrapdoor open', 'minecraft:block.iron_trapdoor.open'),
  iron_door_close('Irondoor close', 'minecraft:block.iron_door.close'),
  note_block_hat('Noteblock hat', 'minecraft:block.note_block.hat'),
  polished_deepslate_place('Polisheddeepslate place', 'minecraft:block.polished_deepslate.place'),
  rooted_dirt_hit('Rooteddirt hit', 'minecraft:block.rooted_dirt.hit'),
  wart_block_step('Wartblock step', 'minecraft:block.wart_block.step'),
  deepslate_bricks_break('Deepslatebricks break', 'minecraft:block.deepslate_bricks.break'),
  chorus_flower_death('Chorusflower death', 'minecraft:block.chorus_flower.death'),
  growing_plant_crop('Growingplant crop', 'minecraft:block.growing_plant.crop'),
  deepslate_place('Deepslate place', 'minecraft:block.deepslate.place'),
  eyeblossom_close('Eyeblossom close', 'minecraft:block.eyeblossom.close'),
  suspicious_gravel_step('Suspiciousgravel step', 'minecraft:block.suspicious_gravel.step'),
  spawner_fall('Spawner fall', 'minecraft:block.spawner.fall'),
  copper_place('Copper place', 'minecraft:block.copper.place'),
  copper_bulb_hit('Copperbulb hit', 'minecraft:block.copper_bulb.hit'),
  note_block_skeleton('Noteblock skeleton', 'minecraft:block.note_block.imitate.skeleton'),
  bamboo_wood_hanging_sign_step('Bamboowoodhangingsign step',
      'minecraft:block.bamboo_wood_hanging_sign.step'),
  soul_sand_step('Soulsand step', 'minecraft:block.soul_sand.step'),
  decorated_pot_fall('Decoratedpot fall', 'minecraft:block.decorated_pot.fall'),
  gilded_blackstone_break('Gildedblackstone break', 'minecraft:block.gilded_blackstone.break'),
  hanging_sign_break('Hangingsign break', 'minecraft:block.hanging_sign.break'),
  pink_petals_hit('Pinkpetals hit', 'minecraft:block.pink_petals.hit'),
  nether_wood_hanging_sign_step('Netherwoodhangingsign step',
      'minecraft:block.nether_wood_hanging_sign.step'),
  ladder_step('Ladder step', 'minecraft:block.ladder.step'),
  spore_blossom_step('Sporeblossom step', 'minecraft:block.spore_blossom.step'),
  froglight_fall('Froglight fall', 'minecraft:block.froglight.fall'),
  azalea_leaves_place('Azalealeaves place', 'minecraft:block.azalea_leaves.place'),
  small_amethyst_bud_place('Smallamethystbud place', 'minecraft:block.small_amethyst_bud.place'),
  flowering_azalea_step('Floweringazalea step', 'minecraft:block.flowering_azalea.step'),
  copper_grate_place('Coppergrate place', 'minecraft:block.copper_grate.place'),
  netherite_block_place('Netheriteblock place', 'minecraft:block.netherite_block.place'),
  tuff_hit('Tuff hit', 'minecraft:block.tuff.hit'),
  powder_snow_hit('Powdersnow hit', 'minecraft:block.powder_snow.hit'),
  cherry_sapling_hit('Cherrysapling hit', 'minecraft:block.cherry_sapling.hit'),
  soul_soil_step('Soulsoil step', 'minecraft:block.soul_soil.step'),
  suspicious_sand_fall('Suspicioussand fall', 'minecraft:block.suspicious_sand.fall'),
  decorated_pot_break('Decoratedpot break', 'minecraft:block.decorated_pot.break'),
  roots_break('Roots break', 'minecraft:block.roots.break'),
  gilded_blackstone_step('Gildedblackstone step', 'minecraft:block.gilded_blackstone.step'),
  sand_idle('Sand idle', 'minecraft:block.sand.idle'),
  composter_fill_success('Composter fillsuccess', 'minecraft:block.composter.fill_success'),
  note_block_banjo('Noteblock banjo', 'minecraft:block.note_block.banjo'),
  bamboo_fall('Bamboo fall', 'minecraft:block.bamboo.fall'),
  basalt_fall('Basalt fall', 'minecraft:block.basalt.fall'),
  sculk_charge('Sculk charge', 'minecraft:block.sculk.charge'),
  muddy_mangrove_roots_fall('Muddymangroveroots fall', 'minecraft:block.muddy_mangrove_roots.fall'),
  azalea_leaves_step('Azalealeaves step', 'minecraft:block.azalea_leaves.step'),
  dripstone_block_fall('Dripstoneblock fall', 'minecraft:block.dripstone_block.fall'),
  small_dripleaf_place('Smalldripleaf place', 'minecraft:block.small_dripleaf.place'),
  creaking_heart_step('Creakingheart step', 'minecraft:block.creaking_heart.step'),
  lily_pad_place('Lilypad place', 'minecraft:block.lily_pad.place'),
  lodestone_break('Lodestone break', 'minecraft:block.lodestone.break'),
  pink_petals_fall('Pinkpetals fall', 'minecraft:block.pink_petals.fall'),
  mangrove_roots_break('Mangroveroots break', 'minecraft:block.mangrove_roots.break'),
  cherry_wood_hanging_sign_hit('Cherrywoodhangingsign hit',
      'minecraft:block.cherry_wood_hanging_sign.hit'),
  nether_bricks_place('Netherbricks place', 'minecraft:block.nether_bricks.place'),
  lantern_step('Lantern step', 'minecraft:block.lantern.step'),
  wood_hit('Wood hit', 'minecraft:block.wood.hit'),
  chest_locked('Chest locked', 'minecraft:block.chest.locked'),
  tuff_break('Tuff break', 'minecraft:block.tuff.break'),
  shroomlight_fall('Shroomlight fall', 'minecraft:block.shroomlight.fall'),
  spore_blossom_break('Sporeblossom break', 'minecraft:block.spore_blossom.break'),
  vault_reject_rewarded_player('Vault rejectrewardedplayer',
      'minecraft:block.vault.reject_rewarded_player'),
  pink_petals_break('Pinkpetals break', 'minecraft:block.pink_petals.break'),
  leaf_litter_place('Leaflitter place', 'minecraft:block.leaf_litter.place'),
  stem_place('Stem place', 'minecraft:block.stem.place'),
  cherry_wood_break('Cherrywood break', 'minecraft:block.cherry_wood.break'),
  nether_sprouts_fall('Nethersprouts fall', 'minecraft:block.nether_sprouts.fall'),
  pointed_dripstone_drip_lava('Pointeddripstone driplava',
      'minecraft:block.pointed_dripstone.drip_lava'),
  vault_insert_item_fail('Vault insertitemfail', 'minecraft:block.vault.insert_item_fail'),
  trial_spawner_spawn_item('Trialspawner spawnitem', 'minecraft:block.trial_spawner.spawn_item'),
  cherry_wood_hanging_sign_step('Cherrywoodhangingsign step',
      'minecraft:block.cherry_wood_hanging_sign.step'),
  trial_spawner_break('Trialspawner break', 'minecraft:block.trial_spawner.break'),
  lantern_place('Lantern place', 'minecraft:block.lantern.place'),
  chain_place('Chain place', 'minecraft:block.chain.place'),
  soul_sand_hit('Soulsand hit', 'minecraft:block.soul_sand.hit'),
  sculk_vein_hit('Sculkvein hit', 'minecraft:block.sculk_vein.hit'),
  amethyst_block_fall('Amethystblock fall', 'minecraft:block.amethyst_block.fall'),
  wood_place('Wood place', 'minecraft:block.wood.place'),
  wooden_door_open('Woodendoor open', 'minecraft:block.wooden_door.open'),
  chain_hit('Chain hit', 'minecraft:block.chain.hit'),
  deepslate_tiles_place('Deepslatetiles place', 'minecraft:block.deepslate_tiles.place'),
  bamboo_break('Bamboo break', 'minecraft:block.bamboo.break'),
  respawn_anchor_charge('Respawnanchor charge', 'minecraft:block.respawn_anchor.charge'),
  note_block_harp('Noteblock harp', 'minecraft:block.note_block.harp'),
  metal_break('Metal break', 'minecraft:block.metal.break'),
  copper_trapdoor_open('Coppertrapdoor open', 'minecraft:block.copper_trapdoor.open'),
  ancient_debris_fall('Ancientdebris fall', 'minecraft:block.ancient_debris.fall'),
  leaf_litter_hit('Leaflitter hit', 'minecraft:block.leaf_litter.hit'),
  stone_step('Stone step', 'minecraft:block.stone.step'),
  polished_tuff_break('Polishedtuff break', 'minecraft:block.polished_tuff.break'),
  calcite_place('Calcite place', 'minecraft:block.calcite.place'),
  hanging_sign_waxed_interact_fail('Hangingsign waxedinteractfail',
      'minecraft:block.hanging_sign.waxed_interact_fail'),
  calcite_fall('Calcite fall', 'minecraft:block.calcite.fall'),
  dispenser_dispense('Dispenser dispense', 'minecraft:block.dispenser.dispense'),
  nether_bricks_step('Netherbricks step', 'minecraft:block.nether_bricks.step'),
  trial_spawner_open_shutter('Trialspawner openshutter',
      'minecraft:block.trial_spawner.open_shutter'),
  beacon_activate('Beacon activate', 'minecraft:block.beacon.activate'),
  bone_block_place('Boneblock place', 'minecraft:block.bone_block.place'),
  large_amethyst_bud_break('Largeamethystbud break', 'minecraft:block.large_amethyst_bud.break'),
  wet_grass_step('Wetgrass step', 'minecraft:block.wet_grass.step'),
  nether_wood_hanging_sign_break('Netherwoodhangingsign break',
      'minecraft:block.nether_wood_hanging_sign.break'),
  portal_ambient('Portal ambient', 'minecraft:block.portal.ambient'),
  netherrack_break('Netherrack break', 'minecraft:block.netherrack.break'),
  note_block_bass('Noteblock bass', 'minecraft:block.note_block.bass'),
  wool_place('Wool place', 'minecraft:block.wool.place'),
  nether_wood_hit('Netherwood hit', 'minecraft:block.nether_wood.hit'),
  polished_deepslate_hit('Polisheddeepslate hit', 'minecraft:block.polished_deepslate.hit'),
  nether_wood_fall('Netherwood fall', 'minecraft:block.nether_wood.fall'),
  fire_extinguish('Fire extinguish', 'minecraft:block.fire.extinguish'),
  stone_hit('Stone hit', 'minecraft:block.stone.hit'),
  sculk_break('Sculk break', 'minecraft:block.sculk.break'),
  big_dripleaf_step('Bigdripleaf step', 'minecraft:block.big_dripleaf.step'),
  cherry_leaves_hit('Cherryleaves hit', 'minecraft:block.cherry_leaves.hit'),
  frogspawn_hit('Frogspawn hit', 'minecraft:block.frogspawn.hit'),
  smithing_table_use('Smithingtable use', 'minecraft:block.smithing_table.use'),
  resin_break('Resin break', 'minecraft:block.resin.break'),
  pointed_dripstone_land('Pointeddripstone land', 'minecraft:block.pointed_dripstone.land'),
  sweet_berry_bush_break('Sweetberrybush break', 'minecraft:block.sweet_berry_bush.break'),
  amethyst_cluster_step('Amethystcluster step', 'minecraft:block.amethyst_cluster.step'),
  wet_sponge_dries('Wetsponge dries', 'minecraft:block.wet_sponge.dries'),
  amethyst_block_chime('Amethystblock chime', 'minecraft:block.amethyst_block.chime'),
  bubble_column_whirlpool_ambient('Bubblecolumn whirlpoolambient',
      'minecraft:block.bubble_column.whirlpool_ambient'),
  crop_break('Crop break', 'minecraft:block.crop.break'),
  gilded_blackstone_hit('Gildedblackstone hit', 'minecraft:block.gilded_blackstone.hit'),
  big_dripleaf_place('Bigdripleaf place', 'minecraft:block.big_dripleaf.place'),
  dried_ghast_fall('Driedghast fall', 'minecraft:block.dried_ghast.fall'),
  nether_ore_step('Netherore step', 'minecraft:block.nether_ore.step'),
  big_dripleaf_tilt_down('Bigdripleaf tiltdown', 'minecraft:block.big_dripleaf.tilt_down'),
  mud_hit('Mud hit', 'minecraft:block.mud.hit'),
  bone_block_step('Boneblock step', 'minecraft:block.bone_block.step');

  final String name;
  final String key;

  const BlockSound(this.name, this.key);

}