/// Generated class for the sound events. Don't edit this file manually
enum EntitySound {

  genericEat('Generic eat', 'minecraft:entity.generic.eat'),
  happyGhastRiding('Happy Ghast riding', 'minecraft:entity.happy_ghast.riding'),
  smallSulfurCubeJump('Small Sulfur Cube jump', 'minecraft:entity.small_sulfur_cube.jump'),
  ironGolemAttack('Iron Golem attack', 'minecraft:entity.iron_golem.attack'),
  pandaAggressiveAmbient('Panda aggressive Ambient', 'minecraft:entity.panda.aggressive_ambient'),
  shulkerDeath('Shulker death', 'minecraft:entity.shulker.death'),
  snowGolemShoot('Snow Golem shoot', 'minecraft:entity.snow_golem.shoot'),
  guardianHurtLand('Guardian hurt Land', 'minecraft:entity.guardian.hurt_land'),
  drownedDeath('Drowned death', 'minecraft:entity.drowned.death'),
  chickenDeath('Chicken death', 'minecraft:entity.chicken.death'),
  evokerDeath('Evoker death', 'minecraft:entity.evoker.death'),
  donkeyAngry('Donkey angry', 'minecraft:entity.donkey.angry'),
  mooshroomEat('Mooshroom eat', 'minecraft:entity.mooshroom.eat'),
  turtleEggHatch('Turtle egg Hatch', 'minecraft:entity.turtle.egg_hatch'),
  playerKnockback('Player knockback', 'minecraft:entity.player.attack.knockback'),
  pigBigHurt('Pig Big hurt', 'minecraft:entity.pig_big.hurt'),
  llamaSpit('Llama spit', 'minecraft:entity.llama.spit'),
  glowItemFrameRotateItem('Glow Item Frame rotate Item',
      'minecraft:entity.glow_item_frame.rotate_item'),
  parrotZoglin('Parrot zoglin', 'minecraft:entity.parrot.imitate.zoglin'),
  frogLaySpawn('Frog lay Spawn', 'minecraft:entity.frog.lay_spawn'),
  horseAngry('Horse angry', 'minecraft:entity.horse.angry'),
  endermanHurt('Enderman hurt', 'minecraft:entity.enderman.hurt'),
  turtleSwim('Turtle swim', 'minecraft:entity.turtle.swim'),
  parchedDeath('Parched death', 'minecraft:entity.parched.death'),
  babyHorseAngry('Baby Horse angry', 'minecraft:entity.baby_horse.angry'),
  copperGolemOxidizedStep('Copper Golem Oxidized step',
      'minecraft:entity.copper_golem_oxidized.step'),
  evokerHurt('Evoker hurt', 'minecraft:entity.evoker.hurt'),
  fishingBobberRetrieve('Fishing Bobber retrieve', 'minecraft:entity.fishing_bobber.retrieve'),
  endermanScream('Enderman scream', 'minecraft:entity.enderman.scream'),
  beeSting('Bee sting', 'minecraft:entity.bee.sting'),
  witherHurt('Wither hurt', 'minecraft:entity.wither.hurt'),
  lightningBoltThunder('Lightning Bolt thunder', 'minecraft:entity.lightning_bolt.thunder'),
  strayAmbient('Stray ambient', 'minecraft:entity.stray.ambient'),
  foxDeath('Fox death', 'minecraft:entity.fox.death'),
  beeLoop('Bee loop', 'minecraft:entity.bee.loop'),
  playerHurtDrown('Player hurt Drown', 'minecraft:entity.player.hurt_drown'),
  babyCatDeath('Baby Cat death', 'minecraft:entity.baby_cat.death'),
  pandaBite('Panda bite', 'minecraft:entity.panda.bite'),
  armadilloScuteDrop('Armadillo scute Drop', 'minecraft:entity.armadillo.scute_drop'),
  zombieDeath('Zombie death', 'minecraft:entity.zombie.death'),
  playerBigFall('Player big Fall', 'minecraft:entity.player.big_fall'),
  spiderHurt('Spider hurt', 'minecraft:entity.spider.hurt'),
  skeletonHorseGallopWater('Skeleton Horse gallop Water',
      'minecraft:entity.skeleton_horse.gallop_water'),
  drownedAmbientWater('Drowned ambient Water', 'minecraft:entity.drowned.ambient_water'),
  glowSquidHurt('Glow Squid hurt', 'minecraft:entity.glow_squid.hurt'),
  vexCharge('Vex charge', 'minecraft:entity.vex.charge'),
  striderRetreat('Strider retreat', 'minecraft:entity.strider.retreat'),
  ghastShoot('Ghast shoot', 'minecraft:entity.ghast.shoot'),
  slimeDeathSmall('Slime death Small', 'minecraft:entity.slime.death_small'),
  dolphinPlay('Dolphin play', 'minecraft:entity.dolphin.play'),
  catRoyalDeath('Cat Royal death', 'minecraft:entity.cat_royal.death'),
  armorStandBreak('Armor Stand break', 'minecraft:entity.armor_stand.break'),
  frogDeath('Frog death', 'minecraft:entity.frog.death'),
  snifferEat('Sniffer eat', 'minecraft:entity.sniffer.eat'),
  endermanTeleport('Enderman teleport', 'minecraft:entity.enderman.teleport'),
  shulkerBulletHurt('Shulker Bullet hurt', 'minecraft:entity.shulker_bullet.hurt'),
  piglinAngry('Piglin angry', 'minecraft:entity.piglin.angry'),
  parrotZombie('Parrot zombie', 'minecraft:entity.parrot.imitate.zombie'),
  babyNautilusHurt('Baby Nautilus hurt', 'minecraft:entity.baby_nautilus.hurt'),
  dolphinAttack('Dolphin attack', 'minecraft:entity.dolphin.attack'),
  ironGolemRepair('Iron Golem repair', 'minecraft:entity.iron_golem.repair'),
  pillagerAmbient('Pillager ambient', 'minecraft:entity.pillager.ambient'),
  sulfurCubePush('Sulfur Cube push', 'minecraft:entity.sulfur_cube.high_resistance.push'),
  wardenListeningAngry('Warden listening Angry', 'minecraft:entity.warden.listening_angry'),
  wardenNearbyClosest('Warden nearby Closest', 'minecraft:entity.warden.nearby_closest'),
  creakingTwitch('Creaking twitch', 'minecraft:entity.creaking.twitch'),
  wolfPuglinPant('Wolf Puglin pant', 'minecraft:entity.wolf_puglin.pant'),
  camelDashReady('Camel dash Ready', 'minecraft:entity.camel.dash_ready'),
  dolphinSwim('Dolphin swim', 'minecraft:entity.dolphin.swim'),
  pandaEat('Panda eat', 'minecraft:entity.panda.eat'),
  llamaHurt('Llama hurt', 'minecraft:entity.llama.hurt'),
  creakingDeath('Creaking death', 'minecraft:entity.creaking.death'),
  wolfAngryHurt('Wolf Angry hurt', 'minecraft:entity.wolf_angry.hurt'),
  dolphinEat('Dolphin eat', 'minecraft:entity.dolphin.eat'),
  parrotBlaze('Parrot blaze', 'minecraft:entity.parrot.imitate.blaze'),
  spiderDeath('Spider death', 'minecraft:entity.spider.death'),
  sulfurCubeHit('Sulfur Cube hit', 'minecraft:entity.sulfur_cube.sticky.hit'),
  creakingDeactivate('Creaking deactivate', 'minecraft:entity.creaking.deactivate'),
  allayAmbientWithItem('Allay ambient With Item', 'minecraft:entity.allay.ambient_with_item'),
  axolotlHurt('Axolotl hurt', 'minecraft:entity.axolotl.hurt'),
  silverfishAmbient('Silverfish ambient', 'minecraft:entity.silverfish.ambient'),
  witherAmbient('Wither ambient', 'minecraft:entity.wither.ambient'),
  skeletonStep('Skeleton step', 'minecraft:entity.skeleton.step'),
  breezeShoot('Breeze shoot', 'minecraft:entity.breeze.shoot'),
  wardenDeath('Warden death', 'minecraft:entity.warden.death'),
  piglinBruteDeath('Piglin Brute death', 'minecraft:entity.piglin_brute.death'),
  slimeJumpSmall('Slime jump Small', 'minecraft:entity.slime.jump_small'),
  enderDragonHurt('Ender Dragon hurt', 'minecraft:entity.ender_dragon.hurt'),
  parrotCreeper('Parrot creeper', 'minecraft:entity.parrot.imitate.creeper'),
  camelAmbient('Camel ambient', 'minecraft:entity.camel.ambient'),
  sheepHurt('Sheep hurt', 'minecraft:entity.sheep.hurt'),
  pufferFishSting('Puffer Fish sting', 'minecraft:entity.puffer_fish.sting'),
  goatHurt('Goat hurt', 'minecraft:entity.goat.screaming.hurt'),
  horseEat('Horse eat', 'minecraft:entity.horse.eat'),
  paintingPlace('Painting place', 'minecraft:entity.painting.place'),
  parrotPiglinBrute('Parrot piglin Brute', 'minecraft:entity.parrot.imitate.piglin_brute'),
  snifferStep('Sniffer step', 'minecraft:entity.sniffer.step'),
  drownedHurtWater('Drowned hurt Water', 'minecraft:entity.drowned.hurt_water'),
  endermanDeath('Enderman death', 'minecraft:entity.enderman.death'),
  parrotWither('Parrot wither', 'minecraft:entity.parrot.imitate.wither'),
  endermanStare('Enderman stare', 'minecraft:entity.enderman.stare'),
  vindicatorCelebrate('Vindicator celebrate', 'minecraft:entity.vindicator.celebrate'),
  creakingSway('Creaking sway', 'minecraft:entity.creaking.sway'),
  pigMiniEat('Pig Mini eat', 'minecraft:entity.pig_mini.eat'),
  wolfCuteGrowl('Wolf Cute growl', 'minecraft:entity.wolf_cute.growl'),
  villagerWorkButcher('Villager work Butcher', 'minecraft:entity.villager.work_butcher'),
  cowHurt('Cow hurt', 'minecraft:entity.cow.hurt'),
  parrotDrowned('Parrot drowned', 'minecraft:entity.parrot.imitate.drowned'),
  breezeInhale('Breeze inhale', 'minecraft:entity.breeze.inhale'),
  happyGhastHurt('Happy Ghast hurt', 'minecraft:entity.happy_ghast.hurt'),
  zombieVillagerCure('Zombie Villager cure', 'minecraft:entity.zombie_villager.cure'),
  spiderAmbient('Spider ambient', 'minecraft:entity.spider.ambient'),
  pillagerDeath('Pillager death', 'minecraft:entity.pillager.death'),
  copperGolemWeatheredSpin('Copper Golem Weathered spin',
      'minecraft:entity.copper_golem_weathered.spin'),
  camelStep('Camel step', 'minecraft:entity.camel.step'),
  huskConvertedToZombie('Husk converted To Zombie', 'minecraft:entity.husk.converted_to_zombie'),
  villagerWorkShepherd('Villager work Shepherd', 'minecraft:entity.villager.work_shepherd'),
  striderHurt('Strider hurt', 'minecraft:entity.strider.hurt'),
  pandaCantBreed('Panda cant Breed', 'minecraft:entity.panda.cant_breed'),
  pufferFishHurt('Puffer Fish hurt', 'minecraft:entity.puffer_fish.hurt'),
  strayHurt('Stray hurt', 'minecraft:entity.stray.hurt'),
  ironGolemStep('Iron Golem step', 'minecraft:entity.iron_golem.step'),
  zombieDestroyEgg('Zombie destroy Egg', 'minecraft:entity.zombie.destroy_egg'),
  smallSulfurCubeSquish('Small Sulfur Cube squish', 'minecraft:entity.small_sulfur_cube.squish'),
  parrotRavager('Parrot ravager', 'minecraft:entity.parrot.imitate.ravager'),
  slimeDeath('Slime death', 'minecraft:entity.slime.death'),
  wardenHeartbeat('Warden heartbeat', 'minecraft:entity.warden.heartbeat'),
  zoglinHurt('Zoglin hurt', 'minecraft:entity.zoglin.hurt'),
  wardenAttackImpact('Warden attack Impact', 'minecraft:entity.warden.attack_impact'),
  allayAmbientWithoutItem('Allay ambient Without Item',
      'minecraft:entity.allay.ambient_without_item'),
  goatRamImpact('Goat ram Impact', 'minecraft:entity.goat.ram_impact'),
  foxSleep('Fox sleep', 'minecraft:entity.fox.sleep'),
  parrotVindicator('Parrot vindicator', 'minecraft:entity.parrot.imitate.vindicator'),
  copperGolemItemNoDrop('Copper Golem item No Drop', 'minecraft:entity.copper_golem.item_no_drop'),
  salmonHurt('Salmon hurt', 'minecraft:entity.salmon.hurt'),
  shulkerTeleport('Shulker teleport', 'minecraft:entity.shulker.teleport'),
  camelDash('Camel dash', 'minecraft:entity.camel.dash'),
  wanderingTraderDrinkMilk('Wandering Trader drink Milk',
      'minecraft:entity.wandering_trader.drink_milk'),
  wanderingTraderNo('Wandering Trader no', 'minecraft:entity.wandering_trader.no'),
  parchedStep('Parched step', 'minecraft:entity.parched.step'),
  hoglinDeath('Hoglin death', 'minecraft:entity.hoglin.death'),
  sheepShear('Sheep shear', 'minecraft:entity.sheep.shear'),
  wolfGrowl('Wolf growl', 'minecraft:entity.wolf.growl'),
  turtleHurt('Turtle hurt', 'minecraft:entity.turtle.hurt'),
  playerBurp('Player burp', 'minecraft:entity.player.burp'),
  wolfSadPant('Wolf Sad pant', 'minecraft:entity.wolf_sad.pant'),
  batLoop('Bat loop', 'minecraft:entity.bat.loop'),
  skeletonHorseJumpWater('Skeleton Horse jump Water', 'minecraft:entity.skeleton_horse.jump_water'),
  camelHuskSit('Camel Husk sit', 'minecraft:entity.camel_husk.sit'),
  creakingFreeze('Creaking freeze', 'minecraft:entity.creaking.freeze'),
  snowballThrow('Snowball throw', 'minecraft:entity.snowball.throw'),
  evokerPrepareAttack('Evoker prepare Attack', 'minecraft:entity.evoker.prepare_attack'),
  strayDeath('Stray death', 'minecraft:entity.stray.death'),
  villagerNo('Villager no', 'minecraft:entity.villager.no'),
  zombieVillagerAmbient('Zombie Villager ambient', 'minecraft:entity.zombie_villager.ambient'),
  pigBigEat('Pig Big eat', 'minecraft:entity.pig_big.eat'),
  genericSwim('Generic swim', 'minecraft:entity.generic.swim'),
  piglinStep('Piglin step', 'minecraft:entity.piglin.step'),
  splashPotionBreak('Splash Potion break', 'minecraft:entity.splash_potion.break'),
  llamaDeath('Llama death', 'minecraft:entity.llama.death'),
  pandaWorriedAmbient('Panda worried Ambient', 'minecraft:entity.panda.worried_ambient'),
  wolfHurt('Wolf hurt', 'minecraft:entity.wolf.hurt'),
  salmonDeath('Salmon death', 'minecraft:entity.salmon.death'),
  silverfishStep('Silverfish step', 'minecraft:entity.silverfish.step'),
  zombieAttackIronDoor('Zombie attack Iron Door', 'minecraft:entity.zombie.attack_iron_door'),
  wolfCuteDeath('Wolf Cute death', 'minecraft:entity.wolf_cute.death'),
  wolfDeath('Wolf death', 'minecraft:entity.wolf.death'),
  endermiteStep('Endermite step', 'minecraft:entity.endermite.step'),
  parrotAmbient('Parrot ambient', 'minecraft:entity.parrot.ambient'),
  horseArmor('Horse armor', 'minecraft:entity.horse.armor'),
  witherDeath('Wither death', 'minecraft:entity.wither.death'),
  rabbitAttack('Rabbit attack', 'minecraft:entity.rabbit.attack'),
  experienceOrbPickup('Experience Orb pickup', 'minecraft:entity.experience_orb.pickup'),
  hostileSmallFall('Hostile small Fall', 'minecraft:entity.hostile.small_fall'),
  villagerYes('Villager yes', 'minecraft:entity.villager.yes'),
  villagerAmbient('Villager ambient', 'minecraft:entity.villager.ambient'),
  catRoyalPurreow('Cat Royal purreow', 'minecraft:entity.cat_royal.purreow'),
  parrotVex('Parrot vex', 'minecraft:entity.parrot.imitate.vex'),
  wanderingTraderTrade('Wandering Trader trade', 'minecraft:entity.wandering_trader.trade'),
  pigDeath('Pig death', 'minecraft:entity.pig.death'),
  camelHuskHurt('Camel Husk hurt', 'minecraft:entity.camel_husk.hurt'),
  genericExplode('Generic explode', 'minecraft:entity.generic.explode'),
  babyCatHiss('Baby Cat hiss', 'minecraft:entity.baby_cat.hiss'),
  vindicatorHurt('Vindicator hurt', 'minecraft:entity.vindicator.hurt'),
  squidSquirt('Squid squirt', 'minecraft:entity.squid.squirt'),
  parrotWarden('Parrot warden', 'minecraft:entity.parrot.imitate.warden'),
  skeletonDeath('Skeleton death', 'minecraft:entity.skeleton.death'),
  skeletonHorseDeath('Skeleton Horse death', 'minecraft:entity.skeleton_horse.death'),
  copperGolemShear('Copper Golem shear', 'minecraft:entity.copper_golem.shear'),
  nautilusDashLand('Nautilus dash Land', 'minecraft:entity.nautilus.dash_land'),
  wanderingTraderDeath('Wandering Trader death', 'minecraft:entity.wandering_trader.death'),
  dolphinHurt('Dolphin hurt', 'minecraft:entity.dolphin.hurt'),
  babyWolfAmbient('Baby Wolf ambient', 'minecraft:entity.baby_wolf.ambient'),
  babyPigHurt('Baby Pig hurt', 'minecraft:entity.baby_pig.hurt'),
  glowItemFrameRemoveItem('Glow Item Frame remove Item',
      'minecraft:entity.glow_item_frame.remove_item'),
  boggedAmbient('Bogged ambient', 'minecraft:entity.bogged.ambient'),
  armadilloAmbient('Armadillo ambient', 'minecraft:entity.armadillo.ambient'),
  illusionerCastSpell('Illusioner cast Spell', 'minecraft:entity.illusioner.cast_spell'),
  parrotStray('Parrot stray', 'minecraft:entity.parrot.imitate.stray'),
  zoglinAngry('Zoglin angry', 'minecraft:entity.zoglin.angry'),
  huskDeath('Husk death', 'minecraft:entity.husk.death'),
  zombieNautilusDashReady('Zombie Nautilus dash Ready',
      'minecraft:entity.zombie_nautilus.dash_ready'),
  dolphinJump('Dolphin jump', 'minecraft:entity.dolphin.jump'),
  catRoyalBegForFood('Cat Royal beg For Food', 'minecraft:entity.cat_royal.beg_for_food'),
  copperGolemWeatheredHurt('Copper Golem Weathered hurt',
      'minecraft:entity.copper_golem_weathered.hurt'),
  wolfGrumpyGrowl('Wolf Grumpy growl', 'minecraft:entity.wolf_grumpy.growl'),
  parrotBreeze('Parrot breeze', 'minecraft:entity.parrot.imitate.breeze'),
  witchDeath('Witch death', 'minecraft:entity.witch.death'),
  polarBearHurt('Polar Bear hurt', 'minecraft:entity.polar_bear.hurt'),
  minecartUnderwater('Minecart underwater', 'minecraft:entity.minecart.inside.underwater'),
  goatDeath('Goat death', 'minecraft:entity.goat.screaming.death'),
  cowMoodyAmbient('Cow Moody ambient', 'minecraft:entity.cow_moody.ambient'),
  evokerPrepareWololo('Evoker prepare Wololo', 'minecraft:entity.evoker.prepare_wololo'),
  pigEat('Pig eat', 'minecraft:entity.pig.eat'),
  phantomFlap('Phantom flap', 'minecraft:entity.phantom.flap'),
  copperGolemItemDrop('Copper Golem item Drop', 'minecraft:entity.copper_golem.item_drop'),
  camelHuskEat('Camel Husk eat', 'minecraft:entity.camel_husk.eat'),
  turtleAmbientLand('Turtle ambient Land', 'minecraft:entity.turtle.ambient_land'),
  donkeyDeath('Donkey death', 'minecraft:entity.donkey.death'),
  parrotElderGuardian('Parrot elder Guardian', 'minecraft:entity.parrot.imitate.elder_guardian'),
  copperGolemNoItemNoGet('Copper Golem no Item No Get',
      'minecraft:entity.copper_golem.no_item_no_get'),
  rabbitAmbient('Rabbit ambient', 'minecraft:entity.rabbit.ambient'),
  playerHurtOnFire('Player hurt On Fire', 'minecraft:entity.player.hurt_on_fire'),
  elderGuardianFlop('Elder Guardian flop', 'minecraft:entity.elder_guardian.flop'),
  catHiss('Cat hiss', 'minecraft:entity.cat.hiss'),
  horseDeath('Horse death', 'minecraft:entity.horse.death'),
  spiderStep('Spider step', 'minecraft:entity.spider.step'),
  genericDeath('Generic death', 'minecraft:entity.generic.death'),
  babyHorseAmbient('Baby Horse ambient', 'minecraft:entity.baby_horse.ambient'),
  breezeCharge('Breeze charge', 'minecraft:entity.breeze.charge'),
  babyWolfGrowl('Baby Wolf growl', 'minecraft:entity.baby_wolf.growl'),
  wolfBigHurt('Wolf Big hurt', 'minecraft:entity.wolf_big.hurt'),
  wolfGrumpyDeath('Wolf Grumpy death', 'minecraft:entity.wolf_grumpy.death'),
  armadilloPeek('Armadillo peek', 'minecraft:entity.armadillo.peek'),
  babyHorseDeath('Baby Horse death', 'minecraft:entity.baby_horse.death'),
  itemFrameAddItem('Item Frame add Item', 'minecraft:entity.item_frame.add_item'),
  snifferDiggingStop('Sniffer digging Stop', 'minecraft:entity.sniffer.digging_stop'),
  tropicalFishDeath('Tropical Fish death', 'minecraft:entity.tropical_fish.death'),
  piglinConvertedToZombified('Piglin converted To Zombified',
      'minecraft:entity.piglin.converted_to_zombified'),
  striderHappy('Strider happy', 'minecraft:entity.strider.happy'),
  zombieNautilusSwim('Zombie Nautilus swim', 'minecraft:entity.zombie_nautilus.swim'),
  zombieHorseAngry('Zombie Horse angry', 'minecraft:entity.zombie_horse.angry'),
  pigHurt('Pig hurt', 'minecraft:entity.pig.hurt'),
  parrotGuardian('Parrot guardian', 'minecraft:entity.parrot.imitate.guardian'),
  snowGolemDeath('Snow Golem death', 'minecraft:entity.snow_golem.death'),
  witchAmbient('Witch ambient', 'minecraft:entity.witch.ambient'),
  villagerWorkCartographer('Villager work Cartographer',
      'minecraft:entity.villager.work_cartographer'),
  huskAmbient('Husk ambient', 'minecraft:entity.husk.ambient'),
  babyWolfDeath('Baby Wolf death', 'minecraft:entity.baby_wolf.death'),
  hostileBigFall('Hostile big Fall', 'minecraft:entity.hostile.big_fall'),
  elderGuardianAmbientLand('Elder Guardian ambient Land',
      'minecraft:entity.elder_guardian.ambient_land'),
  wanderingTraderAmbient('Wandering Trader ambient', 'minecraft:entity.wandering_trader.ambient'),
  camelSit('Camel sit', 'minecraft:entity.camel.sit'),
  piglinBruteHurt('Piglin Brute hurt', 'minecraft:entity.piglin_brute.hurt'),
  foxAggro('Fox aggro', 'minecraft:entity.fox.aggro'),
  chickenPickyAmbient('Chicken Picky ambient', 'minecraft:entity.chicken_picky.ambient'),
  babyChickenAmbient('Baby Chicken ambient', 'minecraft:entity.baby_chicken.ambient'),
  snifferIdle('Sniffer idle', 'minecraft:entity.sniffer.idle'),
  llamaStep('Llama step', 'minecraft:entity.llama.step'),
  skeletonConvertedToStray('Skeleton converted To Stray',
      'minecraft:entity.skeleton.converted_to_stray'),
  pandaPreSneeze('Panda pre Sneeze', 'minecraft:entity.panda.pre_sneeze'),
  arrowShoot('Arrow shoot', 'minecraft:entity.arrow.shoot'),
  copperGolemNoItemGet('Copper Golem no Item Get', 'minecraft:entity.copper_golem.no_item_get'),
  parrotGhast('Parrot ghast', 'minecraft:entity.parrot.imitate.ghast'),
  skeletonAmbient('Skeleton ambient', 'minecraft:entity.skeleton.ambient'),
  parrotIllusioner('Parrot illusioner', 'minecraft:entity.parrot.imitate.illusioner'),
  endermiteDeath('Endermite death', 'minecraft:entity.endermite.death'),
  wardenAmbient('Warden ambient', 'minecraft:entity.warden.ambient'),
  piglinDeath('Piglin death', 'minecraft:entity.piglin.death'),
  skeletonHorseAmbientWater('Skeleton Horse ambient Water',
      'minecraft:entity.skeleton_horse.ambient_water'),
  enderEyeDeath('Ender Eye death', 'minecraft:entity.ender_eye.death'),
  shulkerHurt('Shulker hurt', 'minecraft:entity.shulker.hurt'),
  pandaHurt('Panda hurt', 'minecraft:entity.panda.hurt'),
  genericHurt('Generic hurt', 'minecraft:entity.generic.hurt'),
  allayItemGiven('Allay item Given', 'minecraft:entity.allay.item_given'),
  armadilloHurtReduced('Armadillo hurt Reduced', 'minecraft:entity.armadillo.hurt_reduced'),
  zombieBreakWoodenDoor('Zombie break Wooden Door', 'minecraft:entity.zombie.break_wooden_door'),
  sheepStep('Sheep step', 'minecraft:entity.sheep.step'),
  hoglinConvertedToZombified('Hoglin converted To Zombified',
      'minecraft:entity.hoglin.converted_to_zombified'),
  magmaCubeDeath('Magma Cube death', 'minecraft:entity.magma_cube.death'),
  creakingStep('Creaking step', 'minecraft:entity.creaking.step'),
  axolotlIdleWater('Axolotl idle Water', 'minecraft:entity.axolotl.idle_water'),
  playerSmallFall('Player small Fall', 'minecraft:entity.player.small_fall'),
  zoglinAmbient('Zoglin ambient', 'minecraft:entity.zoglin.ambient'),
  batTakeoff('Bat takeoff', 'minecraft:entity.bat.takeoff'),
  parrotZombieVillager('Parrot zombie Villager', 'minecraft:entity.parrot.imitate.zombie_villager'),
  parrotHoglin('Parrot hoglin', 'minecraft:entity.parrot.imitate.hoglin'),
  ghastDeath('Ghast death', 'minecraft:entity.ghast.death'),
  horseGallop('Horse gallop', 'minecraft:entity.horse.gallop'),
  cowStep('Cow step', 'minecraft:entity.cow.step'),
  wolfGrumpyPant('Wolf Grumpy pant', 'minecraft:entity.wolf_grumpy.pant'),
  illusionerHurt('Illusioner hurt', 'minecraft:entity.illusioner.hurt'),
  allayHurt('Allay hurt', 'minecraft:entity.allay.hurt'),
  parrotMagmaCube('Parrot magma Cube', 'minecraft:entity.parrot.imitate.magma_cube'),
  beePollinate('Bee pollinate', 'minecraft:entity.bee.pollinate'),
  wardenSonicCharge('Warden sonic Charge', 'minecraft:entity.warden.sonic_charge'),
  fireworkRocketLargeBlastFar('Firework Rocket large Blast Far',
      'minecraft:entity.firework_rocket.large_blast_far'),
  striderStep('Strider step', 'minecraft:entity.strider.step'),
  ravagerRoar('Ravager roar', 'minecraft:entity.ravager.roar'),
  wolfSadWhine('Wolf Sad whine', 'minecraft:entity.wolf_sad.whine'),
  strayStep('Stray step', 'minecraft:entity.stray.step'),
  happyGhastHarnessGogglesUp('Happy Ghast harness Goggles Up',
      'minecraft:entity.happy_ghast.harness_goggles_up'),
  drownedSwim('Drowned swim', 'minecraft:entity.drowned.swim'),
  zombieNautilusDashReadyLand('Zombie Nautilus dash Ready Land',
      'minecraft:entity.zombie_nautilus.dash_ready_land'),
  zoglinStep('Zoglin step', 'minecraft:entity.zoglin.step'),
  hoglinAttack('Hoglin attack', 'minecraft:entity.hoglin.attack'),
  silverfishDeath('Silverfish death', 'minecraft:entity.silverfish.death'),
  camelHuskDashReady('Camel Husk dash Ready', 'minecraft:entity.camel_husk.dash_ready'),
  catEat('Cat eat', 'minecraft:entity.cat.eat'),
  copperGolemSpawn('Copper Golem spawn', 'minecraft:entity.copper_golem.spawn'),
  babyCatBegForFood('Baby Cat beg For Food', 'minecraft:entity.baby_cat.beg_for_food'),
  arrowHitPlayer('Arrow hit Player', 'minecraft:entity.arrow.hit_player'),
  ghastScream('Ghast scream', 'minecraft:entity.ghast.scream'),
  turtleLayEgg('Turtle lay Egg', 'minecraft:entity.turtle.lay_egg'),
  wolfPuglinHurt('Wolf Puglin hurt', 'minecraft:entity.wolf_puglin.hurt'),
  codDeath('Cod death', 'minecraft:entity.cod.death'),
  zombieHorseHurt('Zombie Horse hurt', 'minecraft:entity.zombie_horse.hurt'),
  guardianFlop('Guardian flop', 'minecraft:entity.guardian.flop'),
  skeletonHorseSwim('Skeleton Horse swim', 'minecraft:entity.skeleton_horse.swim'),
  babyWolfPant('Baby Wolf pant', 'minecraft:entity.baby_wolf.pant'),
  zombifiedPiglinAmbient('Zombified Piglin ambient', 'minecraft:entity.zombified_piglin.ambient'),
  wolfAngryAmbient('Wolf Angry ambient', 'minecraft:entity.wolf_angry.ambient'),
  babyPigEat('Baby Pig eat', 'minecraft:entity.baby_pig.eat'),
  zombifiedPiglinHurt('Zombified Piglin hurt', 'minecraft:entity.zombified_piglin.hurt'),
  breezeDeath('Breeze death', 'minecraft:entity.breeze.death'),
  pufferFishBlowOut('Puffer Fish blow Out', 'minecraft:entity.puffer_fish.blow_out'),
  babyCatStrayAmbient('Baby Cat stray Ambient', 'minecraft:entity.baby_cat.stray_ambient'),
  pillagerHurt('Pillager hurt', 'minecraft:entity.pillager.hurt'),
  nautilusRiding('Nautilus riding', 'minecraft:entity.nautilus.riding'),
  ghastlingAmbient('Ghastling ambient', 'minecraft:entity.ghastling.ambient'),
  parrotDeath('Parrot death', 'minecraft:entity.parrot.death'),
  camelEat('Camel eat', 'minecraft:entity.camel.eat'),
  playerCrit('Player crit', 'minecraft:entity.player.attack.crit'),
  axolotlIdleAir('Axolotl idle Air', 'minecraft:entity.axolotl.idle_air'),
  babyNautilusDeathLand('Baby Nautilus death Land', 'minecraft:entity.baby_nautilus.death_land'),
  witchThrow('Witch throw', 'minecraft:entity.witch.throw'),
  sulfurCubeBounce('Sulfur Cube bounce', 'minecraft:entity.sulfur_cube.bounce'),
  playerDeath('Player death', 'minecraft:entity.player.death'),
  evokerFangsAttack('Evoker Fangs attack', 'minecraft:entity.evoker_fangs.attack'),
  wolfBigAmbient('Wolf Big ambient', 'minecraft:entity.wolf_big.ambient'),
  elderGuardianHurtLand('Elder Guardian hurt Land', 'minecraft:entity.elder_guardian.hurt_land'),
  wolfStep('Wolf step', 'minecraft:entity.wolf.step'),
  minecartInside('Minecart inside', 'minecraft:entity.minecart.inside'),
  parrotEat('Parrot eat', 'minecraft:entity.parrot.eat'),
  allayItemThrown('Allay item Thrown', 'minecraft:entity.allay.item_thrown'),
  villagerWorkWeaponsmith('Villager work Weaponsmith',
      'minecraft:entity.villager.work_weaponsmith'),
  muleAngry('Mule angry', 'minecraft:entity.mule.angry'),
  wolfPuglinWhine('Wolf Puglin whine', 'minecraft:entity.wolf_puglin.whine'),
  enderDragonAmbient('Ender Dragon ambient', 'minecraft:entity.ender_dragon.ambient'),
  catAmbient('Cat ambient', 'minecraft:entity.cat.ambient'),
  babyCatAmbient('Baby Cat ambient', 'minecraft:entity.baby_cat.ambient'),
  snifferHappy('Sniffer happy', 'minecraft:entity.sniffer.happy'),
  nautilusDeathLand('Nautilus death Land', 'minecraft:entity.nautilus.death_land'),
  villagerTrade('Villager trade', 'minecraft:entity.villager.trade'),
  catRoyalHurt('Cat Royal hurt', 'minecraft:entity.cat_royal.hurt'),
  itemFramePlace('Item Frame place', 'minecraft:entity.item_frame.place'),
  glowSquidDeath('Glow Squid death', 'minecraft:entity.glow_squid.death'),
  drownedDeathWater('Drowned death Water', 'minecraft:entity.drowned.death_water'),
  goatEat('Goat eat', 'minecraft:entity.goat.screaming.eat'),
  zombieHorseAmbient('Zombie Horse ambient', 'minecraft:entity.zombie_horse.ambient'),
  camelHuskStep('Camel Husk step', 'minecraft:entity.camel_husk.step'),
  pigMiniDeath('Pig Mini death', 'minecraft:entity.pig_mini.death'),
  goatMilk('Goat milk', 'minecraft:entity.goat.milk'),
  zombieNautilusHurt('Zombie Nautilus hurt', 'minecraft:entity.zombie_nautilus.hurt'),
  parrotWitch('Parrot witch', 'minecraft:entity.parrot.imitate.witch'),
  magmaCubeDeathSmall('Magma Cube death Small', 'minecraft:entity.magma_cube.death_small'),
  armadilloEat('Armadillo eat', 'minecraft:entity.armadillo.eat'),
  zombieVillagerDeath('Zombie Villager death', 'minecraft:entity.zombie_villager.death'),
  elderGuardianHurt('Elder Guardian hurt', 'minecraft:entity.elder_guardian.hurt'),
  nautilusAmbientLand('Nautilus ambient Land', 'minecraft:entity.nautilus.ambient_land'),
  snifferSearching('Sniffer searching', 'minecraft:entity.sniffer.searching'),
  breezeDeflect('Breeze deflect', 'minecraft:entity.breeze.deflect'),
  tadpoleFlop('Tadpole flop', 'minecraft:entity.tadpole.flop'),
  zombieVillagerHurt('Zombie Villager hurt', 'minecraft:entity.zombie_villager.hurt'),
  villagerDeath('Villager death', 'minecraft:entity.villager.death'),
  illusionerDeath('Illusioner death', 'minecraft:entity.illusioner.death'),
  wanderingTraderDrinkPotion('Wandering Trader drink Potion',
      'minecraft:entity.wandering_trader.drink_potion'),
  breezeSlide('Breeze slide', 'minecraft:entity.breeze.slide'),
  babyPigStep('Baby Pig step', 'minecraft:entity.baby_pig.step'),
  eggThrow('Egg throw', 'minecraft:entity.egg.throw'),
  goatAmbient('Goat ambient', 'minecraft:entity.goat.ambient'),
  enderEyeLaunch('Ender Eye launch', 'minecraft:entity.ender_eye.launch'),
  experienceBottleThrow('Experience Bottle throw', 'minecraft:entity.experience_bottle.throw'),
  magmaCubeSquish('Magma Cube squish', 'minecraft:entity.magma_cube.squish'),
  camelHuskDash('Camel Husk dash', 'minecraft:entity.camel_husk.dash'),
  villagerWorkLeatherworker('Villager work Leatherworker',
      'minecraft:entity.villager.work_leatherworker'),
  pandaDeath('Panda death', 'minecraft:entity.panda.death'),
  parrotShulker('Parrot shulker', 'minecraft:entity.parrot.imitate.shulker'),
  ghastAmbient('Ghast ambient', 'minecraft:entity.ghast.ambient'),
  copperGolemWeatheredStep('Copper Golem Weathered step',
      'minecraft:entity.copper_golem_weathered.step'),
  illusionerPrepareMirror('Illusioner prepare Mirror',
      'minecraft:entity.illusioner.prepare_mirror'),
  turtleShamble('Turtle shamble', 'minecraft:entity.turtle.shamble'),
  wolfSadHurt('Wolf Sad hurt', 'minecraft:entity.wolf_sad.hurt'),
  chickenHurt('Chicken hurt', 'minecraft:entity.chicken.hurt'),
  horseHurt('Horse hurt', 'minecraft:entity.horse.hurt'),
  polarBearStep('Polar Bear step', 'minecraft:entity.polar_bear.step'),
  parrotPhantom('Parrot phantom', 'minecraft:entity.parrot.imitate.phantom'),
  beeDeath('Bee death', 'minecraft:entity.bee.death'),
  pillagerCelebrate('Pillager celebrate', 'minecraft:entity.pillager.celebrate'),
  striderDeath('Strider death', 'minecraft:entity.strider.death'),
  frogEat('Frog eat', 'minecraft:entity.frog.eat'),
  ocelotDeath('Ocelot death', 'minecraft:entity.ocelot.death'),
  itemFrameRotateItem('Item Frame rotate Item', 'minecraft:entity.item_frame.rotate_item'),
  genericBurn('Generic burn', 'minecraft:entity.generic.burn'),
  catRoyalPurr('Cat Royal purr', 'minecraft:entity.cat_royal.purr'),
  windChargeWindBurst('Wind Charge wind Burst', 'minecraft:entity.wind_charge.wind_burst'),
  horseJump('Horse jump', 'minecraft:entity.horse.jump'),
  creakingAmbient('Creaking ambient', 'minecraft:entity.creaking.ambient'),
  zoglinDeath('Zoglin death', 'minecraft:entity.zoglin.death'),
  armadilloDeath('Armadillo death', 'minecraft:entity.armadillo.death'),
  paintingBreak('Painting break', 'minecraft:entity.painting.break'),
  axolotlSplash('Axolotl splash', 'minecraft:entity.axolotl.splash'),
  windChargeThrow('Wind Charge throw', 'minecraft:entity.wind_charge.throw'),
  babyCatEat('Baby Cat eat', 'minecraft:entity.baby_cat.eat'),
  babyNautilusHurtLand('Baby Nautilus hurt Land', 'minecraft:entity.baby_nautilus.hurt_land'),
  zombieNautilusAmbientLand('Zombie Nautilus ambient Land',
      'minecraft:entity.zombie_nautilus.ambient_land'),
  villagerWorkLibrarian('Villager work Librarian', 'minecraft:entity.villager.work_librarian'),
  smallSulfurCubeEat('Small Sulfur Cube eat', 'minecraft:entity.small_sulfur_cube.eat'),
  pigStep('Pig step', 'minecraft:entity.pig.step'),
  drownedHurt('Drowned hurt', 'minecraft:entity.drowned.hurt'),
  rabbitHurt('Rabbit hurt', 'minecraft:entity.rabbit.hurt'),
  shulkerClose('Shulker close', 'minecraft:entity.shulker.close'),
  zombieAmbient('Zombie ambient', 'minecraft:entity.zombie.ambient'),
  arrowHit('Arrow hit', 'minecraft:entity.arrow.hit'),
  cowDeath('Cow death', 'minecraft:entity.cow.death'),
  vindicatorDeath('Vindicator death', 'minecraft:entity.vindicator.death'),
  catRoyalEat('Cat Royal eat', 'minecraft:entity.cat_royal.eat'),
  hoglinAmbient('Hoglin ambient', 'minecraft:entity.hoglin.ambient'),
  happyGhastUnequip('Happy Ghast unequip', 'minecraft:entity.happy_ghast.unequip'),
  illusionerPrepareBlindness('Illusioner prepare Blindness',
      'minecraft:entity.illusioner.prepare_blindness'),
  piglinBruteStep('Piglin Brute step', 'minecraft:entity.piglin_brute.step'),
  zombieNautilusEat('Zombie Nautilus eat', 'minecraft:entity.zombie_nautilus.eat'),
  piglinAdmiringItem('Piglin admiring Item', 'minecraft:entity.piglin.admiring_item'),
  snowGolemHurt('Snow Golem hurt', 'minecraft:entity.snow_golem.hurt'),
  skeletonHorseHurt('Skeleton Horse hurt', 'minecraft:entity.skeleton_horse.hurt'),
  zombifiedPiglinAngry('Zombified Piglin angry', 'minecraft:entity.zombified_piglin.angry'),
  parrotHusk('Parrot husk', 'minecraft:entity.parrot.imitate.husk'),
  shulkerHurtClosed('Shulker hurt Closed', 'minecraft:entity.shulker.hurt_closed'),
  snifferScenting('Sniffer scenting', 'minecraft:entity.sniffer.scenting'),
  rabbitJump('Rabbit jump', 'minecraft:entity.rabbit.jump'),
  magmaCubeHurtSmall('Magma Cube hurt Small', 'minecraft:entity.magma_cube.hurt_small'),
  horseLand('Horse land', 'minecraft:entity.horse.land'),
  itemBreak('Item break', 'minecraft:entity.item.break'),
  zombieHorseDeath('Zombie Horse death', 'minecraft:entity.zombie_horse.death'),
  magmaCubeSquishSmall('Magma Cube squish Small', 'minecraft:entity.magma_cube.squish_small'),
  wanderingTraderYes('Wandering Trader yes', 'minecraft:entity.wandering_trader.yes'),
  frogTongue('Frog tongue', 'minecraft:entity.frog.tongue'),
  armadilloBrush('Armadillo brush', 'minecraft:entity.armadillo.brush'),
  parrotBogged('Parrot bogged', 'minecraft:entity.parrot.imitate.bogged'),
  piglinBruteConvertedToZombified('Piglin Brute converted To Zombified',
      'minecraft:entity.piglin_brute.converted_to_zombified'),
  wardenTendrilClicks('Warden tendril Clicks', 'minecraft:entity.warden.tendril_clicks'),
  pandaStep('Panda step', 'minecraft:entity.panda.step'),
  squidHurt('Squid hurt', 'minecraft:entity.squid.hurt'),
  guardianHurt('Guardian hurt', 'minecraft:entity.guardian.hurt'),
  villagerWorkCleric('Villager work Cleric', 'minecraft:entity.villager.work_cleric'),
  axolotlDeath('Axolotl death', 'minecraft:entity.axolotl.death'),
  playerSweep('Player sweep', 'minecraft:entity.player.attack.sweep'),
  parrotPiglin('Parrot piglin', 'minecraft:entity.parrot.imitate.piglin'),
  boatPaddleLand('Boat paddle Land', 'minecraft:entity.boat.paddle_land'),
  phantomAmbient('Phantom ambient', 'minecraft:entity.phantom.ambient'),
  playerSplash('Player splash', 'minecraft:entity.player.splash'),
  pufferFishDeath('Puffer Fish death', 'minecraft:entity.puffer_fish.death'),
  dragonFireballExplode('Dragon Fireball explode', 'minecraft:entity.dragon_fireball.explode'),
  wardenDig('Warden dig', 'minecraft:entity.warden.dig'),
  sulfurCubeDeath('Sulfur Cube death', 'minecraft:entity.sulfur_cube.death'),
  armadilloUnrollFinish('Armadillo unroll Finish', 'minecraft:entity.armadillo.unroll_finish'),
  babyHorseBreathe('Baby Horse breathe', 'minecraft:entity.baby_horse.breathe'),
  parrotCreaking('Parrot creaking', 'minecraft:entity.parrot.imitate.creaking'),
  armadilloHurt('Armadillo hurt', 'minecraft:entity.armadillo.hurt'),
  slimeHurt('Slime hurt', 'minecraft:entity.slime.hurt'),
  enderDragonFlap('Ender Dragon flap', 'minecraft:entity.ender_dragon.flap'),
  mooshroomConvert('Mooshroom convert', 'minecraft:entity.mooshroom.convert'),
  zombieAttackWoodenDoor('Zombie attack Wooden Door', 'minecraft:entity.zombie.attack_wooden_door'),
  llamaChest('Llama chest', 'minecraft:entity.llama.chest'),
  magmaCubeHurt('Magma Cube hurt', 'minecraft:entity.magma_cube.hurt'),
  breezeIdleGround('Breeze idle Ground', 'minecraft:entity.breeze.idle_ground'),
  slimeSquish('Slime squish', 'minecraft:entity.slime.squish'),
  babyHorseHurt('Baby Horse hurt', 'minecraft:entity.baby_horse.hurt'),
  wardenRoar('Warden roar', 'minecraft:entity.warden.roar'),
  sheepDeath('Sheep death', 'minecraft:entity.sheep.death'),
  nautilusHurtLand('Nautilus hurt Land', 'minecraft:entity.nautilus.hurt_land'),
  slimeJump('Slime jump', 'minecraft:entity.slime.jump'),
  phantomBite('Phantom bite', 'minecraft:entity.phantom.bite'),
  glowSquidAmbient('Glow Squid ambient', 'minecraft:entity.glow_squid.ambient'),
  illusionerAmbient('Illusioner ambient', 'minecraft:entity.illusioner.ambient'),
  pandaAmbient('Panda ambient', 'minecraft:entity.panda.ambient'),
  glowItemFramePlace('Glow Item Frame place', 'minecraft:entity.glow_item_frame.place'),
  ghastlingHurt('Ghastling hurt', 'minecraft:entity.ghastling.hurt'),
  magmaCubeJump('Magma Cube jump', 'minecraft:entity.magma_cube.jump'),
  wanderingTraderHurt('Wandering Trader hurt', 'minecraft:entity.wandering_trader.hurt'),
  armorStandHit('Armor Stand hit', 'minecraft:entity.armor_stand.hit'),
  tadpoleHurt('Tadpole hurt', 'minecraft:entity.tadpole.hurt'),
  hoglinHurt('Hoglin hurt', 'minecraft:entity.hoglin.hurt'),
  goatPrepareRam('Goat prepare Ram', 'minecraft:entity.goat.prepare_ram'),
  cowMoodyHurt('Cow Moody hurt', 'minecraft:entity.cow_moody.hurt'),
  muleHurt('Mule hurt', 'minecraft:entity.mule.hurt'),
  babyHorseEat('Baby Horse eat', 'minecraft:entity.baby_horse.eat'),
  villagerWorkToolsmith('Villager work Toolsmith', 'minecraft:entity.villager.work_toolsmith'),
  playerBreath('Player breath', 'minecraft:entity.player.breath'),
  snifferDeath('Sniffer death', 'minecraft:entity.sniffer.death'),
  ravagerHurt('Ravager hurt', 'minecraft:entity.ravager.hurt'),
  enderDragonShoot('Ender Dragon shoot', 'minecraft:entity.ender_dragon.shoot'),
  fishSwim('Fish swim', 'minecraft:entity.fish.swim'),
  nautilusSwim('Nautilus swim', 'minecraft:entity.nautilus.swim'),
  vexAmbient('Vex ambient', 'minecraft:entity.vex.ambient'),
  wardenListening('Warden listening', 'minecraft:entity.warden.listening'),
  genericSplash('Generic splash', 'minecraft:entity.generic.splash'),
  striderStepLava('Strider step Lava', 'minecraft:entity.strider.step_lava'),
  sulfurCubeEject('Sulfur Cube eject', 'minecraft:entity.sulfur_cube.eject'),
  sulfurCubeHurt('Sulfur Cube hurt', 'minecraft:entity.sulfur_cube.hurt'),
  hoglinRetreat('Hoglin retreat', 'minecraft:entity.hoglin.retreat'),
  foxScreech('Fox screech', 'minecraft:entity.fox.screech'),
  muleJump('Mule jump', 'minecraft:entity.mule.jump'),
  catDeath('Cat death', 'minecraft:entity.cat.death'),
  villagerWorkFletcher('Villager work Fletcher', 'minecraft:entity.villager.work_fletcher'),
  goatLongJump('Goat long Jump', 'minecraft:entity.goat.long_jump'),
  frogLongJump('Frog long Jump', 'minecraft:entity.frog.long_jump'),
  copperGolemOxidizedDeath('Copper Golem Oxidized death',
      'minecraft:entity.copper_golem_oxidized.death'),
  armadilloLand('Armadillo land', 'minecraft:entity.armadillo.land'),
  copperGolemDeath('Copper Golem death', 'minecraft:entity.copper_golem.death'),
  witchDrink('Witch drink', 'minecraft:entity.witch.drink'),
  chickenPickyHurt('Chicken Picky hurt', 'minecraft:entity.chicken_picky.hurt'),
  nautilusAmbient('Nautilus ambient', 'minecraft:entity.nautilus.ambient'),
  codFlop('Cod flop', 'minecraft:entity.cod.flop'),
  nautilusDeath('Nautilus death', 'minecraft:entity.nautilus.death'),
  drownedAmbient('Drowned ambient', 'minecraft:entity.drowned.ambient'),
  turtleShambleBaby('Turtle shamble Baby', 'minecraft:entity.turtle.shamble_baby'),
  sulfurCubeJump('Sulfur Cube jump', 'minecraft:entity.sulfur_cube.jump'),
  babyHorseLand('Baby Horse land', 'minecraft:entity.baby_horse.land'),
  witherSkeletonHurt('Wither Skeleton hurt', 'minecraft:entity.wither_skeleton.hurt'),
  wolfGrumpyHurt('Wolf Grumpy hurt', 'minecraft:entity.wolf_grumpy.hurt'),
  itemFrameRemoveItem('Item Frame remove Item', 'minecraft:entity.item_frame.remove_item'),
  boggedShear('Bogged shear', 'minecraft:entity.bogged.shear'),
  dolphinDeath('Dolphin death', 'minecraft:entity.dolphin.death'),
  parrotEvoker('Parrot evoker', 'minecraft:entity.parrot.imitate.evoker'),
  donkeyChest('Donkey chest', 'minecraft:entity.donkey.chest'),
  creeperDeath('Creeper death', 'minecraft:entity.creeper.death'),
  genericDrink('Generic drink', 'minecraft:entity.generic.drink'),
  copperGolemSpin('Copper Golem spin', 'minecraft:entity.copper_golem.spin'),
  zombieVillagerStep('Zombie Villager step', 'minecraft:entity.zombie_villager.step'),
  muleDeath('Mule death', 'minecraft:entity.mule.death'),
  wolfCutePant('Wolf Cute pant', 'minecraft:entity.wolf_cute.pant'),
  armorStandFall('Armor Stand fall', 'minecraft:entity.armor_stand.fall'),
  zombieNautilusDashLand('Zombie Nautilus dash Land', 'minecraft:entity.zombie_nautilus.dash_land'),
  witherBreakBlock('Wither break Block', 'minecraft:entity.wither.break_block'),
  wardenNearbyClose('Warden nearby Close', 'minecraft:entity.warden.nearby_close'),
  parrotWitherSkeleton('Parrot wither Skeleton', 'minecraft:entity.parrot.imitate.wither_skeleton'),
  breezeWindBurst('Breeze wind Burst', 'minecraft:entity.breeze.wind_burst'),
  polarBearWarning('Polar Bear warning', 'minecraft:entity.polar_bear.warning'),
  babyChickenDeath('Baby Chicken death', 'minecraft:entity.baby_chicken.death'),
  wolfAngryWhine('Wolf Angry whine', 'minecraft:entity.wolf_angry.whine'),
  axolotlAttack('Axolotl attack', 'minecraft:entity.axolotl.attack'),
  wolfBigWhine('Wolf Big whine', 'minecraft:entity.wolf_big.whine'),
  skeletonHorseStepWater('Skeleton Horse step Water', 'minecraft:entity.skeleton_horse.step_water'),
  piglinBruteAmbient('Piglin Brute ambient', 'minecraft:entity.piglin_brute.ambient'),
  snowGolemAmbient('Snow Golem ambient', 'minecraft:entity.snow_golem.ambient'),
  pigSaddle('Pig saddle', 'minecraft:entity.pig.saddle'),
  huskHurt('Husk hurt', 'minecraft:entity.husk.hurt'),
  pigAmbient('Pig ambient', 'minecraft:entity.pig.ambient'),
  foxBite('Fox bite', 'minecraft:entity.fox.bite'),
  chickenAmbient('Chicken ambient', 'minecraft:entity.chicken.ambient'),
  babyPigAmbient('Baby Pig ambient', 'minecraft:entity.baby_pig.ambient'),
  babyWolfHurt('Baby Wolf hurt', 'minecraft:entity.baby_wolf.hurt'),
  breezeHurt('Breeze hurt', 'minecraft:entity.breeze.hurt'),
  zombieNautilusDash('Zombie Nautilus dash', 'minecraft:entity.zombie_nautilus.dash'),
  playerWeak('Player weak', 'minecraft:entity.player.attack.weak'),
  guardianDeath('Guardian death', 'minecraft:entity.guardian.death'),
  breezeIdleAir('Breeze idle Air', 'minecraft:entity.breeze.idle_air'),
  playerLevelup('Player levelup', 'minecraft:entity.player.levelup'),
  allayItemTaken('Allay item Taken', 'minecraft:entity.allay.item_taken'),
  blazeHurt('Blaze hurt', 'minecraft:entity.blaze.hurt'),
  villagerWorkArmorer('Villager work Armorer', 'minecraft:entity.villager.work_armorer'),
  blazeShoot('Blaze shoot', 'minecraft:entity.blaze.shoot'),
  chickenStep('Chicken step', 'minecraft:entity.chicken.step'),
  horseStep('Horse step', 'minecraft:entity.horse.step'),
  camelStepSand('Camel step Sand', 'minecraft:entity.camel.step_sand'),
  villagerWorkMason('Villager work Mason', 'minecraft:entity.villager.work_mason'),
  playerNodamage('Player nodamage', 'minecraft:entity.player.attack.nodamage'),
  lightningBoltImpact('Lightning Bolt impact', 'minecraft:entity.lightning_bolt.impact'),
  snifferDropSeed('Sniffer drop Seed', 'minecraft:entity.sniffer.drop_seed'),
  zombieConvertedToDrowned('Zombie converted To Drowned',
      'minecraft:entity.zombie.converted_to_drowned'),
  horseAmbient('Horse ambient', 'minecraft:entity.horse.ambient'),
  breezeJump('Breeze jump', 'minecraft:entity.breeze.jump'),
  ravagerDeath('Ravager death', 'minecraft:entity.ravager.death'),
  wardenEmerge('Warden emerge', 'minecraft:entity.warden.emerge'),
  babyPigDeath('Baby Pig death', 'minecraft:entity.baby_pig.death'),
  playerStrong('Player strong', 'minecraft:entity.player.attack.strong'),
  striderSaddle('Strider saddle', 'minecraft:entity.strider.saddle'),
  catPurreow('Cat purreow', 'minecraft:entity.cat.purreow'),
  fireworkRocketShoot('Firework Rocket shoot', 'minecraft:entity.firework_rocket.shoot'),
  parrotEndermite('Parrot endermite', 'minecraft:entity.parrot.imitate.endermite'),
  babyCatPurreow('Baby Cat purreow', 'minecraft:entity.baby_cat.purreow'),
  villagerWorkFarmer('Villager work Farmer', 'minecraft:entity.villager.work_farmer'),
  horseSaddle('Horse saddle', 'minecraft:entity.horse.saddle'),
  guardianAttack('Guardian attack', 'minecraft:entity.guardian.attack'),
  slimeSquishSmall('Slime squish Small', 'minecraft:entity.slime.squish_small'),
  frogHurt('Frog hurt', 'minecraft:entity.frog.hurt'),
  witchCelebrate('Witch celebrate', 'minecraft:entity.witch.celebrate'),
  polarBearDeath('Polar Bear death', 'minecraft:entity.polar_bear.death'),
  endermanAmbient('Enderman ambient', 'minecraft:entity.enderman.ambient'),
  parrotFly('Parrot fly', 'minecraft:entity.parrot.fly'),
  beeHurt('Bee hurt', 'minecraft:entity.bee.hurt'),
  glowItemFrameAddItem('Glow Item Frame add Item', 'minecraft:entity.glow_item_frame.add_item'),
  snifferSniffing('Sniffer sniffing', 'minecraft:entity.sniffer.sniffing'),
  shulkerOpen('Shulker open', 'minecraft:entity.shulker.open'),
  drownedStep('Drowned step', 'minecraft:entity.drowned.step'),
  evokerAmbient('Evoker ambient', 'minecraft:entity.evoker.ambient'),
  wardenNearbyCloser('Warden nearby Closer', 'minecraft:entity.warden.nearby_closer'),
  tadpoleGrowUp('Tadpole grow Up', 'minecraft:entity.tadpole.grow_up'),
  turtleEggCrack('Turtle egg Crack', 'minecraft:entity.turtle.egg_crack'),
  glowSquidSquirt('Glow Squid squirt', 'minecraft:entity.glow_squid.squirt'),
  happyGhastAmbient('Happy Ghast ambient', 'minecraft:entity.happy_ghast.ambient'),
  fireworkRocketTwinkleFar('Firework Rocket twinkle Far',
      'minecraft:entity.firework_rocket.twinkle_far'),
  breezeLand('Breeze land', 'minecraft:entity.breeze.land'),
  ghastHurt('Ghast hurt', 'minecraft:entity.ghast.hurt'),
  piglinJealous('Piglin jealous', 'minecraft:entity.piglin.jealous'),
  parrotHurt('Parrot hurt', 'minecraft:entity.parrot.hurt'),
  boggedHurt('Bogged hurt', 'minecraft:entity.bogged.hurt'),
  ghastlingSpawn('Ghastling spawn', 'minecraft:entity.ghastling.spawn'),
  zombieNautilusDeath('Zombie Nautilus death', 'minecraft:entity.zombie_nautilus.death'),
  foxEat('Fox eat', 'minecraft:entity.fox.eat'),
  chickenEgg('Chicken egg', 'minecraft:entity.chicken.egg'),
  evokerCelebrate('Evoker celebrate', 'minecraft:entity.evoker.celebrate'),
  itemFrameBreak('Item Frame break', 'minecraft:entity.item_frame.break'),
  parrotPillager('Parrot pillager', 'minecraft:entity.parrot.imitate.pillager'),
  salmonAmbient('Salmon ambient', 'minecraft:entity.salmon.ambient'),
  vexDeath('Vex death', 'minecraft:entity.vex.death'),
  genericBigFall('Generic big Fall', 'minecraft:entity.generic.big_fall'),
  babyChickenHurt('Baby Chicken hurt', 'minecraft:entity.baby_chicken.hurt'),
  creakingActivate('Creaking activate', 'minecraft:entity.creaking.activate'),
  nautilusHurt('Nautilus hurt', 'minecraft:entity.nautilus.hurt'),
  hostileSwim('Hostile swim', 'minecraft:entity.hostile.swim'),
  tadpoleDeath('Tadpole death', 'minecraft:entity.tadpole.death'),
  copperGolemOxidizedSpin('Copper Golem Oxidized spin',
      'minecraft:entity.copper_golem_oxidized.spin'),
  phantomDeath('Phantom death', 'minecraft:entity.phantom.death'),
  camelSaddle('Camel saddle', 'minecraft:entity.camel.saddle'),
  camelHuskSaddle('Camel Husk saddle', 'minecraft:entity.camel_husk.saddle'),
  codAmbient('Cod ambient', 'minecraft:entity.cod.ambient'),
  zombieInfect('Zombie infect', 'minecraft:entity.zombie.infect'),
  zombieNautilusAmbient('Zombie Nautilus ambient', 'minecraft:entity.zombie_nautilus.ambient'),
  copperGolemHurt('Copper Golem hurt', 'minecraft:entity.copper_golem.hurt'),
  zombifiedPiglinDeath('Zombified Piglin death', 'minecraft:entity.zombified_piglin.death'),
  wolfSadGrowl('Wolf Sad growl', 'minecraft:entity.wolf_sad.growl'),
  parrotCamelHusk('Parrot camel Husk', 'minecraft:entity.parrot.imitate.camel_husk'),
  ravagerAmbient('Ravager ambient', 'minecraft:entity.ravager.ambient'),
  armadilloUnrollStart('Armadillo unroll Start', 'minecraft:entity.armadillo.unroll_start'),
  wolfPuglinGrowl('Wolf Puglin growl', 'minecraft:entity.wolf_puglin.growl'),
  splashPotionThrow('Splash Potion throw', 'minecraft:entity.splash_potion.throw'),
  armadilloStep('Armadillo step', 'minecraft:entity.armadillo.step'),
  guardianAmbientLand('Guardian ambient Land', 'minecraft:entity.guardian.ambient_land'),
  ravagerAttack('Ravager attack', 'minecraft:entity.ravager.attack'),
  smallSulfurCubeDeath('Small Sulfur Cube death', 'minecraft:entity.small_sulfur_cube.death'),
  fishingBobberThrow('Fishing Bobber throw', 'minecraft:entity.fishing_bobber.throw'),
  babyHorseStep('Baby Horse step', 'minecraft:entity.baby_horse.step'),
  codHurt('Cod hurt', 'minecraft:entity.cod.hurt'),
  frogAmbient('Frog ambient', 'minecraft:entity.frog.ambient'),
  shulkerShoot('Shulker shoot', 'minecraft:entity.shulker.shoot'),
  drownedShoot('Drowned shoot', 'minecraft:entity.drowned.shoot'),
  wolfSadDeath('Wolf Sad death', 'minecraft:entity.wolf_sad.death'),
  shulkerAmbient('Shulker ambient', 'minecraft:entity.shulker.ambient'),
  pigBigAmbient('Pig Big ambient', 'minecraft:entity.pig_big.ambient'),
  allayDeath('Allay death', 'minecraft:entity.allay.death'),
  armorStandPlace('Armor Stand place', 'minecraft:entity.armor_stand.place'),
  cowAmbient('Cow ambient', 'minecraft:entity.cow.ambient'),
  parrotSilverfish('Parrot silverfish', 'minecraft:entity.parrot.imitate.silverfish'),
  wolfPuglinDeath('Wolf Puglin death', 'minecraft:entity.wolf_puglin.death'),
  batDeath('Bat death', 'minecraft:entity.bat.death'),
  tropicalFishFlop('Tropical Fish flop', 'minecraft:entity.tropical_fish.flop'),
  hoglinStep('Hoglin step', 'minecraft:entity.hoglin.step'),
  wolfCuteWhine('Wolf Cute whine', 'minecraft:entity.wolf_cute.whine'),
  cowMoodyStep('Cow Moody step', 'minecraft:entity.cow_moody.step'),
  nautilusDashReadyLand('Nautilus dash Ready Land', 'minecraft:entity.nautilus.dash_ready_land'),
  slimeAttack('Slime attack', 'minecraft:entity.slime.attack'),
  camelHuskDeath('Camel Husk death', 'minecraft:entity.camel_husk.death'),
  wardenHurt('Warden hurt', 'minecraft:entity.warden.hurt'),
  ravagerStep('Ravager step', 'minecraft:entity.ravager.step'),
  zombieHurt('Zombie hurt', 'minecraft:entity.zombie.hurt'),
  babyNautilusAmbient('Baby Nautilus ambient', 'minecraft:entity.baby_nautilus.ambient'),
  copperGolemWeatheredDeath('Copper Golem Weathered death',
      'minecraft:entity.copper_golem_weathered.death'),
  zoglinAttack('Zoglin attack', 'minecraft:entity.zoglin.attack'),
  ghastWarn('Ghast warn', 'minecraft:entity.ghast.warn'),
  blazeBurn('Blaze burn', 'minecraft:entity.blaze.burn'),
  happyGhastDeath('Happy Ghast death', 'minecraft:entity.happy_ghast.death'),
  babyCatHurt('Baby Cat hurt', 'minecraft:entity.baby_cat.hurt'),
  camelHuskStand('Camel Husk stand', 'minecraft:entity.camel_husk.stand'),
  zombieNautilusDeathLand('Zombie Nautilus death Land',
      'minecraft:entity.zombie_nautilus.death_land'),
  ocelotAmbient('Ocelot ambient', 'minecraft:entity.ocelot.ambient'),
  goatStep('Goat step', 'minecraft:entity.goat.step'),
  rabbitDeath('Rabbit death', 'minecraft:entity.rabbit.death'),
  ironGolemDeath('Iron Golem death', 'minecraft:entity.iron_golem.death'),
  batHurt('Bat hurt', 'minecraft:entity.bat.hurt'),
  parrotSlime('Parrot slime', 'minecraft:entity.parrot.imitate.slime'),
  catRoyalHiss('Cat Royal hiss', 'minecraft:entity.cat_royal.hiss'),
  witherSkeletonStep('Wither Skeleton step', 'minecraft:entity.wither_skeleton.step'),
  witchHurt('Witch hurt', 'minecraft:entity.witch.hurt'),
  wolfAngryPant('Wolf Angry pant', 'minecraft:entity.wolf_angry.pant'),
  turtleEggBreak('Turtle egg Break', 'minecraft:entity.turtle.egg_break'),
  ironGolemDamage('Iron Golem damage', 'minecraft:entity.iron_golem.damage'),
  wanderingTraderDisappeared('Wandering Trader disappeared',
      'minecraft:entity.wandering_trader.disappeared'),
  piglinAmbient('Piglin ambient', 'minecraft:entity.piglin.ambient'),
  wolfGrumpyAmbient('Wolf Grumpy ambient', 'minecraft:entity.wolf_grumpy.ambient'),
  enderDragonGrowl('Ender Dragon growl', 'minecraft:entity.ender_dragon.growl'),
  fireworkRocketLargeBlast('Firework Rocket large Blast',
      'minecraft:entity.firework_rocket.large_blast'),
  phantomHurt('Phantom hurt', 'minecraft:entity.phantom.hurt'),
  wolfWhine('Wolf whine', 'minecraft:entity.wolf.whine'),
  dolphinAmbientWater('Dolphin ambient Water', 'minecraft:entity.dolphin.ambient_water'),
  lingeringPotionThrow('Lingering Potion throw', 'minecraft:entity.lingering_potion.throw'),
  foxAmbient('Fox ambient', 'minecraft:entity.fox.ambient'),
  cowMoodyDeath('Cow Moody death', 'minecraft:entity.cow_moody.death'),
  itemPickup('Item pickup', 'minecraft:entity.item.pickup'),
  catRoyalStrayAmbient('Cat Royal stray Ambient', 'minecraft:entity.cat_royal.stray_ambient'),
  ocelotHurt('Ocelot hurt', 'minecraft:entity.ocelot.hurt'),
  fireworkRocketBlastFar('Firework Rocket blast Far', 'minecraft:entity.firework_rocket.blast_far'),
  creeperPrimed('Creeper primed', 'minecraft:entity.creeper.primed'),
  ravagerStunned('Ravager stunned', 'minecraft:entity.ravager.stunned'),
  donkeyAmbient('Donkey ambient', 'minecraft:entity.donkey.ambient'),
  copperGolemOxidizedHurt('Copper Golem Oxidized hurt',
      'minecraft:entity.copper_golem_oxidized.hurt'),
  pufferFishBlowUp('Puffer Fish blow Up', 'minecraft:entity.puffer_fish.blow_up'),
  fireworkRocketTwinkle('Firework Rocket twinkle', 'minecraft:entity.firework_rocket.twinkle'),
  nautilusDashReady('Nautilus dash Ready', 'minecraft:entity.nautilus.dash_ready'),
  mooshroomShear('Mooshroom shear', 'minecraft:entity.mooshroom.shear'),
  happyGhastEquip('Happy Ghast equip', 'minecraft:entity.happy_ghast.equip'),
  foxTeleport('Fox teleport', 'minecraft:entity.fox.teleport'),
  foxSpit('Fox spit', 'minecraft:entity.fox.spit'),
  babyNautilusAmbientLand('Baby Nautilus ambient Land',
      'minecraft:entity.baby_nautilus.ambient_land'),
  parrotEnderDragon('Parrot ender Dragon', 'minecraft:entity.parrot.imitate.ender_dragon'),
  sulfurCubeSquish('Sulfur Cube squish', 'minecraft:entity.sulfur_cube.squish'),
  huskStep('Husk step', 'minecraft:entity.husk.step'),
  elderGuardianCurse('Elder Guardian curse', 'minecraft:entity.elder_guardian.curse'),
  enderDragonDeath('Ender Dragon death', 'minecraft:entity.ender_dragon.death'),
  parrotZombieNautilus('Parrot zombie Nautilus', 'minecraft:entity.parrot.imitate.zombie_nautilus'),
  minecartRiding('Minecart riding', 'minecraft:entity.minecart.riding'),
  creakingSpawn('Creaking spawn', 'minecraft:entity.creaking.spawn'),
  babyWolfStep('Baby Wolf step', 'minecraft:entity.baby_wolf.step'),
  catHurt('Cat hurt', 'minecraft:entity.cat.hurt'),
  hostileHurt('Hostile hurt', 'minecraft:entity.hostile.hurt'),
  babyCatPurr('Baby Cat purr', 'minecraft:entity.baby_cat.purr'),
  skeletonHorseAmbient('Skeleton Horse ambient', 'minecraft:entity.skeleton_horse.ambient'),
  squidDeath('Squid death', 'minecraft:entity.squid.death'),
  enderPearlThrow('Ender Pearl throw', 'minecraft:entity.ender_pearl.throw'),
  chickenPickyDeath('Chicken Picky death', 'minecraft:entity.chicken_picky.death'),
  elderGuardianAmbient('Elder Guardian ambient', 'minecraft:entity.elder_guardian.ambient'),
  creakingUnfreeze('Creaking unfreeze', 'minecraft:entity.creaking.unfreeze'),
  foxSniff('Fox sniff', 'minecraft:entity.fox.sniff'),
  wolfShake('Wolf shake', 'minecraft:entity.wolf.shake'),
  hostileDeath('Hostile death', 'minecraft:entity.hostile.death'),
  camelHuskAmbient('Camel Husk ambient', 'minecraft:entity.camel_husk.ambient'),
  guardianDeathLand('Guardian death Land', 'minecraft:entity.guardian.death_land'),
  playerSwim('Player swim', 'minecraft:entity.player.swim'),
  piglinRetreat('Piglin retreat', 'minecraft:entity.piglin.retreat'),
  evokerPrepareSummon('Evoker prepare Summon', 'minecraft:entity.evoker.prepare_summon'),
  witherSkeletonDeath('Wither Skeleton death', 'minecraft:entity.wither_skeleton.death'),
  pandaSneeze('Panda sneeze', 'minecraft:entity.panda.sneeze'),
  creeperHurt('Creeper hurt', 'minecraft:entity.creeper.hurt'),
  muleAmbient('Mule ambient', 'minecraft:entity.mule.ambient'),
  wardenAngry('Warden angry', 'minecraft:entity.warden.angry'),
  piglinBruteAngry('Piglin Brute angry', 'minecraft:entity.piglin_brute.angry'),
  babyNautilusEat('Baby Nautilus eat', 'minecraft:entity.baby_nautilus.eat'),
  guardianAmbient('Guardian ambient', 'minecraft:entity.guardian.ambient'),
  illusionerMirrorMove('Illusioner mirror Move', 'minecraft:entity.illusioner.mirror_move'),
  playerHighSpeed('Player high Speed', 'minecraft:entity.player.splash.high_speed'),
  villagerHurt('Villager hurt', 'minecraft:entity.villager.hurt'),
  polarBearAmbient('Polar Bear ambient', 'minecraft:entity.polar_bear.ambient'),
  happyGhastHarnessGogglesDown('Happy Ghast harness Goggles Down',
      'minecraft:entity.happy_ghast.harness_goggles_down'),
  frogStep('Frog step', 'minecraft:entity.frog.step'),
  endermiteAmbient('Endermite ambient', 'minecraft:entity.endermite.ambient'),
  wardenSonicBoom('Warden sonic Boom', 'minecraft:entity.warden.sonic_boom'),
  ravagerCelebrate('Ravager celebrate', 'minecraft:entity.ravager.celebrate'),
  fireworkRocketBlast('Firework Rocket blast', 'minecraft:entity.firework_rocket.blast'),
  elderGuardianDeathLand('Elder Guardian death Land', 'minecraft:entity.elder_guardian.death_land'),
  parrotParched('Parrot parched', 'minecraft:entity.parrot.imitate.parched'),
  dolphinAmbient('Dolphin ambient', 'minecraft:entity.dolphin.ambient'),
  snowGolemShear('Snow Golem shear', 'minecraft:entity.snow_golem.shear'),
  nautilusEat('Nautilus eat', 'minecraft:entity.nautilus.eat'),
  llamaEat('Llama eat', 'minecraft:entity.llama.eat'),
  wolfGrumpyWhine('Wolf Grumpy whine', 'minecraft:entity.wolf_grumpy.whine'),
  camelHuskStepSand('Camel Husk step Sand', 'minecraft:entity.camel_husk.step_sand'),
  wardenAgitated('Warden agitated', 'minecraft:entity.warden.agitated'),
  turtleDeath('Turtle death', 'minecraft:entity.turtle.death'),
  skeletonHurt('Skeleton hurt', 'minecraft:entity.skeleton.hurt'),
  foxHurt('Fox hurt', 'minecraft:entity.fox.hurt'),
  wolfCuteHurt('Wolf Cute hurt', 'minecraft:entity.wolf_cute.hurt'),
  playerHurtFreeze('Player hurt Freeze', 'minecraft:entity.player.hurt_freeze'),
  turtleHurtBaby('Turtle hurt Baby', 'minecraft:entity.turtle.hurt_baby'),
  witherSkeletonAmbient('Wither Skeleton ambient', 'minecraft:entity.wither_skeleton.ambient'),
  slimeHurtSmall('Slime hurt Small', 'minecraft:entity.slime.hurt_small'),
  wolfPant('Wolf pant', 'minecraft:entity.wolf.pant'),
  parrotZombieHorse('Parrot zombie Horse', 'minecraft:entity.parrot.imitate.zombie_horse'),
  muleEat('Mule eat', 'minecraft:entity.mule.eat'),
  parrotSkeleton('Parrot skeleton', 'minecraft:entity.parrot.imitate.skeleton'),
  blazeDeath('Blaze death', 'minecraft:entity.blaze.death'),
  beeLoopAggressive('Bee loop Aggressive', 'minecraft:entity.bee.loop_aggressive'),
  llamaAmbient('Llama ambient', 'minecraft:entity.llama.ambient'),
  boggedStep('Bogged step', 'minecraft:entity.bogged.step'),
  glowItemFrameBreak('Glow Item Frame break', 'minecraft:entity.glow_item_frame.break'),
  donkeyHurt('Donkey hurt', 'minecraft:entity.donkey.hurt'),
  catPurr('Cat purr', 'minecraft:entity.cat.purr'),
  donkeyEat('Donkey eat', 'minecraft:entity.donkey.eat'),
  snifferHurt('Sniffer hurt', 'minecraft:entity.sniffer.hurt'),
  parrotStep('Parrot step', 'minecraft:entity.parrot.step'),
  dolphinSplash('Dolphin splash', 'minecraft:entity.dolphin.splash'),
  striderEat('Strider eat', 'minecraft:entity.strider.eat'),
  wolfSadAmbient('Wolf Sad ambient', 'minecraft:entity.wolf_sad.ambient'),
  babyWolfWhine('Baby Wolf whine', 'minecraft:entity.baby_wolf.whine'),
  mooshroomSuspiciousMilk('Mooshroom suspicious Milk',
      'minecraft:entity.mooshroom.suspicious_milk'),
  babyChickenStep('Baby Chicken step', 'minecraft:entity.baby_chicken.step'),
  vexHurt('Vex hurt', 'minecraft:entity.vex.hurt'),
  creakingAttack('Creaking attack', 'minecraft:entity.creaking.attack'),
  horseBreathe('Horse breathe', 'minecraft:entity.horse.breathe'),
  genericExtinguishFire('Generic extinguish Fire', 'minecraft:entity.generic.extinguish_fire'),
  tropicalFishHurt('Tropical Fish hurt', 'minecraft:entity.tropical_fish.hurt'),
  pigBigDeath('Pig Big death', 'minecraft:entity.pig_big.death'),
  catBegForFood('Cat beg For Food', 'minecraft:entity.cat.beg_for_food'),
  camelHurt('Camel hurt', 'minecraft:entity.camel.hurt'),
  copperGolemBecomeStatueCopperGolemBecomeStatue('Copper Golem Become Statue copper Golem Become Statue',
      'minecraft:entity.copper_golem_become_statue'),
  donkeyJump('Donkey jump', 'minecraft:entity.donkey.jump'),
  wardenSniff('Warden sniff', 'minecraft:entity.warden.sniff'),
  villagerWorkFisherman('Villager work Fisherman', 'minecraft:entity.villager.work_fisherman'),
  witherShoot('Wither shoot', 'minecraft:entity.wither.shoot'),
  hoglinAngry('Hoglin angry', 'minecraft:entity.hoglin.angry'),
  catRoyalAmbient('Cat Royal ambient', 'minecraft:entity.cat_royal.ambient'),
  evokerCastSpell('Evoker cast Spell', 'minecraft:entity.evoker.cast_spell'),
  wolfPuglinAmbient('Wolf Puglin ambient', 'minecraft:entity.wolf_puglin.ambient'),
  copperGolemStep('Copper Golem step', 'minecraft:entity.copper_golem.step'),
  fireworkRocketLaunch('Firework Rocket launch', 'minecraft:entity.firework_rocket.launch'),
  cowMilk('Cow milk', 'minecraft:entity.cow.milk'),
  pigMiniAmbient('Pig Mini ambient', 'minecraft:entity.pig_mini.ambient'),
  parrotSpider('Parrot spider', 'minecraft:entity.parrot.imitate.spider'),
  ironGolemHurt('Iron Golem hurt', 'minecraft:entity.iron_golem.hurt'),
  armadilloRoll('Armadillo roll', 'minecraft:entity.armadillo.roll'),
  babyNautilusSwim('Baby Nautilus swim', 'minecraft:entity.baby_nautilus.swim'),
  zombieVillagerConverted('Zombie Villager converted',
      'minecraft:entity.zombie_villager.converted'),
  sheepAmbient('Sheep ambient', 'minecraft:entity.sheep.ambient'),
  phantomSwoop('Phantom swoop', 'minecraft:entity.phantom.swoop'),
  llamaAngry('Llama angry', 'minecraft:entity.llama.angry'),
  boatPaddleWater('Boat paddle Water', 'minecraft:entity.boat.paddle_water'),
  witherSpawn('Wither spawn', 'minecraft:entity.wither.spawn'),
  tntPrimed('Tnt primed', 'minecraft:entity.tnt.primed'),
  villagerCelebrate('Villager celebrate', 'minecraft:entity.villager.celebrate'),
  ghastlingDeath('Ghastling death', 'minecraft:entity.ghastling.death'),
  snifferDigging('Sniffer digging', 'minecraft:entity.sniffer.digging'),
  nautilusDash('Nautilus dash', 'minecraft:entity.nautilus.dash'),
  playerTeleport('Player teleport', 'minecraft:entity.player.teleport'),
  batAmbient('Bat ambient', 'minecraft:entity.bat.ambient'),
  catStrayAmbient('Cat stray Ambient', 'minecraft:entity.cat.stray_ambient'),
  hostileSplash('Hostile splash', 'minecraft:entity.hostile.splash'),
  llamaSwag('Llama swag', 'minecraft:entity.llama.swag'),
  elderGuardianDeath('Elder Guardian death', 'minecraft:entity.elder_guardian.death'),
  skeletonShoot('Skeleton shoot', 'minecraft:entity.skeleton.shoot'),
  wanderingTraderReappeared('Wandering Trader reappeared',
      'minecraft:entity.wandering_trader.reappeared'),
  zombieNautilusHurtLand('Zombie Nautilus hurt Land', 'minecraft:entity.zombie_nautilus.hurt_land'),
  parchedHurt('Parched hurt', 'minecraft:entity.parched.hurt'),
  piglinCelebrate('Piglin celebrate', 'minecraft:entity.piglin.celebrate'),
  camelStand('Camel stand', 'minecraft:entity.camel.stand'),
  wolfCuteAmbient('Wolf Cute ambient', 'minecraft:entity.wolf_cute.ambient'),
  vindicatorAmbient('Vindicator ambient', 'minecraft:entity.vindicator.ambient'),
  fishingBobberSplash('Fishing Bobber splash', 'minecraft:entity.fishing_bobber.splash'),
  squidAmbient('Squid ambient', 'minecraft:entity.squid.ambient'),
  genericSmallFall('Generic small Fall', 'minecraft:entity.generic.small_fall'),
  axolotlSwim('Axolotl swim', 'minecraft:entity.axolotl.swim'),
  striderAmbient('Strider ambient', 'minecraft:entity.strider.ambient'),
  wolfAngryGrowl('Wolf Angry growl', 'minecraft:entity.wolf_angry.growl'),
  piglinHurt('Piglin hurt', 'minecraft:entity.piglin.hurt'),
  goatHornBreak('Goat horn Break', 'minecraft:entity.goat.horn_break'),
  wolfBigGrowl('Wolf Big growl', 'minecraft:entity.wolf_big.growl'),
  camelDeath('Camel death', 'minecraft:entity.camel.death'),
  silverfishHurt('Silverfish hurt', 'minecraft:entity.silverfish.hurt'),
  zombieHorseEat('Zombie Horse eat', 'minecraft:entity.zombie_horse.eat'),
  muleChest('Mule chest', 'minecraft:entity.mule.chest'),
  wolfBigPant('Wolf Big pant', 'minecraft:entity.wolf_big.pant'),
  endermiteHurt('Endermite hurt', 'minecraft:entity.endermite.hurt'),
  breezeWhirl('Breeze whirl', 'minecraft:entity.breeze.whirl'),
  pufferFishFlop('Puffer Fish flop', 'minecraft:entity.puffer_fish.flop'),
  wardenStep('Warden step', 'minecraft:entity.warden.step'),
  shulkerBulletHit('Shulker Bullet hit', 'minecraft:entity.shulker_bullet.hit'),
  babyNautilusDeath('Baby Nautilus death', 'minecraft:entity.baby_nautilus.death'),
  sulfurCubeAbsorb('Sulfur Cube absorb', 'minecraft:entity.sulfur_cube.absorb'),
  polarBearAmbientBaby('Polar Bear ambient Baby', 'minecraft:entity.polar_bear.ambient_baby'),
  horseStepWood('Horse step Wood', 'minecraft:entity.horse.step_wood'),
  zombieStep('Zombie step', 'minecraft:entity.zombie.step'),
  mooshroomMilk('Mooshroom milk', 'minecraft:entity.mooshroom.milk'),
  wolfAmbient('Wolf ambient', 'minecraft:entity.wolf.ambient'),
  smallSulfurCubeHurt('Small Sulfur Cube hurt', 'minecraft:entity.small_sulfur_cube.hurt'),
  blazeAmbient('Blaze ambient', 'minecraft:entity.blaze.ambient'),
  parchedAmbient('Parched ambient', 'minecraft:entity.parched.ambient'),
  tropicalFishAmbient('Tropical Fish ambient', 'minecraft:entity.tropical_fish.ambient'),
  playerHurtSweetBerryBush('Player hurt Sweet Berry Bush',
      'minecraft:entity.player.hurt_sweet_berry_bush'),
  wolfAngryDeath('Wolf Angry death', 'minecraft:entity.wolf_angry.death'),
  boggedDeath('Bogged death', 'minecraft:entity.bogged.death'),
  wolfBigDeath('Wolf Big death', 'minecraft:entity.wolf_big.death'),
  playerHurt('Player hurt', 'minecraft:entity.player.hurt'),
  pigMiniHurt('Pig Mini hurt', 'minecraft:entity.pig_mini.hurt'),
  turtleDeathBaby('Turtle death Baby', 'minecraft:entity.turtle.death_baby'),
  salmonFlop('Salmon flop', 'minecraft:entity.salmon.flop');

  final String name;
  final String key;

  const EntitySound(this.name, this.key);

}