/// Generated class for the sound events. Don't edit this file manually
enum ItemSound {

  lodestoneCompassLock('Lodestone Compass lock', 'minecraft:item.lodestone_compass.lock'),
  leadTied('Lead tied', 'minecraft:item.lead.tied'),
  spearLunge3('Spear lunge 3', 'minecraft:item.spear.lunge_3'),
  nautilusSaddleUnderwaterEquipNautilusSaddleUnderwaterEquip('Nautilus Saddle Underwater Equip nautilus Saddle Underwater Equip',
      'minecraft:item.nautilus_saddle_underwater_equip'),
  spearLunge2('Spear lunge 2', 'minecraft:item.spear.lunge_2'),
  armorEquipNetherite('Armor equip Netherite', 'minecraft:item.armor.equip_netherite'),
  spearLunge1('Spear lunge 1', 'minecraft:item.spear.lunge_1'),
  bundleRemoveOne('Bundle remove One', 'minecraft:item.bundle.remove_one'),
  bucketFillPowderSnow('Bucket fill Powder Snow', 'minecraft:item.bucket.fill_powder_snow'),
  netherWartPlant('Nether Wart plant', 'minecraft:item.nether_wart.plant'),
  bucketEmptyTadpole('Bucket empty Tadpole', 'minecraft:item.bucket.empty_tadpole'),
  flintandsteelUse('Flintandsteel use', 'minecraft:item.flintandsteel.use'),
  bundleInsertFail('Bundle insert Fail', 'minecraft:item.bundle.insert_fail'),
  elytraFlying('Elytra flying', 'minecraft:item.elytra.flying'),
  hoeTill('Hoe till', 'minecraft:item.hoe.till'),
  spearWoodAttack('Spear Wood attack', 'minecraft:item.spear_wood.attack'),
  armorEquipGold('Armor equip Gold', 'minecraft:item.armor.equip_gold'),
  spearAttack('Spear attack', 'minecraft:item.spear.attack'),
  crossbowShoot('Crossbow shoot', 'minecraft:item.crossbow.shoot'),
  wolfArmorBreak('Wolf Armor break', 'minecraft:item.wolf_armor.break'),
  crossbowQuickCharge3('Crossbow quick Charge 3', 'minecraft:item.crossbow.quick_charge_3'),
  tridentRiptide3('Trident riptide 3', 'minecraft:item.trident.riptide_3'),
  crossbowQuickCharge2('Crossbow quick Charge 2', 'minecraft:item.crossbow.quick_charge_2'),
  spearUse('Spear use', 'minecraft:item.spear.use'),
  bottleFill('Bottle fill', 'minecraft:item.bottle.fill'),
  tridentRiptide2('Trident riptide 2', 'minecraft:item.trident.riptide_2'),
  crossbowQuickCharge1('Crossbow quick Charge 1', 'minecraft:item.crossbow.quick_charge_1'),
  brushGeneric('Brush generic', 'minecraft:item.brush.brushing.generic'),
  tridentRiptide1('Trident riptide 1', 'minecraft:item.trident.riptide_1'),
  crossbowLoadingMiddle('Crossbow loading Middle', 'minecraft:item.crossbow.loading_middle'),
  armorEquipChain('Armor equip Chain', 'minecraft:item.armor.equip_chain'),
  leadUntied('Lead untied', 'minecraft:item.lead.untied'),
  spearWoodUse('Spear Wood use', 'minecraft:item.spear_wood.use'),
  bucketFill('Bucket fill', 'minecraft:item.bucket.fill'),
  leadBreak('Lead break', 'minecraft:item.lead.break'),
  armorEquipElytra('Armor equip Elytra', 'minecraft:item.armor.equip_elytra'),
  honeycombWaxOn('Honeycomb wax On', 'minecraft:item.honeycomb.wax_on'),
  bucketEmptyFish('Bucket empty Fish', 'minecraft:item.bucket.empty_fish'),
  wolfArmorCrack('Wolf Armor crack', 'minecraft:item.wolf_armor.crack'),
  bucketEmptySulfurCube('Bucket empty Sulfur Cube', 'minecraft:item.bucket.empty_sulfur_cube'),
  shieldBreak('Shield break', 'minecraft:item.shield.break'),
  goldenDandelionUse('Golden Dandelion use', 'minecraft:item.golden_dandelion.use'),
  shearsSnip('Shears snip', 'minecraft:item.shears.snip'),
  dyeUse('Dye use', 'minecraft:item.dye.use'),
  brushComplete('Brush complete', 'minecraft:item.brush.brushing.gravel.complete'),
  bucketEmptyLava('Bucket empty Lava', 'minecraft:item.bucket.empty_lava'),
  bookPageTurn('Book page Turn', 'minecraft:item.book.page_turn'),
  armorEquipIron('Armor equip Iron', 'minecraft:item.armor.equip_iron'),
  armorEquipTurtle('Armor equip Turtle', 'minecraft:item.armor.equip_turtle'),
  bucketFillSulfurCube('Bucket fill Sulfur Cube', 'minecraft:item.bucket.fill_sulfur_cube'),
  glowInkSacUse('Glow Ink Sac use', 'minecraft:item.glow_ink_sac.use'),
  crossbowLoadingEnd('Crossbow loading End', 'minecraft:item.crossbow.loading_end'),
  llamaCarpetUnequip('Llama Carpet unequip', 'minecraft:item.llama_carpet.unequip'),
  maceSmashAir('Mace smash Air', 'minecraft:item.mace.smash_air'),
  brushGravel('Brush gravel', 'minecraft:item.brush.brushing.gravel'),
  bucketEmptyAxolotl('Bucket empty Axolotl', 'minecraft:item.bucket.empty_axolotl'),
  nautilusSaddleEquipNautilusSaddleEquip('Nautilus Saddle Equip nautilus Saddle Equip',
      'minecraft:item.nautilus_saddle_equip'),
  tridentThrow('Trident throw', 'minecraft:item.trident.throw'),
  spyglassUse('Spyglass use', 'minecraft:item.spyglass.use'),
  tridentThunder('Trident thunder', 'minecraft:item.trident.thunder'),
  tridentReturn('Trident return', 'minecraft:item.trident.return'),
  bookPut('Book put', 'minecraft:item.book.put'),
  armorUnequipWolf('Armor unequip Wolf', 'minecraft:item.armor.unequip_wolf'),
  armorEquipLeather('Armor equip Leather', 'minecraft:item.armor.equip_leather'),
  maceSmashGround('Mace smash Ground', 'minecraft:item.mace.smash_ground'),
  inkSacUse('Ink Sac use', 'minecraft:item.ink_sac.use'),
  armorEquipNautilus('Armor equip Nautilus', 'minecraft:item.armor.equip_nautilus'),
  armorUnequipNautilus('Armor unequip Nautilus', 'minecraft:item.armor.unequip_nautilus'),
  armorEquipDiamond('Armor equip Diamond', 'minecraft:item.armor.equip_diamond'),
  armorEquipCopper('Armor equip Copper', 'minecraft:item.armor.equip_copper'),
  chorusFruitTeleport('Chorus Fruit teleport', 'minecraft:item.chorus_fruit.teleport'),
  tridentHit('Trident hit', 'minecraft:item.trident.hit'),
  bucketFillTadpole('Bucket fill Tadpole', 'minecraft:item.bucket.fill_tadpole'),
  bucketFillFish('Bucket fill Fish', 'minecraft:item.bucket.fill_fish'),
  armorEquipGeneric('Armor equip Generic', 'minecraft:item.armor.equip_generic'),
  bundleDropContents('Bundle drop Contents', 'minecraft:item.bundle.drop_contents'),
  crossbowHit('Crossbow hit', 'minecraft:item.crossbow.hit'),
  ominousBottleDispose('Ominous Bottle dispose', 'minecraft:item.ominous_bottle.dispose'),
  honeyBottleDrink('Honey Bottle drink', 'minecraft:item.honey_bottle.drink'),
  axeScrape('Axe scrape', 'minecraft:item.axe.scrape'),
  bucketFillLava('Bucket fill Lava', 'minecraft:item.bucket.fill_lava'),
  horseArmorUnequip('Horse Armor unequip', 'minecraft:item.horse_armor.unequip'),
  bundleInsert('Bundle insert', 'minecraft:item.bundle.insert'),
  wolfArmorRepair('Wolf Armor repair', 'minecraft:item.wolf_armor.repair'),
  totemUse('Totem use', 'minecraft:item.totem.use'),
  axeStrip('Axe strip', 'minecraft:item.axe.strip'),
  brushSand('Brush sand', 'minecraft:item.brush.brushing.sand'),
  boneMealUse('Bone Meal use', 'minecraft:item.bone_meal.use'),
  firechargeUse('Firecharge use', 'minecraft:item.firecharge.use'),
  cropPlant('Crop plant', 'minecraft:item.crop.plant'),
  tridentHitGround('Trident hit Ground', 'minecraft:item.trident.hit_ground'),
  bucketEmpty('Bucket empty', 'minecraft:item.bucket.empty'),
  spyglassStopUsing('Spyglass stop Using', 'minecraft:item.spyglass.stop_using'),
  axeWaxOff('Axe wax Off', 'minecraft:item.axe.wax_off'),
  bottleFillDragonbreath('Bottle fill Dragonbreath', 'minecraft:item.bottle.fill_dragonbreath'),
  goldenDandelionUnuse('Golden Dandelion unuse', 'minecraft:item.golden_dandelion.unuse'),
  goatHorn7('Goat Horn 7', 'minecraft:item.goat_horn.sound.7'),
  bucketFillAxolotl('Bucket fill Axolotl', 'minecraft:item.bucket.fill_axolotl'),
  goatHorn6('Goat Horn 6', 'minecraft:item.goat_horn.sound.6'),
  maceSmashGroundHeavy('Mace smash Ground Heavy', 'minecraft:item.mace.smash_ground_heavy'),
  goatHorn5('Goat Horn 5', 'minecraft:item.goat_horn.sound.5'),
  bottleEmpty('Bottle empty', 'minecraft:item.bottle.empty'),
  goatHorn4('Goat Horn 4', 'minecraft:item.goat_horn.sound.4'),
  spearHit('Spear hit', 'minecraft:item.spear.hit'),
  saddleUnequip('Saddle unequip', 'minecraft:item.saddle.unequip'),
  goatHorn3('Goat Horn 3', 'minecraft:item.goat_horn.sound.3'),
  goatHorn2('Goat Horn 2', 'minecraft:item.goat_horn.sound.2'),
  goatHorn1('Goat Horn 1', 'minecraft:item.goat_horn.sound.1'),
  crossbowLoadingStart('Crossbow loading Start', 'minecraft:item.crossbow.loading_start'),
  shieldBlock('Shield block', 'minecraft:item.shield.block'),
  goatHorn0('Goat Horn 0', 'minecraft:item.goat_horn.sound.0'),
  spearWoodHit('Spear Wood hit', 'minecraft:item.spear_wood.hit'),
  bucketEmptyPowderSnow('Bucket empty Powder Snow', 'minecraft:item.bucket.empty_powder_snow'),
  armorEquipWolf('Armor equip Wolf', 'minecraft:item.armor.equip_wolf'),
  wolfArmorDamage('Wolf Armor damage', 'minecraft:item.wolf_armor.damage'),
  shovelFlatten('Shovel flatten', 'minecraft:item.shovel.flatten');

  final String name;
  final String key;

  const ItemSound(this.name, this.key);

}